
		ORG $8000

_txt_block5B:
_msg5A3:		.BYTE	_apu,_Y,_o,_u,_,_g,_e,_t,_,_s,_t,_r,_a,_i,_g,_h,_t,_,_t,_o,_,_t,_h,_e,_,_p,_o,_i,_n,_t,_sem,_,_d,_o,_n,_apo,_t,_,_y,_o,_u,_que,_,_O,_o,_h,_sem,_,_I,_,_l,_i,_k,_e,_,_t,_h,_a,_t,_smc,$FD,$EB
				.BYTE	_apu,_D,_o,_,_y,_o,_u,_,_k,_n,_o,_w,_,_t,_h,_e,_,_i,_s,_l,_a,_n,_d,_,_o,_f,_,_L,_u,_z,_a,_m,_i,_que,_,_F,_r,_o,_m,_,_h,_e,_r,_e,_,_i,_t,_s,_,_s,_o,_u,_t,_h,_,_a,_n,_d,_,_s,_l,_i,_g,_h,_t,_l,_y,_,_w,_e,_s,_t,_smc,$EF
_msg5A4:		.BYTE	_apu,_D,_o,_n,_apo,_t,_,_l,_i,_e,_exc,$EB
				.BYTE	_I,_,_w,_a,_s,_n,_apo,_t,_,_t,_o,_l,_d,_,_t,_h,_e,_,_l,_i,_k,_e,_s,_,_o,_f,_,_y,_o,_u,_,_w,_o,_u,_l,_d,_,_c,_o,_m,_e,_exc,_apd,$EF
_msg5A5:		.BYTE	_apu,_T,_h,_a,_t,_,_w,_h,_i,_c,_h,_,_y,_o,_u,_,_s,_e,_e,_,_r,_i,_s,_i,_n,_g,_,_u,_p,_,_o,_n,_,_t,_h,_a,_t,_,_i,_s,_l,_a,_n,_d,_,_i,_s,_,_t,_h,_e,_,_T,_o,_w,_e,_r,_,_o,_f,_,_N,_a,_j,_i,_m,_a,_smc,$EF
_msg5A6:		.BYTE	_apu,_H,_a,_s,_t,_e,_,_m,_a,_k,_e,_s,_,_w,_a,_s,_t,_e,_exc,$EB
				.BYTE	_T,_h,_a,_t,_apo,_s,_,_t,_h,_e,_,_h,_o,_n,_e,_s,_t,_,_t,_r,_u,_t,_h,_exc,_,_H,_e,_h,_sem,_,_h,_e,_h,_sem,_,_h,_e,_h,_smc,$EF
_msg5A7:		.BYTE	_apu,_W,_e,_l,_l,_sem,_,_c,_o,_m,_e,_,_o,_n,_,_i,_n,_smc,$EF
_msg5A8:		.BYTE	_apu,_I,_,_h,_e,_a,_r,_,_t,_h,_e,_r,_e,_,_i,_s,_,_a,_,_c,_a,_v,_e,_,_i,_n,_,_t,_h,_e,_,_f,_o,_r,_e,_s,_t,_,_s,_o,_u,_t,_h,_,_o,_f,_,_t,_h,_i,_s,_,_v,_i,_l,_l,_a,_g,_e,_,_t,_h,_a,_t,_,_c,_o,_n,_n,_e,_c,_t,_s,_,_t,_o,_,_t,_h,_e,_,_T,_o,_w,_e,_r,_,_o,_f,_,_N,_a,_j,_i,_m,_a,_smc,$EF
_msg5A9:		.BYTE	_apu,_T,_h,_a,_t,_apo,_s,_,_o,_u,_t,_,_o,_f,_,_t,_h,_e,_,_q,_u,_e,_s,_t,_i,_o,_n,_exc,_,_G,_o,_,_b,_a,_c,_k,_,_t,_o,_,_R,_e,_e,_v,_e,_exc,_apd,$EF
_msg5AA:		.BYTE	_apu,_I,_,_m,_u,_s,_t,_,_h,_a,_v,_e,_,_h,_a,_d,_,_a,_,_s,_o,_u,_n,_d,_,_s,_l,_e,_e,_p,_sem,_,_t,_h,_e,_n,_smc,$EF
_msg5AB:		.BYTE	_apu,_O,_h,_exc,_,_I,_,_t,_h,_o,_u,_g,_h,_t,_,_y,_o,_u,_,_w,_e,_r,_e,_,_s,_o,_m,_e,_o,_n,_e,_,_e,_l,_s,_e,_smc,$EF
_msg5AC:		.BYTE	_apu,_I,_n,_,_t,_h,_a,_t,_,_c,_a,_s,_e,_,_I,_,_w,_o,_n,_apo,_t,_,_s,_a,_y,_,_a,_n,_y,_t,_h,_i,_n,_g,_smc,$EF
_msg5AD:		.BYTE	_apu,_I,_,_s,_e,_e,_smc,$EF
_msg5AE:		.BYTE	_apu,_W,_h,_y,_sem,_,_d,_i,_d,_,_y,_o,_u,_,_c,_o,_m,_e,_,_o,_n,_,_f,_o,_o,_t,_que,_exc,_,_W,_h,_a,_t,_,_c,_u,_r,_i,_o,_u,_s,_,_f,_o,_l,_k,_s,_exc,_apd,$EF
_msg5AF:		.BYTE	_apu,_L,_o,_n,_g,_sem,_,_l,_o,_n,_g,_,_a,_g,_o,_,_p,_e,_o,_p,_l,_e,_,_l,_e,_f,_t,_,_t,_h,_i,_s,_,_v,_i,_l,_l,_a,_g,_e,_,_t,_o,_,_g,_o,_,_t,_h,_e,_r,_e,_,_t,_o,_,_b,_u,_i,_l,_d,_,_a,_,_t,_o,_w,_n,_,_a,_n,_d,_,_h,_a,_v,_e,_,_n,_e,_v,_e,_r,_,_r,_e,_t,_u,_r,_n,_e,_d,_smc,$EF
_msg5B0:		.BYTE	_apu,_H,_u,_m,_f,_dot,_,_O,_n,_e,_,_t,_h,_i,_n,_g,_,_I,_,_d,_o,_n,_apo,_t,_,_l,_i,_k,_e,_,_i,_s,_,_a,_,_f,_l,_a,_t,_t,_e,_r,_e,_r,_exc,_apd,$EF
_msg5B1:		.BYTE	_apu,_N,_o,_w,_sem,_,_y,_o,_u,_,_b,_e,_s,_t,_,_b,_e,_,_o,_n,_,_y,_o,_u,_r,_,_w,_a,_y,_smc,$EF
_msg5B2:		.BYTE	_apu,_Y,_o,_u,_,_s,_h,_o,_u,_l,_d,_,_s,_e,_e,_,_i,_t,_,_a,_s,_,_s,_o,_o,_n,_,_a,_s,_,_y,_o,_u,_,_g,_o,_,_o,_u,_t,_s,_i,_d,_e,_smc,$EF
_txt_block5C:
_msg5B3:		.BYTE	_apu,_T,_h,_a,_t,_apo,_s,_,_a,_,_p,_i,_t,_y,_smc,$EF
_msg5B4:		.BYTE	_apu,_I,_f,_,_t,_h,_a,_t,_apo,_s,_,_t,_h,_e,_,_c,_a,_s,_e,_sem,_,_i,_t,_apo,_s,_,_b,_e,_t,_t,_e,_r,_,_t,_o,_,_g,_o,_,_a,_r,_o,_u,_n,_d,_,_f,_r,_o,_n,_t,_smc,$EF
_msg5B5:		.BYTE	_apu,_W,_o,_n,_apo,_t,_,_y,_o,_u,_r,_,_m,_o,_m,_m,_y,_,_b,_e,_,_w,_o,_r,_r,_i,_e,_d,_,_i,_f,_,_y,_o,_u,_,_d,_o,_n,_apo,_t,_,_g,_o,_,_h,_o,_m,_e,_que,_exc,_apd,$EF
_msg5B6:		.BYTE	_apu,_O,_h,_sem,_,_w,_h,_a,_t,_,_h,_a,_s,_,_b,_e,_c,_o,_m,_e,_,_o,_f,_,_m,_y,_,$F5,_exc,_apd,$EF
_msg5B7:		.BYTE	_apu,_W,_e,_l,_c,_o,_m,_e,_,_b,_a,_c,_k,_sem,_,$F5,_,_m,_y,_,_d,_e,_a,_r,_smc,$FD,$EB
				.BYTE	_apu,_Y,_o,_u,_,_m,_u,_s,_t,_,_b,_e,_,_e,_x,_h,_a,_u,_s,_t,_e,_d,_dot,_,_S,_i,_t,_,_d,_o,_w,_n,_,_a,_n,_d,_,_r,_e,_s,_t,_smc,$EF
_msg5B8:		.BYTE	$FD,$EB
				.BYTE	_apu,_Y,_o,_u,_r,_,_f,_r,_i,_e,_n,_d,$B7,_,_s,_h,_o,_u,_l,_d,_,_c,_o,_m,_e,_,_i,_n,_,_a,_n,_d,_,_r,_e,_s,_t,_sem,_,_t,_o,_o,_smc,$EF
_msg5B9:		.BYTE	_apu,_G,_o,_o,_d,_,_m,_o,_r,_n,_i,_n,_g,_exc,_,_T,_i,_m,_e,_,_t,_o,_,_g,_e,_t,_,_u,_p,_,_a,_n,_d,_,_g,_o,_sem,_,$F5,_smc,$EF
_msg5BA:		.BYTE	_apu,_O,_h,_exc,_,_Y,_o,_u,_apo,_r,_e,_,_b,_a,_c,_k,_,_l,_a,_t,_e,_dot,_,_I,_apo,_m,_,_g,_l,_a,_d,_,_y,_o,_u,_apo,_r,_e,_,_s,_a,_f,_e,_,_a,_n,_d,_,_s,_o,_u,_n,_d,_smc,$FD,$EB
				.BYTE	_apu,_G,_o,_,_u,_p,_s,_t,_a,_i,_r,_s,_,_a,_n,_d,_,_r,_e,_s,_t,_,_n,_o,_w,_smc,$FD,$FF
_msg5BB:		.BYTE	_apu,_W,_h,_a,_t,_,_w,_r,_o,_n,_g,_sem,_,$F5,_que,_,_I,_s,_,_t,_h,_e,_,_l,_i,_f,_e,_,_o,_f,_,_a,_d,_v,_e,_n,_t,_u,_r,_e,_,_t,_o,_o,_,_t,_o,_u,_g,_h,_que,_,_A,_r,_e,_n,_apo,_t,_,_y,_o,_u,_,_g,_o,_i,_n,_g,_,_t,_o,_,_g,_e,_t,_,_u,_p,_,_a,_n,_d,_,_g,_o,_que,_apd,$EF
_msg5BC:		.BYTE	_apu,_A,_s,_,_y,_o,_u,_r,_,_m,_o,_t,_h,_e,_r,_sem,_,_I,_apo,_d,_,_l,_i,_k,_e,_,_y,_o,_u,_,_t,_o,_,_s,_t,_a,_y,_,_w,_i,_t,_h,_,_m,_e,_,_a,_l,_w,_a,_y,_s,_sem,_,$F5,_smc,$FD,$EB
				.BYTE	_apu,_B,_u,_t,_,_t,_h,_e,_r,_e,_,_c,_o,_m,_e,_s,_,_a,_,_d,_a,_y,_,_w,_h,_e,_n,_,_c,_h,_i,_l,_d,_r,_e,_n,_,_m,_u,_s,_t,_,_p,_a,_r,_t,_,_w,_i,_t,_h,_,_t,_h,_e,_i,_r,_,_p,_a,_r,_e,_n,_t,_s,_smc,$FD,$FF
_msg5BD:		.BYTE	_apu,_C,_o,_m,_e,_,_o,_n,_,_t,_h,_e,_n,_exc,_,_I,_t,_apo,_s,_,_t,_i,_m,_e,_,_t,_o,_,_g,_o,_exc,_,_L,_i,_k,_e,_,_y,_o,_u,_r,_,_f,_i,_n,_e,_,_b,_r,_a,_v,_e,_,_f,_a,_t,_h,_e,_r,_exc,_apd,$EF
_msg5BE:		.BYTE	_apu,_T,_h,_a,_t,_apo,_s,_,_r,_i,_g,_h,_t,_exc,_,_T,_h,_e,_,_b,_l,_o,_o,_d,_,_o,_f,_,_t,_h,_e,_,_g,_r,_e,_a,_t,_,_O,_r,_t,_e,_g,_a,_,_r,_u,_n,_s,_,_t,_h,_r,_o,_u,_g,_h,_,_y,_o,_u,_r,_,_v,_e,_i,_n,_s,_exc,_apd,$FD,$FF
_msg5BF:		.BYTE	_apu,_O,_h,_sem,_,_m,_e,_r,_c,_y,_exc,$EB
				.BYTE	_M,_y,_,_d,_e,_a,_r,_,_s,_w,_e,_e,_t,_,$F5,_exc,_apd,$FD,$EB
				.BYTE	_apu,_P,_l,_e,_a,_s,_e,_,_h,_e,_l,_p,_,$F5,_exc,_,$B5,_,_m,_y,_,_o,_n,_l,_y,_,_c,_h,_i,_l,_d,_exc,_apd,$EF
_msg5C0:		.BYTE	_apu,_A,_,_s,_o,_l,_o,_,_j,_o,_u,_r,_n,_e,_y,_,_i,_s,_,_t,_o,_o,_,_d,_a,_n,_g,_e,_r,_o,_u,_s,_smc,$FD,$EB
				.BYTE	_apu,_I,_t,_apo,_s,_,_b,_e,_s,_t,_,_t,_o,_,_g,_o,_,_t,_o,_,_L,_u,_i,_s,_a,_apo,_s,_,_P,_l,_a,_c,_e,_,_a,_t,_,_t,_h,_e,_,_w,_e,_s,_t,_,_e,_d,_g,_e,_,_o,_f,_,_t,_o,_w,_n,_,_a,_n,_d,_,_f,_i,_n,_d,_,_s,_o,_m,_e,_,_c,_o,_m,_p,_a,_n,_i,_o,_n,_s,_smc,$EF
_msg5C1:		.BYTE	_apu,_F,_i,_r,_s,_t,_,_f,_i,_n,_d,_,_a,_,_k,_e,_y,_dot,_,_E,_v,_e,_r,_y,_t,_h,_i,_n,_g,_,_b,_e,_g,_i,_n,_s,_,_w,_i,_t,_h,_,_t,_h,_a,_t,_smc,$EF
_msg5C2:		.BYTE	_apu,_A,_,_y,_o,_u,_n,_g,_,_h,_e,_r,_o,_,_f,_r,_o,_m,_,_A,_l,_i,_a,_h,_a,_n,_,_w,_i,_l,_l,_,_t,_r,_a,_v,_e,_l,_,_t,_h,_e,_,_w,_o,_r,_l,_d,_,_a,_g,_a,_i,_n,_exc,_apd,$EF
_txt_block5D:
_msg5C3:		.BYTE	_apu,_A,_n,_y,_w,_a,_y,_sem,_,_y,_o,_u,_,_d,_o,_n,_apo,_t,_,_h,_a,_v,_e,_,_t,_h,_e,_,_k,_e,_y,_,_t,_o,_,_o,_p,_e,_n,_,_t,_h,_e,_,_j,_a,_i,_l,_exc,_,_G,_e,_t,_,_a,_w,_a,_y,_,_f,_r,_o,_m,_,_h,_e,_r,_e,_exc,_apd,$EF
_msg5C4:		.BYTE	_apu,_T,_h,_a,_n,_k,_s,_,_f,_o,_r,_,_l,_e,_t,_t,_i,_n,_g,_,_m,_e,_,_o,_u,_t,_dot,_,_I,_apo,_l,_l,_,_t,_e,_l,_l,_,_y,_o,_u,_,_s,_o,_m,_e,_t,_h,_i,_n,_g,_,_n,_o,_w,_smc,$FD,$EB
				.BYTE	_apu,_T,_h,_e,_y,_,_s,_a,_y,_,_t,_h,_e,_r,_e,_,_i,_s,_,_a,_,_c,_a,_s,_t,_l,_e,_,_s,_o,_m,_e,_w,_h,_e,_r,_e,_,_w,_h,_e,_r,_e,_,_t,_h,_e,_,_D,_r,_a,_g,_o,_n,_,_Q,_u,_e,_e,_n,_,_l,_i,_v,_e,_s,_smc,$EF
_msg5C5:		.BYTE	_apu,_H,_e,_a,_v,_e,_,_h,_o,_exc,_,_U,_g,_h,_exc,$EB
				.BYTE	_N,_o,_,_w,_a,_y,_exc,_,_I,_t,_apo,_s,_,_t,_o,_o,_,_h,_e,_a,_v,_y,_dot,_,_I,_t,_,_w,_o,_n,_apo,_t,_,_b,_u,_d,_g,_e,_exc,_apd,$EF
_msg5C6:		.BYTE	_apu,_W,_o,_w,_exc,_,_T,_h,_a,_t,_,_s,_t,_r,_e,_n,_g,_t,_h,_,_o,_f,_,_y,_o,_u,_r,_s,_,_w,_i,_l,_l,_,_c,_o,_m,_e,_,_i,_n,_,_h,_a,_n,_d,_y,_,_s,_o,_m,_e,_d,_a,_y,_exc,_apd,$EF
_msg5C7:		.BYTE	_apu,_W,_o,_w,_exc,_,$F5,_,_i,_s,_,_a,_,_w,_o,_m,_a,_n,_que,_apd,$FD,$EB
				.BYTE	_apu,_W,_h,_a,_t,_apo,_s,_,_t,_h,_a,_t,_que,_,_I,_apo,_m,_,_w,_r,_o,_n,_g,_que,$EB
				.BYTE	_S,_u,_r,_e,_,_l,_o,_o,_k,_s,_,_l,_i,_k,_e,_,_a,_,_w,_o,_m,_a,_n,_,_t,_o,_,_m,_e,_smc,$EF
_msg5C8:		.BYTE	_apu,_S,_c,_o,_r,_c,_h,_,_a,_,_l,_o,_t,_,_o,_f,_,_m,_o,_n,_s,_t,_e,_r,_s,_sem,_,_O,_K,_que,$EB
				.BYTE	_T,_h,_e,_y,_,_d,_i,_d,_,_i,_n,_,_m,_y,_,_M,_a,_m,_a,_,_a,_n,_d,_,_P,_a,_p,_a,_dot,$EB
				.BYTE	_W,_h,_i,_m,_p,_e,_r,_sem,_,_w,_h,_i,_m,_p,_e,_r,_smc,$EF
_msg5C9:		.BYTE	_apu,_I,_apo,_v,_e,_,_h,_e,_a,_r,_d,_,_t,_h,_e,_,_s,_t,_o,_r,_y,_,_a,_l,_r,_e,_a,_d,_y,_smc,$FD,$EB
				.BYTE	_apu,_G,_o,_,_a,_h,_e,_a,_d,_,_a,_n,_d,_,_b,_r,_e,_a,_k,_,_t,_h,_e,_,_s,_e,_a,_l,_,_w,_i,_t,_h,_,_t,_h,_i,_s,_,_M,_a,_g,_i,_c,_,_B,_a,_l,_l,_exc,_apd,$EF
_msg5CA:		.BYTE	_apu,_P,_e,_o,_p,_l,_e,_,_a,_c,_r,_o,_s,_s,_,_t,_h,_e,_,_d,_i,_s,_t,_a,_n,_t,_,_s,_e,_a,_s,_,_a,_r,_e,_,_s,_u,_r,_e,_l,_y,_,_w,_a,_i,_t,_i,_n,_g,_,_a,_n,_d,_,_h,_o,_p,_i,_n,_g,_,_f,_o,_r,_,_a,_,_h,_e,_r,_o,_,_t,_o,_,_c,_o,_m,_e,_,_f,_r,_o,_m,_,_A,_l,_i,_a,_h,_a,_n,_smc,$EF
_msg5CB:		.BYTE	_apu,_O,_h,_exc,_,_P,_l,_e,_a,_s,_e,_exc,_,$EB
				.BYTE	_Y,_o,_u,_,_s,_h,_o,_u,_l,_d,_n,_apo,_t,_,_c,_o,_m,_e,_,_i,_n,_,_h,_e,_r,_e,_exc,_apd,$EF
_msg5CC:		.BYTE	_apu,_I,_,_t,_h,_i,_n,_k,_,_I,_apo,_l,_l,_,_b,_u,_i,_l,_d,_,_a,_,_t,_o,_w,_n,_,_h,_e,_r,_e,_smc,$FD,$EB
				.BYTE	_apu,_O,_n,_c,_e,_,_a,_,_t,_o,_w,_n,_,_i,_s,_,_b,_u,_i,_l,_t,_,_i,_t,_,_w,_i,_l,_l,_,_b,_e,_,_a,_,_g,_o,_o,_d,_,_t,_h,_i,_n,_g,_,_f,_o,_r,_,_e,_v,_e,_r,_y,_o,_n,_e,_smc,$FD,$EB
				.BYTE	_apu,_B,_u,_t,_,_I,_apo,_l,_l,_,_n,_e,_e,_d,_,_s,_o,_m,_e,_,_m,_e,_r,_c,_h,_a,_n,_t,_s,_smc,$FD,$FF
_msg5CD:		.BYTE	_apu,_I,_apo,_m,_,_n,_o,_t,_,_p,_a,_r,_t,_i,_c,_u,_l,_a,_r,_dot,_,_E,_v,_e,_n,_,_i,_f,_,_s,_o,_m,_e,_o,_n,_e,_apo,_s,_,_l,_e,_v,_e,_l,_,_i,_s,_,_l,_o,_w,_sem,_,_i,_f,_,_t,_h,_e,_y,_,_b,_e,_c,_o,_m,_e,_,_a,_,_m,_e,_r,_c,_h,_a,_n,_t,_,_I,_,_w,_o,_n,_apo,_t,_,_m,_i,_n,_d,_dot,_,_A,_n,_y,_,_t,_a,_k,_e,_r,_s,_que,_apd,$EF
_msg5CE:		.BYTE	_apu,_W,_h,_a,_t,_,_d,_o,_,_y,_o,_u,_,_s,_a,_y,_sem,_,$F5,_que,_,_W,_i,_l,_l,_,_y,_o,_u,_,_a,_c,_c,_e,_p,_t,_,_t,_h,_e,_,_j,_o,_b,_que,_apd,$EF
_msg5CF:		.BYTE	_apu,_I,_,_s,_e,_e,_dot,_,_T,_h,_a,_t,_apo,_s,_,_t,_o,_o,_,_b,_a,_d,_smc,$EF
_msg5D0:		.BYTE	_apu,_R,_e,_a,_l,_l,_y,_que,_,$F5,_,_w,_i,_l,_l,_,_g,_i,_v,_e,_,_u,_p,_,_t,_h,_e,_,_j,_o,_u,_r,_n,_e,_y,_,_a,_n,_d,_,_s,_e,_t,_t,_l,_e,_,_d,_o,_w,_n,_,_i,_n,_,_t,_h,_i,_s,_,_t,_o,_w,_n,_que,_,_I,_s,_,_t,_h,_a,_t,_,_r,_e,_a,_l,_l,_y,_,_w,_h,_a,_t,_,_y,_o,_u,_,_w,_a,_n,_t,_que,_apd,$EF
_msg5D1:		.BYTE	_apu,_O,_h,_sem,_,_I,_apo,_m,_,_g,_r,_a,_t,_e,_f,_u,_l,_dot,_,_F,_r,_o,_m,_,_t,_h,_i,_s,_,_d,_a,_y,_,_f,_o,_r,_w,_a,_r,_d,_,$F5,_,_a,_n,_d,_,_I,_,_s,_h,_a,_l,_l,_,_s,_t,_a,_r,_t,_,_t,_o,_,_b,_u,_i,_l,_d,_,_a,_,_t,_o,_w,_n,_,_t,_o,_g,_e,_t,_h,_e,_r,_exc,_apd,$FD,$EF
_msg5D2:		.BYTE	$F5,_,_col,$EB
				.BYTE	_apu,_W,_e,_l,_l,_sem,_,_I,_apo,_m,_,_g,_o,_i,_n,_g,_,_t,_o,_,_s,_t,_a,_y,_,_h,_e,_r,_e,_smc,$FD,$EB
				.BYTE	_,_,_,$EB
				.BYTE	$F5,_,_col,$EB
				.BYTE	_apu,_I,_apo,_l,_l,_,_s,_e,_n,_d,_,_t,_h,_e,_,_t,_h,_i,_n,_g,_s,_,_I,_apo,_v,_e,_,_b,_e,_e,_n,_,_c,_a,_r,_r,_y,_i,_n,_g,_,_t,_o,_,_t,_h,_e,_,_V,_a,_u,_l,_t,_,_a,_t,_,_A,_l,_i,_a,_h,_a,_n,_smc,$EF
_txt_block5E:
_msg5D3:		.BYTE	_apu,_T,_h,_a,_n,_k,_s,_,_f,_o,_r,_,_m,_a,_n,_y,_,_f,_a,_v,_o,_r,_s,_dot,_,_G,_o,_o,_d,_b,_y,_e,_,$F5,_exc,_apd,$FD,$EB
				.BYTE	_apu,_I,_apo,_l,_l,_,_n,_e,_v,_e,_r,_,_f,_o,_r,_g,_e,_t,_,_o,_u,_r,_,_t,_r,_a,_v,_e,_l,_s,_,_t,_o,_g,_e,_t,_h,_e,_r,_exc,_apd,$EF
_msg5D4:		.BYTE	_apu,_H,_e,_y,_,_t,_h,_e,_r,_e,_,$F5,_exc,$EB
				.BYTE	_I,_t,_apo,_s,_,_m,_e,_sem,_,$ED,_exc,$EB
				.BYTE	_I,_apo,_v,_e,_,_c,_h,_a,_n,_g,_e,_d,_sem,_,_h,_u,_h,_que,_apd,$FD,$EB
				.BYTE	_apu,_I,_apo,_m,_,_b,_u,_i,_l,_d,_i,_n,_g,_,_a,_,_s,_h,_o,_p,_,_h,_e,_r,_e,_,_n,_o,_w,_smc,$EF
_msg5D5:		.BYTE	_apu,_H,_e,_y,_,_t,_h,_e,_r,_e,_,$F5,_exc,$EB
				.BYTE	_L,_o,_n,_g,_,_t,_i,_m,_e,_,_n,_o,_,_s,_e,_e,_exc,_,_I,_t,_apo,_s,_,_m,_e,_sem,_,$ED,_exc,_apd,$FD,$EB
				.BYTE	_apu,_J,_u,_s,_t,_,_y,_o,_u,_,_w,_a,_i,_t,_,_a,_n,_d,_,_s,_e,_e,_dot,_,_I,_apo,_m,_,_g,_o,_i,_n,_g,_,_t,_o,_,_m,_a,_k,_e,_,_t,_h,_i,_s,_,_a,_,_b,_i,_g,_,_t,_o,_w,_n,_exc,_apd,$EF
_msg5D6:		.BYTE	_apu,_H,_e,_y,_,_t,_h,_e,_r,_e,_,$F5,_exc,$EB
				.BYTE	_I,_t,_apo,_s,_,_m,_e,_sem,_,$ED,_exc,_apd,$FD,$EB
				.BYTE	_apu,_I,_apo,_m,_,_b,_u,_i,_l,_d,_i,_n,_g,_,_a,_,_t,_h,_e,_a,_t,_e,_r,_,_n,_e,_x,_t,_exc,_apd,$EF
_msg5D7:		.BYTE	_apu,_T,_h,_a,_t,_,$ED,_,_i,_s,_,_a,_,_r,_e,_a,_l,_,_w,_h,_e,_e,_l,_e,_r,_str,_d,_e,_a,_l,_e,_r,_exc,_apd,$EF
_msg5D8:		.BYTE	_apu,_W,_e,_l,_c,_o,_m,_e,_,_t,_o,_,$ED,_v,_i,_l,_l,_e,_smc,$FD,$FF
_msg5D9:		.BYTE	_apu,_T,_h,_i,_s,_,_i,_s,_,$ED,_apo,_s,_,_h,_o,_m,_e,_smc,$EF
_msg5DA:		.BYTE	_apu,_H,_e,_l,_l,_o,_,_t,_h,_e,_r,_e,_dot,_,_r,_e,_m,_e,_m,_b,_e,_r,_,_m,_e,_que,$EB
				.BYTE	_I,_apo,_m,_,_t,_h,_e,_,_o,_l,_d,_,_g,_u,_y,_,_w,_h,_o,_,_w,_a,_s,_,_h,_e,_r,_e,_,_f,_r,_o,_m,_,_t,_h,_e,_,_b,_e,_g,_i,_n,_n,_i,_n,_g,_smc,$FD,$EB
				.BYTE	_apu,$ED,_,_h,_a,_s,_,_m,_a,_d,_e,_,_p,_e,_o,_p,_l,_e,_,_w,_o,_r,_k,_,_t,_o,_o,_,_h,_a,_r,_d,_,_a,_n,_d,_,_I,_,_h,_e,_a,_r,_,_t,_h,_e,_,_t,_o,_w,_n,_s,_f,_o,_l,_k,_,_a,_r,_e,_,_r,_e,_b,_e,_l,_l,_i,_n,_g,_smc,$EF
_msg5DB:		.BYTE	_apu,$ED,_,_m,_a,_k,_e,_s,_,_u,_s,_,_t,_o,_w,_n,_s,_f,_o,_l,_k,_,_w,_o,_r,_k,_,_t,_o,_o,_,_h,_a,_r,_d,_exc,_apd,$EF
_msg5DC:		.BYTE	_apu,_H,_e,_a,_d,_i,_n,_g,_,_b,_a,_c,_k,_que,_,_W,_e,_l,_l,_,_I,_apo,_l,_l,_,_t,_a,_k,_e,_,_t,_h,_e,_,_t,_o,_l,_l,_,_f,_e,_e,_,_t,_h,_e,_n,_smc,$FD,$EB
				.BYTE	_apu,_A,_l,_l,_,_t,_o,_g,_e,_t,_h,_e,_r,_,_t,_h,_a,_t,_apo,_s,_,_5,_0,_sem,_0,_0,_0,_,_p,_i,_e,_c,_e,_s,_,_o,_f,_,_g,_o,_l,_d,_smc,$EF
_msg5DD:		.BYTE	_apu,_O,_h,_sem,_,_a,_,_f,_r,_i,_e,_n,_d,_,_o,_f,_,_M,_r,_dot,_,$ED,_apo,_s,_que,$EB
				.BYTE	_W,_e,_l,_l,_,_t,_h,_e,_n,_ddt,_dot,_sem,_,_i,_t,_apo,_s,_,_O,_K,_smc,$EF
_msg5DE:		.BYTE	_apu,$ED,_,_h,_a,_s,_,_g,_o,_n,_e,_,_t,_o,_,_b,_e,_d,_exc,_,_G,_o,_,_h,_o,_m,_e,_exc,_apd,$EF
_msg5DF:		.BYTE	_apu,_I,_,_n,_e,_e,_d,_,_t,_o,_,_m,_e,_e,_t,_,_w,_i,_t,_h,_,$ED,_,_a,_n,_d,_,_t,_e,_l,_l,_,_h,_i,_m,_,_w,_h,_a,_t,_,_t,_h,_e,_,_t,_o,_w,_n,_s,_f,_o,_l,_k,_,_a,_r,_e,_,_t,_h,_i,_n,_k,_i,_n,_g,_smc,$FD,$EB
				.BYTE	_apu,_P,_l,_e,_a,_s,_e,_,_l,_e,_t,_,_m,_e,_,_p,_a,_s,_s,_exc,_apd,$EF
_msg5E0:		.BYTE	_apu,$ED,_apo,_s,_,_w,_a,_y,_,_o,_f,_,_d,_o,_i,_n,_g,_,_t,_h,_i,_n,_g,_s,_,_i,_s,_,_u,_n,_b,_e,_a,_r,_a,_b,_l,_e,_exc,_apd,$EF
_msg5E1:		.BYTE	_apu,_H,_e,_y,_,_t,_h,_e,_r,_e,_,$F5,_exc,$EB
				.BYTE	_I,_t,_apo,_s,_,_m,_e,_sem,_,$ED,_exc,_apd,$FD,$EB
				.BYTE	_apu,_I,_,_w,_a,_s,_,_j,_u,_s,_t,_,_d,_o,_i,_n,_g,_,_t,_h,_i,_s,_,_f,_o,_r,_,_t,_h,_e,_,_s,_a,_k,_e,_,_o,_f,_,_t,_h,_e,_,_t,_o,_w,_n,_s,_f,_o,_l,_k,_,_a,_n,_d,_,_n,_o,_w,_,_i,_t,_apo,_s,_,_c,_o,_m,_e,_,_t,_o,_,_t,_h,_i,_s,_smc,$FD,$FF
_msg5E2:		.BYTE	_apu,_O,_h,_sem,_,_I,_,_a,_l,_m,_o,_s,_t,_,_f,_o,_r,_g,_o,_t,_dot,_,$EB
				.BYTE	_P,_l,_e,_a,_s,_e,_,_l,_o,_o,_k,_,_b,_e,_h,_i,_n,_d,_,_t,_h,_e,_,_c,_h,_a,_i,_r,_,_i,_n,_,_m,_y,_,_h,_o,_u,_s,_e,_smc,$FD,$FF
_txt_block5F:
_msg5E3:		.BYTE	_apu,_L,_e,_t,_apo,_s,_,_a,_l,_l,_,_h,_o,_p,_e,_,_f,_o,_r,_,$F5,_apo,_s,_,_s,_a,_f,_e,_,_c,_o,_n,_d,_u,_c,_t,_,_i,_n,_,_h,_i,_s,_,_j,_o,_u,_r,_n,_e,_y,_smc,$EF
_msg5E4:		.BYTE	_apu,_F,_i,_n,_a,_l,_l,_y,_sem,_,_a,_,_r,_e,_v,_o,_l,_u,_t,_i,_o,_n,_,_o,_c,_c,_u,_r,_r,_e,_d,_,_a,_n,_d,_,_t,_h,_e,_y,_,_t,_h,_r,_e,_w,_,$ED,_,_i,_n,_,_j,_a,_i,_l,_dot,$EB
				.BYTE	_W,_h,_o,_,_w,_o,_u,_l,_d,_,_h,_a,_v,_e,_,_t,_h,_o,_u,_g,_h,_t,_exc,_apd,$EF
_msg5E5:		.BYTE	_apu,_T,_h,_i,_n,_k,_i,_n,_g,_,_b,_a,_c,_k,_,_n,_o,_w,_sem,_,_i,_t,_,_s,_e,_e,_m,_s,_,_b,_e,_t,_t,_e,_r,_,_i,_n,_,$ED,_apo,_s,_,_t,_i,_m,_e,_smc,$EF
_msg5E6:		.BYTE	_apu,_I,_t,_apo,_s,_,_a,_,_l,_i,_e,_sem,_,_i,_s,_n,_apo,_t,_,_i,_t,_que,_,_T,_h,_a,_t,_,_y,_o,_u,_,_a,_n,_d,_,$ED,_,_u,_s,_e,_d,_,_t,_o,_,_b,_e,_,_f,_r,_i,_e,_n,_d,_s,_dot,_,_I,_t,_,_m,_u,_s,_t,_,_b,_e,_smc,$EF
_msg5E7:		.BYTE	_apu,_T,_h,_i,_s,_,_i,_s,_,_t,_h,_e,_,_t,_o,_w,_n,_,_o,_f,_,$ED,_v,_i,_l,_l,_e,_smc,$FD,$FF
_msg5E8:		.BYTE	_apu,_O,_h,_exc,_,_M,_y,_,_f,_r,_i,_e,_n,_d,_s,_exc,_,_I,_apo,_v,_e,_,_b,_e,_e,_n,_,_w,_a,_i,_t,_i,_n,_g,_,_f,_o,_r,_,_y,_o,_u,_exc,$EB
				.BYTE	_W,_o,_u,_l,_d,_,_y,_o,_u,_,_l,_i,_k,_e,_,_t,_o,_,_s,_e,_e,_,_m,_y,_,_w,_a,_r,_e,_s,_que,_apd,$EF
_msg5E9:		.BYTE	_apu,_D,_o,_n,_apo,_t,_,_b,_e,_,_t,_h,_a,_t,_,_w,_a,_y,_exc,$EB
				.BYTE	_T,_a,_k,_e,_,_a,_,_l,_o,_o,_k,_exc,_apd,$EF
_msg5EA:		.BYTE	_apu,_H,_o,_w,_apo,_s,_,_t,_h,_a,_t,_que,_,_N,_o,_t,_h,_i,_n,_g,_,_t,_o,_,_y,_o,_u,_r,_,_l,_i,_k,_i,_n,_g,_que,$EB
				.BYTE	_T,_h,_a,_t,_apo,_s,_,_t,_o,_o,_,_b,_a,_d,_dot,_,$EB
				.BYTE	_P,_l,_e,_a,_s,_e,_,_c,_o,_m,_e,_,_a,_g,_a,_i,_n,_smc,$EF
_msg5EB:		.BYTE	_apu,_O,_h,_sem,_,_y,_o,_u,_,_k,_n,_o,_w,_,_g,_o,_o,_d,_,_m,_e,_r,_c,_h,_a,_n,_d,_i,_s,_e,_exc,$EB
				.BYTE	_T,_h,_a,_t,_apo,_s,_,$F8,_,_p,_i,_e,_c,_e,$C0,_,_o,_f,_,_g,_o,_l,_d,_dot,$EB
				.BYTE	_S,_h,_a,_l,_l,_,_I,_,_w,_r,_a,_p,_,_i,_t,_,_u,_p,_,_f,_o,_r,_,_y,_o,_u,_que,_apd,$EF
_msg5EC:		.BYTE	_apu,_I,_,_s,_e,_e,_,_y,_o,_u,_apo,_r,_e,_,_g,_o,_o,_d,_,_a,_t,_,_b,_a,_r,_t,_e,_r,_i,_n,_g,_dot,$EB
				.BYTE	_Y,_o,_u,_apo,_v,_e,_,_b,_e,_s,_t,_e,_d,_,_m,_e,_smc,$FD,$FF
_msg5ED:		.BYTE	_apu,_O,_K,_sem,_,_l,_e,_t,_apo,_s,_,_m,_a,_k,_e,_,_i,_t,_,$F8,_,_p,_i,_e,_c,_e,$C0,_,_o,_f,_,_g,_o,_l,_d,_dot,$EB
				.BYTE	_I,_s,_,_t,_h,_a,_t,_,_m,_o,_r,_e,_,_t,_o,_,_y,_o,_u,_r,_,_l,_i,_k,_i,_n,_g,_que,_,_W,_i,_l,_l,_,_y,_o,_u,_,_t,_a,_k,_e,_,_i,_t,_que,_apd,$EF
_msg5EE:		.BYTE	_apu,_I,_f,_,_I,_,_g,_o,_,_a,_n,_y,_,_l,_o,_w,_e,_r,_,_I,_apo,_l,_l,_,_l,_o,_s,_e,_,_m,_o,_n,_e,_y,_exc,_,_B,_u,_t,_,_a,_g,_a,_i,_n,_sem,_,_y,_o,_u,_apo,_r,_e,_,_a,_,_f,_r,_i,_e,_n,_d,_ddt,_smc,$FD,$FF
_msg5EF:		.BYTE	_apu,_S,_h,_o,_w,_,_s,_o,_m,_e,_,_m,_e,_r,_c,_y,_exc,_,_D,_o,_,_y,_o,_u,_,_w,_a,_n,_t,_,_m,_e,_,_t,_o,_,_g,_o,_,_b,_r,_o,_k,_e,_que,_,_W,_e,_l,_l,_sem,_,_a,_l,_l,_,_r,_i,_g,_h,_t,_smc,$FD,$FF
_msg5F0:		.BYTE	_apu,_O,_h,_sem,_,_I,_,_s,_e,_e,_dot,_,_T,_o,_o,_,_b,_a,_d,_dot,$EB
				.BYTE	_C,_o,_m,_e,_,_b,_a,_c,_k,_,_a,_g,_a,_i,_n,_smc,$FF
_msg5F1:		.BYTE	_apu,_Y,_o,_u,_apo,_l,_l,_,_t,_a,_k,_e,_,_i,_t,_que,_,_M,_y,_,_e,_v,_e,_r,_l,_a,_s,_t,_i,_n,_g,_,_f,_r,_i,_e,_n,_d,_exc,$EB
				.BYTE	_D,_o,_,_c,_o,_m,_e,_,_a,_g,_a,_i,_n,_exc,_apd,$EF
_msg5F2:		.BYTE	_apu,_O,_h,_sem,_,_y,_o,_u,_apo,_r,_e,_,_a,_l,_r,_e,_a,_d,_y,_,_c,_a,_r,_r,_y,_i,_n,_g,_,_a,_l,_l,_,_y,_o,_u,_,_c,_a,_n,_dot,$EB
				.BYTE	_C,_o,_m,_e,_,_a,_g,_a,_i,_n,_,_a,_n,_o,_t,_h,_e,_r,_,_t,_i,_m,_e,_smc,$EF
_txt_block60:
_msg5F3:		.BYTE	_apu,_B,_u,_t,_sem,_,_y,_o,_u,_,_d,_o,_n,_apo,_t,_,_h,_a,_v,_e,_,_e,_n,_o,_u,_g,_h,_,_m,_o,_n,_e,_y,_exc,$EB
				.BYTE	_C,_o,_m,_e,_,_a,_g,_a,_i,_n,_,_a,_n,_o,_t,_h,_e,_r,_,_t,_i,_m,_e,_smc,$EF
_msg5F4:		.BYTE	_apu,_M,_e,_o,_w,_apd,$FD,$EB
				.BYTE	_apu,_ldt,_ddt,_que,_que,_que,_apd,$FD,$EB
				.BYTE	_apu,_U,_g,_h,_exc,_,_T,_h,_i,_s,_,_i,_s,_n,_apo,_t,_,_t,_h,_e,_,_s,_h,_a,_p,_e,_,_I,_,_w,_a,_n,_t,_e,_d,_,_t,_o,_,_c,_h,_a,_n,_g,_e,_,_i,_n,_t,_o,_exc,_,_O,_h,_,_w,_e,_l,_l,_sem,_,_i,_t,_,_d,_o,_e,_s,_n,_apo,_t,_,_m,_a,_t,_t,_e,_r,_smc,$EF
_msg5F5:		.BYTE	_apu,_A,_t,_,_a,_n,_y,_,_r,_a,_t,_e,_sem,_,_r,_e,_t,_u,_r,_n,_,_t,_h,_e,_,_D,_r,_e,_a,_m,_,_R,_u,_b,_y,_,_t,_o,_,_t,_h,_e,_,_e,_l,_v,_e,_s,_smc,$FD,$EB
				.BYTE	_apu,_I,_f,_,_y,_o,_u,_,_d,_o,_n,_apo,_t,_sem,_,_t,_h,_e,_,_s,_p,_e,_l,_l,_,_o,_n,_,_t,_h,_e,_,_v,_i,_l,_l,_a,_g,_e,_,_w,_i,_l,_l,_,_n,_e,_v,_e,_r,_,_b,_e,_,_b,_r,_o,_k,_e,_n,_exc,_apd,$FD,$EB
				.BYTE	_apu,_T,_h,_e,_,_h,_i,_d,_d,_e,_n,_,_v,_i,_l,_l,_a,_g,_e,_,_o,_f,_,_t,_h,_e,_,_e,_l,_v,_e,_s,_,_i,_s,_,_i,_n,_,_t,_h,_e,_,_w,_e,_s,_t,_,_f,_o,_r,_e,_s,_t,_smc,$EF
_msg5F6:		.BYTE	_apu,_I,_,_d,_o,_n,_apo,_t,_,_k,_n,_o,_w,_,_h,_o,_w,_,_I,_,_c,_a,_n,_,_e,_v,_e,_r,_,_t,_h,_a,_n,_k,_,_y,_o,_u,_exc,_apd,$EF
_msg5F7:		.BYTE	_apu,_D,_o,_,_y,_o,_u,_,_w,_a,_n,_t,_,_s,_o,_m,_e,_,_w,_e,_a,_p,_o,_n,_s,_que,_apd,$EF
_msg5F8:		.BYTE	_apu,_I,_f,_,_y,_o,_u,_,_d,_o,_sem,_,_c,_o,_m,_e,_,_t,_o,_,_m,_y,_,_s,_h,_o,_p,_,_d,_u,_r,_i,_n,_g,_,_t,_h,_e,_,_d,_a,_y,_smc,$EF
_msg5F9:		.BYTE	_apu,_W,_e,_l,_l,_,_t,_h,_e,_n,_sem,_,_a,_r,_m,_o,_r,_,_i,_s,_,_i,_t,_que,_apd,$EF
_msg5FA:		.BYTE	_apu,_I,_,_k,_n,_o,_w,_exc,_,_Y,_o,_u,_,_w,_a,_n,_t,_,_t,_h,_e,_,_M,_e,_t,_e,_o,_r,_i,_t,_e,_,_A,_r,_m,_b,_a,_n,_d,_exc,_,_A,_m,_,_I,_,_r,_i,_g,_h,_t,_que,_,_I,_f,_,_t,_h,_a,_t,_apo,_s,_,_s,_o,_sem,_,_I,_,_h,_e,_a,_r,_,_i,_t,_apo,_s,_,_i,_n,_,_t,_h,_e,_,_c,_a,_s,_t,_l,_e,_smc,$EF
_msg5FB:		.BYTE	_apu,_H,_e,_h,_sem,_,_h,_e,_h,_sem,_,_h,_e,_h,_exc,$EB
				.BYTE	_I,_,_a,_m,_,_t,_h,_e,_,_A,_r,_c,_h,_f,_i,_e,_n,_d,_apo,_s,_,_f,_a,_m,_i,_l,_i,_a,_r,_smc,$FD,$EB
				.BYTE	_apu,_Y,_o,_u,_apo,_l,_l,_,_m,_e,_e,_t,_,_w,_i,_t,_h,_,_a,_,_t,_r,_a,_g,_i,_c,_,_e,_n,_d,_exc,_,_H,_e,_h,_sem,_,_h,_e,_h,_,_h,_e,_h,_exc,_apd,$EF
_msg5FC:		.BYTE	_apu,_W,_o,_w,_i,_e,_exc,$EB
				.BYTE	_I,_t,_apo,_s,_,_a,_,_m,_a,_n,_exc,$EB
				.BYTE	_Z,_o,_w,_i,_e,_exc,_exc,_apd,$EF
_msg5FD:		.BYTE	$FD,$EB
				.BYTE	_apu,_A,_t,_,_l,_e,_a,_s,_t,_,_I,_,_t,_h,_o,_u,_g,_h,_t,_,_s,_o,_ddt,_dot,$EB
				.BYTE	_S,_o,_r,_r,_y,_,_I,_,_y,_e,_l,_l,_e,_d,_smc,$EF
_msg5FE:		.BYTE	_apu,_A,_r,_e,_,_y,_o,_u,_,_t,_h,_e,_,_o,_n,_e,_s,_,_w,_h,_o,_,_h,_a,_v,_e,_,_d,_i,_s,_t,_u,_r,_b,_e,_d,_,_m,_y,_,_s,_l,_u,_m,_b,_e,_r,_que,_apd,$EF
_msg5FF:		.BYTE	_apu,_O,_h,_sem,_,_n,_o,_t,_,_y,_o,_u,_sem,_,_h,_u,_h,_que,$EB
				.BYTE	_S,_o,_r,_r,_y,_dot,_,_M,_y,_,_m,_i,_s,_t,_a,_k,_e,_smc,$EF
_msg600:		.BYTE	_apu,_W,_e,_l,_l,_sem,_,_a,_r,_e,_,_y,_o,_u,_,_a,_l,_s,_o,_,_t,_h,_e,_,_p,_e,_r,_s,_o,_n,_,_w,_h,_o,_,_t,_o,_o,_k,_,_t,_h,_e,_,_c,_o,_n,_t,_e,_n,_t,_s,_,_o,_f,_,_t,_h,_e,_,_t,_r,_e,_a,_s,_u,_r,_e,_,_c,_h,_e,_s,_t,_que,_apd,$EF
_msg601:		.BYTE	_apu,_Y,_o,_u,_apo,_r,_e,_,_a,_n,_,_h,_o,_n,_e,_s,_t,_,_p,_e,_r,_s,_o,_n,_sem,_,_a,_r,_e,_n,_apo,_t,_,_y,_o,_u,_dot,_,_A,_l,_l,_,_r,_i,_g,_h,_t,_,_t,_h,_e,_n,_dot,_,_T,_h,_e,_r,_e,_,_i,_s,_,_n,_o,_t,_h,_i,_n,_g,_,_m,_o,_r,_e,_,_I,_,_n,_e,_e,_d,_smc,$FD,$EB
				.BYTE	_apu,_I,_apo,_l,_l,_,_g,_i,_v,_e,_,_i,_t,_,_t,_o,_,_y,_o,_u,_smc,$EF
_msg602:		.BYTE	_apu,_I,_,_c,_a,_n,_n,_o,_t,_,_s,_e,_l,_l,_,_a,_n,_y,_t,_h,_i,_n,_g,_,_t,_o,_,_a,_,_h,_u,_m,_a,_n,_,_b,_e,_i,_n,_g,_dot,$EB
				.BYTE	_P,_l,_e,_a,_s,_e,_,_l,_e,_a,_v,_e,_,_i,_f,_,_y,_o,_u,_,_w,_i,_l,_l,_exc,_apd,$EF
_txt_block61:
_msg603:		.BYTE	_apu,_A,_a,_h,_exc,_,_A,_,_h,_u,_m,_a,_n,_exc,$EB
				.BYTE	_I,_apo,_l,_l,_,_b,_e,_,_k,_i,_d,_n,_a,_p,_p,_e,_d,_exc,_apd,$EF
_msg604:		.BYTE	_apu,_T,_h,_e,_,_d,_w,_a,_r,_f,_,_i,_s,_,_m,_y,_,_f,_r,_i,_e,_n,_d,_smc,$EF
_msg605:		.BYTE	_apu,_T,_h,_i,_s,_,_i,_s,_,_t,_h,_e,_,_h,_i,_d,_d,_e,_n,_,_v,_i,_l,_l,_a,_g,_e,_,_o,_f,_,_t,_h,_e,_,_e,_l,_v,_e,_s,_smc,$FF
_msg606:		.BYTE	$FD,$EB
				.BYTE	_apu,_M,_y,_,_m,_o,_t,_h,_e,_r,_,_w,_i,_l,_l,_,_b,_e,_,_m,_a,_d,_,_i,_f,_,_I,_,_t,_a,_l,_k,_,_t,_o,_,_a,_,_h,_u,_m,_a,_n,_exc,_apd,$EF
_msg607:		.BYTE	_apu,_L,_o,_n,_g,_,_a,_g,_o,_,_m,_y,_,_d,_a,_u,_g,_h,_t,_e,_r,_sem,_,_A,_n,_n,_e,_sem,_,_f,_e,_l,_l,_,_i,_n,_,_l,_o,_v,_e,_,_w,_i,_t,_h,_,_a,_,_h,_u,_m,_a,_n,_smc,$FD,$EB
				.BYTE	_apu,_S,_h,_e,_,_t,_o,_o,_k,_,_t,_h,_e,_,_D,_r,_e,_a,_m,_,_R,_u,_b,_y,_,_a,_n,_d,_,_w,_e,_n,_t,_,_t,_o,_,_h,_i,_m,_sem,_,_n,_e,_v,_e,_r,_,_t,_o,_,_r,_e,_t,_u,_r,_n,_smc,$FD,$EB
				.BYTE	_apu,_A,_f,_t,_e,_r,_,_a,_l,_l,_sem,_,_w,_h,_a,_t,_,_h,_o,_p,_e,_,_d,_o,_,_a,_n,_,_e,_l,_f,_,_a,_n,_d,_,_a,_,_h,_u,_m,_a,_n,_,_h,_a,_v,_e,_que,$EB
				.BYTE	_A,_n,_n,_e,_,_m,_u,_s,_t,_,_h,_a,_v,_e,_,_b,_e,_e,_n,_,_f,_o,_o,_l,_i,_n,_g,_,_h,_e,_r,_s,_e,_l,_f,_smc,$FD,$EB
				.BYTE	_apu,_I,_,_c,_a,_n,_apo,_t,_,_s,_t,_a,_n,_d,_,_t,_h,_e,_,_s,_i,_g,_h,_t,_,_o,_f,_,_h,_u,_m,_a,_n,_s,_exc,$EB
				.BYTE	_G,_e,_t,_,_a,_w,_a,_y,_,_f,_r,_o,_m,_,_m,_e,_exc,_apd,$EF
_msg608:		.BYTE	$FD,$EB
				.BYTE	_apu,_P,_l,_e,_a,_s,_e,_,_w,_a,_i,_t,_smc,$FD,$FF
_msg609:		.BYTE	_apu,_I,_s,_,_t,_h,_a,_t,_,_w,_h,_i,_c,_h,_,_y,_o,_u,_,_c,_a,_r,_r,_y,_sem,_,_t,_h,_e,_,_D,_r,_e,_a,_m,_,_R,_u,_b,_y,_sem,_,_b,_y,_,_a,_n,_y,_,_c,_h,_a,_n,_c,_e,_que,_apd,$FD,$EB
				.BYTE	_apu,_W,_h,_a,_t,_exc,_,_A,_r,_e,_,_y,_o,_u,_,_s,_a,_y,_i,_n,_g,_,_t,_h,_a,_t,_,_A,_n,_n,_e,_,_a,_n,_d,_,_t,_h,_a,_t,_,_m,_a,_n,_,_c,_a,_s,_t,_,_t,_h,_e,_m,_s,_e,_l,_v,_e,_s,_,_i,_n,_t,_o,_,_a,_n,_,_u,_n,_d,_e,_r,_g,_r,_o,_u,_n,_d,_,_l,_a,_k,_e,_que,_exc,_apd,$FD,$EB
				.BYTE	_apu,_O,_h,_exc,_,_W,_h,_y,_,_w,_a,_s,_,_I,_,_s,_o,_,_h,_a,_r,_d,_,_o,_n,_,_t,_h,_e,_m,_que,_exc,_apd,$FD,$EB
				.BYTE	_apu,_W,_h,_a,_t,_,_a,_m,_,_I,_,_t,_o,_,_d,_o,_ddt,_smc,$FD,$EB
				.BYTE	_apu,_ldt,_ddt,_N,_o,_w,_,_I,_,_s,_e,_e,_dot,$EB
				.BYTE	_H,_e,_r,_e,_sem,_,_t,_a,_k,_e,_,_t,_h,_i,_s,_,_W,_a,_k,_e,_,_U,_p,_,_P,_o,_w,_d,_e,_r,_,_w,_i,_t,_h,_,_y,_o,_u,_,_a,_n,_d,_,_g,_o,_,_b,_a,_c,_k,_,_t,_o,_,_t,_h,_e,_,_v,_i,_l,_l,_a,_g,_e,_smc,$FD,$EB
				.BYTE	_apu,_T,_h,_e,_n,_,_y,_o,_u,_,_m,_a,_y,_,_r,_e,_m,_o,_v,_e,_,_t,_h,_e,_,_c,_u,_r,_s,_e,_dot,$EB
				.BYTE	_A,_n,_n,_e,_,_w,_o,_u,_l,_d,_,_w,_a,_n,_t,_,_i,_t,_,_t,_h,_a,_t,_,_w,_a,_y,_smc,$FD,$EB
				.BYTE	_apu,_O,_h,_sem,_,_A,_n,_n,_e,_exc,$EB
				.BYTE	_F,_o,_r,_g,_i,_v,_e,_,_y,_o,_u,_r,_,_m,_o,_t,_h,_e,_r,_exc,_apd,$EF
_msg60A:		.BYTE	_apu,_T,_h,_a,_t,_,_d,_o,_e,_s,_n,_apo,_t,_,_m,_e,_a,_n,_,_I,_,_l,_i,_k,_e,_,_h,_u,_m,_a,_n,_s,_,_n,_o,_w,_dot,$EB
				.BYTE	_G,_o,_,_n,_o,_w,_exc,_apd,$EF
_msg60B:		.BYTE	_apu,_T,_h,_a,_t,_,_t,_h,_e,_,_v,_i,_l,_l,_a,_g,_e,_,_w,_a,_s,_,_p,_u,_t,_,_t,_o,_,_s,_l,_e,_e,_p,_,_i,_s,_,_m,_y,_,_s,_o,_n,_apo,_s,_,_f,_a,_u,_l,_t,_smc,$FD,$EB
				.BYTE	_apu,_B,_e,_c,_a,_u,_s,_e,_,_h,_e,_,_e,_l,_o,_p,_e,_d,_,_w,_i,_t,_h,_,_a,_n,_,_e,_l,_f,_i,_n,_,_p,_r,_i,_n,_c,_e,_s,_s,_ddt,_smc,$FD,$EB
				.BYTE	_apu,_I,_apo,_v,_e,_,_c,_o,_m,_e,_,_h,_e,_r,_e,_,_i,_n,_,_m,_y,_,_s,_o,_n,_apo,_s,_,_p,_l,_a,_c,_e,_,_t,_o,_,_s,_e,_e,_k,_,_a,_m,_e,_n,_d,_s,_dot,_,_B,_u,_t,_,_t,_h,_e,_y,_,_w,_o,_n,_apo,_t,_,_f,_o,_r,_g,_i,_v,_e,_,_u,_s,_smc,$EF
_msg60C:		.BYTE	_apu,_T,_h,_i,_s,_,_c,_a,_n,_apo,_t,_,_b,_e,_exc,$EB
				.BYTE	_M,_y,_,_s,_o,_n,_que,_,_D,_e,_a,_d,_que,_exc,_apd,$EF
_msg60D:		.BYTE	_apu,_I,_t,_,_i,_s,_,_s,_a,_i,_d,_,_t,_h,_a,_t,_,_i,_n,_,_a,_,_c,_o,_u,_n,_t,_r,_y,_,_i,_n,_,_t,_h,_e,_,_f,_a,_r,_,_e,_a,_s,_t,_sem,_,_b,_l,_a,_c,_k,_,_p,_e,_p,_p,_e,_r,_,_m,_a,_y,_,_b,_e,_,_h,_a,_d,_,_i,_n,_,_p,_l,_e,_n,_t,_y,_smc,$FD,$EB
				.BYTE	_apu,_T,_h,_e,_r,_e,_f,_o,_r,_e,_,_I,_,_s,_a,_y,_,_u,_n,_t,_o,_,_t,_h,_e,_e,_sem,_,_g,_o,_,_y,_e,_,_t,_o,_,_t,_h,_e,_,_e,_a,_s,_t,_,_a,_n,_d,_,_r,_e,_p,_o,_r,_t,_,_b,_a,_c,_k,_,_t,_o,_,_m,_e,_,_w,_h,_a,_t,_,_t,_h,_o,_u,_,_d,_o,_s,_t,_,_e,_n,_c,_o,_u,_n,_t,_e,_r,_,_t,_h,_e,_r,_e,_smc,$FD,$EB
				.BYTE	_apu,_W,_h,_e,_n,_s,_o,_e,_v,_e,_r,_,_t,_h,_o,_u,_,_s,_h,_o,_u,_l,_d,_s,_t,_,_r,_e,_t,_u,_r,_n,_,_w,_i,_t,_h,_,_b,_l,_a,_c,_k,_,_p,_e,_p,_p,_e,_r,_sem,_,_I,_,_w,_i,_l,_t,_,_a,_c,_k,_n,_o,_w,_l,_e,_d,_g,_e,_,_t,_h,_e,_e,_,_a,_s,_,_h,_e,_r,_o,_e,_s,_,_t,_r,_u,_e,_,_a,_n,_d,_,_g,_r,_a,_n,_t,_,_t,_h,_e,_e,_,_a,_,_s,_h,_i,_p,_smc,$FD,$EB
				.BYTE	_apu,_I,_f,_,_t,_h,_o,_u,_,_w,_o,_u,_l,_d,_s,_t,_,_s,_h,_o,_w,_,_N,_o,_r,_u,_d,_,_t,_h,_i,_s,_sem,_,_m,_y,_,_s,_c,_r,_o,_l,_l,_sem,_,_h,_e,_,_w,_i,_l,_t,_,_s,_e,_r,_v,_e,_,_t,_h,_e,_e,_,_a,_s,_,_t,_h,_i,_n,_e,_,_g,_u,_i,_d,_e,_smc,$EF
_msg60E:		.BYTE	$FD,$EB
				.BYTE	_,_,_,$EB
				.BYTE	$F5,_,_t,_a,_k,_e,_s,_,_t,_h,_e,_,_s,_c,_r,_o,_l,_l,_,_f,_r,_o,_m,_,_t,_h,_e,_,_k,_i,_n,_g,_dot,$EB
				.BYTE	_apu,_T,_h,_e,_n,_sem,_,_b,_e,_,_o,_f,_f,_,_w,_i,_t,_h,_,_y,_o,_u,_exc,_apd,$EF
_msg60F:		.BYTE	_apu,_W,_h,_a,_t,_apo,_s,_,_t,_h,_e,_,_m,_a,_t,_t,_e,_r,_que,$EB
				.BYTE	_I,_,_s,_h,_a,_l,_t,_,_a,_w,_a,_i,_t,_,_t,_h,_y,_,_r,_e,_t,_u,_r,_n,_,_w,_i,_t,_h,_,_b,_l,_a,_c,_k,_,_p,_e,_p,_p,_e,_r,_smc,$EF
_msg610:		.BYTE	_apu,_I,_,_h,_a,_i,_l,_,_t,_h,_e,_e,_sem,_,$F5,_dot,_,_T,_h,_o,_u,_,_h,_a,_s,_t,_,_d,_o,_n,_e,_,_w,_e,_l,_l,_,_a,_n,_d,_,_r,_e,_t,_u,_r,_n,_e,_d,_,_w,_i,_t,_h,_,_b,_l,_a,_c,_k,_,_p,_e,_p,_p,_e,_r,_smc,$FD,$EB
				.BYTE	_apu,_A,_s,_,_p,_r,_o,_m,_i,_s,_e,_d,_sem,_,_I,_,_s,_h,_a,_l,_l,_,_g,_i,_v,_e,_,_u,_n,_t,_o,_,_t,_h,_e,_e,_,_a,_,_s,_h,_i,_p,_exc,_,_G,_o,_,_t,_h,_e,_e,_,_o,_u,_t,_,_i,_n,_,_f,_r,_o,_n,_t,_,_a,_n,_d,_,_b,_e,_h,_o,_l,_d,_exc,_apd,$EF
_msg611:		.BYTE	_apu,_I,_t,_,_i,_s,_,_i,_n,_d,_e,_e,_d,_,_g,_o,_o,_d,_sem,_,_t,_h,_i,_s,_,_p,_e,_p,_p,_e,_r,_dot,$EB
				.BYTE	_I,_,_v,_e,_r,_i,_l,_y,_,_m,_u,_s,_t,_,_h,_a,_v,_e,_,_p,_a,_r,_t,_a,_k,_e,_n,_,_i,_n,_,_e,_x,_c,_e,_s,_s,_sem,_,_f,_o,_r,_,_I,_,_a,_m,_,_s,_l,_e,_e,_p,_y,_smc,$EF
_msg612:		.BYTE	_apu,_H,_e,_a,_r,_,_y,_e,_sem,_,_w,_a,_y,_f,_a,_r,_e,_r,_s,_,_a,_l,_l,_smc,$FD,$EB
				.BYTE	_apu,_M,_y,_,_d,_e,_a,_r,_,_g,_r,_a,_n,_d,_d,_a,_u,_g,_h,_t,_e,_r,_sem,_,_T,_a,_n,_i,_a,_,_w,_a,_s,_,_k,_i,_d,_n,_a,_p,_p,_e,_d,_,_b,_y,_,_v,_i,_l,_e,_,_f,_o,_l,_k,_smc,$FD,$EB
				.BYTE	_apu,_T,_h,_a,_t,_,_y,_o,_u,_t,_h,_,_t,_h,_e,_r,_e,_,_i,_s,_,_T,_a,_n,_i,_a,_apo,_s,_,_s,_w,_e,_e,_t,_h,_e,_a,_r,_t,_sem,_,_G,_a,_l,_e,_n,_smc,$FD,$EB
				.BYTE	_apu,_I,_,_t,_h,_o,_u,_g,_h,_t,_,_t,_h,_a,_t,_,_t,_h,_e,_,_t,_w,_o,_,_o,_f,_,_t,_h,_e,_m,_,_w,_o,_u,_l,_d,_,_m,_a,_r,_r,_y,_ddt,_smc,$FD,$EB
				.BYTE	_apu,_Y,_o,_u,_,_s,_e,_e,_m,_,_t,_o,_,_b,_e,_,_s,_t,_r,_o,_n,_g,_dot,_,_W,_i,_l,_l,_,_y,_o,_u,_,_s,_a,_v,_e,_,_T,_a,_n,_i,_a,_que,_apd,$EF
_txt_block62:
_msg613:		.BYTE	_apu,_I,_f,_,_f,_o,_r,_,_s,_o,_m,_e,_,_r,_e,_a,_s,_o,_n,_,_G,_a,_l,_e,_n,_sem,_,_t,_o,_o,_sem,_,_s,_h,_o,_u,_l,_d,_,_b,_e,_,_c,_a,_p,_t,_u,_r,_e,_d,_ddt,_smc,$EF
_msg614:		.BYTE	_apu,_C,_o,_m,_e,_,_i,_n,_exc,_,_W,_e,_l,_c,_o,_m,_e,_exc,$EB
				.BYTE	_T,_h,_i,_s,_,_i,_s,_,_a,_,_p,_e,_p,_p,_e,_r,_,_s,_t,_o,_r,_e,_smc,$FD,$EB
				.BYTE	_apu,_H,_i,_,_f,_e,_l,_l,_o,_w,_s,_exc,_apd,$FD,$EB
				.BYTE	_apu,_I,_t,_apo,_s,_,_m,_e,_sem,_,_G,_a,_l,_e,_n,_exc,$EB
				.BYTE	_T,_h,_a,_n,_k,_s,_,_f,_o,_r,_,_s,_a,_v,_i,_n,_g,_,_m,_e,_exc,_apd,$FD,$EB
				.BYTE	_apu,_A,_r,_e,_,_y,_o,_u,_,_i,_n,_,_n,_e,_e,_d,_,_o,_f,_,_p,_e,_p,_p,_e,_r,_que,_apd,$EF
_msg615:		.BYTE	_apu,_H,_e,_r,_e,_,_y,_o,_u,_,_a,_r,_e,_exc,_,_I,_t,_apo,_s,_,_o,_n,_,_t,_h,_e,_,_h,_o,_u,_s,_e,_smc,$EF
_msg616:		.BYTE	_apu,_T,_a,_k,_e,_,_c,_a,_r,_e,_dot,_,_T,_h,_e,_y,_,_s,_a,_y,_,_t,_h,_e,_,_S,_h,_r,_i,_n,_e,_,_o,_f,_,_D,_h,_a,_m,_a,_,_i,_s,_,_d,_e,_e,_p,_,_i,_n,_,_t,_h,_e,_,_m,_o,_u,_n,_t,_a,_i,_n,_s,_,_o,_f,_,_t,_h,_e,_,_n,_o,_r,_t,_h,_smc,$EF
_msg617:		.BYTE	_apu,_H,_e,_y,_,_t,_h,_e,_r,_e,_exc,_,_P,_a,_p,_a,_g,_a,_t,_e,_r,_o,_exc,$EB
				.BYTE	_P,_a,_p,_a,_g,_a,_t,_e,_r,_o,_exc,_,_I,_s,_,_t,_h,_a,_t,_,_y,_o,_u,_que,_apd,$FD,$FF
_msg618:		.BYTE	_apu,_W,_h,_a,_t,_que,_,_Y,_o,_u,_apo,_r,_e,_,_n,_o,_t,_,_h,_i,_m,_que,$EB
				.BYTE	_W,_e,_l,_l,_sem,_,_y,_o,_u,_,_s,_u,_r,_e,_,_l,_o,_o,_k,_,_l,_i,_k,_e,_,_h,_i,_m,_exc,_apd,$EF
_msg619:		.BYTE	_apu,_I,_t,_apo,_s,_,_P,_a,_p,_a,_g,_a,_t,_e,_r,_o,_exc,$EB
				.BYTE	_W,_e,_l,_c,_o,_m,_e,_exc,_apd,$FD,$FF
_msg61A:		.BYTE	_apu,_H,_i,_,_t,_h,_e,_r,_e,_sem,_,_P,_a,_p,_a,_g,_a,_t,_e,_r,_o,_exc,$EB
				.BYTE	_L,_o,_n,_g,_,_t,_i,_m,_e,_,_n,_o,_,_s,_e,_e,_dot,_,_W,_h,_e,_r,_e,_,_h,_a,_v,_e,_,_y,_o,_u,_,_b,_e,_e,_n,_que,_apd,$FD,$FF
_msg61B:		.BYTE	_apu,_W,_o,_w,_exc,_,_I,_t,_apo,_s,_,_P,_a,_p,_a,_g,_a,_t,_e,_r,_o,_exc,_apd,$FD,$FF
_msg61C:		.BYTE	_apu,_M,_y,_,_n,_a,_m,_e,_,_i,_s,_,_P,_o,_p,_o,_t,_a,_smc,$FD,$EB
				.BYTE	_apu,_P,_a,_p,_a,_g,_a,_t,_e,_r,_o,_,_g,_a,_v,_e,_,_m,_e,_,_a,_,_w,_a,_t,_e,_r,_,_g,_u,_n,_,_h,_e,_,_m,_a,_d,_e,_smc,$EF
_msg61D:		.BYTE	$FD,$EB
				.BYTE	_apu,_S,_i,_n,_c,_e,_,_y,_o,_u,_,_g,_u,_y,_s,_,_r,_e,_m,_i,_n,_d,_,_m,_e,_,_o,_f,_,_P,_a,_p,_a,_g,_a,_t,_e,_r,_o,_sem,_,_I,_apo,_l,_l,_,_g,_i,_v,_e,_,_y,_o,_u,_,_t,_h,_i,_s,_smc,$EF
_msg61E:		.BYTE	_apu,_A,_r,_e,_,_y,_o,_u,_,_g,_u,_y,_s,_,_f,_r,_o,_m,_,_A,_l,_i,_a,_h,_a,_n,_,_b,_y,_,_a,_n,_y,_,_c,_h,_a,_n,_c,_e,_que,_apd,$FD,$EB
				.BYTE	_apu,_I,_,_t,_h,_o,_u,_g,_h,_t,_,_s,_o,_dot,_,_P,_a,_p,_a,_g,_a,_t,_e,_r,_o,_,_s,_a,_i,_d,_,_h,_e,_,_c,_a,_m,_e,_,_f,_r,_o,_m,_,_t,_h,_e,_r,_e,_,_t,_o,_o,_smc,$FD,$EB
				.BYTE	_apu,_I,_,_t,_h,_i,_n,_k,_,_i,_n,_,_A,_l,_i,_a,_h,_a,_n,_,_h,_e,_,_w,_e,_n,_t,_,_b,_y,_ddt,_dot,_,_O,_r,_t,_e,_g,_a,_smc,$FD,$EB
				.BYTE	_apu,_I,_,_r,_e,_m,_e,_m,_b,_e,_r,_,_h,_i,_m,_,_s,_a,_y,_i,_n,_g,_,_h,_o,_w,_,_h,_e,_,_r,_e,_g,_r,_e,_t,_t,_e,_d,_,_l,_e,_a,_v,_i,_n,_g,_,_h,_i,_s,_,$B6,_sem,_,_b,_e,_h,_i,_n,_d,_smc,$EF
_msg61F:		.BYTE	$FD,$EB
				.BYTE	_ldt,_ddt,_b,_u,_t,_,_s,_o,_m,_e,_t,_h,_i,_n,_g,_,_w,_a,_s,_,_s,_c,_r,_a,_w,_l,_e,_d,_,_o,_n,_,_t,_h,_e,_,_w,_a,_l,_l,_col,$FD,$EB
				.BYTE	_apu,_I,_,_w,_a,_n,_t,_e,_d,_,_t,_o,_,_g,_i,_v,_e,_,_s,_o,_m,_e,_o,_n,_e,_,_t,_h,_e,_,_O,_r,_b,_,_I,_,_h,_a,_d,_,_w,_h,_i,_l,_e,_,_I,_,_w,_a,_s,_,_s,_t,_i,_l,_l,_,_a,_l,_i,_v,_e,_smc,$EF
_msg620:		.BYTE	_apu,_I,_,_h,_a,_v,_e,_,_w,_a,_i,_t,_e,_d,_,_l,_o,_n,_g,_,_f,_o,_r,_,_t,_h,_i,_s,_,_d,_a,_y,_,_t,_o,_,_c,_o,_m,_e,_smc,$FD,$EB
				.BYTE	_apu,_H,_e,_r,_e,_dot,_,_T,_a,_k,_e,_,_t,_h,_i,_s,_,_O,_r,_b,_exc,_apd,$EF
_msg621:		.BYTE	_apu,_W,_e,_l,_c,_o,_m,_e,_,$F5,_exc,$EB
				.BYTE	_A,_t,_,_t,_h,_i,_s,_,_s,_h,_r,_i,_n,_e,_,_y,_o,_u,_,_m,_a,_y,_,_t,_r,_y,_,_y,_o,_u,_r,_,_c,_o,_u,_r,_a,_g,_e,_exc,_apd,$FD,$EB
				.BYTE	_apu,_I,_s,_,_t,_h,_e,_r,_e,_,_o,_n,_e,_,_a,_m,_o,_n,_g,_,_y,_o,_u,_,_w,_i,_t,_h,_,_t,_h,_e,_,_c,_o,_u,_r,_a,_g,_e,_,_t,_o,_,_f,_i,_g,_h,_t,_,_a,_l,_o,_n,_e,_que,_apd,$EF
_msg622:		.BYTE	_apu,_I,_,_r,_e,_s,_p,_e,_c,_t,_,_y,_o,_u,_r,_,_h,_o,_n,_e,_s,_t,_y,_exc,$EB
				.BYTE	_Y,_o,_u,_,_m,_a,_y,_,_l,_e,_a,_v,_e,_smc,$EF
_txt_block63:
_msg623:		.BYTE	_apu,_V,_e,_r,_y,_,_w,_e,_l,_l,_dot,_,_C,_o,_m,_e,_,_w,_i,_t,_h,_,_m,_e,_exc,_apd,$EF
_msg624:		.BYTE	_apu,_G,_o,_o,_d,_,_l,_u,_c,_k,_exc,_apd,$EF
_msg625:		.BYTE	_apu,_P,_l,_e,_a,_s,_e,_,_b,_e,_,_c,_a,_r,_e,_f,_u,_l,_exc,$EB
				.BYTE	_C,_o,_m,_e,_,_b,_a,_c,_k,_,_s,_o,_o,_n,_exc,_apd,$EF
_msg626:		.BYTE	_apu,_W,_e,_l,_l,_,_t,_h,_e,_n,_sem,_,_b,_e,_,_o,_f,_f,_,$F5,_exc,_apd,$EF
_msg627:		.BYTE	_apu,_O,_h,_sem,_,$F5,_exc,$EB
				.BYTE	_Y,_o,_u,_,_h,_a,_v,_e,_,_b,_e,_e,_n,_,_d,_e,_f,_e,_a,_t,_e,_d,_smc,$FD,$EB
				.BYTE	_apu,_W,_o,_u,_l,_d,_,_y,_o,_u,_,_l,_i,_k,_e,_,_t,_o,_,_t,_r,_y,_,_o,_n,_c,_e,_,_m,_o,_r,_e,_que,_apd,$EF
_msg628:		.BYTE	_apu,_B,_e,_,_o,_f,_f,_,_t,_h,_e,_n,_smc,$EF
_msg629:		.BYTE	$F5,_,_col,$EB
				.BYTE	_apu,_I,_,_w,_a,_s,_,_s,_o,_,_w,_o,_r,_r,_i,_e,_d,_exc,_,_I,_apo,_m,_,_s,_o,_,_g,_l,_a,_d,_,_y,_o,_u,_apo,_r,_e,_,_s,_a,_f,_e,_exc,_apd,$EE
_msg62A:		.BYTE	$F5,_,_col,$EB
				.BYTE	_apu,_Y,_o,_u,_apo,_v,_e,_,_c,_o,_m,_e,_,_b,_a,_c,_k,_exc,_,_I,_apo,_m,_,_s,_o,_,_h,_a,_p,_p,_y,_exc,_apd,$EF
_msg62B:		.BYTE	$FD,$EB
				.BYTE	_apu,_C,_o,_m,_e,_,_n,_o,_w,_dot,_,_C,_a,_l,_m,_,_d,_o,_w,_n,_sem,_,_c,_a,_l,_m,_,_d,_o,_w,_n,_ddt,_dot,_,_A,_n,_y,_w,_a,_y,_ddt,_smc,$FD,$FF
_msg62C:		.BYTE	_apu,_W,_e,_l,_c,_o,_m,_e,_,_b,_a,_c,_k,_exc,_,_I,_,_s,_e,_e,_,_y,_o,_u,_,_a,_r,_e,_,_s,_a,_f,_e,_exc,_apd,$FD,$EB
				.BYTE	_apu,_W,_e,_r,_e,_,_y,_o,_u,_,_c,_o,_u,_r,_a,_g,_e,_o,_u,_s,_que,_,_Y,_o,_u,_,_a,_r,_e,_,_t,_h,_e,_,_o,_n,_e,_,_w,_h,_o,_,_k,_n,_o,_w,_s,_,_b,_e,_s,_t,_smc,$FD,$EB
				.BYTE	_apu,_W,_e,_l,_l,_sem,_,_b,_e,_,_o,_n,_,_y,_o,_u,_r,_,_w,_a,_y,_smc,$EF
_msg62D:		.BYTE	_H,_i,_m,_i,_k,_o,_,_col,$EB
				.BYTE	_apu,_A,_r,_e,_,_y,_o,_u,_,_t,_h,_e,_,_o,_u,_t,_l,_a,_n,_d,_e,_r,_,_c,_a,_l,_l,_e,_d,_,$F5,_que,$EB
				.BYTE	_I,_,_d,_e,_s,_p,_i,_s,_e,_,_o,_u,_t,_l,_a,_n,_d,_e,_r,_s,_exc,_apd,$EF
_msg62E:		.BYTE	_apu,_B,_r,_a,_v,_e,_,$F5,_exc,$EB
				.BYTE	_Y,_o,_u,_,_a,_r,_e,_,_i,_n,_d,_e,_e,_d,_,_s,_t,_r,_o,_n,_g,_exc,_apd,$EF
_msg62F:		.BYTE	_apu,_I,_,_h,_e,_a,_r,_,_t,_h,_a,_t,_,_y,_o,_u,_,_m,_a,_y,_,_f,_i,_n,_d,_,_t,_h,_e,_,_I,_n,_v,_i,_s,_i,_b,_i,_l,_i,_t,_y,_,_H,_e,_r,_b,_,_o,_n,_,_a,_n,_,_i,_s,_l,_a,_n,_d,_,_t,_o,_,_t,_h,_e,_,_d,_i,_s,_t,_a,_n,_t,_,_s,_o,_u,_t,_h,_,_o,_f,_,_t,_h,_e,_,_t,_o,_w,_n,_,_w,_h,_e,_r,_e,_,_t,_h,_e,_,_s,_a,_c,_r,_e,_d,_,_r,_i,_v,_e,_r,_,_f,_l,_o,_w,_s,_smc,$EF
_msg630:		.BYTE	_apu,_T,_h,_a,_n,_k,_,_y,_o,_u,_,_v,_e,_r,_y,_,_m,_u,_c,_h,_exc,_apd,$EF
_msg631:		.BYTE	_apu,_I,_t,_apo,_s,_,_b,_e,_e,_n,_,_m,_a,_n,_y,_,_y,_e,_a,_r,_s,_,_s,_i,_n,_c,_e,_,_I,_apo,_v,_e,_,_m,_e,_t,_,_a,_n,_o,_t,_h,_e,_r,_,_p,_e,_r,_s,_o,_n,_smc,$FD,$EB
				.BYTE	_apu,_L,_e,_t,_,_m,_e,_,_s,_e,_e,_dot,_,_W,_h,_e,_n,_,_w,_a,_s,_,_t,_h,_e,_,_l,_a,_s,_t,_,_t,_i,_m,_e,_que,$EB
				.BYTE	_I,_t,_,_w,_a,_s,_,_t,_h,_a,_t,_,_t,_i,_m,_e,_,_t,_h,_e,_,_p,_i,_r,_a,_t,_e,_s,_,_c,_a,_m,_e,_,_a,_n,_d,_,_l,_e,_f,_t,_,_a,_,_s,_t,_r,_a,_n,_g,_e,_,_b,_o,_n,_e,_smc,$FD,$EB
				.BYTE	_apu,_W,_e,_l,_l,_sem,_,_n,_e,_v,_e,_r,_,_m,_i,_n,_d,_dot,$EB
				.BYTE	_B,_y,_,_t,_h,_e,_,_w,_a,_y,_sem,_,_d,_o,_,_y,_o,_u,_,_k,_n,_o,_w,_,_a,_n,_y,_t,_h,_i,_n,_g,_,_a,_b,_o,_u,_t,_,_t,_h,_e,_,_S,_t,_a,_f,_f,_,_o,_f,_,_C,_h,_a,_n,_g,_e,_que,_apd,$FF
_msg632:		.BYTE	_apu,_R,_e,_a,_l,_l,_y,_exc,_que,_,_I,_s,_,_t,_h,_a,_t,_,_t,_r,_u,_e,_exc,_que,$EB
				.BYTE	_W,_e,_l,_l,_sem,_,_t,_h,_a,_t,_apo,_s,_,_w,_h,_a,_t,_,_I,_,_w,_a,_n,_t,_dot,_,_H,_a,_sem,_,_h,_a,_sem,_,_h,_a,_smc,$EF
_txt_block64:
_msg633:		.BYTE	_apu,_W,_i,_t,_h,_,_t,_h,_a,_t,_,_s,_t,_a,_f,_f,_,_y,_o,_u,_,_c,_a,_n,_,_c,_h,_a,_n,_g,_e,_,_y,_o,_u,_r,_,_s,_h,_a,_p,_e,_,_i,_n,_t,_o,_,_a,_n,_y,_t,_h,_i,_n,_g,_,_y,_o,_u,_,_l,_i,_k,_e,_dot,_,_I,_,_h,_e,_a,_r,_,_t,_e,_l,_l,_,_t,_h,_a,_t,_,_t,_h,_e,_,_k,_i,_n,_g,_,_o,_f,_,_S,_a,_m,_a,_n,_a,_o,_,_h,_a,_s,_,_i,_t,_smc,$EF
_msg634:		.BYTE	_apu,_A,_h,_exc,_,_T,_h,_a,_t,_apo,_s,_,_t,_h,_e,_,_S,_t,_a,_f,_f,_,_o,_f,_,_C,_h,_a,_n,_g,_e,_exc,_,_I,_apo,_v,_e,_,_b,_e,_e,_n,_,_w,_a,_n,_t,_i,_n,_g,_,_t,_h,_a,_t,_,_t,_o,_o,_smc,$FD,$EB
				.BYTE	_apu,_H,_o,_w,_,_a,_b,_o,_u,_t,_,_t,_h,_i,_s,_dot,_,_W,_h,_a,_t,_,_i,_f,_,_I,_,_t,_r,_a,_d,_e,_,_y,_o,_u,_,_t,_h,_i,_s,_,_S,_a,_i,_l,_o,_r,_apo,_s,_,_T,_h,_i,_g,_h,_,_B,_o,_n,_e,_,_f,_o,_r,_,_t,_h,_a,_t,_,_S,_t,_a,_f,_f,_,_o,_f,_,_C,_h,_a,_n,_g,_e,_que,_apd,$EF
_msg635:		.BYTE	_apu,_R,_e,_a,_l,_l,_y,_exc,_,_A,_r,_e,_,_y,_o,_u,_,_s,_e,_r,_i,_o,_u,_s,_que,$EB
				.BYTE	_A,_s,_k,_,_a,_n,_d,_,_y,_e,_,_s,_h,_a,_l,_l,_,_r,_e,_c,_e,_i,_v,_e,_sem,_,_t,_h,_e,_y,_,_s,_a,_y,_exc,_apd,$FD,$FF
_msg636:		.BYTE	_apu,_O,_h,_sem,_,_t,_h,_a,_n,_k,_s,_exc,_,_H,_e,_h,_sem,_,_h,_e,_h,_sem,_,_h,_e,_h,_exc,_apd,$EF
_msg637:		.BYTE	_apu,_O,_h,_sem,_,_n,_o,_t,_,_i,_n,_t,_e,_r,_e,_s,_t,_e,_d,_sem,_,_h,_u,_h,_que,_,_I,_,_t,_h,_o,_u,_g,_h,_t,_,_a,_s,_,_m,_u,_c,_h,_smc,$EF
_msg638:		.BYTE	_apu,_I,_t,_apo,_s,_,_m,_e,_exc,_,_I,_t,_apo,_s,_,_m,_e,_exc,_,_H,_e,_h,_sem,_,_h,_e,_h,_sem,_,_h,_e,_h,_exc,_apd,$EF
_msg639:		.BYTE	_apu,_T,_h,_e,_,_S,_t,_a,_f,_f,_,_o,_f,_,_C,_h,_a,_n,_g,_e,_,_i,_s,_,_w,_h,_a,_t,_,_h,_a,_s,_,_m,_a,_d,_e,_,_t,_h,_e,_,_k,_i,_n,_g,_,_s,_t,_r,_a,_n,_g,_e,_smc,$FD,$EB
				.BYTE	_apu,_T,_h,_a,_t,_apo,_s,_,_w,_h,_a,_t,_,_I,_,_t,_h,_i,_n,_k,_,_a,_n,_y,_w,_a,_y,_dot,_,_W,_h,_a,_t,_,_a,_b,_o,_u,_t,_,_y,_o,_u,_que,_apd,$EF
_msg63A:		.BYTE	_apu,_A,_s,_,_I,_,_t,_h,_o,_u,_g,_h,_t,_dot,_,_I,_,_t,_h,_o,_u,_g,_h,_t,_,_y,_o,_u,_apo,_d,_,_s,_a,_y,_,_t,_h,_a,_t,_smc,$EF
_msg63B:		.BYTE	_apu,_H,_e,_h,_sem,_,_h,_e,_h,_sem,_,_h,_e,_h,_dot,_,_Y,_o,_u,_apo,_r,_e,_,_w,_r,_o,_n,_g,_,_I,_apo,_m,_,_a,_f,_r,_a,_i,_d,_dot,_,_G,_o,_,_i,_n,_,_t,_h,_a,_t,_,_d,_i,_r,_e,_c,_t,_i,_o,_n,_smc,$EF
_msg63C:		.BYTE	_apu,_Z,_z,_z,_ddt,_dot,_,_M,_m,_m,_ddt,_dot,$FD,$EB
				.BYTE	_,_,_,$EB
				.BYTE	_T,_h,_e,_,_k,_i,_n,_g,_,_s,_u,_r,_e,_,_h,_a,_s,_,_b,_e,_e,_n,_,_s,_t,_r,_a,_n,_g,_e,_,_l,_a,_t,_e,_l,_y,_dot,_,_B,_u,_t,_,_I,_,_c,_a,_n,_apo,_t,_,_d,_e,_f,_y,_,_t,_h,_e,_,_k,_i,_n,_g,_smc,$FD,$EB
				.BYTE	_apu,_I,_,_c,_a,_n,_apo,_t,_,_l,_e,_a,_v,_e,_sem,_,_b,_u,_t,_,_t,_h,_e,_,_r,_u,_m,_o,_r,_s,_,_s,_a,_y,_,_t,_h,_e,_r,_e,_,_m,_a,_y,_,_b,_e,_,_a,_n,_,_e,_s,_c,_a,_p,_e,_,_p,_a,_s,_s,_a,_g,_e,_,_f,_r,_o,_m,_,_t,_h,_i,_s,_,_d,_u,_n,_g,_e,_o,_n,_dot,_,_Z,_z,_z,_ddt,_smc,$EF
_msg63D:		.BYTE	_apu,_W,_e,_l,_l,_que,_,_W,_a,_s,_,_m,_y,_,_g,_u,_e,_s,_s,_,_r,_i,_g,_h,_t,_que,_apd,$EF
_msg63E:		.BYTE	_apu,_A,_h,_sem,_,_t,_o,_,_b,_e,_,_a,_b,_l,_e,_,_t,_o,_,_m,_e,_e,_t,_,_m,_y,_,_C,_a,_r,_l,_o,_s,_,_a,_g,_a,_i,_n,_exc,$EB
				.BYTE	_T,_h,_a,_n,_k,_,_y,_o,_u,_,_s,_o,_sem,_,_s,_o,_,_m,_u,_c,_h,_smc,$FD,$EB
				.BYTE	_apu,_O,_h,_sem,_,_h,_o,_w,_,_s,_i,_l,_l,_y,_,_o,_f,_,_m,_e,_dot,$EB
				.BYTE	_A,_s,_,_a,_,_t,_o,_k,_e,_n,_,_o,_f,_,_m,_y,_,_a,_p,_p,_r,_e,_c,_i,_a,_t,_i,_o,_n,_sem,_,_I,_,_g,_i,_v,_e,_,_y,_o,_u,_,_t,_h,_i,_s,_,_S,_w,_o,_r,_d,_,_o,_f,_,_I,_l,_l,_u,_s,_i,_o,_n,_smc,$FD,$FF
_msg63F:		.BYTE	_apu,_H,_i,_,_y,_o,_u,_,_g,_u,_y,_s,_exc,_,_C,_o,_m,_e,_,_i,_n,_exc,_,_C,_o,_m,_e,_,_i,_n,_exc,_apd,$EF
_msg640:		.BYTE	_apu,_I,_apo,_m,_,_a,_m,_a,_z,_e,_d,_,_y,_o,_u,_apo,_v,_e,_,_m,_a,_d,_e,_,_i,_t,_,_t,_h,_i,_s,_,_f,_a,_r,_exc,_apd,$FD,$FF
_msg641:		.BYTE	_apu,_Y,_o,_u,_,_c,_a,_n,_,_s,_u,_r,_e,_l,_y,_,_d,_e,_f,_e,_a,_t,_,_t,_h,_e,_,_A,_r,_c,_h,_f,_i,_e,_n,_d,_exc,_apd,$EF
_msg642:		.BYTE	$FD,$EB
				.BYTE	_apu,_H,_e,_r,_e,_exc,_,_T,_a,_k,_e,_,_w,_i,_t,_h,_,_y,_o,_u,_,_t,_h,_i,_s,_,_S,_i,_l,_v,_e,_r,_,_O,_r,_b,_exc,_apd,$EF
_txt_block65:
_msg643:		.BYTE	_apu,_C,_a,_c,_k,_l,_e,_sem,_,_c,_a,_c,_k,_l,_e,_exc,_,_H,_o,_w,_,_a,_p,_p,_r,_o,_p,_r,_i,_a,_t,_e,_exc,_,_C,_o,_r,_p,_s,_e,_s,_,_o,_n,_,_t,_h,_e,_,_P,_h,_a,_n,_t,_o,_m,_,_S,_h,_i,_p,_exc,_apd,$EF
_msg644:		.BYTE	_apu,_M,_e,_o,_w,_que,_apd,$EF
_msg645:		.BYTE	_apu,_F,_r,_o,_m,_,_h,_e,_r,_e,_,_g,_o,_,_s,_o,_u,_t,_h,_,_a,_n,_d,_,_e,_x,_p,_l,_o,_r,_e,_,_t,_h,_e,_,_m,_i,_d,_s,_t,_,_o,_f,_,_t,_h,_e,_,_f,_o,_u,_r,_,_m,_o,_u,_n,_t,_a,_i,_n,_s,_dot,_,_M,_e,_o,_w,_exc,_apd,$EF
_msg646:		.BYTE	_apu,_Y,_o,_u,_,_s,_t,_a,_n,_d,_,_b,_e,_f,_o,_r,_e,_,_t,_h,_e,_,_D,_r,_a,_g,_o,_n,_,_Q,_u,_e,_e,_n,_ddt,_smc,$FD,$EB
				.BYTE	_apu,_I,_f,_,_t,_h,_o,_u,_,_p,_o,_s,_s,_e,_s,_s,_,_t,_h,_e,_,_c,_o,_u,_r,_a,_g,_e,_,_t,_o,_,_d,_o,_,_b,_a,_t,_t,_l,_e,_,_w,_i,_t,_h,_,_t,_h,_e,_,_A,_r,_c,_h,_f,_i,_e,_n,_d,_sem,_,_I,_,_w,_i,_l,_l,_,_g,_i,_v,_e,_,_u,_n,_t,_o,_,_t,_h,_e,_e,_,_t,_h,_e,_,_S,_p,_h,_e,_r,_e,_,_o,_f,_,_L,_i,_g,_h,_t,_exc,_apd,$EE
_msg647:		.BYTE	$FD,$EB
				.BYTE	_apu,_I,_,_h,_o,_p,_e,_sem,_,_w,_i,_t,_h,_,_t,_h,_i,_s,_,_S,_p,_h,_e,_r,_e,_,_o,_f,_,_L,_i,_g,_h,_t,_sem,_,_t,_h,_a,_t,_,_t,_h,_o,_u,_,_c,_a,_n,_s,_t,_,_h,_a,_s,_t,_e,_n,_,_t,_h,_e,_,_r,_e,_t,_u,_r,_n,_,_o,_f,_,_p,_e,_a,_c,_e,_,_t,_o,_,_t,_h,_i,_s,_,_l,_a,_n,_d,_smc,$FD,$EB
				.BYTE	_apu,_F,_o,_r,_,_I,_sem,_,_t,_o,_o,_sem,_,_a,_m,_,_w,_i,_t,_h,_,_c,_h,_i,_l,_d,_ddt,_smc,$FD,$EF
_msg648:		.BYTE	_apu,_O,_u,_g,_h,_exc,_apd,$EF
_msg649:		.BYTE	_apu,_W,_e,_,_a,_r,_e,$FD,$EB
				.BYTE	_apu,_W,_e,_,_a,_r,_e,$FD,$EB
				.BYTE	_,_,_,$EB
				.BYTE	_ldt,_ddt,_p,_r,_o,_t,_e,_c,_t,_i,_n,_g,_,_t,_h,_e,_,_e,_g,_g,_dot,$FD,$EB
				.BYTE	_,_,_,$EB
				.BYTE	_ldt,_ddt,_p,_r,_o,_t,_e,_c,_t,_i,_n,_g,_,_t,_h,_e,_,_e,_g,_g,_smc,$FD,$EB
				.BYTE	_apu,_W,_h,_e,_n,_,_t,_h,_e,_,_S,_i,_x,_,_O,_r,_b,_s,_,_a,_r,_e,_,_p,_l,_a,_c,_e,_d,_,_o,_n,_,_t,_h,_e,_,_T,_h,_r,_o,_n,_e,_,_o,_f,_,_t,_h,_e,_,_G,_o,_l,_d,_e,_n,_,_C,_r,_o,_w,_n,$FD,$EB
				.BYTE	_,_,_,$EB
				.BYTE	_t,_h,_e,_,_l,_e,_g,_e,_n,_d,_a,_r,_y,_,_p,_h,_o,_e,_n,_i,_x,_sem,_,_R,_a,_m,_i,_a,_sem,_,_w,_i,_l,_l,_,_c,_o,_m,_e,_,_b,_a,_c,_k,_,_t,_o,_,_l,_i,_f,_e,_smc,$EF
_msg64A:		.BYTE	$FD,$EB
				.BYTE	_apu,_Y,_o,_u,_,_h,_a,_v,_e,_,_a,_l,_r,_e,_a,_d,_y,_,_p,_l,_a,_c,_e,_d,_,_t,_h,_e,$FD,$FF
_msg64B:		.BYTE	$B8,_S,_i,_l,_v,_e,_r,_,_O,_r,_b,$FD,$FF
_msg64C:		.BYTE	$B8,_R,_e,_d,_,_O,_r,_b,$FD,$FF
_msg64D:		.BYTE	$B8,_Y,_e,_l,_l,_o,_w,_,_O,_r,_b,$FD,$FF
_msg64E:		.BYTE	$B8,_P,_u,_r,_p,_l,_e,_,_O,_r,_b,$FD,$FF
_msg64F:		.BYTE	$B8,_B,_l,_u,_e,_,_O,_r,_b,$FD,$FF
_msg650:		.BYTE	$B8,_G,_r,_e,_e,_n,_,_O,_r,_b,$FD,$FF
_msg651:		.BYTE	$B8,_o,_n,_,_t,_h,_e,_,_t,_h,_r,_o,_n,_e,_,_a,_s,_,_a,_n,_,_o,_f,_f,_e,_r,_i,_n,_g,_smc,$EF
_msg652:		.BYTE	_apu,_S,_o,_,_t,_h,_o,_u,_,_h,_a,_s,_t,_,_f,_i,_n,_a,_l,_l,_y,_,_m,_a,_d,_e,_,_i,_t,_,_h,_e,_r,_e,_sem,_,_e,_h,_,$F5,_que,_apd,$FD,$EB
				.BYTE	_apu,_B,_u,_t,_sem,_,_a,_l,_a,_s,_sem,_,_t,_o,_o,_,_s,_o,_o,_n,_dot,_,_F,_o,_r,_,_t,_h,_o,_u,_,_a,_n,_d,_,_t,_h,_i,_n,_e,_,_d,_o,_,_n,_o,_t,_,_y,_e,_t,_,_k,_n,_o,_w,_,_t,_h,_y,_s,_e,_l,_v,_e,_s,_,_w,_e,_l,_l,_,_e,_n,_o,_u,_g,_h,_,_t,_o,_,_o,_p,_p,_o,_s,_e,_,_t,_h,_e,_,_A,_r,_c,_h,_f,_i,_e,_n,_d,_,_B,_a,_r,_a,_m,_o,_s,_exc,_apd,$FD,$EB
				.BYTE	_apu,_T,_h,_o,_u,_,_w,_i,_l,_t,_,_r,_e,_g,_r,_e,_t,_,_t,_h,_y,_,_c,_o,_m,_i,_n,_g,_,_i,_n,_d,_e,_e,_d,_exc,_apd,$FD,$EB
				.BYTE	_apu,_Y,_o,_u,_,_s,_h,_a,_l,_l,_,_b,_e,_,_d,_e,_a,_d,_,_f,_o,_r,_,_g,_o,_o,_d,_sem,_,_f,_o,_r,_,_I,_,_w,_i,_l,_t,_,_s,_u,_r,_e,_l,_y,_,_f,_e,_a,_s,_t,_,_o,_n,_,_t,_h,_i,_n,_e,_,_i,_n,_n,_a,_r,_d,_s,_exc,_apd,$EF
_txt_block66:
_msg653:		.BYTE	_T,_h,_e,_,_A,_r,_c,_h,_f,_i,_e,_n,_d,_,_B,_a,_r,_a,_m,_o,_s,_,_s,_h,_a,_t,_t,_e,_r,_e,_d,_,_i,_n,_t,_o,_,_l,_i,_t,_t,_l,_e,_,_p,_i,_e,_c,_e,_s,_exc,$EF
_msg654:		.BYTE	_apu,$F5,_,_i,_s,_,_n,_o,_w,_,_s,_t,_r,_o,_n,_g,_,_e,_n,_o,_u,_g,_h,_exc,_apd,$FD,$FF
_msg655:		.BYTE	_apu,_G,_o,_o,_d,_,_f,_o,_r,_t,_u,_n,_e,_,_b,_e,_,_w,_i,_t,_h,_,_t,_h,_e,_s,_e,_,_b,_r,_a,_v,_e,_,_s,_o,_u,_l,_s,_,_f,_r,_o,_m,_,_a,_,_f,_a,_r,_,_o,_f,_f,_,_l,_a,_n,_d,_exc,_apd,$EF
_msg656:		.BYTE	_apu,_B,_r,_a,_v,_e,_,_h,_e,_r,_o,_sem,_,$F5,_exc,_,_P,_l,_e,_a,_s,_e,_,_a,_l,_l,_o,_w,_,_m,_e,_,_t,_o,_,_s,_i,_n,_g,_,_y,_o,_u,_r,_,_p,_r,_a,_i,_s,_e,_s,_exc,_apd,$FD,$EB
				.BYTE	_apu,_ldt,_ddt,_F,_r,_o,_m,_,_d,_i,_s,_t,_a,_n,_t,_,_s,_h,_o,_r,_e,_s,_,_f,_a,_r,_,_f,_a,_r,_,_a,_w,_a,_y,$EB
				.BYTE	_C,_a,_m,_e,_,_t,_h,_e,_,_h,_e,_r,_o,_sem,_,$F5,_sem,_,_l,_a,_sem,_,_l,_a,_str,_d,_i,_str,_l,_a,_y,_ddt,_smc,$EF
_msg657:		.BYTE	_apu,_T,_h,_i,_s,_,_i,_s,_,_a,_,_S,_h,_r,_i,_n,_e,_,_o,_f,_,_H,_o,_n,_o,_r,_smc,$FD,$FF
_msg658:		.BYTE	_apu,_W,_e,_l,_c,_o,_m,_e,_exc,_,_W,_e,_l,_c,_o,_m,_e,_exc,$EB
				.BYTE	_N,_o,_w,_,_i,_t,_,_i,_s,_,_t,_h,_e,_,_t,_i,_m,_e,_,_t,_h,_a,_t,_,_s,_u,_n,_s,_h,_i,_n,_e,_,_a,_n,_d,_,_r,_a,_i,_n,_,_d,_o,_,_m,_e,_e,_t,_smc,$FD,$EB
				.BYTE	_apu,_I,_,_g,_i,_v,_e,_,_u,_n,_t,_o,_,_t,_h,_e,_e,_,_t,_h,_i,_s,_,_R,_a,_i,_n,_b,_o,_w,_,_D,_r,_o,_p,_exc,_apd,$EF
_msg659:		.BYTE	_apu,_W,_h,_e,_n,_,_s,_u,_n,_s,_h,_i,_n,_e,_,_a,_n,_d,_,_r,_a,_i,_n,_,_d,_o,_,_m,_e,_e,_t,_sem,_,_a,_,_R,_a,_i,_n,_b,_o,_w,_,_B,_r,_i,_d,_g,_e,_,_i,_s,_,_m,_a,_d,_e,_smc,$FD,$EB
				.BYTE	_apu,_G,_o,_,_t,_h,_e,_n,_,_a,_n,_d,_,_s,_e,_a,_r,_c,_h,_,_f,_o,_r,_,_t,_h,_a,_t,_smc,$EF
_msg65A:		.BYTE	_apu,_I,_f,_,_t,_h,_o,_u,_,_w,_e,_r,_e,_,_a,_,_h,_e,_r,_o,_,_t,_r,_u,_e,_sem,_,_t,_h,_e,_,_S,_a,_c,_r,_e,_d,_,_A,_m,_u,_l,_e,_t,_,_t,_h,_o,_u,_,_w,_o,_u,_l,_d,_s,_t,_,_c,_a,_r,_r,_y,_sem,_,_t,_h,_e,_r,_e,_f,_o,_r,_e,_sem,_,_a,_s,_,_p,_r,_o,_o,_f,_smc,$FD,$EB
				.BYTE	_apu,_S,_i,_n,_c,_e,_,_t,_h,_o,_u,_,_d,_o,_s,_t,_,_n,_o,_t,_sem,_,_I,_,_p,_r,_i,_t,_h,_e,_e,_,_d,_e,_p,_a,_r,_t,_,_t,_o,_,_r,_e,_t,_u,_r,_n,_,_a,_n,_e,_w,_smc,$EF
_msg65B:		.BYTE	_apu,_I,_apo,_m,_,_t,_h,_e,_,_f,_a,_i,_r,_y,_,_s,_p,_i,_r,_i,_t,_,_t,_h,_a,_t,_,_o,_n,_c,_e,_,_s,_e,_r,_v,_e,_d,_,_R,_u,_b,_i,_s,_s,_smc,$FD,$EB
				.BYTE	_apu,_I,_,_g,_i,_v,_e,_,_y,_o,_u,_,_t,_h,_i,_s,_,_S,_t,_a,_f,_f,_,_o,_f,_,_R,_a,_i,_n,_dot,_,_M,_a,_y,_,_f,_o,_r,_t,_u,_n,_e,_,_b,_e,_,_w,_i,_t,_h,_,_y,_o,_u,_exc,_apd,$EF
_msg65C:		.BYTE	_apu,_W,_o,_u,_l,_d,_,_y,_o,_u,_,_s,_h,_o,_w,_,_m,_e,_,_t,_h,_e,_,_M,_a,_g,_i,_c,_,_K,_e,_y,_,_t,_h,_a,_t,_,_y,_o,_u,_,_h,_a,_v,_e,_que,_apd,$FD,$EB
				.BYTE	_apu,_O,_h,_sem,_,_t,_h,_i,_s,_,_i,_s,_,_i,_t,_que,$EB
				.BYTE	_I,_apo,_m,_,_t,_h,_i,_n,_k,_i,_n,_g,_,_o,_f,_,_m,_a,_k,_i,_n,_g,_,_t,_h,_e,_,_s,_a,_m,_e,_,_t,_h,_i,_n,_g,_,_a,_n,_d,_,_s,_e,_l,_l,_i,_n,_g,_,_i,_t,_smc,$EF
_msg65D:		.BYTE	_apu,_I,_apo,_d,_,_s,_u,_r,_e,_,_l,_i,_k,_e,_,_t,_o,_,_t,_a,_k,_e,_,_a,_,_l,_o,_o,_k,_,_a,_t,_,_t,_h,_e,_,_M,_a,_g,_i,_c,_,_K,_e,_y,_,_a,_t,_,_l,_e,_a,_s,_t,_,_o,_n,_c,_e,_,_i,_n,_,_m,_y,_,_l,_i,_f,_e,_smc,$EF
_msg65E:		.BYTE	_apu,_Y,_o,_u,_,_j,_u,_s,_t,_,_c,_a,_n,_apo,_t,_,_d,_e,_f,_e,_a,_t,_,_t,_h,_e,_,_A,_r,_c,_h,_f,_i,_e,_n,_d,_,_u,_n,_l,_e,_s,_s,_,_y,_o,_u,_,_h,_a,_v,_e,_,_t,_h,_e,_,_S,_p,_h,_e,_r,_e,_,_o,_f,_,_L,_i,_g,_h,_t,_exc,_apd,$EF
_msg65F:		.BYTE	$FD,$EB
				.BYTE	_apu,_B,_u,_t,_sem,_,_s,_a,_d,_,_a,_s,_,_i,_t,_,_i,_s,_sem,_,_t,_h,_e,_,_S,_p,_h,_e,_r,_e,_,_o,_f,_,_L,_i,_g,_h,_t,_,_c,_a,_n,_n,_o,_t,_,_b,_e,_,_f,_o,_u,_n,_d,_,_a,_n,_y,_w,_h,_e,_r,_e,_,_i,_n,_,_A,_l,_e,_f,_g,_a,_r,_d,_smc,$EF
_msg660:		.BYTE	_apu,_T,_h,_i,_s,_,_i,_s,_,_t,_h,_e,_,_C,_a,_v,_e,_,_o,_f,_,_E,_n,_t,_i,_c,_e,_m,_e,_n,_t,_dot,_,_B,_u,_t,_,_t,_h,_e,_,_s,_t,_a,_i,_r,_w,_a,_y,_,_i,_s,_,_s,_e,_a,_l,_e,_d,_,_o,_f,_f,_,_b,_y,_,_a,_,_s,_t,_o,_n,_e,_,_w,_a,_l,_l,_smc,$EF
_msg661:		.BYTE	_apu,_T,_h,_i,_s,_,_i,_s,_,_t,_h,_e,_,_C,_a,_v,_e,_,_o,_f,_,_E,_n,_t,_i,_c,_e,_m,_e,_n,_t,_dot,_,_T,_h,_e,_,_s,_e,_a,_l,_,_h,_a,_s,_,_a,_l,_r,_e,_a,_d,_y,_,_b,_e,_e,_n,_,_b,_r,_o,_k,_e,_n,_exc,_apd,$EF
_msg662:		.BYTE	_apu,_S,_o,_sem,_,_y,_o,_u,_,_h,_a,_v,_e,_,_c,_o,_m,_e,_sem,_,$F5,_exc,_apd,$FD,$EB
				.BYTE	_apu,_I,_,_d,_r,_e,_a,_m,_e,_d,_,_t,_h,_a,_t,_,_I,_,_g,_a,_v,_e,_,_y,_o,_u,_,_t,_h,_i,_s,_,_k,_e,_y,_smc,$FD,$EB
				.BYTE	_apu,_S,_o,_,_I,_,_g,_i,_v,_e,_,_y,_o,_u,_,_t,_h,_e,_,_T,_h,_i,_e,_f,_apo,_s,_,_K,_e,_y,_dot,_,_D,_o,_,_y,_o,_u,_,_a,_c,_c,_e,_p,_t,_,_i,_t,_que,_apd,$EF
_txt_block67:
_msg663:		.BYTE	_apu,_W,_e,_l,_l,_,_t,_h,_e,_n,_sem,_,_b,_e,_,_o,_f,_f,_,_w,_i,_t,_h,_,_y,_o,_u,_,$F5,_exc,$EB
				.BYTE	_I,_apo,_l,_l,_,_g,_o,_,_b,_a,_c,_k,_,_t,_o,_,_m,_y,_,_d,_r,_e,_a,_m,_i,_n,_g,_smc,$EF
_msg664:		.BYTE	_apu,_I,_,_s,_e,_e,_dot,_,_E,_v,_e,_n,_,_m,_y,_,_d,_r,_e,_a,_m,_s,_,_s,_o,_m,_e,_t,_i,_m,_e,_s,_,_d,_o,_n,_apo,_t,_,_c,_o,_m,_e,_,_t,_r,_u,_e,_ddt,_smc,$EF
_msg665:		.BYTE	_apu,_W,_e,_l,_c,_o,_m,_e,_,$F5,_dot,$EB
				.BYTE	_D,_i,_d,_,_t,_h,_e,_,_k,_e,_y,_,_c,_o,_m,_e,_,_i,_n,_,_h,_a,_n,_d,_y,_que,_apd,$EF
_msg666:		.BYTE	_apu,_S,_e,_e,_exc,_,_M,_y,_,_d,_r,_e,_a,_m,_s,_,_o,_f,_t,_e,_n,_,_d,_o,_,_c,_o,_m,_e,_,_t,_r,_u,_e,_exc,_apd,$EF
_msg667:		.BYTE	_apu,_E,_v,_e,_n,_,_m,_y,_,_d,_r,_e,_a,_m,_s,_,_s,_o,_m,_e,_t,_i,_m,_e,_s,_,_d,_o,_n,_apo,_t,_,_c,_o,_m,_e,_,_t,_r,_u,_e,_ddt,_smc,$EF
_msg668:		.BYTE	_apu,_Z,_z,_z,_ddt,_dot,_,_Z,_z,_z,_ddt,_dot,$EB
				.BYTE	_S,_o,_m,_e,_t,_h,_i,_n,_g,_ddt,_dot,_,_s,_o,_,_b,_r,_i,_g,_h,_t,_ddt,_dot,$EB
				.BYTE	_b,_u,_t,_,_i,_t,_apo,_s,_,_a,_,_d,_r,_e,_a,_m,_ddt,_dot,_,_M,_u,_m,_b,_l,_e,_ddt,_dot,_,_m,_u,_m,_b,_l,_e,_smc,$EF
_msg669:		.BYTE	_apu,_W,_h,_a,_t,_exc,_,_Y,_o,_u,_,_d,_e,_f,_e,_a,_t,_e,_d,_,_t,_h,_e,_,_A,_r,_c,_h,_f,_i,_e,_n,_d,_,_B,_a,_r,_a,_m,_o,_s,_exc,_que,_,_Y,_o,_u,_,_a,_r,_e,_,_i,_n,_d,_e,_e,_d,_,_h,_e,_r,_o,_e,_s,_,_t,_r,_u,_e,_exc,_apd,$EF
_msg66A:		.BYTE	_apu,_W,_e,_l,_c,_o,_m,_e,_,_b,_a,_c,_k,_,_t,_o,_,_A,_l,_i,_a,_h,_a,_n,_exc,_apd,$FD,$EB
				.BYTE	_apu,_T,_h,_e,_,_r,_u,_m,_o,_r,_,_t,_h,_a,_t,_,_y,_o,_u,_,_d,_e,_f,_e,_a,_t,_e,_d,_,_B,_a,_r,_a,_m,_o,_s,_,_r,_e,_a,_c,_h,_e,_d,_,_h,_e,_r,_e,_,_a,_h,_e,_a,_d,_,_o,_f,_,_y,_o,_u,_exc,_apd,$EF
_msg66B:		.BYTE	_apu,_Y,_o,_u,_,_a,_r,_e,_,_i,_n,_d,_e,_e,_d,_,_t,_r,_u,_e,_,_h,_e,_r,_o,_e,_s,_exc,_apd,$EF
_msg66C:		.BYTE	_apu,_A,_h,_exc,_,_B,_a,_r,_a,_m,_o,_s,_,_d,_e,_a,_d,_exc,_,_I,_t,_apo,_s,_,_l,_i,_k,_e,_,_a,_,_d,_r,_e,_a,_m,_,_c,_o,_m,_e,_,_t,_r,_u,_e,_exc,_apd,$EF
_msg66D:		.BYTE	_apu,_Q,_u,_i,_c,_k,_l,_y,_exc,_,_I,_n,_t,_o,_,_t,_h,_e,_,_c,_a,_s,_t,_l,_e,_exc,$EB
				.BYTE	_T,_h,_e,_,_k,_i,_n,_g,_,_w,_i,_l,_l,_,_s,_u,_r,_e,_l,_y,_,_b,_e,_,_d,_e,_l,_i,_g,_h,_t,_e,_d,_,_t,_o,_,_h,_e,_a,_r,_,_t,_h,_i,_s,_,_n,_e,_w,_s,_smc,$EF
_msg66E:		.BYTE	_apu,_W,_i,_t,_h,_,_t,_h,_i,_s,_sem,_,_s,_u,_r,_e,_l,_y,_,_p,_e,_a,_c,_e,_,_w,_i,_l,_l,_,_c,_o,_m,_e,_,_t,_o,_,_t,_h,_i,_s,_,_w,_o,_r,_l,_d,_smc,$EF
_msg66F:		.BYTE	_apu,_Y,_o,_u,_,_a,_r,_e,_,_i,_n,_d,_e,_e,_d,_,_a,_,_t,_r,_u,_e,_,_s,_o,_n,_,_o,_f,_,_O,_r,_t,_e,_g,_a,_exc,$EB
				.BYTE	_T,_h,_i,_s,_,_m,_a,_r,_k,_s,_,_t,_h,_e,_,_b,_i,_r,_t,_h,_,_o,_f,_,_a,_,_y,_o,_u,_n,_g,_,_h,_e,_r,_o,_exc,_apd,$EF
_msg670:		.BYTE	_apu,_W,_e,_l,_c,_o,_m,_e,_,_b,_a,_c,_k,_,$F5,_,_d,_e,_a,_r,_exc,_,_Y,_o,_u,_r,_,_m,_o,_t,_h,_e,_r,_,_i,_s,_,_s,_o,_,_h,_a,_p,_p,_y,_exc,_apd,$FD,$EB
				.BYTE	_apu,_I,_,_w,_i,_s,_h,_,_y,_o,_u,_r,_,_f,_a,_t,_h,_e,_r,_,_c,_o,_u,_l,_d,_,_s,_e,_e,_,_y,_o,_u,_,_n,_o,_w,_exc,$EB
				.BYTE	_O,_h,_sem,_,$F5,_exc,_apd,$EF
_msg671:		.BYTE	_apu,_T,_h,_e,_r,_e,_,_i,_s,_,_n,_o,_n,_e,_,_s,_o,_,_b,_r,_a,_v,_e,_,_a,_s,_,$F5,_exc,_,_A,_n,_d,_,_heshe,_,_i,_s,_,_m,_y,_,_g,_r,_a,_n,_d,_c,_h,_i,_l,_d,_exc,_apd,$EF
_msg672:		.BYTE	_apu,_W,_e,_l,_l,_,_t,_h,_e,_n,_sem,_,_h,_u,_r,_r,_y,_exc,_,_T,_o,_,_t,_h,_e,_,_k,_i,_n,_g,_exc,$EB
				.BYTE	_H,_e,_,_a,_n,_x,_i,_o,_u,_s,_l,_y,_,_a,_w,_a,_i,_t,_s,_,_y,_o,_u,_exc,_apd,$EF
_txt_block68:
_msg673:		.BYTE	_apu,_E,_v,_e,_n,_,_t,_h,_o,_u,_g,_h,_,_B,_a,_r,_a,_m,_o,_s,_,_i,_s,_,_n,_o,_,_m,_o,_r,_e,_sem,_,_t,_h,_e,_y,_,_w,_o,_n,_apo,_t,_,_l,_e,_t,_,_m,_e,_,_g,_o,_,_o,_u,_t,_,_o,_f,_,_t,_h,_e,_,_c,_a,_s,_t,_l,_e,_smc,$FD,$EB
				.BYTE	_apu,_I,_,_t,_h,_i,_n,_k,_,_m,_y,_,_f,_a,_t,_h,_e,_r,_,_j,_u,_s,_t,_,_d,_o,_e,_s,_n,_apo,_t,_,_w,_a,_n,_t,_,_t,_o,_,_l,_e,_t,_,_m,_e,_,_g,_o,_,_o,_u,_t,_smc,$EF
_msg674:		.BYTE	_apu,_T,_h,_r,_e,_e,_,_c,_h,_e,_e,_r,_s,_,_f,_o,_r,_,$F5,_exc,_apd,$EF
_msg675:		.BYTE	_apu,_T,_h,_e,_,_k,_i,_n,_g,_,_s,_e,_e,_m,_s,_,_t,_o,_,_h,_a,_v,_e,_,_l,_o,_s,_t,_,_a,_l,_l,_,_h,_i,_s,_,_p,_o,_w,_e,_r,_smc,$FD,$FF
_msg676:		.BYTE	_apu,_B,_e,_c,_a,_u,_s,_e,_,_o,_f,_,_t,_h,_i,_s,_sem,_,_t,_h,_e,_,_n,_a,_m,_e,_,_o,_f,_,_A,_l,_i,_a,_h,_a,_n,_,_w,_i,_l,_l,_,_r,_i,_n,_g,_,_t,_h,_r,_o,_u,_g,_h,_o,_u,_t,_,_t,_h,_e,_,_l,_a,_n,_d,_dot,_,_T,_h,_i,_s,_,_i,_s,_,_c,_a,_u,_s,_e,_,_f,_o,_r,_,_c,_e,_l,_e,_b,_r,_a,_t,_i,_o,_n,_exc,_apd,$EF
_msg677:		.BYTE	_apu,_O,_h,_sem,_,$F5,_exc,$EB
				.BYTE	_Y,_o,_u,_,_d,_i,_d,_,_w,_e,_l,_l,_,_i,_n,_,_d,_e,_f,_e,_a,_t,_i,_n,_g,_,_t,_h,_e,_,_A,_r,_c,_h,_f,_i,_e,_n,_d,_,_B,_a,_r,_a,_m,_o,_s,_exc,_apd,$FD,$EB
				.BYTE	_apu,_Y,_o,_u,_,_a,_r,_e,_,_i,_n,_d,_e,_e,_d,_,_a,_,_t,_r,_u,_e,_,_s,_o,_n,_,_o,_f,_,_O,_r,_t,_e,_g,_a,_exc,_,_T,_h,_e,_,_w,_h,_o,_l,_e,_,_c,_o,_u,_n,_t,_r,_y,_,_s,_i,_n,_g,_s,_,_y,_o,_u,_r,_,_p,_r,_a,_i,_s,_e,_s,_sem,_,$F5,_exc,_apd,$FD,$EB
				.BYTE	_apu,_E,_v,_e,_r,_y,_o,_n,_e,_exc,_,_H,_e,_a,_r,_,_m,_e,_exc,_,_L,_e,_t,_,_u,_s,_,_c,_e,_l,_e,_b,_r,_a,_t,_e,_exc,_apd,$EF
_msg678:		.BYTE	_ldt,_ddt,_f,_r,_o,_m,_,_o,_u,_t,_,_o,_f,_,_n,_o,_w,_h,_e,_r,_e,_sem,_,_a,_n,_,_u,_n,_e,_a,_r,_t,_h,_l,_y,_,_v,_o,_i,_c,_e,_,_i,_s,_,_h,_e,_a,_r,_d,_ddt,_dot,$FD,$EB
				.BYTE	_apu,_H,_a,_sem,_,_h,_a,_sem,_,_h,_a,_exc,$EB
				.BYTE	_I,_,_a,_m,_,_Z,_o,_m,_a,_sem,_,_M,_a,_s,_t,_e,_r,_,_A,_r,_c,_h,_f,_i,_e,_n,_d,_,_w,_h,_o,_,_r,_u,_l,_e,_s,_,_t,_h,_e,_,_d,_a,_r,_k,_,_r,_e,_a,_l,_m,_s,_smc,$FD,$EB
				.BYTE	_apu,_B,_y,_,_t,_h,_e,_,_p,_o,_w,_e,_r,_s,_,_I,_,_p,_o,_s,_s,_e,_s,_s,_sem,_,_b,_e,_f,_o,_r,_e,_,_l,_o,_n,_g,_sem,_,_t,_h,_i,_s,_,_w,_o,_r,_l,_d,_,_t,_o,_o,_,_w,_i,_l,_l,_,_b,_e,_,_l,_o,_c,_k,_e,_d,_,_i,_n,_,_d,_a,_r,_k,_n,_e,_s,_s,_smc,$FD,$EB
				.BYTE	_apu,_A,_n,_g,_u,_i,_s,_h,_,_a,_n,_d,_,_s,_u,_f,_f,_e,_r,_i,_n,_g,_,_b,_e,_,_t,_h,_i,_n,_e,_exc,$EB
				.BYTE	_I,_t,_,_i,_s,_,_t,_h,_y,_,_s,_u,_f,_f,_e,_r,_i,_n,_g,_,_t,_h,_a,_t,_,_b,_r,_i,_n,_g,_s,_,_m,_e,_,_j,_o,_y,_exc,_apd,$FD,$EB
				.BYTE	_apu,_H,_a,_sem,_,_h,_a,_sem,_,_h,_a,_ddt,_smc,$EF
_msg679:		.BYTE	_apu,_W,_h,_a,_t,_,_i,_s,_,_t,_h,_e,_,_m,_e,_a,_n,_i,_n,_g,_,_o,_f,_,_t,_h,_i,_s,_que,_,_J,_u,_s,_t,_,_w,_h,_e,_n,_,_w,_e,_,_t,_h,_o,_u,_g,_h,_t,_,_p,_e,_a,_c,_e,_,_h,_a,_d,_,_c,_o,_m,_e,_,_t,_o,_,_o,_u,_r,_,_w,_o,_r,_l,_d,_exc,_apd,$FD,$EB
				.BYTE	_apu,_H,_o,_w,_,_s,_h,_a,_l,_l,_,_I,_,_t,_e,_l,_l,_,_m,_y,_,_s,_u,_b,_j,_e,_c,_t,_s,_,_o,_f,_,_t,_h,_e,_,_c,_o,_m,_i,_n,_g,_,_o,_f,_,_a,_,_w,_o,_r,_l,_d,_,_o,_f,_,_d,_a,_r,_k,_n,_e,_s,_s,_que,_apd,$FD,$EB
				.BYTE	_apu,_S,_w,_e,_a,_r,_,_y,_o,_u,_apo,_l,_l,_,_k,_e,_e,_p,_,_t,_h,_i,_s,_,_n,_e,_w,_s,_,_o,_f,_,_t,_h,_e,_,_A,_r,_c,_h,_f,_i,_e,_n,_d,_,_Z,_o,_m,_a,_,_a,_,_s,_e,_c,_r,_e,_t,_exc,_apd,$FD,$EB
				.BYTE	_apu,_I,_apo,_m,_,_t,_i,_r,_e,_d,_,_n,_o,_w,_ddt,_dot,$EB
				.BYTE	_Y,_o,_u,_apo,_r,_e,_,_d,_i,_s,_m,_i,_s,_s,_e,_d,_smc,$EF
_msg67A:		.BYTE	_apu,_W,_o,_w,_exc,_,_Y,_o,_u,_apo,_r,_e,_,_t,_h,_e,_,_f,_i,_r,_s,_t,_,_h,_e,_r,_o,_,_w,_h,_o,_,_h,_a,_s,_,_e,_v,_e,_r,_,_g,_o,_n,_e,_,_t,_o,_,_t,_h,_e,_,_M,_a,_s,_t,_e,_r,_,_A,_r,_c,_h,_f,_i,_e,_n,_d,_apo,_s,_,_c,_a,_s,_t,_l,_e,_,_a,_n,_d,_,_r,_e,_t,_u,_r,_n,_e,_d,_,_a,_l,_i,_v,_e,_exc,_apd,$EF
_msg67B:		.BYTE	_apu,_O,_h,_,_b,_o,_y,_exc,_,_I,_apo,_m,_,_b,_u,_s,_y,_exc,_,_G,_o,_t,_t,_a,_,_g,_e,_t,_,_r,_e,_a,_d,_y,_,_f,_o,_r,_,_t,_h,_e,_,_c,_e,_l,_e,_b,_r,_a,_t,_i,_o,_n,_exc,_apd,$EF
_msg67C:		.BYTE	_apu,_O,_h,_exc,_,_M,_y,_,_d,_r,_e,_a,_m,_,_h,_a,_s,_,_c,_o,_m,_e,_,_t,_o,_,_p,_a,_s,_s,_exc,_,_Y,_e,_s,_sem,_,_I,_,_h,_a,_v,_e,_,_t,_h,_e,_,_S,_t,_o,_n,_e,_s,_,_o,_f,_,_S,_u,_n,_l,_i,_g,_h,_t,_,_s,_a,_f,_e,_l,_y,_,_i,_n,_,_m,_y,_,_h,_a,_n,_d,_s,_exc,_apd,$EF
_msg67D:		.BYTE	_apu,_M,_a,_y,_,_a,_l,_l,_,_r,_e,_j,_o,_i,_c,_e,_exc,_,_M,_y,_,_s,_o,_n,_sem,_,_G,_a,_r,_i,_n,_sem,_,_m,_a,_y,_,_a,_t,_,_l,_a,_s,_t,_,_r,_e,_t,_u,_r,_n,_exc,_apd,$EF

		ECHO "bank 14 free space", [SAFE_STUB_ORG-.]

		ORG SAFE_STUB_ORG
		SAFE_STUB