
		ORG $8000

_txt_block69:
_msg67E:		.BYTE	_apu,_I,_,_h,_a,_v,_e,_,_n,_a,_m,_e,_d,_,_m,_y,_,_c,_h,_i,_l,_d,_,_Y,_u,_k,_i,_n,_o,_v,_smc,$FD,$EB
				.BYTE	_apu,_T,_h,_i,_s,_,_n,_a,_m,_e,_,_s,_h,_a,_l,_l,_,_b,_e,_,_h,_a,_n,_d,_e,_d,_,_d,_o,_w,_n,_,_a,_c,_r,_o,_s,_s,_,_g,_e,_n,_e,_r,_a,_t,_i,_o,_n,_s,_smc,$EF
_msg67F:		.BYTE	_apu,_W,_e,_,_c,_a,_n,_n,_o,_t,_,_d,_a,_r,_e,_,_t,_o,_,_h,_o,_p,_e,_,_t,_h,_a,_t,_,_t,_h,_i,_s,_,_w,_i,_l,_l,_,_n,_e,_v,_e,_r,_,_h,_a,_p,_p,_e,_n,_,_a,_g,_a,_i,_n,_smc,$FD,$EB
				.BYTE	_apu,_T,_h,_e,_r,_e,_f,_o,_r,_e,_sem,_,_y,_o,_u,_r,_,_l,_i,_n,_e,_a,_g,_e,_,_m,_u,_s,_t,_,_c,_o,_n,_t,_i,_n,_u,_e,_,_i,_n,_t,_o,_,_t,_h,_e,_,_f,_u,_t,_u,_r,_e,_smc,$FD,$EB
				.BYTE	_apu,_I,_,_h,_o,_p,_e,_,_t,_o,_,_l,_i,_v,_e,_,_t,_o,_,_s,_e,_e,_,_t,_h,_a,_t,_,_d,_a,_y,_smc,$EF
_msg680:		.BYTE	_apu,_H,_e,_y,_exc,_,_I,_t,_apo,_s,_,_m,_e,_sem,_,_G,_a,_r,_i,_n,_exc,_apd,$FD,$EB
				.BYTE	_apu,_I,_,_t,_i,_r,_e,_d,_,_o,_f,_,_m,_y,_,_w,_a,_n,_d,_e,_r,_i,_n,_g,_s,_,_a,_n,_d,_,_h,_a,_v,_e,_,_r,_e,_t,_u,_r,_n,_e,_d,_,_h,_o,_m,_e,_smc,$EF
_msg681:		.BYTE	_apu,_I,_,_f,_i,_n,_a,_l,_l,_y,_,_s,_u,_c,_c,_e,_e,_d,_e,_d,_,_i,_n,_,_m,_a,_k,_i,_n,_g,_,_a,_,_M,_a,_g,_i,_c,_,_K,_e,_y,_exc,_apd,$FD,$EB
				.BYTE	_apu,_B,_u,_t,_,_I,_,_m,_u,_s,_t,_,_h,_a,_v,_e,_,_d,_o,_n,_e,_,_s,_o,_m,_e,_t,_h,_i,_n,_g,_,_w,_r,_o,_n,_g,_dot,_,_W,_h,_e,_n,_,_I,_,_u,_s,_e,_,_i,_t,_,_o,_n,_c,_e,_sem,_,_i,_t,_,_b,_r,_e,_a,_k,_s,_dot,_,_W,_h,_a,_t,_,_c,_a,_n,_,_I,_,_d,_o,_que,_apd,$EF
_msg682:		.BYTE	_apu,_L,_o,_o,_k,_i,_n,_g,_,_a,_t,_,_t,_h,_e,_,_s,_t,_a,_r,_s,_,_l,_i,_k,_e,_,_t,_h,_i,_s,_,_I,_,_f,_e,_e,_l,_,_l,_i,_k,_e,_,_m,_y,_,_h,_e,_a,_r,_t,_,_i,_s,_,_c,_l,_e,_a,_n,_s,_e,_d,_dot,_,_B,_y,_,_t,_h,_e,_,_w,_a,_y,_ddt,_smc,$FD,$FF
_msg683:		.BYTE	_apu,_H,_e,_a,_r,_,_t,_h,_e,_,_o,_d,_d,_s,_,_f,_o,_r,_,_t,_h,_e,_,_n,_e,_x,_t,_,_m,_a,_t,_c,_h,_exc,_,_O,_n,_l,_y,_,_5,_,_p,_i,_e,_c,_e,_s,_,_o,_f,_,_g,_o,_l,_d,_exc,_,_A,_r,_e,_,_y,_o,_u,_,_i,_n,_t,_e,_r,_e,_s,_t,_e,_d,_que,_apd,$EF
_msg684:		.BYTE	_apu,_A,_l,_l,_,_r,_i,_g,_h,_t,_exc,_,_H,_e,_r,_e,_,_a,_r,_e,_,_t,_h,_e,_,_o,_d,_d,_s,_smc,$FD,$EB
				.BYTE	_apu,_S,_m,_a,_r,_t,_,_m,_o,_n,_e,_y,_,_i,_s,_,_o,_n,_,$F5,$F2,_dot,_,_T,_h,_a,_t,_apo,_s,_,_t,_h,_e,_,_s,_c,_o,_o,_p,_exc,_apd,$EF
_msg685:		.BYTE	_apu,_W,_h,_a,_t,_apo,_s,_,_t,_h,_i,_s,_que,_,_Y,_o,_u,_,_c,_a,_n,_apo,_t,_,_p,_a,_y,_,_e,_v,_e,_n,_,_5,_,_p,_i,_e,_c,_e,_s,_,_o,_f,_,_g,_o,_l,_d,_que,_,_Y,_o,_u,_,_b,_e,_t,_t,_e,_r,_,_g,_o,_,_h,_o,_m,_e,_,_t,_h,_e,_n,_smc,$EF
_msg686:		.BYTE	_apu,_O,_h,_sem,_,_y,_o,_u,_,_w,_e,_r,_e,_,_w,_o,_n,_d,_e,_r,_f,_u,_l,_sem,_,$F5,_exc,_,_W,_o,_n,_apo,_t,_,_y,_o,_u,_,_c,_o,_m,_e,_,_a,_n,_d,_,_l,_i,_v,_e,_,_w,_i,_t,_h,_,_y,_o,_u,_r,_,_p,_r,_i,_n,_c,_e,_s,_s,_,_f,_o,_r,_e,_v,_e,_r,_que,_exc,_apd,$EF
_msg687:		.BYTE	_apu,_A,_,_n,_e,_w,_,_k,_i,_n,_g,_,_i,_s,_,_c,_r,_o,_w,_n,_e,_d,_exc,_,_A,_l,_l,_,_h,_a,_i,_l,_,_K,_i,_n,_g,_,$F5,_exc,_apd,$EF
_msg688:		.BYTE	_apu,_Y,_o,_u,_r,_,_h,_i,_g,_h,_n,_e,_s,_s,_exc,_,_I,_,_b,_e,_s,_e,_e,_c,_h,_,_t,_h,_e,_e,_exc,_,_P,_l,_e,_a,_s,_e,_,_r,_e,_s,_c,_u,_e,_,_t,_h,_e,_,_v,_i,_l,_l,_a,_g,_e,_,_o,_f,_,_N,_o,_a,_n,_i,_e,_l,_s,_,_i,_n,_,_t,_h,_e,_,_f,_a,_r,_,_n,_o,_r,_t,_h,_exc,_apd,$EF
_msg689:		.BYTE	$FD,$EB
				.BYTE	_apu,_W,_h,_a,_t,_que,_,_Y,_o,_u,_,_s,_a,_y,_,_t,_h,_e,_,_c,_u,_r,_s,_e,_,_h,_a,_s,_,_a,_l,_r,_e,_a,_d,_y,_,_b,_e,_e,_n,_,_l,_i,_f,_t,_e,_d,_que,_,_Y,_o,_u,_,_a,_r,_e,_,_a,_,_t,_r,_u,_e,_,_k,_i,_n,_g,_exc,_apd,$EF
_msg68A:		.BYTE	_apu,_O,_h,_sem,_,_i,_t,_apo,_s,_,_y,_o,_u,_,$F5,_dot,$EB
				.BYTE	_Y,_o,_u,_apo,_v,_e,_,_c,_o,_m,_e,_,_u,_p,_,_i,_n,_,_t,_h,_e,_,_w,_o,_r,_l,_d,_sem,_,_I,_,_s,_e,_e,_smc,$EF
_msg68B:		.BYTE	_apu,_O,_h,_exc,_,_Y,_o,_u,_,_h,_a,_v,_e,_,_r,_e,_t,_u,_r,_n,_e,_d,_,_t,_h,_e,_,_G,_o,_l,_d,_e,_n,_,_C,_r,_o,_w,_n,_dot,_,_H,_o,_w,_,_s,_p,_l,_e,_n,_d,_i,_d,_exc,_apd,$FD,$EB
				.BYTE	_apu,_Y,_o,_u,_,_a,_r,_e,_,_i,_n,_d,_e,_e,_d,_,_a,_,_t,_r,_u,_e,_,_h,_e,_r,_o,_exc,_apd,$FD,$FF
_msg68C:		.BYTE	_apu,_W,_h,_a,_t,_,_s,_a,_y,_,_y,_e,_que,_,_W,_i,_l,_t,_,_t,_h,_o,_u,_,_n,_o,_t,_,_r,_u,_l,_e,_,_t,_h,_i,_s,_,_l,_a,_n,_d,_,_i,_n,_,_m,_y,_,_p,_l,_a,_c,_e,_que,_apd,$EF
_msg68D:		.BYTE	_apu,_S,_p,_e,_a,_k,_,_y,_e,_,_n,_o,_t,_,_t,_h,_u,_s,_l,_y,_dot,_,_A,_c,_c,_e,_p,_t,_,_i,_n,_s,_t,_e,_a,_d,_sem,_,_i,_f,_,_f,_o,_r,_,_t,_h,_e,_,_s,_a,_k,_e,_,_o,_f,_,_e,_x,_p,_e,_r,_i,_e,_n,_c,_e,_,_a,_l,_o,_n,_e,_smc,$FD,$FF
_txt_block6A:
_msg68E:		.BYTE	_apu,_I,_t,_,_i,_s,_,_d,_o,_n,_e,_exc,_,_H,_e,_n,_c,_e,_f,_o,_r,_t,_h,_,$F5,_,_s,_h,_a,_l,_l,_,_r,_u,_l,_e,_,_a,_s,_,_k,_i,_n,_g,_,_o,_f,_,_t,_h,_i,_s,_,_c,_a,_s,_t,_l,_e,_exc,_apd,$EF
_msg68F:		.BYTE	_apu,_H,_o,_sem,_,_h,_o,_sem,_,_h,_o,_exc,_,_I,_t,_,_i,_s,_,_I,_dot,_,_T,_h,_e,_,_f,_o,_r,_m,_e,_r,_,_k,_i,_n,_g,_smc,$FD,$EB
				.BYTE	_apu,_T,_h,_e,_,_c,_o,_m,_m,_o,_n,_,_p,_e,_o,_p,_l,_e,_,_h,_a,_v,_e,_,_i,_t,_,_g,_o,_o,_d,_,_i,_n,_d,_e,_e,_d,_exc,_,_I,_,_n,_e,_v,_e,_r,_,_k,_n,_e,_w,_,_g,_a,_m,_b,_l,_i,_n,_g,_,_w,_a,_s,_,_s,_o,_,_m,_u,_c,_h,_,_f,_u,_n,_smc,$FD,$EB
				.BYTE	_apu,_I,_,_k,_n,_o,_w,_,_t,_h,_o,_u,_,_s,_h,_a,_l,_t,_,_d,_o,_,_a,_,_f,_i,_n,_e,_,_j,_o,_b,_,_r,_u,_l,_i,_n,_g,_,_t,_h,_i,_s,_,_l,_a,_n,_d,_dot,_,_C,_a,_r,_r,_y,_,_o,_n,_exc,_apd,$FF
_msg690:		.BYTE	_apu,_W,_e,_l,_l,_sem,_,_u,_n,_t,_i,_l,_,_w,_e,_,_m,_e,_e,_t,_,_a,_g,_a,_i,_n,_exc,$EB
				.BYTE	_H,_o,_sem,_,_h,_o,_sem,_,_h,_o,_exc,_apd,$EF
_msg691:		.BYTE	_apu,_W,_h,_a,_t,_apo,_s,_,_t,_h,_i,_s,_que,_,_Y,_o,_u,_,_t,_i,_r,_e,_,_a,_l,_r,_e,_a,_d,_y,_,_o,_f,_,_b,_e,_i,_n,_g,_,_k,_i,_n,_g,_que,_apd,$EF
_msg692:		.BYTE	_apu,_W,_h,_e,_w,_exc,_,_T,_h,_a,_t,_apo,_s,_,_a,_,_r,_e,_l,_i,_e,_f,_exc,_apd,$FD,$FF
_msg693:		.BYTE	_apu,_I,_,_s,_e,_e,_dot,_,_I,_,_s,_h,_a,_l,_l,_,_n,_o,_t,_,_m,_a,_k,_e,_,_y,_e,_,_c,_o,_n,_t,_i,_n,_u,_e,_,_i,_n,_,_s,_o,_m,_e,_t,_h,_i,_n,_g,_,_y,_e,_,_d,_i,_s,_l,_i,_k,_e,_smc,$FD,$EB
				.BYTE	_apu,_I,_,_u,_n,_d,_e,_r,_s,_t,_a,_n,_d,_,_n,_o,_w,_sem,_,$F5,_dot,$EB
				.BYTE	_I,_t,_apo,_s,_,_b,_e,_t,_t,_e,_r,_,_f,_o,_r,_,_t,_h,_e,_e,_,_t,_o,_,_c,_o,_n,_t,_i,_n,_u,_e,_,_y,_o,_u,_r,_,_t,_r,_a,_v,_e,_l,_s,_smc,$EF
_msg694:		.BYTE	_apu,_T,_h,_i,_s,_,_i,_s,_,_t,_h,_e,_,_t,_o,_w,_n,_,_t,_h,_a,_t,_,$ED,_,_b,_u,_i,_l,_t,_smc,$EF
_msg695:		.BYTE	_apu,_B,_u,_t,_,_i,_t,_apo,_s,_,_n,_o,_t,_,_j,_u,_s,_t,_,$ED,_apo,_s,_,_t,_o,_w,_n,_,_a,_n,_y,_m,_o,_r,_e,_smc,$EF
_msg696:		.BYTE	_apu,_H,_e,_y,_sem,_,_c,_u,_t,_i,_e,_,_p,_i,_e,_exc,$EB
				.BYTE	_W,_a,_n,_t,_,_t,_o,_,_h,_a,_v,_e,_,_y,_o,_u,_r,_,_f,_o,_r,_t,_u,_n,_e,_,_t,_o,_l,_d,_que,_apd,$EF
_msg697:		.BYTE	_apu,_O,_h,_sem,_,_t,_o,_o,_,_s,_t,_u,_c,_k,_,_u,_p,_sem,_,_h,_u,_h,_que,$EB
				.BYTE	_I,_f,_,_y,_o,_u,_,_h,_a,_v,_e,_,_a,_,_c,_h,_a,_n,_g,_e,_,_o,_f,_,_h,_e,_a,_r,_t,_sem,_,_I,_apo,_l,_l,_,_b,_e,_,_h,_e,_r,_e,_smc,$EF
_msg698:		.BYTE	_apu,_Y,_o,_u,_,_w,_i,_l,_l,_que,_exc,_,_O,_o,_h,_sem,_,_I,_apo,_m,_,_s,_o,_,_e,_x,_c,_i,_t,_e,_d,_exc,$EB
				.BYTE	_C,_o,_m,_e,_,_w,_i,_t,_h,_,_m,_e,_,_t,_h,_e,_n,_smc,$EF
_msg699:		.BYTE	_apu,_I,_,_c,_a,_n,_apo,_t,_,_t,_e,_l,_l,_,_a,_l,_l,_,_o,_f,_,_y,_o,_u,_r,_,_f,_o,_r,_t,_u,_n,_e,_s,_,_a,_t,_,_o,_n,_c,_e,_smc,$FD,$EB
				.BYTE	_apu,_J,_u,_s,_t,_,_y,_o,_u,_,_c,_o,_m,_e,_sem,_,_O,_K,_que,_apd,$EF
_msg69A:		.BYTE	_apu,_O,_h,_sem,_,_r,_e,_a,_l,_l,_y,_que,_,_T,_h,_a,_t,_apo,_s,_,_t,_o,_o,_,_b,_a,_d,_dot,_,_I,_,_g,_u,_e,_s,_s,_,_t,_h,_i,_s,_,_i,_s,_,_g,_o,_o,_d,_b,_y,_e,_smc,$EF
_msg69B:		.BYTE	$F5,_,_col,$EB
				.BYTE	_apu,_O,_h,_sem,_,_y,_o,_u,_,_g,_e,_t,_,_t,_o,_,_h,_a,_v,_e,_,_a,_l,_l,_,_t,_h,_e,_,_f,_u,_n,_que,_,_I,_,_w,_a,_n,_t,_,_t,_o,_,_h,_e,_a,_r,_,_a,_b,_o,_u,_t,_,_i,_t,_,_l,_a,_t,_e,_r,_sem,_,_O,_K,_que,_apd,$EF
_msg69C:		.BYTE	$F5,_,_col,$EB
				.BYTE	_apu,_W,_e,_l,_l,_sem,_,_I,_,_n,_e,_v,_e,_r,_,_g,_e,_t,_,_t,_o,_,_g,_o,_,_f,_i,_r,_s,_t,_exc,_,_I,_t,_apo,_s,_,_j,_u,_s,_t,_,_n,_o,_t,_,_f,_a,_i,_r,_exc,_apd,$EF
_msg69D:		.BYTE	_apu,_S,_i,_t,_,_d,_o,_w,_n,_,_h,_e,_r,_e,_sem,_,_O,_K,_que,_apd,$FD,$FF
_txt_block6B:
_msg69E:		.BYTE	_apu,_L,_e,_t,_apo,_s,_,_t,_u,_r,_n,_,_t,_h,_e,_,_l,_i,_g,_h,_t,_s,_,_o,_f,_f,_sem,_,_O,_K,_que,_apd,$EF
_msg69F:		.BYTE	_apu,_D,_o,_n,_apo,_t,_,_s,_a,_y,_,_t,_h,_a,_t,_smc,$EF
_msg6A0:		.BYTE	_apu,_I,_apo,_m,_,_t,_u,_r,_n,_i,_n,_g,_,_t,_h,_e,_m,_,_o,_f,_f,_,_n,_o,_w,_str,_str,_apd,$EF
_msg6A1:		.BYTE	_apu,_L,_o,_o,_k,_,_i,_n,_t,_o,_,_t,_h,_e,_,_c,_r,_y,_s,_t,_a,_l,_sem,_,_l,_o,_o,_k,_,_d,_e,_e,_p,_l,_y,_ddt,_smc,$FD,$EB
				.BYTE	_,_,_,$EB
				.BYTE	$F9,_,_col,$EB
				.BYTE	_apu,_Y,_e,_s,_sem,_,_e,_v,_e,_r,_y,_t,_h,_i,_n,_g,_,_i,_s,_,_g,_e,_t,_t,_i,_n,_g,_,_c,_l,_e,_a,_r,_e,_r,_sem,_,_c,_l,_e,_a,_r,_e,_r,_sem,_,_c,_l,_e,_a,_r,_e,_r,_ddt,_smc,$FD,$EB
				.BYTE	_,_,_,$EB
				.BYTE	$F9,_,_col,$EB
				.BYTE	_apu,_W,_o,_w,_sem,_,_I,_sem,_,_I,_,_c,_a,_n,_apo,_t,_,_b,_e,_l,_i,_e,_v,_e,_ddt,_dot,$FD,$EB
				.BYTE	_,_,_,$EB
				.BYTE	_N,_i,_c,_e,_,_c,_r,_y,_s,_t,_a,_l,_,_b,_a,_l,_l,_sem,_,_e,_h,_que,_,_I,_,_o,_p,_e,_r,_a,_t,_e,_,_t,_h,_e,_,_s,_l,_i,_d,_e,_,_s,_h,_o,_w,_,_u,_n,_d,_e,_r,_n,_e,_a,_t,_h,_smc,$FD,$EF
_msg6A2:		.BYTE	_apu,_O,_h,_sem,_,_D,_a,_d,_exc,_,_Y,_o,_u,_,_g,_a,_v,_e,_,_i,_t,_,_a,_w,_a,_y,_,_a,_g,_a,_i,_n,_exc,_apd,$FD,$EB
				.BYTE	_apu,_H,_a,_sem,_,_h,_a,_exc,_,_I,_,_c,_o,_u,_l,_d,_n,_apo,_t,_,_r,_e,_s,_i,_s,_t,_exc,_apd,$EF
_msg6A3:		.BYTE	_apu,_V,_e,_r,_y,_,_w,_e,_l,_l,_sem,_,_I,_,_s,_h,_a,_l,_l,_,_r,_e,_c,_o,_r,_d,_,_t,_h,_i,_s,_smc,$FD,$FF
_msg6A4:		.BYTE	$EF
_msg6A5:		.BYTE	$F5,_,_col,$EB
				.BYTE	_apu,_H,_o,_w,_,_w,_a,_s,_,_i,_t,_que,_apd,$FD,$EB
				.BYTE	_,_,_,$EB
				.BYTE	$F5,_,_col,$EB
				.BYTE	_apu,_ddt,_smc,$FD,$EB
				.BYTE	_,_,_,$EB
				.BYTE	$F5,_,_col,$EB
				.BYTE	_apu,_O,_K,_sem,_,_I,_,_g,_u,_e,_s,_s,_dot,_,_L,_e,_t,_apo,_s,_,_g,_o,_smc,$EF
_msg6A6:		.BYTE	$FD,$EB
				.BYTE	_apu,_B,_u,_t,_,_i,_t,_,_l,_o,_o,_k,_s,_,_l,_i,_k,_e,_,_y,_o,_u,_,_h,_a,_v,_e,_,_p,_l,_e,_n,_t,_y,_,_o,_f,_,_t,_h,_i,_n,_g,_s,_,_a,_l,_r,_e,_a,_d,_y,_dot,_,_C,_o,_m,_e,_,_b,_a,_c,_k,_,_a,_g,_a,_i,_n,_smc,$EF
_msg6A7:		.BYTE	$FD,$EB
				.BYTE	_apu,_B,_u,_t,_,_i,_t,_,_l,_o,_o,_k,_s,_,_l,_i,_k,_e,_,_y,_o,_u,_,_h,_a,_v,_e,_,_p,_l,_e,_n,_t,_y,_,_o,_f,_,_t,_h,_i,_n,_g,_s,_,_a,_l,_r,_e,_a,_d,_y,_smc,$FD,$EB
				.BYTE	_apu,_C,_o,_m,_e,_,_b,_a,_c,_k,_,_a,_g,_a,_i,_n,_,_w,_h,_e,_n,_,_y,_o,_u,_,_c,_a,_n,_,_c,_a,_r,_r,_y,_,_m,_o,_r,_e,_dot,_,_S,_e,_e,_,_y,_o,_u,_smc,$EF
_msg6A8:		.BYTE	$FD,$EB
				.BYTE	_apu,_H,_u,_h,_que,_,_Y,_o,_u,_,_g,_u,_y,_s,_,_a,_r,_e,_,_a,_l,_l,_,_f,_u,_l,_l,_,_u,_p,_,_a,_l,_r,_e,_a,_d,_y,_dot,_,_C,_o,_m,_e,_,_b,_a,_c,_k,_,_a,_n,_o,_t,_h,_e,_r,_,_t,_i,_m,_e,_smc,$EF
_msg6A9:		.BYTE	_T,_h,_e,_r,_e,_apo,_s,_,_n,_o,_,_o,_n,_e,_,_i,_n,_,_t,_h,_a,_t,_,_d,_i,_r,_e,_c,_t,_i,_o,_n,_dot,$EF
_msg6AA:		.BYTE	$F5,_,_col,$EB
				.BYTE	_apu,_I,_,_d,_o,_n,_apo,_t,_,_w,_a,_n,_t,_,_t,_o,_,_h,_e,_a,_r,_,_a,_b,_o,_u,_t,_,_i,_t,_exc,_,_L,_e,_t,_apo,_s,_,_g,_o,_exc,_apd,$EF
_msg6AB:		.BYTE	_apu,_G,_o,_o,_d,_,_e,_v,_e,_n,_i,_n,_g,_sem,_,_y,_o,_u,_n,_g,_,_l,_a,_d,_y,_dot,_,_T,_h,_e,_,_s,_t,_a,_r,_s,_,_a,_r,_e,_,_b,_e,_a,_u,_t,_i,_f,_u,_l,_,_t,_o,_n,_i,_g,_h,_t,_sem,_,_w,_o,_u,_l,_d,_n,_apo,_t,_,_y,_o,_u,_,_s,_a,_y,_que,_apd,$EF
_msg6AC:		.BYTE	_apu,_W,_e,_l,_c,_o,_m,_e,_exc,_,_O,_u,_r,_,_b,_r,_a,_v,_e,_,_y,_o,_u,_n,_g,_,_h,_e,_r,_o,_,_o,_f,_,_A,_l,_i,_a,_h,_a,_n,_exc,_apd,$FD,$FF
_msg6AD:		.BYTE	_apu,$F5,_,_n,_e,_e,_d,_s,_,$F8,_,_m,_o,_r,_e,_,_e,_x,_p,_e,_r,_i,_e,_n,_c,_e,_,_p,_o,_i,_n,_t,$C0,_,_t,_o,_,_g,_o,_,_t,_o,_,_t,_h,_e,_,_n,_e,_x,_t,_,_l,_e,_v,_e,_l,_smc,$FD,$FF
_txt_block6C:
_msg6AE:		.BYTE	_apu,_S,_h,_a,_l,_l,_,_I,_,_i,_n,_s,_c,_r,_i,_b,_e,_,_t,_h,_e,_,_r,_e,_s,_u,_l,_t,_s,_,_o,_f,_,_y,_o,_u,_r,_,_j,_o,_u,_r,_n,_e,_y,_s,_,_i,_n,_,_t,_h,_e,_,_I,_m,_p,_e,_r,_i,_a,_l,_,_S,_c,_r,_o,_l,_l,_s,_,_o,_f,_,_H,_o,_n,_o,_r,_que,_apd,$EF
_msg6AF:		.BYTE	_apu,_W,_e,_l,_l,_sem,_,_w,_h,_a,_t,_,_a,_b,_o,_u,_t,_,_i,_t,_que,_,_A,_r,_e,_,_y,_o,_u,_,_a,_b,_o,_u,_t,_,_t,_o,_,_c,_o,_n,_t,_i,_n,_u,_e,_,_o,_n,_,_y,_o,_u,_r,_,_j,_o,_u,_r,_n,_e,_y,_que,_apd,$EF
_msg6B0:		.BYTE	_apu,_B,_e,_,_o,_f,_f,_,_w,_i,_t,_h,_,_y,_o,_u,_,_t,_h,_e,_n,_,$F5,_exc,_apd,$EF
_msg6B1:		.BYTE	_apu,_W,_e,_l,_l,_,_t,_h,_e,_n,_sem,_,_w,_h,_y,_,_n,_o,_t,_,_r,_e,_s,_t,_,_f,_o,_r,_,_a,_,_w,_h,_i,_l,_e,_que,$EB
				.BYTE	_U,_n,_t,_i,_l,_,_w,_e,_,_m,_e,_e,_t,_,_a,_g,_a,_i,_n,_sem,_,$F5,_exc,_apd,$EF
_msg6B2:		.BYTE	_apu,_W,_e,_l,_c,_o,_m,_e,_,_b,_a,_c,_k,_exc,_apd,$FD,$FF
_msg6B3:		.BYTE	_apu,_O,_h,_sem,_,_f,_o,_r,_,_s,_h,_a,_m,_e,_sem,_,$F5,_exc,_,_Y,_o,_u,_,_d,_i,_e,_d,_exc,_apd,$FD,$FF
_msg6B4:		.BYTE	_apu,_I,_,_w,_i,_l,_l,_,_g,_r,_a,_n,_t,_,_t,_h,_e,_e,_,_o,_n,_e,_,_m,_o,_r,_e,_,_c,_h,_a,_n,_c,_e,_smc,$FD,$FF
_msg6B5:		.BYTE	_apu,_D,_o,_n,_apo,_t,_,_d,_i,_s,_g,_r,_a,_c,_e,_,_t,_h,_e,_,_n,_a,_m,_e,_,_o,_f,_,_y,_o,_u,_r,_,_f,_a,_t,_h,_e,_r,_sem,_,_O,_r,_t,_e,_g,_a,_exc,_,_G,_o,_,_n,_o,_w,_,$F5,_exc,_apd,$EF
_msg6B6:		.BYTE	_apu,_I,_,_w,_e,_l,_c,_o,_m,_e,_,_y,_o,_u,_exc,$EB
				.BYTE	_W,_e,_apo,_v,_e,_,_h,_e,_a,_r,_d,_,_t,_e,_l,_l,_,_o,_f,_,_t,_h,_e,_,_b,_r,_a,_v,_e,_,_h,_e,_r,_o,_sem,_,_O,_r,_t,_e,_g,_a,_smc,$FD,$FF
_msg6B7:		.BYTE	_apu,_W,_e,_l,_l,_,_n,_o,_w,_sem,_,_I,_,_h,_a,_v,_e,_,_s,_o,_m,_e,_t,_h,_i,_n,_g,_,_t,_o,_,_a,_s,_k,_,_o,_f,_,_y,_o,_u,_smc,$FD,$EB
				.BYTE	_apu,_S,_o,_m,_e,_o,_n,_e,_,_n,_a,_m,_e,_d,_,_K,_a,_n,_d,_a,_r,_,_h,_a,_s,_,_s,_t,_o,_l,_e,_n,_,_t,_h,_e,_,_G,_o,_l,_d,_e,_n,_,_C,_r,_o,_w,_n,_,_f,_r,_o,_m,_,_t,_h,_e,_,_c,_a,_s,_t,_l,_e,_smc,$FD,$EB
				.BYTE	_apu,_I,_f,_,_y,_o,_u,_,_f,_e,_t,_c,_h,_,_m,_e,_,_t,_h,_a,_t,_,_I,_,_w,_i,_l,_l,_,_a,_c,_k,_n,_o,_w,_l,_e,_d,_g,_e,_,_y,_o,_u,_,_a,_s,_,_a,_,_t,_r,_u,_e,_,_h,_e,_r,_o,_dot,_,_G,_o,_,_t,_h,_e,_n,_sem,_,$F5,_exc,_apd,$EF
_msg6B8:		.BYTE	_apu,_I,_,_w,_o,_u,_l,_d,_,_h,_a,_v,_e,_,_o,_f,_f,_e,_r,_e,_d,_,_y,_o,_u,_,_m,_y,_,_k,_i,_n,_g,_d,_o,_m,_ddt,_dot,_,_A,_l,_a,_s,_ddt,_smc,$FD,$FF
_msg6B9:		.BYTE	_apu,_B,_y,_,_t,_h,_e,_,_w,_a,_y,_sem,_,_w,_h,_a,_t,_,_d,_o,_s,_t,_,_t,_h,_o,_u,_,_s,_a,_y,_que,_,_D,_o,_,_y,_e,_,_w,_a,_n,_t,_,_t,_o,_,_t,_a,_k,_e,_,_m,_y,_,_p,_l,_a,_c,_e,_,_a,_g,_a,_i,_n,_que,_apd,$EF
_msg6BA:		.BYTE	_apu,_O,_h,_sem,_,_I,_,_s,_e,_e,_ddt,_dot,$EB
				.BYTE	_W,_e,_l,_l,_sem,_,_b,_e,_,_o,_n,_,_y,_o,_u,_r,_,_w,_a,_y,_,_t,_h,_e,_n,_exc,_apd,$EF
_msg6BB:		.BYTE	_apu,_I,_,_a,_m,_,_a,_,_v,_e,_r,_y,_,_b,_r,_o,_a,_d,_,_m,_i,_n,_d,_e,_d,_,_k,_i,_n,_g,_dot,_,_I,_,_w,_o,_n,_apo,_t,_,_m,_a,_k,_e,_,_l,_i,_g,_h,_t,_,_o,_f,_,_t,_h,_e,_e,_,_b,_e,_c,_a,_u,_s,_e,_,_y,_e,_,_h,_a,_i,_l,_,_f,_r,_o,_m,_,_t,_h,_e,_,_p,_r,_o,_v,_i,_n,_c,_e,_s,_smc,$FD,$FF
_msg6BC:		.BYTE	_apu,_O,_h,_exc,_,$F5,_exc,$EB
				.BYTE	_W,_h,_a,_t,_,_a,_,_h,_i,_c,_k,_exc,_,_Y,_o,_u,_,_h,_a,_d,_,_t,_o,_,_g,_o,_,_o,_f,_f,_,_a,_n,_d,_,_d,_i,_e,_exc,_apd,$FD,$FF
_msg6BD:		.BYTE	_apu,_E,_v,_e,_r,_y,_o,_n,_e,_,_s,_p,_e,_a,_k,_s,_,_s,_o,_,_h,_i,_g,_h,_l,_y,_,_o,_f,_,_m,_e,_dot,_,_B,_u,_t,_,_w,_h,_a,_t,_,_b,_e,_c,_o,_m,_e,_s,_,_o,_f,_,_b,_e,_a,_u,_t,_y,_,_t,_h,_a,_t,_,_b,_l,_o,_s,_s,_o,_m,_s,_,_b,_r,_i,_e,_f,_l,_y,_sem,_,_o,_n,_l,_y,_,_t,_o,_,_f,_a,_d,_e,_,_a,_w,_a,_y,_que,_apd,$FD,$FF
_txt_block6D:
_msg6BE:		.BYTE	_apu,$F5,_,_n,_e,_e,_d,_s,_,$F8,_,_m,_o,_r,_e,_,_p,_o,_i,_n,_t,$C0,_,_t,_o,_,_g,_o,_,_t,_o,_,_t,_h,_e,_,_n,_e,_x,_t,_,_l,_e,_v,_e,_l,_smc,$FD,$FF
_msg6BF:		.BYTE	_apu,_W,_o,_u,_l,_d,_,_y,_o,_u,_,_l,_i,_k,_e,_,_t,_o,_,_i,_n,_s,_c,_r,_i,_b,_e,_,_y,_o,_u,_r,_,_e,_x,_p,_l,_o,_i,_t,_s,_,_i,_n,_,_t,_h,_e,_,_I,_m,_p,_e,_r,_i,_a,_l,_,_S,_c,_r,_o,_l,_l,_s,_,_o,_f,_,_H,_o,_n,_o,_r,_que,_apd,$EF
_msg6C0:		.BYTE	_apu,_D,_o,_,_y,_o,_u,_,_p,_l,_a,_n,_,_t,_o,_,_l,_e,_a,_v,_e,_,_r,_i,_g,_h,_t,_,_a,_w,_a,_y,_,_a,_g,_a,_i,_n,_que,_apd,$EF
_msg6C1:		.BYTE	_apu,_I,_,_h,_o,_p,_e,_,_f,_o,_r,_,_y,_o,_u,_r,_,_s,_a,_f,_e,_,_r,_e,_t,_u,_r,_n,_smc,$EF
_msg6C2:		.BYTE	_apu,_W,_e,_l,_l,_sem,_,_g,_o,_o,_d,_,_n,_i,_g,_h,_t,_,_t,_h,_e,_n,_dot,_,_I,_,_l,_o,_o,_k,_,_f,_o,_r,_w,_a,_r,_d,_,_t,_o,_,_m,_e,_e,_t,_i,_n,_g,_,_y,_o,_u,_,_a,_g,_a,_i,_n,_smc,$EF
_msg6C3:		.BYTE	_apu,_W,_e,_l,_c,_o,_m,_e,_,_b,_a,_c,_k,_exc,_,_Y,_o,_u,_apo,_v,_e,_,_d,_o,_n,_e,_,_w,_e,_l,_l,_exc,_apd,$FD,$FF
_msg6C4:		.BYTE	_apu,_O,_h,_sem,$F5,_sem,_,_i,_t,_apo,_s,_,_a,_,_p,_i,_t,_y,_,_y,_o,_u,_,_h,_a,_d,_,_t,_o,_,_d,_i,_e,_exc,_apd,$FD,$FF
_msg6C5:		.BYTE	_apu,_I,_apo,_l,_l,_,_g,_i,_v,_e,_,_y,_o,_u,_,_o,_n,_e,_,_m,_o,_r,_e,_,_c,_h,_a,_n,_c,_e,_smc,$FD,$FF
_msg6C6:		.BYTE	_apu,_W,_e,_l,_c,_o,_m,_e,_,_t,_o,_,_t,_h,_e,_,_S,_h,_r,_i,_n,_e,_,_o,_f,_,_D,_h,_a,_m,_a,_exc,_apd,$FD,$FF
_msg6C7:		.BYTE	_apu,_I,_,_n,_e,_v,_e,_r,_,_t,_h,_o,_u,_g,_h,_t,_,_I,_,_w,_o,_u,_l,_d,_,_s,_i,_t,_,_h,_e,_r,_e,_,_a,_g,_a,_i,_n,_exc,_,_I,_,_t,_h,_a,_n,_k,_,_y,_o,_u,_sem,_,$F5,_exc,_apd,$FD,$FF
_msg6C8:		.BYTE	_apu,_I,_,_o,_w,_e,_,_m,_y,_,_l,_i,_f,_e,_,_t,_o,_,_y,_o,_u,_dot,_,_T,_a,_k,_e,_,_c,_a,_r,_e,_,_i,_n,_,_y,_o,_u,_r,_,_t,_r,_a,_v,_e,_l,_s,_exc,_apd,$EF
_msg6C9:		.BYTE	_apu,_O,_h,_sem,_,$F5,_exc,_,_W,_h,_o,_,_w,_o,_u,_l,_d,_,_h,_a,_v,_e,_,_t,_h,_o,_u,_g,_h,_t,_,_t,_h,_a,_t,_,_o,_n,_e,_,_s,_o,_,_s,_t,_r,_o,_n,_g,_,_a,_s,_,_y,_o,_u,_,_w,_o,_u,_l,_d,_,_b,_e,_,_d,_e,_f,_e,_a,_t,_e,_d,_exc,_apd,$FD,$FF
_msg6CA:		.BYTE	_apu,_Y,_e,_s,_que,_,_Y,_o,_u,_apo,_r,_e,_,_h,_e,_r,_e,_,_f,_r,_o,_m,_,_t,_h,_e,_,_u,_p,_p,_e,_r,_,_w,_o,_r,_l,_d,_,_t,_o,_,_d,_e,_f,_e,_a,_t,_,_t,_h,_e,_,_A,_r,_c,_h,_f,_i,_e,_n,_d,_que,_,_W,_e,_l,_c,_o,_m,_e,_sem,_,_I,_,_a,_m,_,_t,_h,_e,_,_k,_i,_n,_g,_,_o,_f,_,_t,_h,_i,_s,_,_c,_o,_u,_n,_t,_r,_y,_smc,$FD,$FF
_msg6CB:		.BYTE	_apu,$F5,_exc,_,_I,_,_a,_m,_,_g,_l,_a,_d,_,_t,_o,_,_s,_e,_e,_,_y,_o,_u,_apo,_r,_e,_,_b,_a,_c,_k,_,_s,_a,_f,_e,_l,_y,_exc,_apd,$FD,$FF
_msg6CC:		.BYTE	_apu,_O,_h,_sem,_,$F5,_exc,_,_H,_o,_w,_,_p,_i,_t,_i,_f,_u,_l,_,_t,_h,_a,_t,_,_y,_o,_u,_,_h,_a,_d,_,_t,_o,_,_d,_i,_e,_exc,_apd,$FD,$FF
_msg6CD:		.BYTE	_apu,_I,_,_a,_m,_,_m,_o,_s,_t,_,_h,_a,_p,_p,_y,_,_y,_o,_u,_,_h,_a,_v,_e,_,_c,_o,_m,_e,_,_t,_o,_,_m,_e,_e,_t,_,_m,_e,_,_i,_n,_,_h,_i,_d,_i,_n,_g,_smc,$FD,$EB
				.BYTE	_apu,_I,_,_c,_a,_n,_apo,_t,_,_r,_e,_a,_l,_l,_y,_,_d,_o,_,_a,_n,_y,_t,_h,_i,_n,_g,_,_f,_o,_r,_,_y,_o,_u,_sem,_,_b,_u,_t,_,_I,_apo,_l,_l,_,_g,_i,_v,_e,_,_y,_o,_u,_,_a,_,_g,_i,_f,_t,_smc,$FD,$EB
				.BYTE	_apu,_L,_o,_o,_k,_,_a,_l,_l,_,_a,_r,_o,_u,_n,_d,_,_m,_e,_smc,$EF
_txt_block6E:
_msg6CE:		.BYTE	_apu,_W,_e,_l,_l,_sem,_,_t,_i,_m,_e,_,_f,_o,_r,_,_y,_o,_u,_,_t,_o,_,_g,_o,_smc,$EF
_msg6CF:		.BYTE	_,_,_,$EB
				.BYTE	_G,_a,_l,_e,_n,_,_col,$EB
				.BYTE	_apu,_I,_apo,_l,_l,_,_g,_o,_exc,_apd,$FD,$EB
				.BYTE	_,_,_,$EB
				.BYTE	_G,_a,_l,_e,_n,_,_col,$EB
				.BYTE	_apu,_I,_,_c,_o,_u,_l,_d,_n,_apo,_t,_,_a,_s,_k,_,_t,_h,_a,_t,_,_o,_f,_,_a,_,_c,_o,_m,_p,_l,_e,_t,_e,_,_s,_t,_r,_a,_n,_g,_e,_r,_smc,$FD,$EB
				.BYTE	_,_,_,$EB
				.BYTE	_G,_a,_l,_e,_n,_,_col,$EB
				.BYTE	_apu,_W,_a,_i,_t,_,_h,_e,_r,_e,_exc,_,_I,_apo,_l,_l,_,_g,_o,_,_s,_a,_v,_e,_,_T,_a,_n,_i,_a,_exc,_apd,$EB
				.BYTE	_apu,_G,_a,_l,_e,_n,_exc,_apd,$EF
_msg6D0:		.BYTE	_apu,_Y,_o,_u,_r,_,_b,_u,_s,_i,_n,_e,_s,_s,_,_i,_s,_,_f,_i,_n,_i,_s,_h,_e,_d,_,_h,_e,_r,_e,_exc,_,_B,_e,_,_o,_n,_,_y,_o,_u,_r,_,_w,_a,_y,_exc,_apd,$EF
_msg6D1:		.BYTE	_apu,_P,_l,_a,_c,_e,_,_t,_h,_e,_,_O,_r,_b,_,_o,_n,_,_t,_h,_e,_,_a,_l,_t,_a,_r,_,_o,_f,_,_L,_i,_a,_m,_l,_a,_n,_d,_,_i,_n,_,_t,_h,_e,_,_d,_i,_s,_t,_a,_n,_t,_,_s,_o,_u,_t,_h,_smc,$EF
_msg6D2:		.BYTE	$FD,$EB
				.BYTE	_B,_u,_t,_,_s,_c,_r,_i,_b,_b,_l,_i,_n,_g,_s,_,_a,_r,_e,_,_f,_o,_u,_n,_d,_,_o,_n,_,_t,_h,_e,_,_w,_a,_l,_l,$FD,$EB
				.BYTE	_apu,_I,_apo,_m,_,_g,_l,_a,_d,_,_I,_,_w,_a,_s,_,_a,_b,_l,_e,_,_t,_o,_,_h,_a,_n,_d,_,_o,_v,_e,_r,_,_t,_h,_e,_,_O,_r,_b,_,_w,_h,_i,_l,_e,_,_I,_,_w,_a,_s,_,_s,_t,_i,_l,_l,_,_a,_l,_i,_v,_e,_ddt,_smc,$EF
_msg6D3:		.BYTE	_apu,_P,_l,_e,_a,_s,_e,_,_s,_a,_v,_e,_,_t,_h,_i,_s,_,_w,_o,_r,_l,_d,_,_f,_o,_r,_,_R,_u,_b,_i,_s,_s,_apo,_s,_,_s,_a,_k,_e,_,_t,_o,_o,_smc,$EF
_msg6D4:		.BYTE	_apu,_W,_e,_l,_l,_sem,_,_i,_f,_,_i,_t,_,_i,_s,_n,_apo,_t,_,$F5,_exc,_apd,$FD,$EB
				.BYTE	_apu,_W,_h,_a,_t,_apo,_s,_,_w,_r,_o,_n,_g,_que,_,_W,_h,_y,_,_a,_r,_e,_,_y,_o,_u,_,_d,_r,_e,_s,_s,_e,_d,_,_t,_h,_a,_t,_,_w,_a,_y,_que,_apd,$EF
_msg6D5:		.BYTE	_apu,_E,_v,_e,_n,_,_i,_f,_,_y,_o,_u,_,_m,_a,_k,_e,_,_y,_o,_u,_r,_s,_e,_l,_f,_,_i,_n,_v,_i,_s,_i,_b,_l,_e,_sem,_,_w,_e,_apo,_l,_l,_,_k,_n,_o,_w,_,_w,_h,_e,_r,_e,_,_y,_o,_u,_,_a,_r,_e,_smc,$FD,$EF
_msg6D6:		.BYTE	_apu,_E,_v,_e,_n,_,_i,_f,_,_y,_o,_u,_,_c,_h,_a,_n,_g,_e,_,_y,_o,_u,_r,_,_f,_o,_r,_m,_sem,_,_w,_e,_apo,_l,_l,_,_k,_n,_o,_w,_,_w,_h,_o,_,_y,_o,_u,_,_a,_r,_e,_smc,$FD,$FF
_msg6D7:		.BYTE	_apu,_W,_h,_o,_a,_exc,$EB
				.BYTE	_D,_i,_d,_,_y,_o,_u,_,_h,_e,_a,_r,_,_t,_h,_a,_t,_,_v,_o,_i,_c,_e,_que,_exc,_,_W,_h,_o,_,_i,_s,_,_t,_h,_a,_t,_que,_exc,_apd,$EF
_msg6D8:		.BYTE	_apu,_G,_e,_e,_exc,_apd,$EF
_msg6D9:		.BYTE	_apu,_H,_u,_h,_que,_,_M,_a,_y,_b,_e,_,_I,_,_h,_e,_a,_r,_d,_,_s,_o,_m,_e,_t,_h,_i,_n,_g,_ddt,_dot,_,_t,_h,_e,_n,_,_a,_g,_a,_i,_n,_sem,_,_m,_a,_y,_b,_e,_,_n,_o,_t,_smc,$EF
_msg6DA:		.BYTE	_apu,_W,_h,_a,_t,_que,_,_T,_h,_e,_r,_e,_,_i,_t,_,_i,_s,_,_a,_g,_a,_i,_n,_dot,_,_O,_r,_,_a,_m,_,_I,_,_j,_u,_s,_t,_,_h,_e,_a,_r,_i,_n,_g,_,_t,_h,_i,_n,_g,_s,_que,_apd,$EF
_msg6DB:		.BYTE	_apu,_H,_u,_h,_que,_exc,_,_W,_h,_o,_,_g,_o,_e,_s,_,_t,_h,_e,_r,_e,_que,_,_C,_o,_m,_e,_,_o,_u,_t,_,_w,_h,_e,_r,_e,_,_I,_,_c,_a,_n,_,_s,_e,_e,_,_y,_o,_u,_exc,_apd,$EF
_msg6DC:		.BYTE	_apu,_W,_h,_a,_t,_que,_,_W,_h,_a,_t,_apo,_s,_,_g,_o,_i,_n,_g,_,_o,_n,_,_h,_e,_r,_e,_que,_apd,$EF
_msg6DD:		.BYTE	_apu,_O,_h,_sem,_,_I,_,_m,_u,_s,_t,_,_b,_e,_,_h,_e,_a,_r,_i,_n,_g,_,_t,_h,_i,_n,_g,_s,_exc,_apd,$EF
_txt_block6F:
_msg6DE:		.BYTE	_apu,_H,_u,_h,_que,$EB
				.BYTE	_D,_i,_d,_,_s,_o,_m,_e,_o,_n,_e,_,_c,_a,_l,_l,_,_o,_u,_t,_que,_apd,$EF
_msg6DF:		.BYTE	_apu,_Y,_i,_k,_e,_s,_exc,_,_W,_h,_o,_s,_e,_,_v,_o,_i,_c,_e,_,_i,_s,_,_t,_h,_a,_t,_que,_apd,$EF
_msg6E0:		.BYTE	_apu,_W,_h,_a,_t,_,_w,_a,_s,_,_t,_h,_a,_t,_que,_que,_apd,$EF
_msg6E1:		.BYTE	_apu,_W,_h,_o,_apo,_s,_,_t,_h,_e,_r,_e,_que,_apd,$FD,$EB
				.BYTE	_apu,_T,_h,_i,_s,_,_i,_s,_,_w,_e,_i,_r,_d,_dot,_,_A,_m,_,_I,_,_h,_e,_a,_r,_i,_n,_g,_,_t,_h,_i,_n,_g,_s,_que,_apd,$EF
_msg6E2:		.BYTE	_apu,_I,_s,_,_s,_o,_m,_e,_b,_o,_d,_y,_,_t,_h,_e,_r,_e,_que,_,_I,_s,_,_s,_o,_m,_e,_o,_n,_e,_,_h,_i,_d,_i,_n,_g,_,_o,_v,_e,_r,_,_t,_h,_e,_r,_e,_que,_apd,$EF
_msg6E3:		.BYTE	_apu,_Y,_o,_u,_,_t,_h,_o,_u,_g,_h,_t,_,_y,_o,_u,_apo,_d,_,_h,_i,_d,_e,_,_b,_y,_,_m,_a,_k,_i,_n,_g,_,_y,_o,_u,_r,_s,_e,_l,_f,_,_i,_n,_v,_i,_s,_i,_b,_l,_e,_sem,_,_b,_u,_t,_,_I,_,_c,_a,_n,_,_s,_e,_e,_,_y,_o,_u,_smc,$EF
_msg6E4:		.BYTE	_apu,_ddt,_dot,$EB
				.BYTE	_que,_que,_que,_que,_que,_apd,$EF
_msg6E5:		.BYTE	_apu,_I,_,_h,_e,_a,_r,_,_a,_,_v,_o,_i,_c,_e,_,_e,_v,_e,_n,_,_t,_h,_o,_u,_g,_h,_,_n,_o,_,_o,_n,_e,_,_i,_s,_,_h,_e,_r,_e,_smc,$FD,$EB
				.BYTE	_apu,_W,_h,_a,_t,_,_d,_o,_e,_s,_,_t,_h,_a,_t,_,_m,_e,_a,_n,_que,_apd,$EF
_msg6E6:		.BYTE	_apu,_H,_o,_w,_,_o,_d,_d,_exc,_,_W,_h,_a,_t,_,_c,_o,_u,_l,_d,_,_i,_t,_,_b,_e,_que,_apd,$EF
_msg6E7:		.BYTE	_apu,_S,_t,_r,_a,_n,_g,_e,_dot,_,_I,_,_h,_e,_a,_r,_,_a,_,_v,_o,_i,_c,_e,_,_f,_r,_o,_m,_,_s,_o,_m,_e,_w,_h,_e,_r,_e,_smc,$EF
_msg6E8:		.BYTE	_apu,_B,_r,_r,_ddt,_smc,$EF
_msg6E9:		.BYTE	_apu,_W,_h,_o,_a,_exc,_apd,$EF
_msg6EA:		.BYTE	_apu,_O,_h,_exc,_exc,_,_W,_h,_a,_t,_apo,_s,_,_t,_h,_i,_s,_,_m,_o,_n,_s,_t,_e,_r,_,_d,_o,_i,_n,_g,_,_h,_e,_r,_e,_que,_apd,$EF
_msg6EB:		.BYTE	_apu,_E,_e,_e,_k,_exc,$EB
				.BYTE	_S,_p,_a,_r,_e,_,_m,_e,_exc,_apd,$EF
_msg6EC:		.BYTE	_apu,_Y,_a,_a,_a,_h,_h,_exc,_exc,_exc,_apd,$EF
_msg6ED:		.BYTE	_apu,_W,_h,_a,_t,_apo,_s,_,_w,_r,_o,_n,_g,_que,_,_C,_o,_m,_e,_,_i,_f,_,_y,_o,_u,_,_d,_a,_r,_e,_exc,_apd,$EF
_txt_block70:
_msg6EE:		.BYTE	_apu,_C,_o,_n,_f,_o,_u,_n,_d,_e,_d,_,_c,_r,_e,_a,_t,_u,_r,_e,_exc,$EB
				.BYTE	_M,_e,_e,_t,_,_y,_o,_u,_r,_,_m,_a,_k,_e,_r,_exc,_apd,$EF
_msg6EF:		.BYTE	_apu,_W,_h,_o,_,_a,_r,_e,_,_y,_o,_u,_,_a,_n,_y,_w,_a,_y,_que,_exc,_apd,$EF
_msg6F0:		.BYTE	_apu,_Y,_i,_k,_e,_s,_exc,_,_G,_e,_t,_,_a,_w,_a,_y,_exc,_apd,$EF
_msg6F1:		.BYTE	_apu,_O,_o,_p,_s,_exc,_apd,$EF
_msg6F2:		.BYTE	_apu,_O,_o,_h,_exc,_,_H,_o,_w,_,_c,_u,_t,_e,_exc,_exc,_apd,$EF
_msg6F3:		.BYTE	_apu,_W,_h,_o,_,_a,_r,_e,_,_y,_o,_u,_que,_apd,$EF
_msg6F4:		.BYTE	_apu,_W,_h,_a,_t,_que,_exc,_apd,$EF
_msg6F5:		.BYTE	_apu,_W,_h,_a,_t,_que,_exc,$EB
				.BYTE	_H,_e,_l,_p,_exc,_apd,$EF
_msg6F6:		.BYTE	_apu,_A,_r,_e,_,_y,_o,_u,_,_t,_r,_y,_i,_n,_g,_,_t,_o,_,_m,_a,_k,_e,_,_m,_e,_,_b,_r,_i,_n,_g,_,_m,_y,_,_g,_u,_a,_r,_d,_,_d,_o,_w,_n,_,_b,_y,_,_c,_h,_a,_n,_g,_i,_n,_g,_,_y,_o,_u,_r,_,_f,_o,_r,_m,_que,_,_I,_t,_,_w,_o,_n,_apo,_t,_,_w,_o,_r,_k,_exc,_apd,$EF
_msg6F7:		.BYTE	_apu,_B,_l,_a,_s,_t,_e,_d,_,_m,_o,_n,_s,_t,_e,_r,_exc,_,_Y,_o,_u,_apo,_l,_l,_,_g,_e,_t,_,_y,_o,_u,_r,_s,_exc,_,_I,_,_s,_w,_e,_a,_r,_,_i,_t,_exc,_exc,_apd,$EF
_msg6F8:		.BYTE	_apu,_T,_h,_e,_r,_e,_,_h,_e,_,_i,_s,_exc,_apd,$EF
_msg6F9:		.BYTE	_apu,_O,_h,_exc,_,_S,_p,_a,_r,_e,_,_u,_s,_exc,_apd,$EF
_msg6FA:		.BYTE	_apu,_I,_y,_a,_a,_a,_y,_exc,_exc,_apd,$EF
_msg6FB:		.BYTE	_apu,_M,_r,_a,_a,_a,_h,_exc,_exc,_apd,$EF
_msg6FC:		.BYTE	_apu,_A,_n,_y,_w,_a,_y,_,_i,_t,_apo,_s,_,_c,_a,_u,_s,_e,_,_t,_o,_,_c,_e,_l,_e,_b,_r,_a,_t,_e,_exc,$EB
				.BYTE	_D,_a,_y,_,_h,_a,_s,_,_b,_r,_o,_k,_e,_n,_,_i,_n,_,_A,_l,_e,_f,_g,_a,_r,_d,_exc,_apd,$EF
_msg6FD:		.BYTE	_apu,_Y,_o,_u,_,_a,_r,_e,_,_i,_n,_d,_e,_e,_d,_,_a,_,_t,_r,_u,_e,_,_h,_e,_r,_o,_exc,$EB
				.BYTE	_T,_h,_e,_,_k,_i,_n,_g,_,_a,_n,_x,_i,_o,_u,_s,_l,_y,_,_w,_a,_i,_t,_s,_,_y,_o,_u,_exc,_apd,$EF
_txt_block71:
_msg6FE:		.BYTE	_apu,_I,_,_c,_a,_n,_apo,_t,_,_b,_e,_l,_i,_e,_v,_e,_,_i,_t,_dot,_,_Y,_o,_u,_,_d,_e,_f,_e,_a,_t,_e,_d,_,_t,_h,_e,_,_M,_a,_s,_t,_e,_r,_,_A,_r,_c,_h,_f,_i,_e,_n,_d,_exc,_,_W,_h,_a,_t,_,_a,_,_s,_p,_l,_e,_n,_d,_i,_d,_,_s,_o,_u,_l,_exc,_apd,$EF
_msg6FF:		.BYTE	_apu,_Y,_o,_u,_,_d,_e,_f,_e,_a,_t,_e,_d,_,_t,_h,_e,_,_M,_a,_s,_t,_e,_r,_,_A,_r,_c,_h,_f,_i,_e,_n,_d,_sem,_,_d,_i,_d,_,_y,_o,_u,_que,$EB
				.BYTE	_H,_o,_o,_r,_a,_y,_exc,_apd,$EF
_msg700:		.BYTE	_apu,_Y,_o,_u,_,_a,_r,_e,_,_a,_l,_l,_,_i,_n,_d,_e,_e,_d,_,_t,_r,_u,_e,_,_h,_e,_r,_o,_e,_s,_exc,_apd,$EF
_msg701:		.BYTE	_apu,_T,_h,_a,_n,_k,_,_y,_o,_u,_,_v,_e,_r,_y,_,_m,_u,_c,_h,_exc,_,_T,_h,_a,_n,_k,_s,_,_t,_o,_,_y,_o,_u,_sem,_,_d,_a,_y,_,_h,_a,_s,_,_d,_a,_w,_n,_e,_d,_,_a,_g,_a,_i,_n,_,_i,_n,_,_t,_h,_i,_s,_,_l,_a,_n,_d,_smc,$EF
_msg702:		.BYTE	_apu,_W,_e,_l,_l,_,_d,_o,_n,_e,_,_i,_n,_d,_e,_e,_d,_exc,_,_Y,_o,_u,_,_h,_a,_v,_e,_,_b,_r,_o,_u,_g,_h,_t,_,_p,_e,_a,_c,_e,_,_a,_g,_a,_i,_n,_,_u,_n,_t,_o,_,_t,_h,_i,_s,_,_l,_a,_n,_d,_exc,_apd,$EF
_msg703:		.BYTE	_apu,_I,_,_w,_i,_l,_l,_,_s,_i,_n,_g,_,_y,_o,_u,_r,_,_s,_t,_o,_r,_y,_,_s,_o,_,_i,_t,_,_w,_i,_l,_l,_,_g,_o,_,_d,_o,_w,_n,_,_i,_n,_,_s,_o,_n,_g,_exc,$EB
				.BYTE	_ldt,_ddt,_L,_a,_sem,_,_l,_a,_sem,_,_l,_a,_dot,_,_A,_n,_d,_,_h,_i,_s,_,_n,_a,_m,_e,_,_w,_a,_s,_,$F5,_exc,_ddt,_smc,$EF
_msg704:		.BYTE	_apu,_O,_h,_sem,_,_I,_,_d,_i,_d,_n,_apo,_t,_,_k,_n,_o,_w,_,_t,_h,_e,_,_l,_i,_g,_h,_t,_,_c,_o,_u,_l,_d,_,_b,_e,_,_s,_o,_,_b,_r,_i,_g,_h,_t,_exc,$EB
				.BYTE	_I,_t,_apo,_s,_,_a,_,_d,_r,_e,_a,_m,_,_c,_o,_m,_e,_,_t,_r,_u,_e,_exc,_apd,$EF
_msg705:		.BYTE	_apu,_T,_h,_r,_e,_e,_,_c,_h,_e,_e,_r,_s,_,_f,_o,_r,_,$F5,_exc,_,_H,_i,_p,_sem,_,_h,_i,_p,_sem,_,_H,_o,_o,_r,_a,_y,_exc,_apd,$EF
_msg706:		.BYTE	_apu,_I,_apo,_l,_l,_,_n,_e,_v,_e,_r,_,_t,_h,_i,_n,_k,_,_o,_f,_,_m,_y,_,_o,_l,_d,_,_h,_o,_m,_e,_,_a,_n,_y,_m,_o,_r,_e,_dot,_,_F,_r,_o,_m,_,_n,_o,_w,_,_o,_n,_,_t,_h,_i,_s,_,_w,_i,_l,_l,_,_b,_e,_,_m,_y,_,_w,_o,_r,_l,_d,_exc,_apd,$EF
_msg707:		.BYTE	_apu,_I,_apo,_d,_,_f,_o,_r,_g,_o,_t,_t,_e,_n,_,_m,_o,_r,_n,_i,_n,_g,_,_c,_o,_u,_l,_d,_,_b,_e,_,_s,_o,_,_b,_e,_a,_u,_t,_i,_f,_u,_l,_exc,_apd,$EF
_msg708:		.BYTE	_apu,_H,_i,_p,_sem,_,_h,_i,_p,_sem,_,_M,_e,_o,_w,_exc,_apd,$EF
_msg709:		.BYTE	_apu,_H,_i,_p,_sem,_,_h,_i,_p,_sem,_,_N,_e,_i,_g,_h,_exc,_apd,$EF
_msg70A:		.BYTE	_apu,_W,_e,_apo,_r,_e,_,_s,_o,_,_g,_r,_a,_t,_e,_f,_u,_l,_,_y,_o,_u,_,_w,_e,_r,_e,_,_s,_e,_n,_t,_,_t,_o,_,_u,_s,_exc,_apd,$EF
_msg70B:		.BYTE	_apu,_W,_i,_t,_h,_,_Z,_o,_m,_a,_,_d,_e,_a,_d,_sem,_,_t,_h,_e,_,_h,_o,_l,_e,_,_i,_n,_,_s,_p,_a,_c,_e,_,_c,_o,_n,_n,_e,_c,_t,_i,_n,_g,_,_t,_o,_,_t,_h,_e,_,_o,_t,_h,_e,_r,_,_w,_o,_r,_l,_d,_,_s,_e,_e,_m,_s,_,_t,_o,_,_h,_a,_v,_e,_,_c,_l,_o,_s,_e,_d,_smc,$FD,$EB
				.BYTE	_apu,_A,_n,_d,_,_t,_h,_e,_,_w,_o,_r,_l,_d,_,_o,_f,_,_A,_l,_e,_f,_g,_a,_r,_d,_sem,_,_b,_r,_i,_m,_m,_i,_n,_g,_,_o,_v,_e,_r,_,_w,_i,_t,_h,_,_l,_i,_g,_h,_t,_sem,_,_i,_s,_,_s,_t,_a,_r,_t,_i,_n,_g,_,_a,_n,_e,_w,_smc,$FD,$EB
				.BYTE	_apu,_W,_h,_y,_,_n,_o,_t,_,_s,_p,_e,_n,_d,_,_t,_h,_e,_,_r,_e,_s,_t,_,_o,_f,_,_y,_o,_u,_r,_,_d,_a,_y,_s,_,_h,_e,_r,_e,_que,_apd,$EF
_msg70C:		.BYTE	_apu,_R,_u,_b,_i,_s,_s,_,_t,_o,_l,_d,_,_m,_e,_,_t,_o,_,_c,_o,_n,_v,_e,_y,_,_h,_e,_r,_,_t,_h,_a,_n,_k,_s,_dot,_,_S,_h,_e,_,_w,_i,_l,_l,_,_n,_e,_v,_e,_r,_,_f,_o,_r,_g,_e,_t,_,_t,_h,_e,_,_d,_e,_e,_d,_s,_,_o,_f,_,$F5,_smc,$FD,$EB
				.BYTE	_apu,_S,_h,_e,_,_h,_o,_p,_e,_s,_,_t,_o,_,_m,_e,_e,_t,_,_y,_o,_u,_,_a,_g,_a,_i,_n,_smc,$EF
_msg70D:		.BYTE	_apu,_T,_h,_e,_,_S,_w,_o,_r,_d,_,_o,_f,_,_I,_l,_l,_u,_s,_i,_o,_n,_,_i,_s,_,_a,_,_m,_y,_s,_t,_e,_r,_i,_o,_u,_s,_,_s,_w,_o,_r,_d,_,_t,_h,_a,_t,_,_o,_n,_l,_y,_,_w,_o,_m,_e,_n,_,_c,_a,_n,_,_u,_s,_e,_smc,$EF
_txt_block72:
_msg70E:		.BYTE	_apu,_Y,_o,_u,_,_a,_r,_e,_,_t,_h,_e,_,_o,_n,_l,_y,_,_o,_n,_e,_s,_,_w,_h,_o,_,_h,_a,_v,_e,_,_s,_e,_e,_n,_,_m,_y,_,_t,_r,_u,_e,_,_f,_o,_r,_m,_smc,$FD,$EB
				.BYTE	_apu,_S,_o,_,_l,_o,_n,_g,_,_a,_s,_,_y,_o,_u,_apo,_r,_e,_,_g,_o,_o,_d,_,_a,_n,_d,_,_k,_e,_e,_p,_,_q,_u,_i,_e,_t,_sem,_,_I,_,_w,_o,_n,_apo,_t,_,_e,_l,_i,_m,_i,_n,_a,_t,_e,_,_y,_o,_u,_dot,_,_U,_n,_d,_e,_r,_s,_t,_o,_o,_d,_que,_apd,$EF
_msg70F:		.BYTE	_apu,_H,_o,_sem,_,_h,_o,_exc,$EB
				.BYTE	_G,_o,_o,_d,_,_f,_o,_r,_,_y,_o,_u,_exc,_apd,$EF
_msg710:		.BYTE	_apu,_H,_e,_h,_sem,_,_h,_e,_h,_sem,_,_h,_e,_h,_dot,_,_I,_,_s,_e,_e,_dot,$EB
				.BYTE	_N,_o,_w,_,_y,_o,_u,_apo,_l,_l,_,_n,_e,_v,_e,_r,_,_g,_e,_t,_,_o,_u,_t,_,_a,_l,_i,_v,_e,_dot,$EB
				.BYTE	_I,_apo,_l,_l,_,_s,_e,_e,_,_h,_o,_w,_,_y,_o,_u,_,_t,_a,_s,_t,_e,_,_o,_n,_,_a,_,_s,_k,_e,_w,_e,_r,_exc,_apd,$EF
_msg711:		.BYTE	_apu,_I,_,_a,_m,_,_N,_o,_r,_u,_d,_,_t,_h,_e,_,_D,_w,_a,_r,_f,_dot,$EB
				.BYTE	_W,_h,_o,_,_a,_r,_e,_,_a,_l,_l,_,_o,_f,_,_y,_o,_u,_que,$EB
				.BYTE	_G,_e,_t,_,_o,_u,_t,_,_o,_f,_,_h,_e,_r,_e,_exc,_apd,$EF
_msg712:		.BYTE	_apu,_F,_r,_o,_m,_,_n,_o,_w,_,_o,_n,_,_l,_e,_t,_,_m,_e,_,_c,_a,_l,_l,_,_y,_o,_u,_,_b,_o,_s,_s,_exc,_apd,$EF
_msg713:		.BYTE	$F7,_,$F5,_,_a,_p,_p,_e,_a,_r,_exc,$EE
_msg714:		.BYTE	$F7,_,$F5,_sem,$EE
_msg715:		.BYTE	$F7,_,$F5,_,_a,_n,_d,$EE
_msg716:		.BYTE	$F7,_,$F5,_,_a,_p,_p,_e,_a,_r,_s,_exc,$EE
_msg717:		.BYTE	$FD,$EE
_msg718:		.BYTE	$FD,$FF

		ECHO "bank 15 free space", [SAFE_STUB_ORG-.]

		ORG SAFE_STUB_ORG
		SAFE_STUB