
		ORG $8000

_b0_s0_world_map_random_enounter_test_ptr:
		.WORD	_b0_s0_world_map_random_enounter_test
_b0_s1_ptr:
		.WORD	_b0_s1
_b0_s2_ptr:
		.WORD	_b0_s2
_b0_s3_ptr:
		.WORD	_b0_s3
_b0_s4_ptr:
		.WORD	_b0_s4
_b0_s5_ptr:
		.WORD	_b0_s5
_b0_s6_ptr:
		.WORD	_b0_s6
_b0_s7_ptr:
		.WORD	_b0_s7		; used only in unreferenced sub_142728 in bank D
_b0_s8_ptr:
		.WORD	_b0_s8
_b0_s9_ptr:
		.WORD	_b0_s9
_b0_sA_ptr:
		.WORD	_b0_sA
_b0_sB_ptr:
		.WORD	_b0_sB
_b0_sC_char_get_level_ptr:
		.WORD	_b0_sC_char_get_level
_b0_sD_ptr:
		.WORD	_b0_sD
_b0_sE_ptr:
		.WORD	_b0_sE
_b0_sF_ptr:
		.WORD	_b0_sF
_b0_s10_ptr:
		.WORD	_b0_s10
_b0_s11_ptr:
		.WORD	_b0_s11
_b0_s12_ptr:
		.WORD	_b0_s12
_b0_s13_ptr:
		.WORD	_b0_s13
_b0_s14_ptr:
		.WORD	_b0_s14
_b0_s15_ptr:
		.WORD	_b0_s15
_b0_s16_ptr:
		.WORD	_b0_s16
_b0_s17_ptr:
		.WORD	_b0_s17
_b0_s18_ptr:
		.WORD	_b0_s18
_b0_s19_ptr:
		.WORD	_b0_s19
_b0_s1A_ptr:
		.WORD	_b0_s1A
_b0_s1B_ptr:
		.WORD	_b0_s1B
_b0_s1C_ptr:
		.WORD	_b0_s1C
_b0_s1D_ptr:
		.WORD	_b0_s1D
_b0_s1E_ptr:
		.WORD	_b0_s1E
_b0_s1F_ptr:
		.WORD	_b0_s1F
_b0_s20_ptr:
		.WORD	_b0_s20
_b0_s21_ptr:
		.WORD	_b0_s21
_b0_s22_ptr:
		.WORD	_b0_s22
_b0_s23_ptr:
		.WORD	_b0_s23
_b0_s24_ptr:
		.WORD	_b0_s24
_b0_s25_ptr:
		.WORD	_b0_s25
_b0_s26_ptr:
		.WORD	_b0_s26
_b0_s27_ptr:
		.WORD	_b0_s27
_b0_s28_ptr:
		.WORD	_b0_s28
_b0_s29_ptr:
		.WORD	_b0_s29
_b0_s2A_ptr:
		.WORD	_b0_s2A
_b0_s2B_ptr:
		.WORD	_b0_s2B
_b0_s2C_ptr:
		.WORD	_b0_s2C
_b0_s2D_ptr:
		.WORD	_b0_s2D
_b0_s2E_ptr:
		.WORD	_b0_s2E
_b0_s2F_ptr:
		.WORD	_b0_s2F
_b0_s30_ptr:
		.WORD	_b0_s30
_b0_s31_ptr:
		.WORD	_b0_s31
_b0_s32_ptr:
		.WORD	_b0_s32
_b0_s33_ptr:
		.WORD	_b0_s33
_b0_s34_ptr:
		.WORD	_b0_s34
_b0_s35_ptr:
		.WORD	_b0_s35
_b0_s36_ptr:
		.WORD	_b0_s36
_b0_s37_ptr:
		.WORD	_b0_s37
_b0_s38_ptr:
		.WORD	_b0_s38
_b0_s39_ptr:
		.WORD	_b0_s39
_b0_s3A_ptr:
		.WORD	_b0_s3A
_b0_s3B_ptr:
		.WORD	_b0_s3B
_b0_s3C_ptr:
		.WORD	_b0_s3C
_b0_s3D_ptr:
		.WORD	_b0_s3D
_b0_s3E_ptr:
		.WORD	_b0_s3E
_b0_d3F_ptr:
		.WORD	_b0_d3F
_b0_d42_effects_list_ptr:
		.WORD	_b0_d42_effects_list
_b0_d44_ptr:
		.WORD	_b0_d44
_b0_s45_ptr:
		.WORD	_b0_s45
_b0_s46_ptr:
		.WORD	_b0_s46
_b0_s47_ptr:
		.WORD	_b0_s47
_b0_s48_ptr:
		.WORD	_b0_s48
_b0_s49_ptr:
		.WORD	_b0_s49
_b0_s4B_ptr:
		.WORD	_b0_s4B
_b0_s4D_ptr:
		.WORD	_b0_s4D
_b0_s4E_ptr:
		.WORD	_b0_s4E
_b0_s4F_ptr:
		.WORD	_b0_s4F
_b0_s50_ptr:
		.WORD	_b0_s50
_b0_s52_ptr:
		.WORD	_b0_s52
_b0_s53_ptr:
		.WORD	_b0_s53
_b0_s54_ptr:
		.WORD	_b0_s54
_b0_s55_ptr:
		.WORD	_b0_s55
_b0_s56_ptr:
		.WORD	_b0_s56
_b0_d58_ptr:
		.WORD	_b0_d58
_b0_d59_ptr:
		.WORD	_b0_d59
_b0_s5B_ptr:
		.WORD	_b0_s5B
_b0_s5C_ptr:
		.WORD	_b0_s5C
_b0_s5D_ptr:
		.WORD	_b0_s5D
_b0_s5E_ptr:
		.WORD	_b0_s5E
_b0_s5F_ptr:
		.WORD	_b0_s5F
_b0_s60_ptr:
		.WORD	_b0_s60
_b0_s61_sram_b0_syscall_shortcuts_load_ptr:
		.WORD	_b0_s61_sram_b0_syscall_shortcuts_load
_b0_s62_ptr:
		.WORD	_b0_s62
_b0_s63_ptr:
		.WORD	_b0_s63
_b0_s64_ptr:
		.WORD	_b0_s64
_b0_s65_ptr:
		.WORD	_b0_s65
_b0_s66_ptr:
		.WORD	_b0_s66
_b0_s67_ptr:
		.WORD	_b0_s67

; =============== S U B	R O U T	I N E =======================================
; unused anymore
;_b0_s51_wrapper_for_b1B_s0:
;		FARX	_b1B_s0
;		RTS

; =============== S U B	R O U T	I N E =======================================
; unreferenced code
;sub_80D4:
;		JSR		sub_81FE
;		LDA		word_5E+1
;		JSR		sub_1743F1
;		SEC
;		SBC		#$A
;		BCS		loc_80E3
;		LDA		#0
;loc_80E3:
;		STA		word_4A+1
;		LDX		#3
;		STX		byte_4D
;loc_80E9:
;		LDA		#$A
;		JSR		sub_1743F1
;		CLC
;		ADC		word_4A+1
;		CMP		#9
;		BEQ		loc_80F9
;		CMP		#$19
;		BNE		loc_80FB
;loc_80F9:
;		LDA		#0
;loc_80FB:
;		LDX		byte_4D
;		STA		_enemy_roster_index_list,X
;		LDA		#1
;		STA		byte_571,X
;		DEC		byte_4D
;		BPL		loc_80E9
;		BRK
;		.BYTE	$CB, 7		; _b2_s9
;		JSR		sub_8650
;		LDX		#3
;		LDA		#0
;loc_8113:
;		CLC
;		ADC		byte_571,X
;		DEX
;		BPL		loc_8113
;		CMP		#2
;		BCC		_b0_s51_wrapper_for_b1B_s0
;		STA		byte_4C
;		JSR		_enemy_roster_get_levels ; enemy roster	get min/max level enemy
;		LDX		#0
;		STX		byte_51
;loc_8127:
;		LDA		byte_4D,X
;		SEC
;		SBC		word_4A+1
;		CMP		#5
;		BCC		loc_8132
;		LDA		#4
;loc_8132:
;		TAY
;		LDA		byte_81AC,Y
;		STA		byte_4D,X
;		CLC
;		ADC		byte_51
;		STA		byte_51
;		INX
;		CPX		byte_4C
;		BCC		loc_8127
;		LDX		#0
;loc_8144:
;		STX		word_4A
;		LDA		byte_51
;		STA		byte_52
;		LDA		#0
;		STA		byte_53
;		LDX		word_4A
;		LDA		byte_4D,X
;		CLC
;		ADC		#1
;		LDX		#byte_52
;		JSR		_div16_to_8
;		LDX		word_4A
;		LDA		byte_52
;		BNE		loc_8162
;		LDA		#1
;loc_8162:
;		STA		byte_6AD5,X
;		CMP		#2
;		BCC		loc_8174
;		LDA		#$A
;		JSR		sub_1743F1
;		STA		byte_6AD9,X
;		JMP		loc_817F
;loc_8174:
;		LDA		#9
;		JSR		sub_1743F1
;		CLC
;		ADC		#1
;		STA		byte_6AD9,X
;loc_817F:
;		INX
;		CPX		byte_4C
;		BCC		loc_8144
;loc_8184:
;		CPX		#4
;		BCS		loc_8193
;		LDA		#0
;		STA		byte_6AD5,X
;		STA		byte_6AD9,X
;		INX
;		BPL		loc_8184
;loc_8193:
;		LDA		byte_4C
;		JSR		sub_1743F1
;		STA		byte_6A6D
;		LDX		#0
;loc_819D:
;		LDA		byte_6A36,X
;		STA		_enemy_roster_index_list,X
;		INX
;		CPX		#4
;		BCC		loc_819D
;		BRK
;		.BYTE	$80, $17		; _b4_s26
;		RTS
;byte_81AC:
;		.BYTE	  1,  2,  3,  4,  5

; =============== S U B	R O U T	I N E =======================================
_b0_s52:
		LDA		#$FF
		STA		byte_62
		JMP		loc_861A

; =============== S U B	R O U T	I N E =======================================
; enemy	roster get min/max level enemy
;
_enemy_roster_get_levels:
		LDA		#$FF
		STA		word_4A+1
		LDX		#0
		STX		word_5E+1
loc_81C0:
		STX		word_4A
		LDA		_enemy_roster_index_list,X
		CMP		#$FF
		BEQ		loc_81DE
		JSR		_get_enemy_info_ptr
		LDY		#0
		LDA		(word_60),Y
		AND		#$3F
		CMP		word_5E+1
		BCC		loc_81D8
		STA		word_5E+1
loc_81D8:
		CMP		word_4A+1
		BCS		loc_81DE
		STA		word_4A+1
loc_81DE:
		LDX		word_4A
		STA		byte_4D,X
		INX
		CPX		#4
		BCC		loc_81C0
		RTS

; =============== S U B	R O U T	I N E =======================================
_get_enemy_info_ptr:
		STA		word_60
		LDA		#0
		STA		word_60+1
		LDA		#$17
		LDX		#word_60
		JSR		_mul16_to_8
		LDA		#<[_b0_d43_enemies_lib]
		LDY		#>[_b0_d43_enemies_lib]
		JMP		_add16_to_16

; =============== S U B	R O U T	I N E =======================================
sub_81FE:
		LDA		#0
		STA		word_5E+1
		JSR		_get_enemy_info_ptr
		LDY		#0
loc_8207:
		LDA		(word_60),Y
		AND		#$3F
		CMP		byte_700
		BEQ		loc_8212
		BCS		locret_8221
loc_8212:
		LDA		#$17
		LDX		#word_60
		JSR		_add8_to_16	; A = value
		INC		word_5E+1
		LDA		word_5E+1
		CMP		#$86
		BCC		loc_8207
locret_8221:
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s0_world_map_random_enounter_test:
		LDA		_pads+1			; random encounter disabled cheat from PRG1J reenabled
		LSR						;
		BCS		locret_823F		;
		LDA		_npc_anim_script_idx
		BNE		locret_823F
		LDX		byte_2A
		DEX
		CPX		#$FE
		BCS		locret_823F
		LDY		byte_2B
		DEY
		CPY		#$FE
		BCS		locret_823F
		LDA		byte_60C5
		BPL		loc_8240
locret_823F:
		RTS
loc_8240:
		LDA		byte_60CB
		AND		#$90
		CMP		#$80
		BEQ		locret_823F
		LDA		#$FF
		STA		byte_5C
		JSR		sub_8261
		LDA		byte_5C
		BEQ		loc_8255
		RTS
loc_8255:
		JMP		sub_174CBD

; =============== S U B	R O U T	I N E =======================================
_b0_s53:
		LDA		#$FF
		STA		word_5E
		STA		_enemy_roster_index_list
		BNE		loc_8292

; =============== S U B	R O U T	I N E =======================================
sub_8261:
		LDA		byte_9A
		BNE		loc_828E
		LDA		byte_AD
		AND		#$7F
		BEQ		loc_828E
		DEC		byte_AD
		LDA		byte_AD
		AND		#$7F
		BNE		loc_828E
		FARX	_bE_sD
		JSR		_wrap_sys0D_wrapper_to_bE_sC_arg3E
		LDA		byte_AD
		AND		#$80
		BEQ		loc_8285
		SYSX	_sys07_msg_m00_arg1,$9B
		JMP		loc_8288
loc_8285:
		SYSX	_sys07_msg_m00_arg1,$9A
loc_8288:
		FARX	_bE_s33
		JSR		_vblank
loc_828E:
		LDA		#0
		STA		word_5E
loc_8292:
		LDA		#0
		STA		byte_4C
		STA		byte_62
		LDA		byte_2F
		AND		#1
		BNE		loc_8310
		LDA		byte_2F
		AND		#2
		BEQ		loc_82C3
		LDA		byte_2A
		SEC
		SBC		#$F
		AND		#$7F
		LSR
		LSR
		LSR
		LSR
		STA		word_4A
		LDA		byte_2B
		SEC
		SBC		#5
		AND		#$70
		LSR
		ORA		word_4A
		TAX
		LDA		byte_8A46,X
		LDY		#$40
		BNE		loc_82D7
loc_82C3:
		LDA		byte_2A
		LSR
		LSR
		LSR
		LSR
		STA		word_4A
		LDA		byte_2B
		AND		#$F0
		ORA		word_4A
		TAX
		LDA		byte_8946,X
		LDY		#0
loc_82D7:
		CMP		#$FF
		BNE		loc_82DC
		RTS
loc_82DC:
		STA		word_4A
		LDA		byte_2C
		CMP		#1
		BEQ		loc_82E7
		BCC		loc_82FA
		RTS
loc_82E7:
		LDA		#0
		STA		byte_4F
		ROL		word_4A
		ROL
		ROL		word_4A
		ROL
		STA		word_4A
		TYA
		CLC
		ADC		word_4A
		JMP		loc_835A
loc_82FA:
		LDA		byte_92
		CMP		#8
		BCC		loc_8307
		CMP		#$1E
		BEQ		loc_8305
		RTS
loc_8305:
		LDA		#1
loc_8307:
		STA		byte_4F
		LDA		word_4A
		AND		#$3F
		JMP		loc_835A
loc_8310:
		LDA		#8
		STA		byte_4F
		LDA		byte_6AE6
		AND		#2
		BEQ		loc_8327
		DEC		byte_4F
		DEC		byte_4F
		LDA		byte_6AE6
		AND		#$FD
		STA		byte_6AE6
loc_8327:
		LDX		#0
		STX		word_4A
loc_832B:
		LDA		byte_8B
		CMP		byte_8377,X
		BCS		loc_8333
		RTS
loc_8333:
		LDA		word_4A
		SEC
		SBC		byte_8377,X
		STA		word_4A
		INX
		LDA		byte_8B
		CMP		byte_8377,X
		BCS		loc_8348
		ADC		word_4A
		JMP		loc_8356
loc_8348:
		LDA		word_4A
		CLC
		ADC		byte_8377,X
		STA		word_4A
		INX
		CPX		#$16
		BCC		loc_832B
		RTS
loc_8356:
		TAX
		LDA		byte_8A86,X
loc_835A:
		STA		word_4A+1
		CMP		#$FF
		BEQ		locret_8376
		LDA		#$F
		LDX		#word_4A+1
		JSR		_mul16_to_8
		LDA		#<[byte_8ADB]
		LDY		#>[byte_8ADB]
		JSR		_add16_to_16
		LDY		#0
		LDA		(word_4A+1),Y
		BNE		loc_838D
locret_8376:
		RTS
byte_8377:
		.BYTE	  3,  4,  8,  9,$2D,$41,$58,$5B,$9C,$AB,$B2,$B3,$BB,$C0,$C3,$CD
		.BYTE	$CF,$D9,$DB,$DF,$E4,$F3
loc_838D:
		STA		word_4A
		LDA		word_5E
		BNE		loc_83F3
		LDA		word_4A
		LSR
		LSR
		LSR
		LSR
		LSR
		TAX
		LDA		byte_8628,X
		CPX		#3
		BCS		loc_83AE
		STA		byte_4D
		JSR		sub_1743B8
		CMP		byte_4D
		BCC		loc_83AC
		RTS
loc_83AC:
		LDA		#1
loc_83AE:
		STA		byte_4D
		LDA		#0
		STA		byte_4E
		LDX		byte_4F
		LDA		byte_2F
		BNE		loc_83C1
		LDA		byte_6DF
		CMP		#$78
		BCS		loc_83C6
loc_83C1:
		LDA		byte_8934,X
		BNE		loc_83C9
loc_83C6:
		LDA		byte_893D,X
loc_83C9:
		LDX		#byte_4D
		JSR		_mul16_to_8
		LDA		#$4A
		STA		byte_CE
		JSR		_b0_s2B
		BCC		loc_83DD
		LDA		#$64
		STA		byte_4D
		BNE		loc_83EB
loc_83DD:
		LDA		byte_4E
		BNE		loc_83E7
		LDA		byte_4D
		CMP		#$64
		BCC		loc_83EB
loc_83E7:
		LDA		#$64
		STA		byte_4D
loc_83EB:
		JSR		sub_1743B8
		CMP		byte_4D
		BCC		loc_83F3
		RTS
loc_83F3:
		JSR		sub_85DB
		LDA		word_4A
		AND		#3
		STA		byte_49
		LDA		word_4A
		AND		#$1C
		LSR
		LSR
		STA		byte_4D
		LDA		#0
		STA		byte_4E
		LDA		#$11
		LDX		#byte_4D
		JSR		_mul16_to_8
		LDA		#<[byte_90F3]
		LDY		#>[byte_90F3]
		JSR		_add16_to_16
		LDA		#1
		LDX		#word_4A+1
		JSR		_add8_to_16
		LDA		#$64
		STA		byte_55
loc_8424:
		DEC		byte_55
		BNE		loc_8429
		RTS
loc_8429:
		JSR		sub_1743B8
		LDY		#0
loc_842E:
		CMP		(byte_4D),Y
		BCC		loc_8437
		INY
		CPY		#$D
		BCC		loc_842E
loc_8437:
		JSR		sub_8595
		BEQ		loc_8424
		LDA		(word_4A+1),Y
		CMP		#$FF
		BEQ		loc_8424
		CPY		#5
		BCC		loc_84B3
		BEQ		loc_84C3
		CPY		#$B
		BCC		loc_84B0
		BEQ		loc_84B6
		LDA		(word_4A+1),Y
		STA		byte_4F
		LDA		#0
		STA		byte_50
		LDA		#6
		LDX		#byte_4F
		JSR		_mul16_to_8
		LDA		#<[byte_907B]
		LDY		#>[byte_907B]
		JSR		_add16_to_16
		LDX		#0
		STX		byte_53
		STX		byte_52
loc_846C:
		TXA
		LSR
		TAY
		LDA		(byte_4F),Y
		STA		byte_51
		TXA
		AND		#1
		BEQ		loc_847E
		LSR		byte_51
		LSR		byte_51
		LSR		byte_51
loc_847E:
		LDA		byte_51
		AND		#7
		TAY
		LDA		byte_8638,Y
		JSR		sub_1743F1
		CLC
		ADC		byte_8640,Y
		BEQ		loc_84A5
		LDX		byte_53
		STA		byte_571,X
		LDA		byte_52
		CLC
		ADC		#2
		TAY
		LDA		(byte_4F),Y
		STA		_enemy_roster_index_list,X
		CMP		#$FF
		BEQ		loc_84A5
		INC		byte_53
loc_84A5:
		INC		byte_52
		LDX		byte_52
		CPX		#4
		BCC		loc_846C
		JMP		sub_85B3
loc_84B0:
		JMP		loc_84E9
loc_84B3:
		JMP		loc_851C
loc_84B6:
		LDA		#1
		STA		byte_571
loc_84BB:
		LDA		(word_4A+1),Y
		STA		_enemy_roster_index_list
		JMP		sub_85B3
loc_84C3:
		LDA		#$14
		STA		byte_56
loc_84C7:
		DEC		byte_56
		BEQ		loc_84E4
		LDA		#5
		JSR		sub_1743F1
		TAY
		JSR		sub_8595
		BEQ		loc_84C7
		LDA		(word_4A+1),Y
		CMP		#$FF
		BEQ		loc_84C7
		STA		_enemy_roster_index_list+1
		LDA		#8
		STA		byte_572
loc_84E4:
		LDY		#5
		JMP		loc_84B6
loc_84E9:
		TYA
		TAX
		LDY		#$F
		LDA		(byte_4D),Y
		STA		byte_4F
		INY
		LDA		(byte_4D),Y
		STA		byte_50
		TXA
		TAY
		SEC
		SBC		#6
		ASL
		TAX
loc_84FD:
		DEX
		BMI		loc_8507
		ROR		byte_50
		ROR		byte_4F
		JMP		loc_84FD
loc_8507:
		LDA		#3
		AND		byte_4F
		TAX
		LDA		byte_8630,X
		JSR		sub_1743F1
		CLC
		ADC		byte_8634,X
		STA		byte_571
		JMP		loc_84BB
loc_851C:
		LDA		#0
		LDX		#9
loc_8520:
		STA		byte_4F,X
		DEX
		BPL		loc_8520
		LDA		(word_4A+1),Y
		STA		_enemy_roster_index_list
		LDX		#1
		LDA		#$D
		STA		byte_53,Y
		STA		byte_59
loc_8533:
		LDA		#$14
		STA		byte_5A
loc_8537:
		DEC		byte_5A
		BEQ		loc_8571
		LDA		#6
		JSR		sub_1743F1
		TAY
		JSR		sub_8595
		BEQ		loc_8537
		LDA		byte_53,Y
		BNE		loc_8537
		LDA		(word_4A+1),Y
		CMP		#$FF
		BEQ		loc_8537
		STA		_enemy_roster_index_list,X
		LDA		#1
		STA		byte_53,Y
		CPY		#5
		BNE		loc_855F
		STA		byte_4F,X
loc_855F:
		JSR		sub_1743B8
		LDY		byte_59
		CMP		(byte_4D),Y
		BCS		loc_8571
		INX
		INC		byte_59
		CPY		#$F
		BCC		loc_8533
		LDX		#3
loc_8571:
		INX
		STX		byte_59
		LDX		#3
		LDA		#1
loc_8578:
		STA		byte_571,X
		DEX
		BPL		loc_8578
loc_857E:
		LDA		#3
		JSR		sub_1743F1
		BEQ		sub_85B3
		LDA		byte_59
		JSR		sub_1743F1
		TAX
		LDA		byte_4F,X
		BNE		loc_857E
		INC		byte_571,X
		JMP		loc_857E

; =============== S U B	R O U T	I N E =======================================
sub_8595:
		LDA		byte_2F
		BEQ		loc_859A
		RTS
loc_859A:
		LDA		byte_6DF
		CMP		#$78
		BCS		loc_85AC
		CPY		#4
		BEQ		locret_85AB
		CPY		#$A
		BEQ		locret_85AB
		CPY		#$D
locret_85AB:
		RTS
loc_85AC:
		CPY		#0
		BEQ		locret_85AB
		CPY		#6
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_85B3:
		JSR		_enemy_roster_get_levels
		LDA		byte_700
		SEC
		SBC		word_5E+1
		BCS		loc_85C0
		LDA		#0
loc_85C0:
		STA		byte_6A6A
		LDA		byte_2F
		AND		#1
		BNE		loc_861A
		LDA		byte_AD
		AND		#$7F
		BEQ		loc_861A
		LDA		word_5E
		BNE		loc_861A
		LDA		byte_6A6A
		CMP		#5
		BCC		loc_861A
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_85DB:
		LDA		#$FF
		LDX		#3
loc_85DF:
		STA		_enemy_roster_index_list,X
		DEX
		BPL		loc_85DF
		LDA		#0
		LDX		#3
loc_85E9:
		STA		byte_571,X
		DEX
		BPL		loc_85E9
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s1:
		TAY
		JSR		sub_85DB
		INY
		STY		byte_62
		LDX		#0
loc_85F9:
		DEY
		BEQ		loc_8606
loc_85FC:
		LDA		byte_88DE,X
		INX
		CMP		#$FF
		BNE		loc_85FC
		BEQ		loc_85F9
loc_8606:
		LDA		byte_88DE,X
		CMP		#$FF
		BEQ		sub_8683
		STA		_enemy_roster_index_list,Y
		LDA		byte_8909,X
		STA		byte_571,Y
		INX
		INY
		BNE		loc_8606
loc_861A:
		JSR		sub_8650
		LDA		_enemy_roster_index_list
		CMP		#$FF
		BNE		sub_8683
		RTS

byte_8628:
		.BYTE	$10,$40,$80,  1,  2,  4,  8,$10
byte_8630:
		.BYTE	  1,  2,  2,  5
byte_8634:
		.BYTE	  8,  4,  2,  3
byte_8638:
		.BYTE	  1,  4,  3,  8,  1,  1,  1,  3
byte_8640:
		.BYTE	  8,  4,  1,  1,  1,  2,  3,  0

; =============== S U B	R O U T	I N E =======================================
sub_8650:
		LDX		#0
		LDY		#0
loc_8654:
		LDA		_enemy_roster_index_list,X
		STA		word_4A
		CMP		#$8B
		BCS		loc_866B
		LDA		byte_571,X
		BEQ		loc_866B
		STA		byte_571,Y
		LDA		word_4A
		STA		_enemy_roster_index_list,Y
		INY
loc_866B:
		INX
		CPX		#4
		BCC		loc_8654
loc_8670:
		CPY		#4
		BCS		locret_8682
		LDA		#$FF
		STA		_enemy_roster_index_list,Y
		LDA		#0
		STA		byte_571,Y
		INY
		JMP		loc_8670
locret_8682:
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_8683:
		JSR		_clear_nmi_flag_10
		JSR		sub_88BD
		LDA		#0
		LDX		#$77
loc_868D:
		STA		byte_580,X
		DEX
		BPL		loc_868D
		LDA		byte_62
		CMP		#$FF
		BNE		loc_86A4
		LDX		#$1B
loc_869B:
		LDA		byte_88A1,X
		STA		byte_5B0,X
		DEX
		BPL		loc_869B
loc_86A4:
		LDA		#$10
		LDX		byte_62
		CPX		#9
		BNE		loc_86AE
		LDA		#$12
loc_86AE:
		FARX	_bB_s3_apu_load
		JSR		sub_8841
		JSR		sub_1742B0
		LDA		byte_62
		CMP		#$FF
		BNE		loc_86C2
		LDX		#$14
		JSR		_vblank_count
loc_86C2:
		JSR		_ppu_screen_clear
		LDA		#$FD
		STA		byte_32
		LDA		byte_60B7
		ORA		#$20
		STA		byte_60B7
		LDA		#0
		STA		byte_6D0
		STA		byte_6D1
		LDA		byte_6D3
		AND		#$FE
		STA		byte_6D3
		JSR		sub_872B
		JSR		_vblank_and_render_off
		LDA		byte_62
		CMP		#$FF
		BNE		loc_86F5
		LDA		#$30
		STA		_ram_pal_buf+1
		STA		byte_6E0
loc_86F5:
		FARX	_b2_s0
		FARX	_b2_s2
		LDA		#$40
		STA		_tmp21
		JSR		_pal_fade
		JSR		sub_872B
		JSR		sub_17443A
		JSR		_pal_fade_in
		LDA		byte_62
		CMP		#1
		BEQ		loc_871B
		CMP		#$FF
		BNE		loc_8721
		FARX	_b4_s24
		JMP		loc_8724
loc_871B:
		FARX	_b4_s25
		JMP		loc_8724
loc_8721:
		FARX	_b4_s0
loc_8724:
		LDA		#0
		STA		byte_32
		STA		byte_5C
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_872B:
		LDA		_nmi_counter
loc_872E:
		CMP		_nmi_counter
		BEQ		loc_872E
		RTS
byte_8734:
		.BYTE	$20,$1E,$20,$1E

; =============== S U B	R O U T	I N E =======================================
sub_8738:
		LDX		#0
loc_873A:
		LDA		byte_4D,X
		CMP		byte_8734,X
		BCC		loc_8752
		CMP		#$90
		BCC		loc_874B
		LDA		#0
		STA		byte_4D,X
		BEQ		loc_8752
loc_874B:
		LDA		byte_8734,X
		TAY
		DEY
		STY		byte_4D,X
loc_8752:
		INX
		CPX		#4
		BCC		loc_873A
		LDA		#0
		STA		byte_55
		LDX		#$FF
		LDA		#1
		STA		byte_53
		STA		byte_54
		LDA		byte_4F
		SEC
		SBC		byte_4D
		BCS		loc_8770
		EOR		#$FF
		ADC		#1
		STX		byte_53
loc_8770:
		STA		byte_51
		LDA		byte_50
		SEC
		SBC		byte_4E
		BCS		loc_877F
		EOR		#$FF
		ADC		#1
		STX		byte_54
loc_877F:
		STA		byte_52
		CMP		byte_51
		BCC		loc_878A
		JSR		sub_87BA
		INC		byte_55
loc_878A:
		LDA		byte_51
		LSR
		STA		word_4A
		LDA		byte_4D
		STA		byte_56
		LDA		byte_4E
		STA		byte_57
loc_8797:
		JSR		sub_87D0
		LDA		word_4A
		CLC
		ADC		byte_52
		STA		word_4A
		CMP		byte_51
		BCC		loc_87B0
		SBC		byte_51
		STA		word_4A
		LDA		byte_57
		CLC
		ADC		byte_54
		STA		byte_57
loc_87B0:
		LDA		byte_56
		CMP		byte_4F
		BNE		sub_87C6
		LDA		byte_55
		BEQ		locret_87C5

; =============== S U B	R O U T	I N E =======================================
sub_87BA:
		LDX		#$4D
loc_87BC:
		JSR		sub_8828
		INX
		INX
		CPX		#$55
		BCC		loc_87BC
locret_87C5:
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_87C6:
		LDA		byte_56
		CLC
		ADC		byte_53
		STA		byte_56
		JMP		loc_8797

; =============== S U B	R O U T	I N E =======================================
sub_87D0:
		LDY		#0
		LDA		byte_55
		BEQ		loc_87D7
		INY
loc_87D7:
		LDA		byte_56,Y
		STA		word_4
		CMP		#$20
		BCS		locret_881F
		INY
		TYA
		AND		#1
		TAY
		LDA		#$80
		STA		word_4A+1
		LDA		#5
		STA		byte_4C
		LDA		byte_56,Y
		STA		word_4+1
		CMP		#$1E
		BCS		locret_881F
		ASL
		ASL
		LDX		#word_4A+1
		JSR		_add8_to_16
		LDA		word_4
		LSR
		LSR
		LSR
		JSR		_add8_to_16
		LDA		word_4
		AND		#7
		TAX
		LDY		#0
		LDA		(word_4A+1),Y
		AND		byte_8820,X
		BNE		locret_881F
		LDA		(word_4A+1),Y
		ORA		byte_8820,X
		STA		(word_4A+1),Y
		LDA		#0
		JSR		sub_1742C7
locret_881F:
		RTS
byte_8820:
		.BYTE	  1,  2,  4,  8,$10,$20,$40,$80

; =============== S U B	R O U T	I N E =======================================
sub_8828:
		LDA		byte_0,X
		LDY		byte_1,X
		STY		byte_0,X
		STA		byte_1,X
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_8831:
		LDY		#0
loc_8833:
		LDA		byte_0,X
		STA		byte_4D,Y
		INX
		INY
		CPY		#4
		BCC		loc_8833
		JMP		sub_8738

; =============== S U B	R O U T	I N E =======================================
sub_8841:
		LDX		#$10
		STX		byte_58
		STX		byte_5A
		STX		byte_5C
		STX		word_5E
		DEX
		STX		byte_59
		STX		byte_5B
		STX		byte_5D
		STX		word_5E+1
loc_8854:
		JSR		sub_8897
		JSR		sub_1742B0
		LDY		#2
loc_885C:
		INC		word_5E
		INC		byte_5B
		DEC		byte_5C
		DEC		byte_59
		DEY
		BNE		loc_885C
		LDA		byte_5C
		BNE		loc_8854
loc_886B:
		JSR		sub_8897
		INC		byte_58
		DEC		byte_5A
		INC		word_5E+1
		DEC		byte_5D
		BNE		loc_886B
loc_8878:
		JSR		sub_8897
		INC		byte_5C
		DEC		word_5E
		INC		byte_58
		DEC		byte_5A
		BNE		loc_8878
loc_8885:
		JSR		sub_8897
		INC		byte_5C
		DEC		word_5E
		INC		byte_59
		DEC		byte_5B
		LDA		byte_59
		CMP		#$F
		BCC		loc_8885
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_8897:
		LDX		#$58
		JSR		sub_8831
		LDX		#$5C
		JMP		sub_8831
byte_88A1:
		.BYTE	$BC,$73,$D2,$27,  4,$89,$12,$21,  4,  9,$12,$21,$1C,  9,$1E,$21
		.BYTE	  4,$E9,$12,$21,  4,$89,$12,  1,$84,$F3,$12,$21

; =============== S U B	R O U T	I N E =======================================
sub_88BD:
		LDX		#$C
loc_88BF:
		TXA
		PHA
		LDA		byte_6D4
		EOR		#1
		STA		byte_6D4
		LDX		#3
		JSR		_vblank_count
		PLA
		TAX
		DEX
		BNE		loc_88BF
		LDA		byte_6D4
		AND		#$EF
		STA		byte_6D4
		JMP		_vblank
byte_88DE:
		.BYTE	$87,$81,$FF,$65,$FF,$88,$8A,$8A,$8A,$FF,$89,$8A,$FF,$8A,$FF,$34
		.BYTE	$FF,$7D,$FF,$83,$FF,$85,$FF,$82,$FF,$7F,$FF,$20,$FF,$62,$FF,$5F
		.BYTE	$FF,$75,$FF,$81,$FF,$6F,$FF,$84,$FF,$36,$FF
byte_8909:
		.BYTE	  1,  1,  0,  1,  0,  1,  1,  1,  1,  0,  1,  2,  0,  5,  0,  1
		.BYTE	  0,  2,  0,  1,  0,  1,  0,  1,  0,  2,  0,  8,  0,  1,  0,  1
		.BYTE	  0,  2,  0,  2,  0,  1,  0,  1,  0,  1,  0
byte_8934:
		.BYTE	  4, $F, $A, $F,$12,$19,$54,$12, $A
byte_893D:
		.BYTE	  5,$13, $D,$13,$16,$1F,$54,$16, $A
byte_8946:
		.BYTE	$1F, $A, $A, $A, $A, $A, $A, $A, $A,$25,$25,$25,$25,$25,$25,$25
		.BYTE	$1F, $A, $A, $A, $A, $A,$CA,$EC,$2C,$2C,$25,$25,$25,$25,$25,$25
		.BYTE	$1F,$1F,  9,$49,$89,$8A,$2E,$2D,$EC,$2C,$24,$24,$24,$24,$24,$24
		.BYTE	$1F,  9,  9,$48,$89,$AE,$AE,$2C,$EC,$EC,$E3,$24,$23,$23,$23,$23
		.BYTE	$1F,  9,$48,  8,$88,$8C,$AD,$2C,$2C,$D8,$E4,$24,$64,$61,$20,$20
		.BYTE	 $F, $F, $F,  8, $C,$8C,$10,$2D,$6D,$18,$18,$24,$64,$61,$61,$20
		.BYTE	 $F, $F, $E, $F, $C, $C,$10,$55,$56,$57,$18,$18,$24,$61,$21,$20
		.BYTE	$1A, $E, $D, $D,$4C,$CC,$11,$55,$56,$17,$17,$20,$20,$20,$20,$20
		.BYTE	$1A,$4E,$4E,$4D,$8D,$91,$11,$54,$54,$16,$17,$27,$27,$27,$2A,$2A
		.BYTE	$1A,$1A,$5A,$4D,$30,$12,$12,$13,$13,$1C,$1C,$1C,$29,$2B,$2A,$27
		.BYTE	$1A,$1A,$5A,$71,$30,$12,$13,$13,$13,$13,$27,$27,$27,$2B,$27,$27
		.BYTE	$1B,$1B,$5B,$30,$30,  6,  6,  6,  6,  6,  6,  7,  7,$29,$27,$27
		.BYTE	$1B,$1B,$1B,$1B,$1B,$1D,$1D,$1D,  5,  5,$46,  7,  7,$27,$27,$27
		.BYTE	$1D,$1D,$1D,$1D,$1D,$1D,$2F,$1D,  5,  5,  4,  7,  7,$29,$27,$27
		.BYTE	$1E,$DE,$DE,$DE,$DE,$DD,$1D,$1D,  5,  5,  4,  7,$E9,$E9,$29,$29
		.BYTE	$1E,$DE,$DE,$DE,$DE,$DE,$1E,$1E,$1E,$1E,$1E,$1E,$E9,$E9,$29,$29
byte_8A46:
		.BYTE	$33,$33,$33,$34,$3D,$3D,$3D,$3D,$33,$33,$33,$34,$34,$3D,$3D,$3D
		.BYTE	$33,$32,$32,$34,$34,$34,$3D,$3D,$33,$32,$32,$34,$34,$3C,$3C,$3C
		.BYTE	$33,$32,$32,$3F,$3C,$3C,$3C,$3C,$36,$36,$36,$37,$39,$39,$3A,$3A
		.BYTE	$36,$36,$36,$37,$37,$39,$3A,$3A,$36,$36,$36,$37,$39,$39,$3A,$3A
byte_8A86:
		.BYTE	 $B,$3F,$41,$4A,$FF,$FF,$4F,$4F,$FF,$53,$58,$5F,$5D,$FF,$3B,$FF
		.BYTE	$4C,$43,$54,$5A,$47,$38, $B,$FF, $B,$4E,$4E,$FF,$42,$FF,$46,$45
		.BYTE	$4A,$4B,$4B,$FF,$3B,$52,$52,$51,$FF,$59,$5F,$57,$5D,$5E,$3E,$FF
		.BYTE	$3E,$FF,$FF,$26,$22,$19,$19,$FF,$50,$50,$4C,$4D,$4D,$4D,$4D,$43
		.BYTE	$44,$FF,$55,$55,$56,$56,$5A,$5B,$5B,$5C,$47,$48,$FF,$48,$FF,$FF
		.BYTE	$FF,$28,$38,$35,$35
byte_8ADB:
		.BYTE	$64,$FF,$3F,$40,$41,$42,$FF,$40,$3F,$41,$45,$42,$42,$FF,$FF,$64
		.BYTE	$FF,$43,$40,$41,$49,$28,$41,$43,$43,$40,$49,$FF,$FF,$FF,$84,$55
		.BYTE	$41,$43,$49,$55,$FF,$45,$43,$55,$44,$55,$55,$FF,$FF,$84,$3F,$42
		.BYTE	$43,$44,$60,$FF,$44,$42,$45,$43,$60,$60,$FF,$FF,$60,$FF,  0,$FF
		.BYTE	  1,$FF,$FF,  1,  0,  0,  1,  1,  0,$FF,$FF,$60,$FF,  1,$FF,  0
		.BYTE	  2,  0,  0,  1,  0,  1,  2,$FF,$FF,$FF,$64,  1,  0,  2,  3,  1
		.BYTE	$FF,  2,  0,  1,  3,  2,$FF,$FF,$FF,$6C,  4,  5,  6,  8, $B,$FF
		.BYTE	  6,  8,  5,  7, $B,  9,$FF,$FF,$64, $D, $C,  7, $B, $D,$FF, $C
		.BYTE	  7, $D, $F, $E,$1B,$FF,$FF,$64, $F, $D,$11,$10, $F,  4,$10, $D
		.BYTE	$10,$11, $E,$1B,$FF,$FF,$64,$12,$14,$15, $F,$16,$1B,$14,$11,$15
		.BYTE	$12,$16,$18,$FF,$FF,$48,$66,$63,$64,$2E,$66,$6C,$66,$2E,$6E,$5B
		.BYTE	$66,$5B,$FF,$FF,$68,$FF,$1E,$1C,$16,$19,$FF,$12,$1C,$1E,$1E,$1B
		.BYTE	$14,$FF,  1,$60,$21,$21,$1C,$23,$20,$13,$21,$1C,$1A,$23,$20,$FF
		.BYTE	$FF,$FF,$64,$1A,$23,$1C,$21,$20,$FF,$23,$23,$21,$1C,$20,$FF,$FF
		.BYTE	$FF,$88,$15,$22,$16,$1B,$19,$22,$17,$22,$FF,$22,$19,$FF,  1,  1
		.BYTE	$60,$27,$29,$21,$1C,$27,$FF,$29,$29,$27,$26,$25,$FF,$FF,  2,$60
		.BYTE	$26,$27,$29,$26,$25,  9,$26,$27,$29,$26,$25,$FF,$FF,$FF,$68,$26
		.BYTE	$2A,$27,$25,$2A,$FF,$2A,$26,$2A,$26,$47,$FF,$FF,$FF,$64,$25,$2A
		.BYTE	$27,$26,$25,$28,$27,$26,$2A,$FF,$47,$FF,$FF,$FF,$68,$28,$2C,$2F
		.BYTE	$2A,$28,$FF,$FF,$2F,$28,$2C,$33,$46,$FF,$FF,$68,$2C,$2F,$28,$31
		.BYTE	$2C,$FF,$2D,$2C,$2F,$28,$33,$46,$FF,$FF,$68,$49,$34,$30,$39,$49
		.BYTE	$3A,$49,$34,$39,$30,$47,$3A,$FF,$FF,$6C,$3D,$39,$34,$3D,$3B,$FF
		.BYTE	$39,$39,$34,$3D,$3B,$FF,$FF,$FF,$6C,$34,$FF,$3D,$39,$3B,$FF,$39
		.BYTE	$34,$31,$3D,$3B,$FF,$FF,$FF,$64,$80,$7F,$7E,$7D,$80,$77,$80,$7F
		.BYTE	$7E,$67,$80,$67, $D, $D,$68,$3C,$3E,$32,$49,$3C,$FF,$3E,$32,$3D
		.BYTE	$3C,$3E,$FF,  2,  7,$68,$4F,$3C,$3E,$32,$4F,$FF,$4F,$3E,$32,$3C
		.BYTE	$4F,$FF,  8,  8,$88,$FF,$FF,$46,$1D,$FF,$FF,$FF,$1D,$46,$FF,$FF
		.BYTE	$FF,$FF,$FF,$68,$FF,$32,$4F,$18,$FF,$49,$FF,$18,$32,$4F,$FF,$FF
		.BYTE	$FF,$FF,$48,$FF,$46,$45,$FF,$52,$FF,$FF,$46,$45,$FF,$52,$5B,$FF
		.BYTE	$FF,$64,$3E,$3C,$3E,$3B,$3E,$2B,$3E,$3B,$3E,$3C,$3E,$FF,$FF,$FF
		.BYTE	$60,$49,$4B,$45,$4F,$48,$FF,$48,$4B,$45,$4B,$FF,$FF,$FF,$FF,$68
		.BYTE	$4B,$4A,$4F,$45,$4B,$FF,$4A,$44,$4B,$48,$4A,$FF,$10,$10,$48,$7F
		.BYTE	$7D,$7E,$7E,$7F,$77,$7F,$7E,$7D,$7E,$7F,$67,  6,  6,$64,$4A,$4F
		.BYTE	$48,$4B,$4A,$49,$4B,$31,$4A,$45,$4B,$FF,$FF,$FF,$68,$48,$4F,$4A
		.BYTE	$4B,$48,$35,$4A,$48,$4B,$FF,$31,$6C,$FF,$FF,$68,$52,$48,$52,$FF
		.BYTE	$52,$FF,$52,$48,$52,$FF,$52,$5B,$FF,$FF,$64,$7D,$7C,$7F,$FF,$7D
		.BYTE	$7B,$7D,$7F,$7C,$77,$7D,$FF,  5,  5,$60,$3E,$4F,$54,$4B,$54,$FF
		.BYTE	$FF,$54,$FF,$54,$FF,$FF,$FF,$FF,$64,$78,$76,$74,$6C,$78,$FF,$78
		.BYTE	$76,$74,$78,$78,$67, $C, $C,$68,$FF,$43,$3F,$31,$54,$FF,$3E,$43
		.BYTE	$45,$54,$4B,$FF,$FF,$FF,$68,$55,$58,$50,$59,$55,$50,$55,$59,$54
		.BYTE	$50,$55,$55,  4,  4,$68,$50,$4C,$54,$4C,$50,$FF,$FF,$50,$54,$4C
		.BYTE	$FF,$54,  9,  9,$68,$50,$58,$3B,$4C,$50,$57,$50,$58,$31,$4C,$50
		.BYTE	$58,$FF,$FF,$68,$58,$50,$4C,$5F,$58,$56,$58,$50,$FF,$3A,$58,$FF
		.BYTE	  3,  3,$68,$4D,$50,$57,$58,$4D,$56,$4D,$57,$50,$58,$4D,$FF,$FF
		.BYTE	$FF,$64, $D, $B,$1B,$16,$19,$17,$21,$16,$19,$1E,$24,$1B,$FF,$FF
		.BYTE	$68,$5C,$5D,$5F,$FF,$5C,$2B,$FF,$5F,$5D,$5C,$5C,$FF,$13,$13,$68
		.BYTE	$5A,$FF,$52,$56,$5A,$5B,$5A,$5D,$52,$5D,$5A,$5B, $A, $A,$68,$68
		.BYTE	$69,  0,$FF,$68,$63,$69,  0,$68,$FF,$FF,$67,$12,$12,$68,$69,$68
		.BYTE	$6D,$FF,$69,$FF,$69,$6D,$68,$FF,$69,$67,$FF,$FF,$68,$66,$6F,$69
		.BYTE	$6F,$66,$67,$66,$6F,$69,$6F,$66,$77,$FF,$FF,$46,$6A,$78,$5A,$76
		.BYTE	$6A,$69,$6A,$FF,$78,$76,$6A,$76,$FF,$FF,$68,$53,$6A,$6F,$68,$53
		.BYTE	$FF,$53,$6A,$53,$66,$53,$FF,$FF,$FF,$64,$69,$53,$71,$6F,$6D,$6B
		.BYTE	$6B,$6F,$53,$71,$6B,$FF,$FF,$FF,$64,$76,$78,$6C,$79,$76,$FF,$76
		.BYTE	$79,$79,$6B,$76,$76,$FF,$FF,$68,$53,$78,$74,$68,  0,$FF,$69,$78
		.BYTE	$74,$53,$69,$6C,$FF,$FF,$68,$53,$70,$6A,$6D,$53,$70,$6D,$74,$70
		.BYTE	$63,$74,$70, $E, $E,$68,$64,$5A,$74,$63,$64,$5E,$74,$63,$5A,$69
		.BYTE	$74,$FF,$FF,$FF,$68,$74,$53,$69,$FF,$74,$6C,$74,$71,$74,$6C,$74
		.BYTE	$FF,$FF,$FF,$68,$6D,$71,$FF,$69,$6D,$79,$6D,$71,$69,$79,$6D,$71
		.BYTE	$FF,$FF,$64,$7B,$7A,$79,$FF,$7B,$67,$7B,$79,$7A,$FF,$7B,$77,$FF
		.BYTE	$FF,$68,$7C,$7B,$7A,$FF,$7C,$6B,$7B,$7A,$FF,$7C,$7C,$FF, $B, $B
		.BYTE	$64,$72,$73,$3F,$40,$72,$64,$73,$60,$72,$5D,$73,$FF,$FF,$FF,$60
		.BYTE	$FF,  2,  0,  1,$FF,$FF,  2,  0,  1,  3,  2,$FF,$FF,$FF,$60,  0
		.BYTE	  3,  5,  2,  0,$FF,  5,  3,  2,  4,  5,$FF,$FF,$FF,$44,  3,  1
		.BYTE	$FF,  5,  3,$FF,  4,  1,  3,  6,  4,$FF,  0,  0,$64,  5,  3,  4
		.BYTE	  6,  5,$FF,  6,  1,  4,  8,  6,  7,$FF,$FF,$84,$FF, $A, $B,  6
		.BYTE	$FF,$FF, $A,  6, $B,  7, $A, $D,$FF,$FF,$44, $B, $A,  4,  8, $B
		.BYTE	$FF, $B, $A, $A, $B,  7, $D,$FF,$FF,$64,$10,$12,$11, $E,$10,$FF
		.BYTE	 $E,$10,$11,$12, $E,$1B,$FF,$FF,$64,$13,$12, $E,$14,$13,$FF,$14
		.BYTE	 $E,$12,$13,$14,$1B,$FF,$FF,$64,$11,$1B,$14,$13,$12, $E,$FF,$13
		.BYTE	$14,$1B,$FF,$1B,$FF,$FF,$40,$16,$17,$FF,$19,$16,$FF,$16,$FF,$17
		.BYTE	$19,$16,$19,$FF,$FF,$64,$1A,$19,$17,$16,$1A,$FF,$1A,$16,$17,$19
		.BYTE	$1A,$19,$FF,$FF,$68,$20,$1D,$23,$FF,$20,$1F,$23,$1D,$20,$FF,$FF
		.BYTE	$1F,$FF,$FF,$64,$24,$FF,$20,$1D,$24,$1F,$24,$FF,$1D,$24,$FF,$FF
		.BYTE	$FF,$FF,$68,$44,$43,$61,$40,$44,$60,$47,$44,$43,$60,$47,$FF,$FF
		.BYTE	$FF,$64,$63,$6E,$5D,$5A,$63,$FF,$5D,$63,$6E,$5A,$5D,$5E,$FF,$FF
		.BYTE	$48,$18,$24,$FF,$20,$18,$FF,$18,$20,$1D,$24,$18,$FF,$FF,$FF,$68
		.BYTE	$6E,$5F,$63,$5D,$6E,$5E,$6E,$5F,$64,$5F,$6E,$6C,$FF,$FF,$60,$5F
		.BYTE	$63,$5C,$64,$5F,$FF,$5F,$5C,$63,$64,$5F,$6C,$FF,$FF,$64,$2D,$33
		.BYTE	$18,$28,$2D,$1F,$2D,$33,$18,$28,$2D,$FF, $F, $F,$68,$38,$2F,$2C
		.BYTE	$18,$38,$28,$38,$2C,$38,$26,$26,$FF,$FF,$FF,$60,$FF,$49,$38,  9
		.BYTE	$FF,$3A,$FF,$38,$49,$FF,$FF,$3A,$FF,$FF,$60,$FF,$30,$49,$31,$FF
		.BYTE	$3A,$30,$49,$31,$38,$30,$3A,$FF,$FF,$44,$2C,$2F,$3C,$25,$1C,$35
		.BYTE	$3E,$24,$23,$3C,$3E,$3A,$FF,$FF,$68,$35,$46,$4E,$1D,$35,$FF,$35
		.BYTE	$46,$4E,$4E,$35,$4E,$FF,  4,$64,$4E,$35,$46,$47,$4E,$FF,$4E,$46
		.BYTE	$35,$47,$4E,$4E,$FF,$FF,$68,$4C,$4A,$37,$4B,$4C,$FF,$4C,$37,$37
		.BYTE	$48,$4C,$FF,$FF,$FF,$68,$3B,$49,$37,$4C,$3B,$18,$37,$4C,$3B,$4C
		.BYTE	$37,$FF,$FF,$FF,$68,$4C,$37,$4B,$37,$3B,$45,$37,$4C,$4C,$3A,$3B
		.BYTE	$3A,$FF,$FF,$68,$59,$55,$61,$51,$59,$51,$59,$55,$61,$51,$59,$55
		.BYTE	$11,$11,$68,$61,$59,$51,$55,$61,$FF,$61,$59,$51,$55,$61,$FF,$FF
		.BYTE	$FF,$44,$26,$34,$1B,$2A,$2F,$31,$1B,$26,$33,$24,$21,$FF,$FF,$FF
byte_907B:
		.BYTE	$13,  0,  2,  4,$FF,$FF, $D,  0,$1B,  9,$FF,$FF,$36,  0,  9,$31
		.BYTE	$FF,$FF, $C,  0,$57,$31,$FF,$FF,  0,  0,$31,$FF,$FF,$FF,$2D,  0
		.BYTE	$77,$6C,$FF,$FF, $C,  0,$75,$69,$FF,$FF, $D,  0,$3E,  9,$FF,$FF
		.BYTE	 $D,  0,$4F,$47,$FF,$FF, $D,  0,$59,$47,$FF,$FF, $C,  0,$5A,$2B
		.BYTE	$FF,$FF,$24,  0,$70,$6C,$FF,$FF,$26,  0,$7C,$56,$FF,$FF,$34,  0
		.BYTE	$75,$77,$FF,$FF,$2C,  0,$70,$57,$FF,$FF,$2E,  0,$26,$1C,$FF,$FF
		.BYTE	$35,  0,$35,$48,$FF,$FF, $D,  0,$4C,$2B,$FF,$FF,$2E,$25,  0,  9
		.BYTE	$39,$6C,$25,  4,$5C,$50,$2B,$FF
byte_90F3:
		.BYTE	$1C,$38,$46,$54,$70,$84,$92,$A0,$AE,$BC,$D8,$E3,$F1,  0,  0,$B6,  2
		.BYTE	$14,$28,$37,$46,$64,$78,$8C,$96,$A5,$AF,$D7,$E2,$F1,$40,$80,$B1,  1
		.BYTE	$12,$32,$3F,$44,$67,$71,$84,$9D,$B0,$BF,$DD,$E2,$F1,$40,$10,$B4,  2
		.BYTE	 $A,$14,$26,$30,$76,$76,$80,$8A,$9C,$A6,$EC,$F6,$FF,$40,  0,$93,  1
_b0_d40_weapon_power_list:
		.BYTE	$FF,$FD,$FD,$FF,$FD,$F1,$79, $A,  2,$40,$B9,$10,$FD,$11,$11,$10
		.BYTE	 $E,$11, $E,$11,$11, $E,$B0,$3D,$29,$10,$11, $A,  1,$19,$11, $C
		.BYTE	$FF,$C8,$3D,$80,$31,$11,$1D,$FF,  1,$20,$FF,$48, $C,$11,  2,$3D
		.BYTE	$BF,$FF,$FF,$3D,$11,$11,$11, $E,$BD,$31,$11,  1,$11,$3D,$1D,$BF
		.BYTE	$1D,$AE,$11,$A0,$FF,$BF,$11,  1,$FF,$FF,$40,$FF,$FF,$FF,$FF
_b0_d41_equip_list:
		.BYTE	$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$11,$11,$FF
		.BYTE	 $E,$FF, $E,$FF,$FF,$FF,$FF,$FF,$20,$FF,$11,$FF,  1,$19,$FF, $C
		.BYTE	  1,$FF,$FF,$40,$FF,  4, $E, $F
_b0_d42_effects_list:
		.BYTE	  0,   1,  2,   2,  1,   2,  2,$E2,  1,   1,  1,   2,  1,$E3,$E3,   2
		.BYTE	$F3,$14,$83, $B, $B,  2,$F0,  2,  3,  2,$A2,$E2,$F3,$E3,  3,$E2
		.BYTE	  1,  1,  1,  2,  2,  2,  2,  2,$10,  2,  1,  2,  2, $B,  2,  1
		.BYTE	  1,  3,$10,  2,$10,  2,$10,  3,  1,  2,$83,$10,  9,  1,  2,$10
		.BYTE	  2,  0,$18,  1,  8,  1,  2,$90,$90,$82,$83,$90,$14,  2,$82,$B0
		.BYTE	$90,$10,$13,$10,$10,$10,  6,$14,$10,$10,$10,$90,$14,$10,$13,$85
		.BYTE	$85,$85,$85,$85,$86,$C4,$C4,$E5,$84,$C4,$81,$14,$C5,  1,$10,$10
		.BYTE	$F0,$A1,$B0,$E6,$E4,$90,$14,$14,$14,$14,$14,$14,$14
_b0_d44:
		.BYTE	  5,  3,  1,  2,$4B,$19, $F, $F,  1,$4D,$20,$25,$37,$41, $F,  5
		.BYTE	  0,$80,  7,$2D,  5,$19,  0,$62,$19,$41,$4B,$19,$23,  1, $F,$1B
		.BYTE	  1,  8, $F, $D, $B,$18,$3A,$1D,  0,  7,$23,  8,$2C,  7,$7D,$30
		.BYTE	  7,$4E,  0,  3,  0,$62,  0,  3,  9,  7, $F,  0,  1,$12,$58,  0
		.BYTE	 $A,  8,  0,$10,  2,  8,$23,$80,$80,$81,$8F,$80,$80,  0,$99,$80
		.BYTE	  0,$80,$80,$80,$80,  0,$83,$80,$80,$80,$80,$80,$80,$80,$1E,$98
		.BYTE	$88,$8C,$86,$90,$82,$88,$8A,$82,$99,$85,$81,$80,$83,$82,$80,$80
		.BYTE	$80,$81,  0,  5,$23,  0,$80,$80,  0,  0,  0,  0,  0

; =============== S U B	R O U T	I N E =======================================
_b0_s2:
		LDA		byte_CE
		ASL
		TAX
		LDA		byte_71C,X
		STA		word_4
		LDA		byte_71D,X
		STA		word_4+1
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s3:
		LDA		byte_CE
		ASL
		TAX
		LDA		byte_724,X
		STA		word_4
		LDA		byte_725,X
		STA		word_4+1
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s4:
		LDA		byte_CE
		ASL
		TAX
		LDA		byte_71C,X
		CLC
		ADC		byte_CF
		STA		word_4
		LDA		byte_71D,X
		ADC		byte_D0
		BCS		loc_92ED
		STA		word_4+1
		LDA		byte_725,X
		CMP		word_4+1
		BEQ		loc_92E6
		BCS		loc_92F7
		BCC		loc_92ED
loc_92E6:
		LDA		byte_724,X
		CMP		word_4
		BCS		loc_92F7
loc_92ED:
		LDA		byte_724,X
		STA		word_4
		LDA		byte_725,X
		STA		word_4+1
loc_92F7:
		LDA		word_4
		STA		byte_71C,X
		LDA		word_4+1
		STA		byte_71D,X
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s5:
		LDA		byte_CE
		ASL
		TAX
		LDA		byte_71C,X
		SEC
		SBC		byte_CF
		STA		word_4
		LDA		byte_71D,X
		SBC		byte_D0
		STA		word_4+1
		BCS		loc_931D
		LDA		#0
		STA		word_4
		STA		word_4+1
loc_931D:
		LDA		word_4
		STA		byte_71C,X
		LDA		word_4+1
		STA		byte_71D,X
		LDA		word_4
		ORA		word_4+1
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s6:
		LDA		byte_CE
		ASL
		TAX
		LDA		byte_72C,X
		STA		word_4
		LDA		byte_72D,X
		STA		word_4+1
		ORA		word_4
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s7:
		LDA		byte_CE
		ASL
		TAX
		LDA		byte_734,X
		STA		word_4
		LDA		byte_735,X
		STA		word_4+1
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s8:
		LDA		byte_CE
		ASL
		TAX
		LDA		byte_72C,X
		CLC
		ADC		byte_CF
		STA		word_4
		LDA		byte_72D,X
		ADC		byte_D0
		BCS		loc_9373
		STA		word_4+1
		LDA		byte_735,X
		CMP		word_4+1
		BEQ		loc_936C
		BCS		loc_937D
		BCC		loc_9373
loc_936C:
		LDA		byte_734,X
		CMP		word_4
		BCS		loc_937D
loc_9373:
		LDA		byte_734,X
		STA		word_4
		LDA		byte_735,X
		STA		word_4+1
loc_937D:
		LDA		word_4
		STA		byte_72C,X
		LDA		word_4+1
		STA		byte_72D,X
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s9:
		LDA		byte_CE
		ASL
		TAX
		LDA		byte_72C,X
		SEC
		SBC		byte_CF
		STA		word_4
		LDA		byte_72D,X
		SBC		byte_D0
		STA		word_4+1
		BCS		loc_93A9
		LDA		byte_72C,X
		STA		word_4
		LDA		byte_72D,X
		STA		word_4+1
		CLC
		RTS
loc_93A9:
		LDA		word_4
		STA		byte_72C,X
		LDA		word_4+1
		STA		byte_72D,X
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
unused
_b0_sA:
		LDA		byte_CE
		ASL
		TAX
		LDA		#0
		STA		byte_72C,X
		STA		byte_72D,X
		STA		word_4
		STA		word_4+1
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_sB:
		JSR		_b0_s9
		BCC		locret_93CF
		JSR		_b0_s8
		SEC
locret_93CF:
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_sC_char_get_level:
		JSR		_b0_sE
		BIT		word_4+1
		BPL		loc_9403
		BVS		loc_9407
		LDA		byte_60B7
		AND		#$20
		BEQ		loc_93EF
		LDX		byte_CE
		LDA		byte_6A9B,X
		AND		#8
		BNE		loc_940F
		LDA		word_4+1
		AND		#$10
		BNE		loc_9413
loc_93EF:
		LDA		word_4+1
		AND		#$20
		BNE		loc_940B
loc_93F5:
		STA		word_4+1
		LDA		#0
		STA		word_6
		LDX		byte_CE
		LDA		byte_700,X
		STA		word_4
		RTS
loc_9403:
		LDA		#3
		BNE		loc_93F5
loc_9407:
		LDA		#2
		BNE		loc_93F5
loc_940B:
		LDA		#1
		BNE		loc_93F5
loc_940F:
		LDA		#4
		BNE		loc_93F5
loc_9413:
		LDA		#5
		BNE		loc_93F5

; =============== S U B	R O U T	I N E =======================================
_b0_sD:
		JSR		_b0_s32
		LDX		byte_CE
		CPX		word_4
		BEQ		loc_9422
		BCS		loc_9431
loc_9422:
		LDA		word_4+1,X
		TAX
		LDA		byte_60D6,X
		STA		word_4
		LDA		#0
		STA		word_4+1
		STA		word_6
		RTS
loc_9431:
		LDA		#$FF
		STA		_tmp12+1
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_sE:
		LDA		byte_CE
		ASL
		TAX
		LDA		byte_73C,X
		STA		word_4
		LDA		byte_73D,X
		STA		word_4+1
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_sF:
		LDA		byte_CE
		JSR		sub_9C21
		ASL
		ASL
		ASL
		TAY
		LDX		#0
loc_9450:
		LDA		byte_75C,Y
		STA		word_4,X
		INY
		INX
		CPX		#8
		BNE		loc_9450
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s10:
		JSR		_b0_s32
		LDX		byte_CE
		CPX		word_4
		BCS		loc_9479
		LDA		word_4+1,X
		ASL
		ASL
		ASL
		TAY
		LDX		#0
loc_946D:
		LDA		_character_names,Y
		STA		word_4,X
		INY
		INX
		CPX		#8
		BNE		loc_946D
		RTS
loc_9479:
		LDA		#$FF
		STA		word_4
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s11:
		LDX		byte_CE
		LDA		byte_704,X
		STA		word_4
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s12:
		LDA		#$4B
		STA		byte_CF
		JSR		_b0_s45
		CMP		#$CB
		BEQ		loc_9499
loc_9491:
		LDX		byte_CE
		LDA		byte_708,X
loc_9496:
		STA		word_4
locret_9498:
		RTS
loc_9499:
		JSR		loc_9491
		ASL		word_4
		BCC		locret_9498
		LDA		#$FF
		BNE		loc_9496

; =============== S U B	R O U T	I N E =======================================
_b0_s13:
		LDX		byte_CE
		LDA		byte_714,X
		STA		word_4
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s14:
		LDX		byte_CE
		LDA		byte_70C,X
		STA		word_4
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s15:
		JSR		_b0_s1E
		LDA		word_6+1
		CMP		#$C2
		BEQ		loc_94CB
		LDX		byte_CE
		LDA		byte_710,X
loc_94C2:
		STA		word_4
		LDA		#0
		STA		word_4+1
		STA		word_6
		RTS
loc_94CB:
		LDA		#0
		BEQ		loc_94C2

; =============== S U B	R O U T	I N E =======================================
_b0_s16:
		JSR		_b0_s2C
		PHA
		JSR		_b0_s1E
		PLA
		STA		word_6+1
		LDA		word_4
		BPL		loc_94E1
		CMP		#$FF
		BNE		loc_94EB
loc_94E1:
		JSR		_b0_s11
		LDA		#0
		STA		word_4+1
		STA		word_6
		RTS
loc_94EB:
		AND		#$7F
		TAY
		JSR		_b0_s11
		LDA		#0
		STA		word_4+1
		LDX		word_6+1
		CPX		#word_6
		BEQ		loc_9508
		LDX		#word_4
loc_94FD:
		JSR		sub_174D3F
loc_9500:
		JSR		_add8_to_16
loc_9503:
		LDA		#0
		STA		word_6
		RTS
loc_9508:
		LDX		#word_4
		CPY		#9
		BEQ		loc_94FD
		CPY		#$4A
		BNE		loc_9516
		LDA		#$37
		BNE		loc_9500
loc_9516:
		JSR		sub_174D3F
		LSR
		JSR		_add8_to_neg16
		BCS		loc_9503
		LDA		#0
		STA		word_4
		STA		word_4+1
		BEQ		loc_9503

; =============== S U B	R O U T	I N E =======================================
_b0_s17:
		TXA
		PHA
		LDA		byte_CE
		TAX
		LDA		byte_6A9B,X
		AND		#3
		ASL
		TAX
		LDA		byte_6AAB,X
		STA		word_4
		LDA		byte_6AAC,X
		STA		word_4+1
		PLA
		TAX
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s18:
		JSR		_b0_s1E
		LDA		word_4+1
		PHA
		JSR		_b0_s12
		LSR		word_4
		LDA		#0
		STA		word_4+1
		PLA
		CMP		#$FF
		BEQ		loc_955F
		AND		#$7F
		TAY
		LDX		#word_4
		JSR		sub_174D3F
		JSR		_add8_to_16
loc_955F:
		LDA		word_6
		CMP		#$FF
		BEQ		loc_9570
		AND		#$7F
		TAY
		LDX		#word_4
		JSR		sub_174D3F
		JSR		_add8_to_16
loc_9570:
		LDA		word_6+1
		CMP		#$FF
		BEQ		loc_9581
		AND		#$7F
		TAY
		LDX		#word_4
		JSR		sub_174D3F
		JSR		_add8_to_16
loc_9581:
		LDA		#0
		STA		word_6
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s19:
		LDX		byte_CE
		JSR		sub_9C55
		LDY		#0
loc_958D:
		LDA		byte_744,X
		STA		word_4,Y
		INX
		INY
		CPY		#3
		BNE		loc_958D
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s1A:
		JSR		_b0_sE
		LDA		word_4
		AND		word_4+1
		BPL		locret_95EC
		JSR		_b0_s19
		CLC
		LDA		word_4
		ADC		byte_CF
		STA		word_4
		LDA		word_4+1
		ADC		byte_D0
		STA		word_4+1
		LDA		word_6
		ADC		byte_D1
		STA		word_6
		CMP		#$98
		BCC		loc_95D9
		BNE		loc_95CD
		LDA		word_4+1
		CMP		#$96
		BCC		loc_95D9
		BNE		loc_95CD
		LDA		word_4
		CMP		#$7F
		BCC		loc_95D9
loc_95CD:
		LDA		#$98
		STA		word_6
		LDA		#$96
		STA		word_4+1
		LDA		#$7F
		STA		word_4
loc_95D9:
		LDX		byte_CE
		JSR		sub_9C55
		LDY		#0
loc_95E0:
		LDA		word_4,Y
		STA		byte_744,X
		INX
		INY
		CPY		#3
		BNE		loc_95E0
locret_95EC:
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s1B:
		LDA		byte_7BC
		STA		word_4
		LDA		byte_7BD
		STA		word_4+1
		LDA		byte_7BE
		STA		word_6
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s1C:
		LDA		byte_7BC
		CLC
		ADC		byte_CE
		STA		word_4
		LDA		byte_7BD
		ADC		byte_CF
		STA		word_4+1
		LDA		byte_7BE
		ADC		byte_D0
		STA		word_6
		LDA		word_6
		BEQ		loc_9631
		LDA		word_4+1
		CMP		#$86
		BCC		loc_9631
		BNE		loc_9625
		LDA		word_4
		CMP		#$9F
		BCC		loc_9631
loc_9625:
		LDA		#$9F
		STA		word_4
		LDA		#$86
		STA		word_4+1
		LDA		#1
		STA		word_6
loc_9631:
		LDY		#2
loc_9633:
		LDA		word_4,Y
		STA		byte_7BC,Y
		DEY
		BPL		loc_9633
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s1D:
		LDA		byte_7BC
		SEC
		SBC		byte_CE
		STA		word_4
		LDA		byte_7BD
		SBC		byte_CF
		STA		word_4+1
		LDA		byte_7BE
		SBC		byte_D0
		BCC		loc_9663
		STA		word_6
		STA		byte_7BE
		LDA		word_4
		STA		byte_7BC
		LDA		word_4+1
		STA		byte_7BD
		RTS
loc_9663:
		LDA		#$FF
		STA		_tmp12+1
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s1E:
		LDA		byte_CE
		ASL
		ASL
		ASL
		TAX
		LDA		#0
		STA		_tmp12+1
loc_9672:
		LDY		#8
		TXA
		PHA
loc_9676:
		LDA		byte_77C,X
		BPL		loc_9688
		CMP		#$FF
		BEQ		loc_9688
		AND		#$7F
		JSR		_b0_s60
		CMP		_tmp12+1
		BEQ		loc_9690
loc_9688:
		INX
		DEY
		BNE		loc_9676
		LDA		#$FF
		BNE		loc_9693
loc_9690:
		LDA		byte_77C,X
loc_9693:
		LDY		_tmp12+1
		STA		word_4,Y
		PLA
		TAX
		INY
		STY		_tmp12+1
		CPY		#4
		BNE		loc_9672
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s1F:
		LDA		#0
		STA		byte_42
		BEQ		sub_96B8

; =============== S U B	R O U T	I N E =======================================
_b0_s21:
		LDA		#1
		STA		byte_42
		BNE		sub_96B8

; =============== S U B	R O U T	I N E =======================================
_b0_s20:
		LDA		#2
		STA		byte_42
		BNE		sub_96B8

; =============== S U B	R O U T	I N E =======================================
_b0_s22:
		LDA		#3
		STA		byte_42

; =============== S U B	R O U T	I N E =======================================
sub_96B8:
		LDA		byte_CE
		ASL
		ASL
		ASL
		TAX
		LDY		#0
		LDA		#8
		STA		_tmp12
loc_96C4:
		LDA		byte_77C,X
		CMP		#$FF
		BEQ		loc_96DB
		AND		#$7F
		JSR		_b0_s60
		CMP		byte_42
		BNE		loc_96DB
		LDA		byte_77C,X
		STA		word_4+1,Y
		INY
loc_96DB:
		INX
		DEC		_tmp12
		BNE		loc_96C4
		STY		word_4
		CPY		byte_CF
		BEQ		loc_96EF
		BCC		loc_96EF
		LDX		byte_CF
		LDA		word_4+1,X
		STA		word_4+1
		RTS
loc_96EF:
		LDA		#$FF
		STA		word_4+1
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s23:
		LDA		#0
		STA		byte_42
		JMP		_b0_s27

; =============== S U B	R O U T	I N E =======================================
_b0_s25:
		LDA		#1
		STA		byte_42
		JMP		_b0_s27

; =============== S U B	R O U T	I N E =======================================
_b0_s24:
		LDA		#2
		STA		byte_42
		JMP		_b0_s27

; =============== S U B	R O U T	I N E =======================================
_b0_s26:
		LDA		#3
		STA		byte_42

; =============== S U B	R O U T	I N E =======================================
_b0_s27:
		JSR		_b0_s63
		LDA		byte_CE
		ASL
		ASL
		ASL
		TAX
		LDY		byte_CF
		INY
		LDA		#9
		STA		_tmp12+1
loc_971D:
		DEC		_tmp12+1
		BEQ		loc_9740
		LDA		byte_77C,X
		CMP		#$FF
		BEQ		loc_9736
		AND		#$7F
		JSR		_b0_s60
		INX
		CMP		byte_42
		BNE		loc_971D
		DEY
		BNE		loc_971D
		DEX
loc_9736:
		LDA		byte_77C,X
		ORA		#$80
		STA		byte_77C,X
		INX
		RTS
loc_9740:
		JMP		_b0_s63

; =============== S U B	R O U T	I N E =======================================
_b0_s63:
		LDA		byte_CE
		ASL
		ASL
		ASL
		TAX
		LDA		#9
		STA		_tmp12+1
loc_974D:
		DEC		_tmp12+1
		BEQ		locret_976F
		LDA		byte_77C,X
		CMP		#$FF
		BEQ		locret_976F
		AND		#$7F
		JSR		_b0_s60
		INX
		CMP		byte_42
		BNE		loc_974D
		DEX
		LDA		byte_77C,X
		AND		#$7F
		STA		byte_77C,X
		INX
		JMP		loc_974D
locret_976F:
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s5E:
		LDX		byte_CF
		LDA		_b0_d40_weapon_power_list,X
		STA		word_4+1
		LDA		byte_CF
		CMP		#$4C
		BCS		loc_978E
loc_977D:
		JSR		_b0_s2C
		LDA		#0
		LDX		word_4
		INX
		SEC
loc_9786:
		ROL
		DEX
		BNE		loc_9786
		AND		word_4+1
		BNE		loc_9790
loc_978E:
		CLC
		RTS
loc_9790:
		JSR		_b0_s2F
		BNE		loc_97A3
		LDA		byte_CF
		CMP		#$16
		BEQ		loc_978E
		CMP		#$31
		BEQ		loc_978E
		CMP		#$32
		BEQ		loc_978E
loc_97A3:
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s5F:
		LDX		byte_CF
		CPX		#$4F
		BCS		loc_97A3
		CPX		#$20
		BCC		loc_97B7
		CPX		#$47
		BCC		loc_97A3
		TXA
		SBC		#$27
		TAX
loc_97B7:
		LDA		_b0_d41_equip_list,X
		STA		word_4+1
		JMP		loc_977D

; =============== S U B	R O U T	I N E =======================================
_b0_s28:
		JSR		sub_97C9
		LDX		byte_CF
		LDA		word_4+1,X
		STA		word_4+1
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_97C9:
		LDA		byte_CE
		ASL
		ASL
		ASL
		TAX
		LDY		#8
		STY		_tmp12
		LDA		#$FF
loc_97D5:
		STA		word_4,Y
		DEY
		BNE		loc_97D5
		STY		word_4
loc_97DD:
		LDA		byte_77C,X
		CMP		#$FF
		BEQ		loc_97EA
		INC		word_4
		STA		word_4+1,Y
		INY
loc_97EA:
		INX
		DEC		_tmp12
		BNE		loc_97DD
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s29:
		JSR		sub_97C9
		LDA		word_4
		CMP		#8
		BCS		loc_9803
		LDA		byte_CF
		LDY		word_4
		STA		word_4+1,Y
		JMP		sub_9813
loc_9803:
		LDA		#$FF
		STA		word_4
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s2A:
		JSR		sub_97C9
		LDY		byte_CF
		LDA		#$FF
		STA		word_4+1,Y

; =============== S U B	R O U T	I N E =======================================
sub_9813:
		LDA		byte_CE
		ASL
		ASL
		ASL
		TAX
		PHA
		LDY		#7
		LDA		#$FF
loc_981E:
		STA		byte_77C,X
		INX
		DEY
		BPL		loc_981E
		PLA
		TAX
		INY
loc_9828:
		LDA		word_4+1,Y
		CMP		#$FF
		BEQ		loc_9833
		STA		byte_77C,X
		INX
loc_9833:
		INY
		CPY		#8
		BNE		loc_9828
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s2B:
		JSR		_b0_s31
		ASL		word_4
		ASL		word_4
		ASL		word_4
		LDX		#0
loc_9845:
		LDA		byte_77C,X
		AND		#$7F
		CMP		byte_CE
		BNE		loc_985B
		TXA
		AND		#7
		STA		word_4+1
		TXA
		LSR
		LSR
		LSR
		STA		word_4
		SEC
		RTS
loc_985B:
		INX
		CPX		word_4
		BNE		loc_9845
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s45:
		LDA		#$FF
		STA		word_4
		LDA		byte_CE
		ASL
		ASL
		ASL
		TAX
		LDY		#8
loc_986E:
		LDA		byte_77C,X
		AND		#$7F
		CMP		byte_CF
		BEQ		loc_987C
loc_9877:
		INX
		DEY
		BNE		loc_986E
		RTS
loc_987C:
		LDA		byte_77C,X
		STA		word_4
		BPL		loc_9877
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s3C:
		JSR		_b0_s31
		ASL		word_4
		ASL		word_4
		ASL		word_4
		LDX		#0
loc_988F:
		LDA		byte_77C,X
		CMP		#$FF
		BEQ		loc_98A0
		INX
		CPX		word_4
		BNE		loc_988F
		FARX	_bD_s26
		CLC
		RTS
loc_98A0:
		TXA
		LSR
		LSR
		LSR
		STA		word_4
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s5C:
		LDA		byte_CE
		ASL
		ASL
		ASL
		TAX
		LDY		#0
loc_98B0:
		TYA
		PHA
		LDA		byte_77C,X
		BPL		loc_98C5
		CMP		#$FF
		BEQ		loc_98C5
		AND		#$7F
		TAY
		LDA		_b0_d42_effects_list,Y
		AND		#8
		BNE		loc_98CF
loc_98C5:
		PLA
		TAY
		INX
		INY
		CPY		#8
		BNE		loc_98B0
		CLC
		RTS
loc_98CF:
		PLA
		STA		word_4
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_98D4:
		LDX		#$C
		LDA		#$FF
loc_98D8:
		STA		word_4,X
		DEX
		BNE		loc_98D8
		LDA		#8
		STA		_tmp12+1
		LDX		#0
		LDY		#0
		LDA		byte_7BF
		JSR		loc_98F2
		LDA		#4
		STA		_tmp12+1
		LDA		byte_7C0
loc_98F2:
		LSR
		BCC		loc_98F8
		STY		word_4+1,X
		INX
loc_98F8:
		INY
		DEC		_tmp12+1
		BNE		loc_98F2
		STX		word_4
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s32:
		JSR		sub_98D4
		LDX		#0
loc_9905:
		LDY		#0
loc_9907:
		LDA		word_4+1,X
		CMP		byte_7C1,Y
		BNE		loc_9914
		LDA		#$FF
		STA		word_4+1,X
		BNE		loc_9919
loc_9914:
		INY
		CPY		#4
		BNE		loc_9907
loc_9919:
		INX
		CPX		word_4
		BNE		loc_9905
		LDX		#0
		LDY		#0
loc_9922:
		LDA		word_4+1,X
		CMP		#$FF
		BEQ		loc_9932
		PHA
		LDA		#$FF
		STA		word_4+1,X
		PLA
		STA		word_4+1,Y
		INY
loc_9932:
		INX
		CPX		word_4
		BNE		loc_9922
		STY		word_4
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s2C:
		LDX		byte_CE
		LDA		byte_718,X
		AND		#7
		STA		word_4
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s2D:
		JMP		_b0_s2C

; =============== S U B	R O U T	I N E =======================================
_b0_s2E:
		JSR		_b0_s32
		LDX		byte_CE
		LDA		word_4+1,X
		TAX
		LDA		byte_611E,X
		AND		#7
		STA		word_4
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s2F:
		LDX		byte_CE
		LDA		byte_718,X

; =============== S U B	R O U T	I N E =======================================
sub_995C:
		LSR
		LSR
		LSR
		AND		#1
		STA		word_4
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s30:
		JSR		_b0_s32
		LDX		byte_CE
		CPX		word_4
		LDA		word_4+1,X
		TAX
		LDA		byte_611E,X
		JMP		sub_995C

; =============== S U B	R O U T	I N E =======================================
_b0_s31:
		LDY		#0
		LDX		#0
loc_997A:
		LDA		byte_7C1,Y
		STA		word_4+1,X
		BMI		loc_9982
		INX
loc_9982:
		INY
		CPY		#4
		BNE		loc_997A
		STX		word_4
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s33:
		TXA
		PHA
		TYA
		PHA
		LDX		#0
		STX		word_4
loc_9992:
		LDA		byte_7C1,X
		BMI		loc_99A1
		TXA
		ASL
		TAY
		LDA		byte_73D,Y
		BPL		loc_99A1
		INC		word_4
loc_99A1:
		INX
		CPX		#4
		BNE		loc_9992
		PLA
		TAY
		PLA
		TAX
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_99AB:
		LDY		byte_E
		CPY		#8
		BCS		loc_99C0
		INY
loc_99B2:
		ROR		byte_F
		DEY
		BNE		loc_99B2
		BCC		loc_99C0
		LDY		byte_E
		LDA		(byte_10),Y
		STA		word_4
		RTS
loc_99C0:
		LDA		#$FF
		STA		word_4
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s34:
		LDA		byte_CF
		STA		byte_42
		JSR		sub_99CF
		JMP		sub_99AB

; =============== S U B	R O U T	I N E =======================================
sub_99CF:
		JSR		_b0_s2C
		LDA		word_4
		BEQ		loc_9A3D
		CMP		#7
		BEQ		loc_9A36
		STA		_tmp12+1
		LDA		byte_D0
		AND		#3
		BNE		loc_99F0
		LDA		_tmp12+1
		CMP		#4
		BCS		loc_9A36
		CMP		#3
		BEQ		loc_99F0
		LDY		byte_D0
		BEQ		loc_99F2
loc_99F0:
		LDA		byte_D0
loc_99F2:
		AND		#3
		SEC
		SBC		#1
		STA		word_4
		ASL
		ASL
		STA		_tmp12+1
		LDA		byte_CE
		ASL
		ASL
		ASL
		CLC
		ADC		_tmp12+1
		STA		_tmp12+1
		LDA		byte_42
		PHA
		AND		#7
		STA		byte_E
		PLA
		LSR
		LSR
		LSR
		CLC
		ADC		_tmp12+1
		TAY
		LDA		byte_79C,Y
		STA		byte_F
		LDA		byte_42
		AND		#$18
		LSR
		LSR
		ASL		word_4
		ASL		word_4
		ASL		word_4
		CLC
		ADC		word_4
		TAX
		LDA		off_9C9B,X
		STA		byte_10
		LDA		off_9C9B+1,X
		STA		byte_11
		RTS
loc_9A36:
		LDA		#0
		STA		byte_F
		STA		byte_E
		RTS
loc_9A3D:
		LDA		byte_D0
		CMP		#2
		BNE		loc_9A4A
		LDA		#0
		STA		byte_F
		STA		byte_E
		RTS
loc_9A4A:
		LDA		byte_CE
		ASL
		ASL
		ASL
		STA		_tmp12+1
		LDA		byte_42
		PHA
		AND		#7
		STA		byte_E
		PLA
		LSR
		LSR
		LSR
		CLC
		ADC		_tmp12+1
		TAY
		LDA		byte_79C,Y
		STA		byte_F
		LDA		byte_42
		AND		#$18
		LSR
		LSR
		TAX
		LDA		off_9C93,X
		STA		byte_10
		LDA		off_9C93+1,X
		STA		byte_11
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s35:
		LDA		byte_CF
		ORA		#$18
		STA		byte_42
		JSR		sub_99CF
		JMP		sub_99AB

; =============== S U B	R O U T	I N E =======================================
_b0_s36:
		LDA		byte_CF
		STA		byte_42
		JSR		sub_99CF
		JMP		sub_99AB

; =============== S U B	R O U T	I N E =======================================
_b0_s37:
		LDA		#8
		JSR		sub_9AFA
		JSR		sub_99CF
		JMP		sub_99AB

; =============== S U B	R O U T	I N E =======================================
_b0_s38:
		LDA		#$10
		JSR		sub_9AFA
		JSR		sub_99CF
		JMP		sub_99AB

; =============== S U B	R O U T	I N E =======================================
_b0_s39:
		LDX		#0
		LDA		#0
		STA		byte_42
loc_9AA9:
		TXA
		PHA
		JSR		sub_99CF
		JSR		sub_9AD7
		PLA
		TAX
		STY		word_4+1,X
		CLC
		LDA		#8
		ADC		byte_42
		STA		byte_42
		INX
		CPX		#4
		BNE		loc_9AA9
		LDX		#0
loc_9AC3:
		LDA		word_4+1,X
		STA		word_4,X
		INX
		CPX		#4
		BNE		loc_9AC3
		LDA		word_4
		ORA		word_4+1
		ORA		word_6
		ORA		word_6+1
		STA		byte_8
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_9AD7:
		LDX		#8
		LDY		#0
loc_9ADB:
		ROR		byte_F
		BCC		loc_9AE0
		INY
loc_9AE0:
		DEX
		BNE		loc_9ADB
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s62:
		LDA		#$18
		STA		byte_42
		JSR		sub_99CF
		LDA		byte_F
		LDX		#0
loc_9AEF:
		CMP		#0
		BEQ		loc_9AF7
		LSR
		INX
		BNE		loc_9AEF
loc_9AF7:
		STX		word_6+1
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_9AFA:
		ORA		byte_CF
		STA		byte_42
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s3A:
		LDA		#7
loc_9B01:
		STA		byte_B
		LDA		#0
		STA		_tmp12+1
loc_9B07:
		ASL
		TAX
		LDA		#4
		CPX		#$12
		BNE		loc_9B11
		LDA		#$C
loc_9B11:
		STA		byte_A
		LDA		off_9B85,X
		STA		word_3C
		LDA		off_9B85+1,X
		STA		word_3C+1
		LDX		_tmp12+1
		LDA		byte_9B99,X
		LDY		byte_9BA3,X
		JSR		sub_9B31
		INC		_tmp12+1
		LDA		_tmp12+1
		CMP		byte_B
		BNE		loc_9B07
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_9B31:
		STA		word_4
		STY		byte_9
loc_9B35:
		LDA		word_4
		STA		byte_8
		LDA		byte_D0
		JSR		sub_9B78
		LDA		word_4+1
		STA		word_6+1
		LDA		byte_CF
		JSR		sub_9B78
loc_9B47:
		LDY		word_4+1
		LDA		(word_3C),Y
		PHA
		LDY		word_6+1
		LDA		(word_3C),Y
		LDY		word_4+1
		STA		(word_3C),Y
		PLA
		LDY		word_6+1
		STA		(word_3C),Y
		INC		word_4+1
		INC		word_6+1
		DEC		byte_8
		BNE		loc_9B47
		LDA		word_4
		STA		word_4+1
		LDA		byte_A
		LDX		#word_4+1
		JSR		_mul16_to_8
		LDX		#word_3C
		LDA		word_4+1
		JSR		_add8_to_16
		DEC		byte_9
		BNE		loc_9B35
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_9B78:
		STA		word_4+1
		LDA		#0
		STA		word_6
		LDX		#word_4+1
		LDA		word_4
		JMP		_mul16_to_8

off_9B85:
		.WORD	byte_700
		.WORD	byte_71C
		.WORD	byte_744
		.WORD	byte_75C
		.WORD	byte_6A4B
		.WORD	byte_7C1
		.WORD	byte_B0
		.WORD	byte_6A9B
		.WORD	byte_6AA3
		.WORD	byte_540
byte_9B99:
		.BYTE	  1,  2,  3,  8,  1,  1,  1,  1,  2,  1
byte_9BA3:
		.BYTE	  7,  5,  2,  3,  1,  1,  1,  2,  2,  3

; =============== S U B	R O U T	I N E =======================================
_b0_s3B:
		LDA		#$A
		JSR		loc_9B01
		LDX		#0
loc_9BB4:
		STX		byte_B
		LDA		byte_540,X
		AND		#$FC
		ORA		byte_B
		STA		byte_540,X
		INX
		CPX		#4
		BNE		loc_9BB4
		LDX		#0
loc_9BC7:
		STX		word_4
		LDA		byte_6A9B,X
		AND		#$10
		BEQ		loc_9BDA
		LDA		byte_6A9B,X
		STA		word_4+1
		JSR		sub_9C09
		BCC		loc_9BE4
loc_9BDA:
		LDA		byte_6A9B,X
		AND		#$FC
		ORA		word_4
		STA		byte_6A9B,X
loc_9BE4:
		INX
		CPX		#4
		BNE		loc_9BC7
		LDX		#0
loc_9BEB:
		STX		word_4
		LDA		byte_54C,X
		BMI		loc_9C03
		STA		word_4+1
		JSR		sub_9C09
		BCC		loc_9C03
		LDA		byte_54C,X
		AND		#$F8
		ORA		word_4
		STA		byte_54C,X
loc_9C03:
		INX
		CPX		#$C
		BNE		loc_9BEB
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_9C09:
		LDA		word_4+1
		AND		#3
		CMP		byte_CF
		BEQ		loc_9C19
		CMP		byte_D0
		BNE		loc_9C1F
		LDA		byte_CF
		BPL		loc_9C1B
loc_9C19:
		LDA		byte_D0
loc_9C1B:
		STA		word_4
		SEC
		RTS
loc_9C1F:
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_9C21:
		STA		word_4
		LDY		#$FF
		LDX		#0
loc_9C27:
		LDA		byte_7C1,X
		BPL		loc_9C34
loc_9C2C:
		INX
		CPX		#4
		BNE		loc_9C27
		LDA		#0
		RTS
loc_9C34:
		INY
		CPY		word_4
		BNE		loc_9C2C
		TXA
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s3D:
		LDA		byte_CE
		ASL
		TAX
		LDA		byte_73D,X
		AND		#$DF
		STA		byte_73D,X
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s3E:
		LDA		byte_CE
		ASL
		TAX
		LDA		byte_73D,X
		ORA		#$80
		STA		byte_73D,X
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_9C55:
		PHA
		TXA
		STA		_tmp12+1
		ASL
		CLC
		ADC		_tmp12+1
		TAX
		PLA
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s60:
		CMP		#$4A
		BEQ		loc_9C6C
		CMP		#0
		BCC		loc_9C6F
		CMP		#$20
		BCS		loc_9C6F
loc_9C6C:
		LDA		#0
		RTS
loc_9C6F:
		CMP		#$20
		BCC		loc_9C7A
		CMP		#$38
		BCS		loc_9C7A
		LDA		#1
		RTS
loc_9C7A:
		CMP		#$38
		BCC		loc_9C85
		CMP		#$3F
		BCS		loc_9C85
		LDA		#2
		RTS
loc_9C85:
		CMP		#$3F
		BCC		loc_9C90
		CMP		#$47
		BCS		loc_9C90
		LDA		#3
		RTS
loc_9C90:
		LDA		#5
		RTS
off_9C93:
		.WORD	_b0_d58
		.WORD	byte_A2DF
		.WORD	byte_A2E7
		.WORD	byte_A2EF
off_9C9B:
		.WORD	_b0_d59
		.WORD	byte_A2FF
		.WORD	byte_A307
		.WORD	byte_A30F
		.WORD	_b0_d5A
		.WORD	byte_A31F
		.WORD	byte_A327
		.WORD	byte_A32F
		.WORD	byte_AA05
		.WORD	byte_AA44
		.WORD	byte_AA83
		.WORD	byte_A9C6

; =============== S U B	R O U T	I N E =======================================
_b0_s48:
		JSR		sub_9E55
		LDA		byte_750,X
		STA		word_6
		LDA		byte_751,X
		STA		word_6+1
		LDA		byte_752,X
		STA		byte_8
		LDA		#0
		STA		word_4
		LDY		byte_CF
		INY
		TAX
loc_9CCD:
		LSR		byte_8
		ROR		word_6+1
		ROR		word_6
		BCC		loc_9CDA
		INC		word_4
		DEY
		BEQ		loc_9CE0
loc_9CDA:
		INX
		CPX		#$14
		BNE		loc_9CCD
		RTS
loc_9CE0:
		TXA
loc_9CE1:
		CPX		#$13
		BEQ		loc_9CF2
		LSR		byte_8
		ROR		word_6+1
		ROR		word_6
		BCC		loc_9CEF
		INC		word_4
loc_9CEF:
		INX
		BNE		loc_9CE1
loc_9CF2:
		STA		word_4+1
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s49:
		LDX		#0
loc_9CF7:
		LDA		byte_9E5C,X
		CMP		byte_8B
		BEQ		loc_9D05
		INX
		CPX		#$14
		BNE		loc_9CF7
		RTS
loc_9D05:
		LDA		#0
		STA		word_4
		STA		word_4+1
		STA		word_6
		INX
		SEC
loc_9D0F:
		ROL		word_4
		ROL		word_4+1
		ROL		word_6
		DEX
		BNE		loc_9D0F
		LDX		#0
loc_9D1A:
		TXA
		ASL
		TAY
		LDA		byte_73C,Y
		AND		byte_73D,Y
		BPL		loc_9D44
		TXA
		STA		word_6+1
		ASL
		ADC		word_6+1
		TAY
		LDA		byte_750,Y
		ORA		word_4
		STA		byte_750,Y
		LDA		byte_751,Y
		ORA		word_4+1
		STA		byte_751,Y
		LDA		byte_752,Y
		ORA		word_6
		STA		byte_752,Y
loc_9D44:
		INX
		CPX		#4
		BNE		loc_9D1A
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s4D:
		JSR		_b0_s2B
		BCS		loc_9D80
		LDA		byte_CE
		FARX	_bD_s17
		BCC		loc_9D80
		JSR		_b0_s32
		LDA		word_4
		BEQ		loc_9D7E
		LDX		#0
loc_9D5F:
		LDA		word_4+1,X
		ASL
		ASL
		ASL
		TAY
		LDA		#8
		STA		_tmp12+1
loc_9D69:
		LDA		byte_624A,Y
		CMP		#$FF
		BEQ		loc_9D74
		CMP		byte_CE
		BEQ		loc_9D80
loc_9D74:
		INY
		DEC		_tmp12+1
		BNE		loc_9D69
		INX
		DEC		word_4
		BNE		loc_9D5F
loc_9D7E:
		CLC
		RTS
loc_9D80:
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s56:
		LDX		#3
loc_9D84:
		TXA
		ASL
		TAY
		LDA		byte_73C,Y
		AND		byte_73D,Y
		BPL		loc_9D98
		LDA		byte_718,X
		STX		word_4
		AND		#7
		BEQ		loc_9D9E
loc_9D98:
		DEX
		BPL		loc_9D84

; =============== S U B	R O U T	I N E =======================================
_b0_s4E:
		FARX	_bD_s26
loc_9D9E:
		LDA		word_4
		STA		byte_6A6C
		JSR		loc_9DF8
		JSR		_b0_s31
		LDA		word_4
		STA		byte_6A62
		LDX		#0
loc_9DB0:
		LDA		byte_7C2,X
		STA		byte_6A59,X
		LDA		#$FF
		STA		byte_7C2,X
		TXA
		ASL
		TAY
		LDA		byte_73E,Y
		STA		byte_6A5C,Y
		LDA		byte_73F,Y
		STA		byte_6A5D,Y
		LDA		#0
		STA		byte_73E,Y
		STA		byte_73F,Y
		INX
		CPX		#3
		BNE		loc_9DB0
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s4F:
		LDX		#0
loc_9DDA:
		TXA
		LDA		byte_6A59,X
		STA		byte_7C2,X
		TXA
		ASL
		TAY
		LDA		byte_6A5C,Y
		STA		byte_73E,Y
		LDA		byte_6A5D,Y
		STA		byte_73F,Y
		INX
		CPX		#3
		BNE		loc_9DDA
		JMP		loc_9DF8
loc_9DF8:
		LDA		#0
		STA		byte_CF
		LDA		byte_6A6C
		AND		#3
		BEQ		locret_9E08
		STA		byte_D0
		JSR		_b0_s3A
locret_9E08:
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s50:
		LDA		#0
		STA		byte_CE
loc_9E0D:
		LDA		byte_CE
		ASL
		TAX
		LDA		byte_73C,X
		BPL		loc_9E42
		LDX		byte_CE
		LDY		#0
		STY		byte_B0,X
loc_9E1C:
		TYA
		PHA
		LDA		byte_9E4B,Y
		STA		byte_CF
		TYA
		PHA
		JSR		_b0_s45
		PLA
		TAY
		LDA		byte_CF
		ORA		#$80
		CMP		word_4
		BNE		loc_9E3B
		LDX		byte_CE
		LDA		byte_9E50,Y
		ORA		byte_B0,X
		STA		byte_B0,X
loc_9E3B:
		PLA
		TAY
		INY
		CPY		#5
		BNE		loc_9E1C
loc_9E42:
		INC		byte_CE
		LDA		byte_CE
		CMP		#4
		BCC		loc_9E0D
		RTS
byte_9E4B:
		.BYTE	$2C,$2E,$28,$48,$49
byte_9E50:
		.BYTE	  1,  1,  3,  2,  4

; =============== S U B	R O U T	I N E =======================================
sub_9E55:
		LDA		byte_CE
		ASL
		ADC		byte_CE
		TAX
		RTS
byte_9E5C:
		.BYTE	  0,  9,  1,$14, $B, $C,$50, $A, $E,$33, $F,$17,  2,  6,$19,  7
		.BYTE	$12,$10,$1A,$11

; =============== S U B	R O U T	I N E =======================================
_b0_s5B:
		BIT		byte_60B7
		BVC		sub_9E9C
		SYSX	_sys0D_wrapper_to_bE_sC,$3E
		SYSX	_sys07_msg_m00_arg1,$64
		JMP		sub_9E8B

; =============== S U B	R O U T	I N E =======================================
; unreferenced code
;sub_9E7E:
;		LDA		#$3E
;		JSR		sub_A120
;		BRK
;		.BYTE	  5, 7		; _bE_s5
;		LDA		byte_42
;		JSR		sub_A100

; =============== S U B	R O U T	I N E =======================================
sub_9E8B:
		JSR		_calc_pads
		LDA		_pads
		BEQ		sub_9E8B

; =============== S U B	R O U T	I N E =======================================
sub_9E92:
		LDA		#0
		FARX	_bE_sB

; =============== S U B	R O U T	I N E =======================================
sub_9E97:
		LDA		#0
		STA		byte_8E
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_9E9C:
		LDA		#$29
		JSR		sub_A120
		CMP		#$FF
		BEQ		sub_9E92
		STA		byte_53
		STA		byte_CE
		JSR		sub_A189
		BCS		loc_9EB3
		LDA		#$C5
		JMP		sub_A13A
loc_9EB3:
		JSR		_b0_sE
		LDA		word_4+1
		AND		#$40
		BEQ		loc_9EC1
		LDA		#$D2
		JMP		sub_A13A
loc_9EC1:
		LDA		#$44
		STA		byte_CF
		JSR		_b0_s45
		LDA		word_4
		CMP		#$C4
		BNE		loc_9ED3
		LDA		#$C6
		JMP		sub_A13A
loc_9ED3:
		JSR		_b0_s2C
		CMP		#7
		BEQ		loc_9EEE
		LDA		#2
		STA		byte_D0
		JSR		_b0_s39
		LDA		word_6+1
		BNE		loc_9EF3
		DEC		byte_D0
		JSR		_b0_s39
		LDA		word_6+1
		BNE		loc_9EF3
loc_9EEE:
		LDA		#$C4
		JMP		sub_A13A
loc_9EF3:
		LDA		byte_D0
		FARX	_b1_s17
		CMP		#$FF
		BEQ		sub_9E8B
		STA		byte_49
		TAX
		LDA		#[_b4_dD_spells_list_idx-_sys_idx_lib]>>1
		JSR		_sys0_byte_read_x
		AND		#$3F
		JSR		_b0_s67
		JSR		_b0_sB
		BCS		loc_9F13
		LDA		#$20
		JMP		sub_A13A
loc_9F13:
		LDX		byte_49
		STX		byte_D3
		CPX		#$26
		BEQ		loc_9F2A
		LDA		#[_b4_dD_spells_list_idx-_sys_idx_lib]>>1
		JSR		_sys0_byte_read_x
		BPL		loc_9F34
		LDA		#$2B
		JSR		sub_A120
		JMP		loc_9F2D
loc_9F2A:
		FARX	_b1_s15
loc_9F2D:
		CMP		#$FF
		BNE		loc_9F34
		JMP		sub_9E8B
loc_9F34:
		STA		byte_50
		STA		word_4
		LDA		byte_53
		STA		byte_D2
		STA		byte_CE
		LDX		byte_49
		LDA		#[_b4_dD_spells_list_idx-_sys_idx_lib]>>1
		JSR		_sys0_byte_read_x
		AND		#$3F
		JSR		_b0_s67
		JSR		_b0_s9
		JSR		sub_A169
		LDA		#2
		JSR		_wrap_bE_s4_msg_m00_arg0_safe
		LDA		#$8E
		FARX	_bB_s3_apu_load
		FARX	_b2_s7_screen_spell_blink
		LDA		byte_50
		STA		byte_CE
		STA		byte_D2
		LDX		#$F
		JSR		_vblank_count
		JSR		_b0_s55
		BCS		loc_9F75
		LDA		#$81
		JSR		_wrap_bE_s4_msg_m00_arg0_safe
		JMP		sub_9E8B
loc_9F75:
		LDX		#0
loc_9F77:
		LDA		byte_A1F4,X
		CMP		byte_49
		BEQ		loc_9F81
		INX
		BNE		loc_9F77
loc_9F81:
		TXA
		ASL
		TAX
		LDA		off_A1D0,X
		LDY		off_A1D0+1,X
		STA		word_3C
		STY		word_3C+1
		LDA		byte_50
		STA		byte_CE
		JSR		_call_indirect_3C
		BCS		loc_9F9F
		LDA		#$40
		JSR		_wrap_bE_s4_msg_m00_arg0_safe
		JMP		sub_9E8B
loc_9F9F:
		LDA		byte_49
		CMP		#$26
		BEQ		loc_9FB8
		CMP		#$3B
		BEQ		loc_9FB8
		CMP		#$38
		BEQ		loc_9FB8
		CMP		#$3C
		BEQ		loc_9FB8
		CMP		#$39
		BEQ		loc_9FB8
		JMP		sub_9E8B
loc_9FB8:
		JMP		sub_9E97

; =============== S U B	R O U T	I N E =======================================
_call_indirect_3C:
		JMP		(word_3C)

; =============== S U B	R O U T	I N E =======================================
sub_9FBE:
		LDA		byte_50
		JSR		sub_A187
		BCC		locret_9FE9
		LDA		byte_49
		SEC
		SBC		#$1A
		FARX	_b4_s1E

; =============== S U B	R O U T	I N E =======================================
sub_9FCD:
		LDA		word_4
		STA		byte_CF
		LDA		word_4+1
		STA		byte_D0
		JSR		sub_A187
		BCC		locret_9FE9
		JSR		_b0_s4
		LDA		#$14
		JSR		_wrap_bE_s4_msg_m00_arg0_safe
		JSR		sub_A172
		JSR		__pause_or_skip
		SEC
locret_9FE9:
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s54:
		LDA		#$1F
		STA		byte_49
		LDA		#$FF
		STA		byte_46
		BNE		sub_9FF8

; =============== S U B	R O U T	I N E =======================================
sub_9FF4:
		LDA		#0
		STA		byte_46

; =============== S U B	R O U T	I N E =======================================
sub_9FF8:
		LDX		#$FF
		STX		byte_CF
		STX		byte_D0
		INX
loc_9FFF:
		TXA
		PHA
		STA		byte_CE
		STA		byte_D2
		JSR		sub_A189
		BCC		loc_A031
		LDA		byte_49
		CMP		#$1F
		BEQ		loc_A01D
		LDA		#$C
		FARX	_b4_sF
		ADC		#$2C
		STA		byte_CF
		LDA		#0
		STA		byte_D0
loc_A01D:
		JSR		_b0_s4
		LDA		byte_46
		BNE		loc_A031
		LDA		#5
		JSR		_wrap_bE_s4_msg_m00_arg0_safe
		LDA		#$14
		JSR		_wrap_bE_s4_msg_m00_arg0_safe
		JSR		sub_A172
loc_A031:
		PLA
		TAX
		INX
		CPX		#4
		BNE		loc_9FFF
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A039:
		JSR		sub_A197
		BCC		loc_A077
		LDY		byte_49
		CPY		#$20
		BNE		loc_A04B
		JSR		sub_1743B8
		AND		#1
		BNE		loc_A079
loc_A04B:
		LDA		byte_50
		ASL
		TAX
		LDA		#$80
		STA		byte_73D,X
		JSR		_b0_s3
		CPY		#$20
		BNE		loc_A05F
		LSR		word_4+1
		ROR		word_4
loc_A05F:
		LDA		word_4
		STA		byte_CF
		LDA		word_4+1
		STA		byte_D0
		JSR		_b0_s4
		LDA		#$3C
loc_A06C:
		JSR		_wrap_bE_s4_msg_m00_arg0_safe
		JSR		sub_A172
		FARX	_bE_s10
		SEC
		RTS
loc_A077:
		CLC
		RTS
loc_A079:
		LDA		#$3D
		BNE		loc_A06C

; =============== S U B	R O U T	I N E =======================================
sub_A07D:
		JSR		sub_A187
		BCC		locret_A09B
		JSR		_b0_s5C
		BCC		locret_A09B
		LDA		word_4
		STA		byte_CF
		JSR		_b0_s28
		LDA		word_4+1
		STA		byte_D3
		JSR		_b0_s2A
		LDA		#$C3
		JSR		_wrap_bE_s4_msg_m00_arg0_safe
		SEC
locret_A09B:
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A09C:
		JSR		sub_A187
		BCC		locret_A0B9
		LDA		byte_73D,X
		AND		#$20
		BEQ		loc_A0BA
		LDA		byte_73D,X
		AND		#$DF
		STA		byte_73D,X
		LDA		#$44
		JSR		_wrap_bE_s4_msg_m00_arg0_safe
		JSR		sub_A172
		SEC
locret_A0B9:
		RTS
loc_A0BA:
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A0BC:
		JSR		sub_A187
		BCC		locret_A0D9
		LDA		byte_73D,X
		AND		#$40
		BEQ		loc_A0BA
		LDA		byte_73D,X
		AND		#$BF
		STA		byte_73D,X
		LDA		#$42
		JSR		_wrap_bE_s4_msg_m00_arg0_safe
		JSR		sub_A172
		SEC
locret_A0D9:
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A0DA:
		LDA		#$FF
		STA		byte_AD
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A0E0:
		FARX	_bC_s10
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A0E4:
		FARX	_bC_sF
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A0E8:
		FARX	_bC_s1E
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A0EC:
		LDA		byte_53
		STA		byte_CE
		FARX	_b6_s6
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A0F4:
		FARX	_b6_sC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A0F8:
		FARX	_b6_sD
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A0FC:
		FARX	_b6_sF
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A100:
		PHA
		JSR		_b0_s31
		PLA
		TAX
		LDA		word_4
		CMP		#1
		BEQ		loc_A10D
		INX
loc_A10D:
		TXA

; =============== S U B	R O U T	I N E =======================================
_wrap_bE_s4_msg_m00_arg0_safe:
		PHA
		LDA		byte_CE
		PHA
		TSX
		LDA		_players_pos_list+2,X
		LDX		#0
		FARX	_bE_s4_msg_m00
		PLA
		STA		byte_CE
		PLA
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A120:
		STA		byte_44
		TXA
		PHA
		TYA
		PHA
		LDA		byte_CE
		PHA
		LDA		byte_44
		FARX	_bE_sC
		STA		byte_44
		PLA
		STA		byte_CE
		PLA
		TAY
		PLA
		TAX
		LDA		byte_44
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A13A:
		PHA
		JSR		sub_A169
		LDA		byte_53
		STA		byte_D2
		PLA
		JSR		_wrap_bE_s4_msg_m00_arg0_safe
		JMP		sub_9E8B

; =============== S U B	R O U T	I N E =======================================
_b0_s55:
		LDA		byte_2F
		AND		#1
		BEQ		loc_A167
		LDA		byte_8B
		CMP		#$38
		BEQ		loc_A165
		CMP		#$C3
		BCC		loc_A167
		CMP		#$C6
		BCC		loc_A165
		CMP		#$CF
		BEQ		loc_A165
		CMP		#$D0
		BNE		loc_A167
loc_A165:
		CLC
		RTS
loc_A167:
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A169:
		LDA		#$3E
		FARX	_bE_sC
		FARX	_bE_s5
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A172:
		LDA		byte_CE
		PHA
		FARX	_b4_s1A
		JSR		_b0_s31
		LDA		word_4
		CLC
		ADC		#$D
		FARX	_bE_sC
		PLA
		STA		byte_CE
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A187:
		LDA		byte_50

; =============== S U B	R O U T	I N E =======================================
sub_A189:
		ASL
		TAX
		LDA		byte_73C,X
		AND		byte_73D,X
		BPL		loc_A195
		SEC
		RTS
loc_A195:
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A197:
		LDA		byte_50
		ASL
		TAX
		LDA		byte_73C,X
		BPL		loc_A195
		LDA		byte_73D,X
		BMI		loc_A195
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s67:
		PHA
		JSR		_b0_s1E
		LDA		word_6+1
		CMP		#$C1
		BNE		loc_A1C8
		PLA
		BEQ		sub_A1C9
		JSR		sub_A1C9
		LDA		#3
		LDX		#byte_CF
		JSR		_mul16_to_8
		LDA		#4
		JSR		_div16_to_8
		LDA		#1
		JMP		_add8_to_16	; A = value
loc_A1C8:
		PLA

; =============== S U B	R O U T	I N E =======================================
sub_A1C9:
		STA		byte_CF
		LDA		#0
		STA		byte_D0
		RTS
off_A1D0:
		.WORD	sub_9FBE
		.WORD	sub_9FBE
		.WORD	sub_9FBE
		.WORD	sub_9FF4
		.WORD	sub_9FF4
		.WORD	sub_A039
		.WORD	sub_A039
		.WORD	sub_A07D
		.WORD	sub_A09C
		.WORD	sub_A0BC
		.WORD	sub_A0DA
		.WORD	sub_A0E0
		.WORD	sub_A0E4
		.WORD	sub_A0E8
		.WORD	sub_A0EC
		.WORD	sub_A0F4
		.WORD	sub_A0F8
		.WORD	sub_A0FC
byte_A1F4:
		.BYTE	$1A,$1B,$1C,$1E,$1F,$20,$21,$36,$34,$35,$37,$38,$39,$3A,$26,$3B
		.BYTE	$3C,$3D

; =============== S U B	R O U T	I N E =======================================
; ok, got it. previously Y adresation of 34*5 bytes runs out of 256 range, so
; it will wrap around. need more offsets to load the rest, so we has here a lot
; of redundant code. rewritten.
;
_b0_s61_sram_b0_syscall_shortcuts_load:
		LDA		#<[_sram_b0_s2]
		STA		word_4
		LDA		#>[_sram_b0_s2]
		STA		word_4+1
		LDX		#[_b0_s2_idx-_sys_idx_lib]>>1	; first sub idx in lib
loc_A208a:
		LDY		#0
loc_A208:
		LDA		_sram_bank0_bn_code,Y
		STA		(word_4),Y
		INY
		CPY		#[_sram_bank0_bn_code_end-_sram_bank0_bn_code]
		BNE		loc_A208
		TXA
		LDY		#1
		STA		(word_4),Y
		LDA		word_4
		CLC
		ADC		#[_sram_bank0_bn_code_end-_sram_bank0_bn_code]
		STA		word_4
		LDA		word_4+1
		ADC		#0
		STA		word_4+1
		INX
		CPX		#[_b0_s3B_idx-_sys_idx_lib+1]>>1	; last sub idx in lib
		BNE		loc_A208a
		RTS

; code loaded into 6xxx sram area to faster access of code
; rewritten with direct access without stack parameters
_sram_bank0_bn_code:
		LDY		#0
		JMP		_sys0_safe
_sram_bank0_bn_code_end:

; =============== S U B	R O U T	I N E =======================================
_b0_s64:
;		JSR		_sram_b0_s31
		JSR		_b0_s31
		LDX		#0
loc_A292:
		LDA		byte_718,X
		AND		#7
		BEQ		loc_A2A0
		INX
		CPX		word_4
		BNE		loc_A292
		LDX		#0
loc_A2A0:
		TXA
		ASL
		TAY
		LDA		#$80
		STA		byte_73C,Y
		STA		byte_73D,Y
		LDA		byte_724,Y
		STA		byte_71C,Y
		LDA		byte_725,Y
		STA		byte_71D,Y
		LDA		byte_734,Y
		STA		byte_72C,Y
		LDA		byte_735,Y
		STA		byte_72D,Y
		LSR		byte_7BE
		ROR		byte_7BD
		ROR		byte_7BC
		FARX	_bD_s28
		LDA		#0
		STA		byte_6DF
		JMP		sub_1743B5
_b0_d58:
		.BYTE	  0,$1A,$15,$2A,  3,$26,$24,$22
byte_A2DF:
		.BYTE	$10,$1B,  4,$1C,  7,$20,$11,$1F
byte_A2E7:
		.BYTE	$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
byte_A2EF:
		.BYTE	$1A,$26,$3B,$37,$1B,$1C,$20,$1F
_b0_d59:
		.BYTE	  0,$2D,  9,$2E,  3,$26,  6,$18
byte_A2FF:
		.BYTE	  1,$17, $A, $C,  4,$32,  7,$30
byte_A307:
		.BYTE	  2,$27, $B,$29,  5,$28,  8,$33
byte_A30F:
		.BYTE	$3B,$26,$3A,$3D,$38,$36,$3C,$39
_b0_d5A:
		.BYTE	$2B,$1A,$15,$34, $D,$19,$25,$22
byte_A31F:
		.BYTE	$2C,$1B,$12,$35, $E,$24,$16,$23
byte_A327:
		.BYTE	$31,$1C,$13,$1E, $F,$20,$14,$21
byte_A32F:
		.BYTE	$1A,$34,$1B,$35,$20,$1C,$1E,$21
_b0_d3F:
		.BYTE	  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, $A, $B, $C, $D, $E, $F
		.BYTE	$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$1A,$1B,$1C,$1D,$1E,$1F
		.BYTE	$20,$21,$22,$23

; =============== S U B	R O U T	I N E =======================================
_b0_s47:
		LDX		#0
loc_A35D:
		TXA
		PHA
		STA		byte_CE
		JSR		sub_A36C
		PLA
		TAX
		INX
		CPX		#4
		BNE		loc_A35D
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A36C:
		TXA
		PHA
		LDA		byte_700,X
		LDX		#0
		JSR		sub_A725
		PLA
		STA		word_6+1
		ASL
		ADC		word_6+1
		TAX
		LDA		word_4
		STA		byte_6A3F,X
		LDA		word_4+1
		STA		byte_6A40,X
		LDA		word_6
		STA		byte_6A41,X
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s46:
		LDX		#0
		STX		byte_48
		STX		byte_51
loc_A393:
		LDA		byte_51
		ASL
		TAX
		LDA		byte_73C,X
		AND		byte_73D,X
		BPL		loc_A3CE
		LDX		byte_51
		LDA		byte_700,X
		CMP		#$63
		BCS		loc_A3CE
		LDA		byte_51
		ASL
		ADC		byte_51
		TAX
		LDA		byte_746,X
		CMP		byte_6A41,X
		BCC		loc_A3CE
		BEQ		loc_A3BA
		BCS		sub_A3FB
loc_A3BA:
		LDA		byte_745,X
		CMP		byte_6A40,X
		BCC		loc_A3CE
		BEQ		loc_A3C6
		BCS		sub_A3FB
loc_A3C6:
		LDA		byte_744,X
		CMP		byte_6A3F,X
		BCS		sub_A3FB
loc_A3CE:
		INC		byte_51
		LDX		byte_51
		CPX		#4
		BNE		loc_A393
		LDA		byte_48
		BEQ		locret_A3EF
;		JSR		_sram_b0_s31
		JSR		_b0_s31
		LDA		word_4
		CLC
		ADC		#$D
		FARX	_bE_sC
		JSR		__pause_or_skip
		LDA		#0
		STA		byte_8E
		FARX	_bE_sB
locret_A3EF:
		RTS
loc_A3F0:
		LDX		byte_51
		INC		byte_700,X
		JSR		_b0_s47
		JMP		loc_A393

; =============== S U B	R O U T	I N E =======================================
sub_A3FB:
		LDA		byte_60B7
		AND		#$20
		BNE		loc_A410
		LDA		byte_48
		BNE		loc_A410
		FARX	_bE_sD
		SYSX	_sys0D_wrapper_to_bE_sC,$3D
		LDA		#$F4
		STA		byte_48
loc_A410:
		LDA		#5
		JSR		_wrap_bE_s4_msg_m00_arg0
		LDA		#0
		STA		byte_56
		STA		byte_58
		FARX	_bB_s3_apu_load
		SYSX	_sys12_wrapper_to_bB_s3_apu_load,$01
		LDA		byte_51
		STA		byte_D2
		LDA		#$C0
		JSR		_wrap_bE_s4_msg_m00_arg0
		LDX		byte_51
		INC		byte_700,X
		FARX	_bB_s7
		FARX	_bE_s31
		FARX	_bB_s3_apu_load
		JSR		sub_A8BB
		LDX		byte_51
		DEC		byte_700,X
		LDA		byte_51
		STA		byte_CE
		LDY		#0
		STY		byte_52
loc_A448:
		LDA		byte_52
		ASL
		TAY
		LDA		off_A70C,Y
		LDX		off_A70C+1,Y
		STA		word_40
		STX		word_40+1
		LDX		byte_51
		LDA		byte_700,X
		PHA
		LDX		byte_52
		INX
		JSR		sub_A725
		LDA		word_4
		CLC
		ADC		#$A
		STA		byte_42
		PLA
		LSR
		CLC
		ADC		byte_42
		LDY		byte_51
		CMP		(word_40),Y
		BCS		loc_A47D
loc_A474:
		JSR		sub_1743B8
		AND		#1
		BEQ		loc_A4C7
		BNE		loc_A4AA
loc_A47D:
		LDY		byte_11
		LDA		(word_3E),Y
		STA		word_4
		LDA		_tmp12
		LDX		#word_4
		LDY		#word_4
		JSR		_div24_to_16
		FARX	_b4_sE
		LDA		word_4
		LDX		#word_3C
		JSR		_mul16_to_8
		LDA		#$6E
		JSR		_div16_to_8
		LDA		word_3C
		BEQ		loc_A474
		LDX		byte_52
		BEQ		loc_A4A6
		STA		byte_54,X
loc_A4A6:
		CMP		#0
		BEQ		loc_A4C7
loc_A4AA:
		JSR		sub_A8AD
		LDY		byte_51
		CLC
		ADC		(word_40),Y
		BCC		loc_A4B6
		LDA		#$FF
loc_A4B6:
		STA		(word_40),Y
		LDA		byte_52
		CLC
		ADC		#$A0
		PHA
		LDA		#5
		JSR		_wrap_bE_s4_msg_m00_arg0
		PLA
		JSR		_wrap_bE_s4_msg_m00_arg0
loc_A4C7:
		INC		byte_52
		LDA		byte_52
		CMP		#5
		BEQ		loc_A4D2
		JMP		loc_A448
loc_A4D2:
		LDX		byte_51
		LDA		byte_700,X
		LDX		#3
		JSR		sub_A5A4
		JSR		sub_A8A8
		LDA		byte_725,X
		CMP		word_4+1
		BCC		loc_A4FA
		BEQ		loc_A4EA
		BCS		loc_A4F1
loc_A4EA:
		LDA		byte_724,X
		CMP		word_4
		BCC		loc_A4FA
loc_A4F1:
		JSR		sub_1743B8
		AND		#1
		BEQ		loc_A52C
		BNE		loc_A50D
loc_A4FA:
		ASL		byte_56
		BEQ		loc_A52C
		LDA		#5
		FARX	_b4_sF
		CLC
		ADC		#$FE
		CLC
		ADC		byte_56
		BMI		loc_A52C
		BEQ		loc_A52C
loc_A50D:
		JSR		sub_A8AD
		JSR		sub_A8A8
		LDA		byte_63F
		CLC
		ADC		byte_724,X
		STA		byte_724,X
		BCC		loc_A522
		INC		byte_725,X
loc_A522:
		LDA		#5
		JSR		_wrap_bE_s4_msg_m00_arg0
		LDA		#$B8
		JSR		_wrap_bE_s4_msg_m00_arg0
loc_A52C:
		JSR		_b0_s2C
		CMP		#4
		BCS		loc_A58D
		LDX		byte_51
		LDA		byte_700,X
		LDX		#5
		JSR		sub_A5A4
		JSR		sub_A8A8
		LDA		byte_735,X
		CMP		word_4+1
		BCC		loc_A55B
		BEQ		loc_A54B
		BCS		loc_A552
loc_A54B:
		LDA		byte_734,X
		CMP		word_4
		BCC		loc_A55B
loc_A552:
		JSR		sub_1743B8
		AND		#1
		BEQ		loc_A58D
		BNE		loc_A56E
loc_A55B:
		ASL		byte_58
		BEQ		loc_A58D
		LDA		#5
		FARX	_b4_sF
		CLC
		ADC		#$FE
		CLC
		ADC		byte_58
		BMI		loc_A58D
		BEQ		loc_A58D
loc_A56E:
		JSR		sub_A8AD
		JSR		sub_A8A8
		LDA		byte_63F
		CLC
		ADC		byte_734,X
		STA		byte_734,X
		BCC		loc_A583
		INC		byte_735,X
loc_A583:
		LDA		#5
		JSR		_wrap_bE_s4_msg_m00_arg0
		LDA		#$B9
		JSR		_wrap_bE_s4_msg_m00_arg0
loc_A58D:
		JSR		_b0_s2C
		LDA		word_4
		CMP		#7
		BNE		loc_A59A
		LDA		#4
		BNE		loc_A59E
loc_A59A:
		CMP		#4
		BCS		loc_A5A1
loc_A59E:
		JSR		sub_A5B9
loc_A5A1:
		JMP		loc_A3F0

; =============== S U B	R O U T	I N E =======================================
sub_A5A4:
		PHA
		JSR		sub_A725
		LDA		#4
		LDX		#word_4
		JSR		_mul16_to_8
		LDA		#$A
		JSR		_add8_to_16
		PLA
		LSR
		JMP		_add8_to_16

; =============== S U B	R O U T	I N E =======================================
sub_A5B9:
		STA		byte_55
		ASL
		TAX
		LDA		off_A6EE,X
		LDY		off_A6EE+1,X
		STA		word_40
		STY		word_40+1
		LDA		#0
		STA		byte_52
		STA		byte_45
loc_A5CD:
		LDY		byte_52
		LDA		(word_40),Y
		CMP		#$FF
		BNE		loc_A5D6
		RTS
loc_A5D6:
		STA		byte_57
		AND		#$3F
		STA		byte_58
		LDA		byte_55
		CMP		#4
		BNE		loc_A5E5
		JMP		loc_A65B
loc_A5E5:
		LDA		byte_58
		CMP		#$3F
		BNE		loc_A5EE
		JMP		loc_A6E7
loc_A5EE:
		LDA		byte_57
		BMI		loc_A642
		LDX		byte_51
		LDA		byte_700,X
		SEC
		SBC		byte_58
		CLC
		ADC		#1
		CMP		#3
		BCC		loc_A604
		JMP		loc_A6E7
loc_A604:
		ASL
		TAX
		LDA		off_A716,X
		LDY		off_A716+1,X
		STA		word_4A
		STY		word_4A+1
		LDX		byte_51
		LDA		byte_700,X
		LDX		#5
		JSR		sub_A725
		LDY		#2
		LDX		byte_51
		SEC
		LDA		byte_70C,X
		SBC		word_4
		CLC
		ADC		#$F
		BMI		loc_A62F
		DEY
		CMP		#$19
		BCC		loc_A62F
		DEY
loc_A62F:
		LDA		(word_4A),Y
		BNE		loc_A636
		JMP		loc_A6E7
loc_A636:
		JSR		sub_1743B8
		CMP		(word_4A),Y
		BEQ		loc_A661
		BCC		loc_A661
		JMP		loc_A6E7
loc_A642:
		LDX		byte_51
		LDA		byte_700,X
		CLC
		ADC		#1
		CMP		byte_58
		BCS		loc_A651
		JMP		loc_A6E7
loc_A651:
		JSR		sub_1743B8
		AND		#8
		BNE		loc_A661
		JMP		loc_A6E7
loc_A65B:
		LDA		byte_57
		STA		byte_58
		BNE		loc_A642
loc_A661:
		LDX		#$20
		LDA		byte_55
		CMP		#4
		BNE		loc_A66D
		LDX		#$24
		BNE		loc_A673
loc_A66D:
		CMP		#3
		BNE		loc_A673
		LDX		#$40
loc_A673:
		STX		byte_43
		ASL
		TAX
		LDA		off_A6F8,X
		LDY		off_A6F8+1,X
		STA		word_3C
		STY		word_3C+1
		LDA		off_A702,X
		LDY		off_A702+1,X
		STA		word_3E
		STY		word_3E+1
		LDA		byte_51
		ASL
		ASL
		ASL
		LDX		#word_3E
		JSR		_add8_to_16
		LDA		#0
		STA		byte_44
loc_A699:
		LDY		byte_44
		LDA		(word_3C),Y
		CMP		byte_52
		BEQ		loc_A6C0
loc_A6A1:
		INC		byte_44
		LDA		byte_44
		CMP		byte_43
		BNE		loc_A699
		LDA		byte_45
		BEQ		loc_A6E7
		LDA		byte_55
		CMP		#4
		BCS		loc_A6E7
		LDA		#5
		JSR		_wrap_bE_s4_msg_m00_arg0
		LDA		#$BA
		JSR		_wrap_bE_s4_msg_m00_arg0
		JMP		loc_A6E7
loc_A6C0:
		TYA
		PHA
		LSR
		LSR
		LSR
		TAY
		PLA
		AND		#7
		TAX
		SEC
		LDA		#0
loc_A6CD:
		ROL
		DEX
		BPL		loc_A6CD
		STA		byte_42
		AND		(word_3E),Y
		BNE		loc_A6E7
		LDA		byte_42
		ORA		(word_3E),Y
		STA		(word_3E),Y
		LDA		#1
		STA		byte_45
		JSR		sub_A8AD
		JMP		loc_A6A1
loc_A6E7:
		INC		byte_52
		LDA		byte_52
		JMP		loc_A5CD
off_A6EE:
		.WORD	byte_A9C6
		.WORD	byte_AA05
		.WORD	byte_AA44
		.WORD	byte_AA83
		.WORD	byte_AAC2
off_A6F8:
		.WORD	_b0_d58
		.WORD	_b0_d59
		.WORD	_b0_d5A
		.WORD	_b0_d59
		.WORD	_b0_d3F
off_A702:
		.WORD	byte_79C
		.WORD	byte_79C
		.WORD	byte_7A0
		.WORD	byte_79C
		.WORD	byte_79C
off_A70C:
		.WORD	byte_704
		.WORD	byte_708
		.WORD	byte_714
		.WORD	byte_710
		.WORD	byte_70C
off_A716:
		.WORD	byte_A71C
		.WORD	byte_A71F
		.WORD	byte_A722
byte_A71C:
		.BYTE	$FF,$80,  0
byte_A71F:
		.BYTE	$FF,$FF,$80
byte_A722:
		.BYTE	$FF,$FF,$FF

; =============== S U B	R O U T	I N E =======================================
sub_A725:
		STA		_tmp12+1
		STX		byte_10
		TXA
		ASL
		TAY
		LDA		off_A7F4,Y
		LDX		off_A7F4+1,Y
		STA		word_3C
		STX		word_3C+1
		JSR		_b0_s2C
loc_A739:
		DEC		word_4
		BMI		loc_A747
		LDA		#5
		LDX		#word_3C
		JSR		_add8_to_16
		JMP		loc_A739
loc_A747:
		LDA		#<[byte_A806]
		LDY		#>[byte_A806]
		LDX		byte_10
		BEQ		loc_A761
		LDY		#0
		LDX		#0
		LDA		(word_3C),Y
		BPL		loc_A75B
		INX
		INX
loc_A75B:
		LDA		off_A802,X
		LDY		off_A802+1,X
loc_A761:
		STA		word_3E
		STY		word_3E+1
		LDA		#0
		STA		_tmp12
		LDY		#4
loc_A76B:
		TYA
		PHA
		LDA		(word_3C),Y
		AND		#$80
loc_A771:
		LSR
		DEY
		BPL		loc_A771
		ORA		_tmp12
		STA		_tmp12
		PLA
		TAY
		DEY
		BPL		loc_A76B
		LSR		_tmp12
		LSR		_tmp12
		LDA		byte_10
		BEQ		loc_A78C
		LDA		_tmp12
		AND		#$F
		STA		_tmp12
loc_A78C:
		LDY		#0
		STY		word_4
loc_A790:
		LDA		(word_3C),Y
		AND		#$7F
		CLC
		ADC		word_4
		STA		word_4
		CMP		_tmp12+1
		BCS		loc_A7A2
		INY
		CPY		#5
		BNE		loc_A790
loc_A7A2:
		STY		byte_11
		LDA		#0
		LDY		#$A
loc_A7A8:
		STA		word_4,Y
		DEY
		BPL		loc_A7A8
		LDA		#$10
		STA		word_6+1
		LDA		byte_10
		BEQ		loc_A7BE
		LDA		_tmp12
		STA		word_4
		DEC		_tmp12+1
		BEQ		locret_A7F3
loc_A7BE:
		LDY		byte_E
		LDA		(word_3C),Y
		AND		#$7F
		BEQ		loc_A7EF
		STA		byte_F
loc_A7C8:
		LDX		#word_6+1
		LDY		#byte_B
		LDA		_tmp12
		JSR		_div24_to_16
		LDX		#byte_B
		LDY		#word_4
		JSR		_add_24_to_24
		LDA		byte_10
		BNE		loc_A7E7
		LDY		byte_E
		LDA		(word_3E),Y
		LDX		#word_6+1
		LDY		#word_6+1
		JSR		_div24_to_16
loc_A7E7:
		DEC		_tmp12+1
		BEQ		locret_A7F3
		DEC		byte_F
		BNE		loc_A7C8
loc_A7EF:
		INC		byte_E
		BNE		loc_A7BE
locret_A7F3:
		RTS
off_A7F4:
		.WORD	_b0_s4B
		.WORD	byte_A8FE
		.WORD	byte_A926
		.WORD	byte_A94E
		.WORD	byte_A976
		.WORD	byte_A99E
off_A802:
		.WORD	byte_A80B
		.WORD	byte_A810
byte_A806:
		.BYTE	$20,$18,$14,$12,$10
byte_A80B:
		.BYTE	  0,$10,  8,$10,$20
byte_A810:
		.BYTE	  8,$10,$18,$20,  8

; =============== S U B	R O U T	I N E =======================================
_div24_to_16:
		JSR		_div24_to_8
		LDA		#4
		STA		byte_47
		TYA
		TAX
loc_A81E:
		LSR		byte_46
		ROR		2,X
		ROR		1,X
		ROR		0,X
		DEC		byte_47
		BNE		loc_A81E
		RTS

; =============== S U B	R O U T	I N E =======================================
_div24_to_8:
		PHA
		STA		byte_42
		LDA		#0
		STA		byte_43
		STA		byte_44
		STA		byte_45
		STA		byte_46
		STA		byte_47
		LDA		0,X
		STA		0,Y
		LDA		1,X
		STA		1,Y
		LDA		2,X
		STA		2,Y
loc_A849:
		LSR		byte_42
		BCC		loc_A869
		LDA		0,Y
		CLC
		ADC		byte_43
		STA		byte_43
		LDA		1,Y
		ADC		byte_44
		STA		byte_44
		LDA		2,Y
		ADC		byte_45
		STA		byte_45
		LDA		byte_47
		ADC		byte_46
		STA		byte_46
loc_A869:
		TYA
		TAX
		ASL		0,X
		ROL		1,X
		ROL		2,X
		ROL		byte_46
		LDA		byte_42
		BNE		loc_A849
		LDA		byte_43
		STA		0,Y
		LDA		byte_44
		STA		1,Y
		LDA		byte_45
		STA		2,Y
		PLA
		RTS

; =============== S U B	R O U T	I N E =======================================
_add_24_to_24:
		CLC
		LDA		0,X
		ADC		0,Y
		STA		0,Y
		LDA		1,X
		ADC		1,Y
		STA		1,Y
		LDA		2,X
		ADC		2,Y
		STA		2,Y
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A8A8:
		LDA		byte_51
		ASL
		TAX
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A8AD:
		PHA
		STA		byte_63F
		LDA		#0
		STA		byte_640
		STA		byte_641
		PLA
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_A8BB:
		LDA		byte_CE
		PHA
		JSR		_b0_s31
		LDA		word_4
		CLC
		ADC		#3
		TAX
		LDA		byte_60B7
		AND		#$20
		BEQ		loc_A8D2
		TXA
		FARX	_bE_s0
loc_A8D2:
		PLA
		STA		byte_CE
		RTS

_b0_s4B:
		.BYTE	$81,$88,$84,$1C,$FF,  2,$88,$85,$9C,$FF,  2,$88,$86,$9A,$7F,$82
		.BYTE	  8,$86,$19,$7F,  2,$88,$88,$16,$7F,  2,$88,  7,$99,$7F,$82,  8
		.BYTE	  5,$9B,$7F,  2,$88,  8,$98,$FF
byte_A8FE:
		.BYTE	$82,$20, $A,$80,$FF,  4,$28,  5,$31,$FF,  0,$12,$29,$A7,$7F,$80
		.BYTE	$25, $C,$82,$7F,$80,  9,$23,$80,$FF,$86,$17,  0,$80,$FF,$86,  8
		.BYTE	$80,$23,$7F,$84,$2B,  0,$1B,$FF
byte_A926:
		.BYTE	$82,$20, $C,$80,$7F,$8E,$10,  0,$93,$FF,$87,  7, $F,$80,$7F,$80
		.BYTE	$1B,$16,$86,$7F,$80,$62,  0,  0,$FF,$80,$3B,  0,$80,$7F,$80, $B
		.BYTE	$8D,$14,$7F,  0,  9,$46,$8A,$7F
byte_A94E:
		.BYTE	$85,$1F,$88,  0,$7F,$83,  6,$28,$85,$7F,$81,  8, $F,$94,$7F,$80
		.BYTE	$2E,  8,$80,$FF,$84, $A,$8E, $B,$7F,  0,$24,$26,$98,$FF,$82,  9
		.BYTE	$26,$80,$FF,$82,  3, $E,$85,$7F
byte_A976:
		.BYTE	 $A,$27,$31,$80,$FF,$82,  9,$25,$80,$FF,$83,$1D, $E,$80,$FF,$80
		.BYTE	$27,$3B,$80,$7F,  0,$1D,$45,  0,$FF,$95,$1C, $A,$80,$7F,$84,  5
		.BYTE	$1E,$8A,$FF,  0,$89, $A,$85,$7F
byte_A99E:
		.BYTE	$8E,$23,  0,$80,$7F,$80, $E,$37,$80,$7F,$80, $E,$37,$80,$7F,$80
		.BYTE	$18,$4A,$80,$7F,  4,$1E,$40,  0,$FF,$80, $D,  0,$42,$FF,$82,$43
		.BYTE	  0,  0,$FF,  0,  5,$4A,$80,$FF
byte_A9C6:
		.BYTE	  2,$3F,$3F, $A,$17,$3F,$3F,$1F,$3F,$3F,$3F,$3F,$3F,$3F,$3F,$3F
		.BYTE	$1A,$29,$3F,$3F,$3F,  6,$3F,$3F,$3F,$3F,  4,$1D,$21,$3F,$3F,$26
		.BYTE	$23,$3F,$10,$3F,$12,$3F,  7,$3F,$3F,$3F, $C,$3F,$3F,$3F,$3F,$3F
		.BYTE	$3F,$3F,$3F,$3F,$3F,$3F,$3F,$14,$3F,$3F,$3F, $E,$3F,$3F,$FF
byte_AA05:
		.BYTE	  1,$11,$24,$87, $E,$1D, $B,$17,$26,  5,$14,$1A,$20,$3F,$3F,$3F
		.BYTE	$3F,$3F,$3F,$3F,$3F,$3F,$3F,$8F, $C,$3F,$3F,$3F,$3F,$3F,$3F,$3F
		.BYTE	$3F,$3F,$3F,$3F,$3F,$3F, $D,$9B,$A5,$A2,$3F,$3F,$3F,$84,$89,$3F
		.BYTE	$98,$3F,$95,$A8,$3F,$3F,$1E,$3F,$19,$23,$12, $A,$21,$13,$FF
byte_AA44:
		.BYTE	$3F,$3F,$3F,$3F,$3F,$3F,$3F,$3F,$3F,$3F,$3F,$3F,$3F, $C,$1A,$A4
		.BYTE	$3F,$3F,$96,$1C,$A9,  2,$94,$3F,$3F,$85,  1, $E,$1E,$3F,$22,$3F
		.BYTE	$18,$26,  9,$90, $D,$87,$3F,$3F,$3F,$3F,$3F,$88,$12,$3F,$3F,$3F
		.BYTE	$3F,$20,$3F,$3F, $B, $F,$3F,$3F,$3F,$3F,$3F,$3F,$3F,$3F,$FF
byte_AA83:
		.BYTE	  1,$11,$24,$87, $E,$1D, $B,$17,$26,  5,$14,$1A,$20, $C,$1A,$A4
		.BYTE	$3F,$3F,$96,$1C,$A9,  2,$94,$8F, $C,$85,  1, $E,$1E,$3F,$22,$3F
		.BYTE	$18,$26,  9,$90, $D,$87, $D,$9B,$A5,$A2,$3F,$88,$12,$84,$89,$3F
		.BYTE	$98,$20,$95,$A8, $B, $F,$1E,$3F,$19,$23,$12, $A,$21,$13,$FF
byte_AAC2:
		.BYTE	$1C,$14,$28,$10, $A,  5,$18,$13,  7,$22,$1D,  3, $F,$20,  2,$5F
		.BYTE	$1F,$2D, $E,$1E,$25,$27,$1A,$15, $B,$32,$46,$55,$21,$3C, $C,$1B
		.BYTE	$12,$23,$FF

; =============== S U B	R O U T	I N E =======================================
sub_AAE5:
		LDA		#$48
		BNE		sub_AAEB

; =============== S U B	R O U T	I N E =======================================
sub_AAE9:
		LDA		#$67

; =============== S U B	R O U T	I N E =======================================
sub_AAEB:
		JSR		sub_ADE0
		FARX	_bE_s33
		RTS

; =============== S U B	R O U T	I N E =======================================
_b0_s5D:
		LDA		byte_60B7
		AND		#$40
		BNE		sub_AAE9
		SYSX	_sys0D_wrapper_to_bE_sC,$2C
		LDX		#5
		JSR		_vblank_count
		SYSX	_sys0D_wrapper_to_bE_sC,$69
		FARX	_bA_sE
		CMP		#$FF
		BEQ		loc_AB46
		STA		byte_45
		STA		byte_53
		STA		byte_D2
		STA		byte_CE
		STA		byte_CF
		JSR		_b0_s28
		LDA		word_4
		BEQ		sub_AAE5
		SYSX	_sys0D_wrapper_to_bE_sC,$6B
		CMP		#$FF
		BEQ		loc_AB46
		STA		byte_46
		STA		byte_CF
		JSR		_b0_s28
		LDA		word_4+1
		STA		byte_48
		AND		#$7F
		STA		byte_D3
		JSR		_b0_s2C
		LDA		word_4
		CMP		#5
		BNE		loc_AB3F
		LDA		#$4C
		BNE		loc_AB41
loc_AB3F:
		LDA		#$15
loc_AB41:
		FARX	_bE_sC
		CMP		#$FF
loc_AB46:
		BEQ		loc_AB88
		CMP		#3
		BNE		loc_AB4F
		JMP		loc_AD4F
loc_AB4F:
		CMP		#1
		BNE		loc_AB56
		JMP		loc_ABE7
loc_AB56:
		CMP		#2
		BNE		loc_AB5D
		JMP		loc_AC2E
loc_AB5D:
		JSR		sub_ADAC
		BCC		loc_AB65
		JMP		sub_AC9F
loc_AB65:
		LDA		byte_48
		AND		#$7F
		CMP		#$77
		BCS		loc_AB8B
		TAX
		LDA		_b0_d44,X
		BPL		loc_ABDD
		LDA		_b0_d42_effects_list,X
		AND		#$40
		BEQ		loc_AB8B
		CPX		#$67
		BEQ		loc_AB8B
		CPX		#$70
		BEQ		loc_AB8B
		JSR		sub_ACB4
		TAX
		BPL		loc_AB8B
loc_AB88:
		JMP		loc_ACA2
loc_AB8B:
		LDA		byte_45
		PHA
		LDA		byte_46
		PHA
		LDA		byte_47
		PHA
		LDA		byte_48
		PHA
		JSR		sub_AE12
		PLA
		STA		byte_48
		AND		#$7F
		TAX
		PLA
		STA		byte_47
		PLA
		STA		byte_46
		PLA
		STA		byte_45
		BCC		loc_ABE0
		LDA		_b0_d42_effects_list,X
		AND		#4
		BEQ		loc_ABCF
		CPX		#$68
		BEQ		loc_ABCC
		CPX		#$76
		BCS		loc_ABCC
		CPX		#$4C
		BEQ		loc_ABC9
		CPX		#$58
		BCC		loc_ABCC
		CPX		#$65
		BNE		loc_ABC9
		JMP		loc_AC4E
loc_ABC9:
		JMP		loc_AC4B
loc_ABCC:
		JMP		loc_AC51
loc_ABCF:
		CPX		#$4E
		BEQ		loc_AC0D
		CPX		#$6D
		BNE		loc_ABDA
		JMP		sub_ACA5
loc_ABDA:
		JMP		loc_ACA2
loc_ABDD:
		JSR		_wrap_sys0D_wrapper_to_bE_sC_arg3E
loc_ABE0:
		CPX		#$6B
		BEQ		loc_AC0D
		JMP		sub_AC8A
loc_ABE7:
		JSR		sub_ADF4
		BCS		loc_AC0D
		JSR		_b0_s31
		DEC		word_4
		LDA		word_4
		BEQ		loc_ABF8
		JSR		sub_ACB4
loc_ABF8:
		STA		byte_47
		STA		byte_CE
		CMP		#$FF
		BEQ		loc_AB88
		JSR		sub_AC74
		LDA		word_4
		BMI		loc_AC10
		JSR		sub_ACBE
		JSR		sub_AC57
loc_AC0D:
		JMP		sub_AC9F
loc_AC10:
		LDA		byte_47
		CMP		byte_45
		BNE		sub_AC7D
		PHA
		LDA		byte_48
		PHA
		JSR		sub_AC57
		PLA
		STA		byte_48
		PLA
		STA		byte_45
		STA		byte_CE
		JSR		sub_AC74
		JSR		sub_ACBE
		JMP		loc_AC0D
loc_AC2E:
		JSR		sub_ADF4
		BCS		loc_AC0D
		JSR		_wrap_sys0D_wrapper_to_bE_sC_arg3E
		LDA		byte_48
		AND		#$7F
		TAX
		LDA		_b0_d42_effects_list,X
		AND		#$10
		BEQ		loc_AC48
		SYSX	_sys07_msg_m00_arg1,$2A
		JMP		sub_AC9F
loc_AC48:
		JSR		sub_AD31
loc_AC4B:
		JSR		__pause_or_skip
loc_AC4E:
		FARX	_bC_s20
loc_AC51:
		JSR		sub_AC57
		JMP		sub_ACA9

; =============== S U B	R O U T	I N E =======================================
sub_AC57:
		LDA		byte_45
		STA		byte_CE
		LDA		byte_46
		STA		byte_CF
		JSR		_b0_s2A
		LDA		byte_48
		CMP		#$AA
		BEQ		loc_AC70
		CMP		#$B1
		BEQ		loc_AC70
		CMP		#$B2
		BNE		locret_AC73
loc_AC70:
		FARX	_bE_s10
locret_AC73:
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_AC74:
		LDA		byte_48
		AND		#$7F
		STA		byte_CF
		JMP		_b0_s29

; =============== S U B	R O U T	I N E =======================================
sub_AC7D:
		JSR		_wrap_sys0D_wrapper_to_bE_sC_arg3E
		LDA		byte_47
		STA		byte_D2
		SYSX	_sys07_msg_m00_arg1,$69
		JMP		sub_AC9F

; =============== S U B	R O U T	I N E =======================================
sub_AC8A:
		LDA		byte_48
		AND		#$7F
		CMP		#$68
		BEQ		loc_ACA2
		LDX		#3
loc_AC94:
		CMP		byte_ACB1-1,X
		BEQ		sub_AC9F
		DEX
		BNE		loc_AC94
		SYSX	_sys06_msg_m00_arg0,$40

; =============== S U B	R O U T	I N E =======================================
sub_AC9F:
		JSR		__pause_or_skip
loc_ACA2:
		FARX	_bC_s20

; =============== S U B	R O U T	I N E =======================================
sub_ACA5:
		LDA		#0
		STA		byte_48

; =============== S U B	R O U T	I N E =======================================
sub_ACA9:
		LDA		#0
		STA		byte_8E
		FARX	_b0_s50
		RTS
byte_ACB1:
		.BYTE	$52,$57,$76

; =============== S U B	R O U T	I N E =======================================
sub_ACB4:
		SYSX	_sys0D_wrapper_to_bE_sC,$2E
		STA		byte_47
		STA		byte_D4
		STA		byte_50
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_ACBE:
		JSR		_wrap_sys0D_wrapper_to_bE_sC_arg3E
		JSR		sub_AD1E
		LDA		byte_45
		CMP		byte_47
		BEQ		loc_ACFC
		LDY		#$2B
		ASL
		TAX
		LDA		byte_73D,X
		ASL
		BMI		loc_ACD9
		BCS		loc_ACE1
		INY
		INY
		INY
loc_ACD9:
		INY
		INY
		INY
		LDX		#2
		JSR		sub_AD13
loc_ACE1:
		LDA		byte_47
		ASL
		TAX
		LDA		byte_73D,X
		ASL
		BMI		loc_ACEE
		BCS		loc_ACF8
		INY
loc_ACEE:
		INY
		CPY		#$2E
		BCC		loc_ACF8
		LDX		#3
		JSR		sub_AD13
loc_ACF8:
		TYA
		JMP		_wrap_bE_s4_msg_m00_arg1
loc_ACFC:
		ASL
		TAX
		LDY		#$34
		LDA		byte_73D,X
		ASL
		BMI		loc_AD09
		BCS		loc_AD0F
		INY
loc_AD09:
		INY
		LDX		#3
		JSR		sub_AD13
loc_AD0F:
		TYA
		JMP		_wrap_bE_s4_msg_m00_arg1

; =============== S U B	R O U T	I N E =======================================
sub_AD13:
		LDA		byte_D2,X
		PHA
		LDA		byte_D2
		STA		byte_D2,X
		PLA
		STA		byte_D2
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_AD1E:
		LDX		#0
loc_AD20:
		LDA		byte_73D,X
		ASL
		BMI		loc_AD28
		BCS		loc_AD2C
loc_AD28:
		INX
		INX
		BNE		loc_AD20
loc_AD2C:
		TXA
		LSR
		STA		byte_D5
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_AD31:
		JSR		sub_AD1E
		STA		byte_D4
		LDY		#$27
		LDA		byte_45
		ASL
		TAX
		LDA		byte_73D,X
		ASL
		BMI		loc_AD45
		BCS		loc_AD4B
		INY
loc_AD45:
		INY
		LDX		#2
		JSR		sub_AD13
loc_AD4B:
		TYA
		JMP		_wrap_bE_s4_msg_m00_arg1
loc_AD4F:
		JSR		_wrap_sys0D_wrapper_to_bE_sC_arg3E
		LDA		byte_45
		ASL
		TAX
		LDA		byte_73D,X
		ASL
		BCS		loc_AD62
		SYSX	_sys07_msg_m00_arg1,$26
		JMP		sub_AC9F
loc_AD62:
		SYSX	_sys07_msg_m00_arg1,$1B
		LDA		byte_48
		AND		#$7F
		TAX
		LDA		_b0_d42_effects_list,X
		PHA
		AND		#$10
		BEQ		loc_AD7B
		SYSX	_sys07_msg_m00_arg1,$23
		SYSX	_sys07_msg_m00_arg1,$24
		JMP		loc_ADA1
loc_AD7B:
		LDA		byte_48
		AND		#$7F
		JSR		_b0_s60
		CLC
		ADC		#$1D
		JSR		_wrap_bE_s4_msg_m00_arg1
		LDA		byte_48
		AND		#$7F
		TAX
		FARX	_bD_s12
		FARX	_bD_s13
		LDX		#3
loc_AD95:
		LDA		byte_BF,X
		STA		byte_63E,X
		DEX
		BNE		loc_AD95
		SYSX	_sys07_msg_m00_arg1,$21
loc_ADA1:
		PLA
		AND		#8
		BNE		loc_ADA9
		SYSX	_sys07_msg_m00_arg1,$16
loc_ADA9:
		JMP		sub_AC9F

; =============== S U B	R O U T	I N E =======================================
sub_ADAC:
		LDA		byte_48
		AND		#$7F
		STA		byte_CF
		LDA		byte_45
		STA		byte_CE
		ASL
		TAX
		LDY		#$26
		LDA		byte_73D,X
		ASL
		BCC		loc_ADC3
		BPL		loc_ADC6
		DEY
loc_ADC3:
		TYA
		BNE		sub_ADE0
loc_ADC6:
		JSR		_b0_s5F
		BCC		loc_ADEC
		LDA		#$44
		STA		byte_CF
		JSR		_b0_s45
		LDA		word_4
		BPL		_set_carry_ret
		CMP		#$FF
		BEQ		_set_carry_ret
		AND		#$7F
		STA		byte_D3
		LDA		#$15

; =============== S U B	R O U T	I N E =======================================
sub_ADE0:
		PHA
		JSR		_wrap_sys0D_wrapper_to_bE_sC_arg3E
		PLA
		JSR		_wrap_bE_s4_msg_m00_arg1
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
_set_carry_ret:
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
loc_ADEC:
		JSR		_wrap_sys0D_wrapper_to_bE_sC_arg3E
		SYSX	_sys06_msg_m00_arg0,$BF
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_ADF4:
		LDA		byte_48
		BPL		_set_carry_ret
		AND		#$7F
		TAX
		LDA		_b0_d42_effects_list,X
		AND		#8
		BEQ		_set_carry_ret
		STX		byte_D2
		SYSX	_sys12_wrapper_to_bB_s3_apu_load,$17
		JSR		_wrap_sys0D_wrapper_to_bE_sC_arg3E
		SYSX	_sys07_msg_m00_arg1,$52
		FARX	_bD_s22
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_AE12:
		LDA		byte_48
		AND		#$7F
		CMP		#$68
		BEQ		loc_AE1D
		JSR		_wrap_sys0D_wrapper_to_bE_sC_arg3E
loc_AE1D:
		LDY		#$FD
		LDA		byte_48
		AND		#$7F
		TAX
loc_AE24:
		LDA		_b0_d44,X
		BPL		loc_AE2C
		INY
		INY
		INY
loc_AE2C:
		DEX
		BNE		loc_AE24
		LDA		off_B0C6,Y
		STA		word_3C
		LDA		off_B0C6+1,Y
		STA		word_3C+1
		LDA		byte_B0C5,Y
		BEQ		loc_AE4F
		CMP		#$5C
		BEQ		loc_AE52
		CMP		#$64
		BCC		loc_AE4C
		JSR		_wrap_bE_s4_msg_m00_arg0
		JMP		loc_AE4F
loc_AE4C:
		JSR		_wrap_bE_s4_msg_m00_arg1
loc_AE4F:
		JMP		(word_3C)
loc_AE52:
		LDA		byte_2F
		CMP		#2
		BCC		loc_AE68
		BEQ		loc_AE62
		CMP		#3
		BEQ		loc_AE62
		CMP		#7
		BNE		loc_AE68
loc_AE62:
		SYSX	_sys06_msg_m00_arg0,$40
		JMP		loc_AF3B
loc_AE68:
		LDA		#$5C
		BNE		loc_AE4C

; =============== S U B	R O U T	I N E =======================================
sub_AE6C:
		LDA		byte_2A
		CMP		#$4A
		BNE		loc_AEB0
		LDA		byte_2B
		CMP		#$90
		BNE		loc_AEB0
		SYSX	_sys07_msg_m00_arg1,$3C
		JSR		sub_176C3C
		FARX	_bC_s24
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_AE82:
		JSR		sub_B143
		BCC		locret_AE8B
		FARX	_bE_s33
		SEC
locret_AE8B:
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_AE92:
		LDA		byte_8B
		CMP		#$62
		BNE		sub_AEB3
		LDA		byte_30
		CMP		#$D
		BNE		sub_AEB3
		LDA		byte_31
		CMP		#6
		BNE		sub_AEB3
		LDA		byte_60CD
		AND		#$20
		BNE		sub_AEB3
		FARX	_b5_s5
		SEC
		RTS
loc_AEB0:
		SYSX	_sys07_msg_m00_arg1,$53

; =============== S U B	R O U T	I N E =======================================
sub_AEB3:
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_AEB5:
		FARX	_bC_s22
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_AEB9:
		FARX	_bC_s12_vblank_count_50
		FARX	_bC_s11
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_AEC0:
		FARX	_b6_s15
		BCC		locret_AECC
		JSR		sub_176C3C
		FARX	_bC_s20
		SEC
locret_AECC:
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_AECD:
		JSR		sub_176C3C
		FARX	_b6_sE
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_AED4:
		FARX	_bC_s13
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_AED8:
		FARX	_bC_sD
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_AEDC:
		FARX	_bC_sE
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_AEE0:
		FARX	_bC_sF
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_AEE4:
		SYSX	_sys06_msg_m00_arg0,$18
		JSR		sub_B298
		JMP		loc_AF3B

; =============== S U B	R O U T	I N E =======================================
sub_AEED:
		FARX	_b6_s12
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_AEF1:
		LDA		byte_60B6
		AND		#$20
		BNE		sub_AEB3
		LDA		byte_8B
		CMP		#$2F
		BNE		loc_AF38
		LDA		byte_30
		CMP		#$26
		BCC		loc_AF38
		CMP		#$29
		BCS		loc_AF38
		LDA		byte_31
		CMP		#5
		BCC		loc_AF38
		CMP		#7
		BCS		loc_AF38
		LDA		_npcs_pos_list
		CMP		#$27
		BNE		loc_AF38
		SYSX	_sys07_msg_m00_arg1,$A1
		SYSX	_sys12_wrapper_to_bB_s3_apu_load,$86
		SYSX	_sys0D_wrapper_to_bE_sC,$1D
		TAX
		BNE		loc_AF32
		SYSX	_sys07_msg_m00_arg1,$A2
		FARX	_bC_s2E_vblank_count_50_wait_50_or_skip
		LDA		#4
		FARX	_bC_s0_npc_anim_script_init
		SEC
		RTS
loc_AF32:
		SYSX	_sys07_msg_m00_arg1,$A3
		JMP		loc_AF3B
loc_AF38:
		SYSX	_sys07_msg_m00_arg1,$06
loc_AF3B:
		JSR		__pause_or_skip

; =============== S U B	R O U T	I N E =======================================
sub_AF3E:
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_AF5B:
		FARX	_b1_s15
		CMP		#$FF
		BEQ		loc_AF78
		STA		byte_50
		JSR		_wrap_sys0D_wrapper_to_bE_sC_arg3E
		SYSX	_sys06_msg_m00_arg0,$AA
		JSR		sub_176C3C
		FARX	_b6_s6
		BCS		sub_AF3E
		SYSX	_sys06_msg_m00_arg0,$40
		JSR		__pause_or_skip
loc_AF78:
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_AF7D:
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_AF7F:
		SYSX	_sys07_msg_m00_arg1,$08
		JSR		sub_176C3C
		FARX	_b6_s11
		BCC		loc_AF92
		SYSX	_sys07_msg_m00_arg1,$0B
		SYSX	_sys07_msg_m00_arg1,$09
		SEC
		RTS
loc_AF92:
		SYSX	_sys07_msg_m00_arg1,$02
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_AF9A:
		LDA		byte_30
		STA		word_4+1
		LDA		byte_31
		STA		word_6
		LDY		byte_644
		BEQ		loc_AFB2
		DEY
		BEQ		loc_AFB7
		DEY
		BEQ		loc_AFBC
		DEC		word_4+1
		JMP		loc_AFBE
loc_AFB2:
		DEC		word_6
		JMP		loc_AFBE
loc_AFB7:
		INC		word_4+1
		JMP		loc_AFBE
loc_AFBC:
		INC		word_6
loc_AFBE:
		LDX		#0
loc_AFC0:
		LDA		_npcs_pos_list+1,X
		CMP		#$FF
		BEQ		sub_AF7D
		CMP		word_6
		BNE		loc_AFD2
		LDA		_npcs_pos_list,X
		CMP		word_4+1
		BEQ		loc_AFD8
loc_AFD2:
		INX
		INX
		INX
		INX
		BNE		loc_AFC0
loc_AFD8:
		TXA
		LSR
		LSR
		STA		word_4
		JSR		sub_177EFC
		LDA		word_6
		AND		#$1F
		TAX
		LDA		#$70
		LDY		byte_B006,X
		BEQ		loc_AFF6
		DEY
		BEQ		loc_AFF8
		DEY
		BNE		sub_AF7D
		LDA		#$B4
		BNE		loc_AFF8
loc_AFF6:
		LDA		#$6F
loc_AFF8:
		JSR		_wrap_bE_s4_msg_m00_arg0
		FARX	_bC_s12_vblank_count_50
		FARX	_bC_s20
		FARX	_b6_s10
		SEC
		RTS
byte_B006:
		.BYTE	  0,  0,  0,  0,  0,  0,  1,  0,  0,  1,  0,  1,  0,  0,  0,  1
		.BYTE	  2,  2,  3,  3,  0,  2,  2,  2,  3,  1,  0,  3,  3,  3,  0,  2

; =============== S U B	R O U T	I N E =======================================
sub_B026:
		LDA		#0
		STA		byte_640
		STA		byte_641
		LDA		byte_9C
		SEC
		SBC		byte_2B
		BMI		loc_B03C
		STA		byte_63F
		LDA		#$12
		BNE		loc_B045
loc_B03C:
		EOR		#$FF
		TAX
		INX
		STX		byte_63F
		LDA		#$10
loc_B045:
		JSR		_wrap_bE_s4_msg_m00_arg1
		LDA		byte_9B
		SEC
		SBC		byte_2A
		BMI		loc_B056
		STA		byte_63F
		LDA		#$11
		BNE		loc_B05F
loc_B056:
		EOR		#$FF
		TAX
		INX
		STX		byte_63F
		LDA		#$13
loc_B05F:
		JSR		_wrap_bE_s4_msg_m00_arg1
		SYSX	_sys07_msg_m00_arg1,$14
		JMP		loc_AF3B

; =============== S U B	R O U T	I N E =======================================
sub_B068:
		FARX	_bC_sC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_B06C:
		SYSX	_sys12_wrapper_to_bB_s3_apu_load,$1C
		JSR		sub_176C3C
		LDA		byte_8B
		CMP		#$EF
		BNE		loc_B097
		LDA		byte_30
		CMP		#$F
		BCC		loc_B097
		CMP		#$12
		BCS		loc_B097
		LDA		byte_31
		CMP		#$11
		BCC		loc_B097
		CMP		#$14
		BCS		loc_B097
		LDA		byte_60BA
		AND		#$20
		BNE		loc_B097
		FARX	_bC_s2B
		RTS
loc_B097:
		FARX	_bD_s22
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_B09C:
		SYSX	_sys12_wrapper_to_bB_s3_apu_load,$1B
		FARX	_bB_s7
		LDA		byte_60C5
		BMI		loc_B0B5
		FARX	_b0_s53
		LDY		_enemy_roster_index_list
		INY
		BEQ		loc_B0B5
		JSR		sub_174CBD
		SEC
		RTS
loc_B0B5:
		FARX	_bD_s22
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_B0BA:
		JSR		sub_176C3C
		FARX	_b6_s1F
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_B0C1:
		FARX	_bC_s26
		RTS
byte_B0C5:
		.BYTE	  0
off_B0C6:
		.WORD	sub_AE6C
		.BYTE	  0
		.WORD	sub_AE82
		.BYTE	  0
		.WORD	sub_AE82
		.BYTE	  0
		.WORD	sub_AE82
		.BYTE	  0
		.WORD	sub_AE82
		.BYTE	  0
		.WORD	sub_AE82
		.BYTE	  0
		.WORD	sub_AEB3
		.BYTE	$A5
		.WORD	sub_B16B
		.BYTE	$9B
		.WORD	sub_B269
		.BYTE	$C
		.WORD	sub_AE92
		.BYTE	  0
		.WORD	sub_AEB5
		.BYTE	$56
		.WORD	sub_AEB9
		.BYTE	$60
		.WORD	sub_AEC0
		.BYTE	$57
		.WORD	sub_AECD
		.BYTE	  0
		.WORD	sub_AED4
		.BYTE	$53
		.WORD	sub_AED8
		.BYTE	$53
		.WORD	sub_AEDC
		.BYTE	$53
		.WORD	sub_AEE0
		.BYTE	$C
		.WORD	sub_AEE4
		.BYTE	$62
		.WORD	sub_AEED
		.BYTE	$58
		.WORD	sub_AEF1
		.BYTE	$53
		.WORD	sub_B198
		.BYTE	$53
		.WORD	sub_B1A5
		.BYTE	$53
		.WORD	sub_B1CC
		.BYTE	$53
		.WORD	sub_B1BF
		.BYTE	$53
		.WORD	sub_B1B2
		.BYTE	$A7
		.WORD	sub_B1F6
		.BYTE	$53
		.WORD	sub_B21E
		.BYTE	$53
		.WORD	sub_B234
		.BYTE	$A9
		.WORD	sub_B240
		.BYTE	  0
		.WORD	sub_AF5B
		.BYTE	$AB
		.WORD	sub_B246
		.BYTE	$AC
		.WORD	sub_AF7D
		.BYTE	$53
		.WORD	sub_AF7F
		.BYTE	$53
		.WORD	sub_B256
		.BYTE	$5B
		.WORD	sub_AF9A
		.BYTE	$5C
		.WORD	sub_B026
		.BYTE	$59
		.WORD	sub_B068
		.BYTE	$59
		.WORD	sub_B06C
		.BYTE	$AF
		.WORD	sub_B09C
		.BYTE	$5F
		.WORD	sub_B0BA
		.BYTE	$C7
		.WORD	sub_B0C1

; =============== S U B	R O U T	I N E =======================================
sub_B143:
		LDA		byte_48
		AND		#$7F
		STA		byte_D3
		LDA		byte_45
		STA		byte_CE
		STA		byte_D2
		LDA		byte_46
		STA		byte_CF
		JSR		_b0_s28
		LDA		word_4+1
		BMI		loc_B166
		STA		byte_42
		LDA		byte_45
		FARX	_b4_s1F
		SYSX	_sys06_msg_m00_arg0,$9F
		SEC
		RTS
loc_B166:
		SYSX	_sys07_msg_m00_arg1,$63
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_B16B:
		LDA		byte_45
		STA		byte_CE
		LDA		#$19
		FARX	_b4_sF
		ADC		#$A
		STA		byte_CF
		LDA		#0
		STA		byte_D0
		JSR		_b0_s8
		JSR		sub_A172
		JSR		sub_1743B8
		CMP		#$19
		BCS		loc_B196
		LDA		#$4E
		FARX	_b4_s20
		JSR		_b0_s2A
		LDA		#$A6
		JSR		_wrap_bE_s4_msg_m00_arg0_idx05_then_A_safe
loc_B196:
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_B198:
		LDX		byte_45
		LDA		byte_704,X
		JSR		sub_B1D9
		STA		byte_704,X
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_B1A5:
		LDX		byte_45
		LDA		byte_708,X
		JSR		sub_B1D9
		STA		byte_708,X
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_B1B2:
		LDX		byte_45
		LDA		byte_70C,X
		JSR		sub_B1D9
		STA		byte_70C,X
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_B1BF:
		LDX		byte_45
		LDA		byte_710,X
		JSR		sub_B1D9
		STA		byte_710,X
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_B1CC:
		LDX		byte_45
		LDA		byte_714,X
		JSR		sub_B1D9
		STA		byte_714,X
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_B1D9:
		PHA
		JSR		sub_1743B8
		AND		#1
		ADC		#1
		JSR		sub_B2AD
		PLA
		CLC
		ADC		byte_63F
		PHA
		LDA		byte_48
		CLC
		ADC		#$41
		JSR		_wrap_bE_s4_msg_m00_arg0_idx05_then_A_safe
		PLA
		LDX		byte_45
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_B1F6:
		JSR		sub_1743B8
		AND		#3
		CLC
		ADC		#2
		STA		word_4
		LDA		byte_45
		ASL
		TAX
		CLC
		LDA		byte_724,X
		ADC		word_4
		STA		byte_724,X
		BCC		loc_B212
		INC		byte_725,X
loc_B212:
		LDA		word_4
		JSR		sub_B2AD
		LDA		#$A8
		JSR		_wrap_bE_s4_msg_m00_arg0_idx05_then_A_safe
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_B21E:
		JSR		sub_B2B9
		JSR		_wrap_bE_s4_msg_m00_arg0_idx05_safe
		LDA		#$F
		FARX	_b4_sF
		ADC		#$23
		STA		word_4
		LDA		#0
		STA		word_4+1
		JMP		sub_9FCD

; =============== S U B	R O U T	I N E =======================================
sub_B234:
		JSR		sub_B2B9
		JSR		_wrap_bE_s4_msg_m00_arg0_idx05_safe
		JSR		sub_A09C
		BCC		_wrap_bE_s4_msg_m00_arg0_idx40_safe
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_B240:
		LDA		#$7F
		STA		byte_AD
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_B246:
		JSR		sub_B2B9
		LDA		#$21
		STA		byte_49
		JSR		_wrap_bE_s4_msg_m00_arg0_idx05_safe
		JSR		sub_A039
		BCC		_wrap_bE_s4_msg_m00_arg0_idx40_safe
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_B256:
		JSR		sub_B2B9
		JSR		_wrap_bE_s4_msg_m00_arg0_idx05_safe
		JSR		sub_A0BC
		BCC		_wrap_bE_s4_msg_m00_arg0_idx40_safe
		RTS

; =============== S U B	R O U T	I N E =======================================
_wrap_bE_s4_msg_m00_arg0_idx40_safe:
		LDA		#$40
		JSR		_wrap_bE_s4_msg_m00_arg0_safe
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_B269:
		JSR		_b0_s33
		LDA		word_4
		STA		byte_55
		LDX		#0
loc_B272:
		TXA
		PHA
		STA		byte_D2
		ASL
		TAX
		LDA		byte_73C,X
		AND		byte_73D,X
		BPL		loc_B28C
		LDA		#$9C
		JSR		_wrap_bE_s4_msg_m00_arg0_safe
		DEC		byte_55
		BEQ		loc_B28C
		JSR		_wrap_bE_s4_msg_m00_arg0_idx05_safe
loc_B28C:
		PLA
		TAX
		INX
		CPX		#4
		BNE		loc_B272
		JSR		__pause_or_skip
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_B298:
		LDA		byte_45
		STA		byte_D2
		ASL
		TAX
		LDA		byte_73D,X
		ORA		#$40
		STA		byte_73D,X
		LDA		#$A
		JSR		_wrap_bE_s4_msg_m00_arg0_idx05_then_A_safe
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_B2AD:
		STA		byte_63F
		LDA		#0
		STA		byte_640
		STA		byte_641
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_B2B9:
		LDA		byte_47
		STA		byte_50
		STA		byte_CE
		STA		byte_D2
		LDA		byte_45
		STA		byte_53
		RTS

; =============== S U B	R O U T	I N E =======================================
_wrap_bE_s4_msg_m00_arg0_idx05_safe:
		LDA		#5
		JMP		_wrap_bE_s4_msg_m00_arg0_safe

; =============== S U B	R O U T	I N E =======================================
_wrap_bE_s4_msg_m00_arg0_idx05_then_A_safe:
		PHA
		JSR		_wrap_bE_s4_msg_m00_arg0_idx05_safe
		PLA
		JMP		_wrap_bE_s4_msg_m00_arg0_safe

_b0_d43_enemies_lib:
		.BYTE	  1,  4,  0,  4,  2,  9,  5,  8,  0,$E5,$82,  2,$82,  2,  7,  2,  7,  2,  0,  0,$30,$30,$16
		.BYTE	  1,  5,  0,  6,  2, $A,  6,  9,  0,$E5,$82,  2,  2,  2,  2,  2,  2,  2,  0,  0,$30,$30,$25
		.BYTE	  2,  7,  0,  5,  2, $C,  8, $A,  0,$E5,$82,  7,  2,  2,  2,  7,  2,  2,  0,  0,$30,$30,$22
		.BYTE	  3,  8,  0,  6,  3, $D,  8, $D,  0,$C5,$82,  2,$82,  2,  2,  2,  2,  2,  0,  0,$70,$30,$24
		.BYTE	$43,  6,  0,  8,  4, $B,  7, $C, $C,$68,  2,$82,$82,  2,$26,  2,$26,  2,  0,  0,$40,$10,$14
		.BYTE	$43, $B,  0,  7,  3, $E,  8, $F,  0,$65,  2,  2,  1,$82,  2,  2,  2,  2,  0,  0,$30,$30,$22
		.BYTE	  4, $C,  0, $C,  6,$10,  9, $A,  0,$E6,$87,  2,  5,  2,  7,  5,  2,  2,  0,  0,$B0,$30,$12
		.BYTE	  4, $D,  0, $D, $A, $B, $F,$17, $A,$67,$13,$93,$82,  7,$13,$13,$13,$13,  0,  0,  0,  4,$34
		.BYTE	  4,  8,  0, $A,  4,$12, $B, $C,  0,$E2,$82,  2,  2,  8,  2,  8,  2,  8,  0,  0,$30,$30,$15
		.BYTE	  4,$15,  0,$14,  5, $E, $A,$1E,$FF,$5F,  2,$36,$36,  2,$36,$36,$36,$36,$A4,$10,$B0,$24,$35
		.BYTE	  4, $C,  0, $A,  7,$14,  9,$11,  0,$65,$82,  2,$82,  7,  2,  2,  2,  2,  0,  0,$74,$34,$2A
		.BYTE	  4, $E,  0,  9,  8,$13, $C,$14,$14,$C5,  7,  2,$87,  2,  2,$22,  2,$22,  0,  0,$40,$24,$64
		.BYTE	  5,$14,  0, $C,  9,$18, $C,$19,  0,$E6,  7,  5,$82,  2,  5,  2,  2,  5,  0,  0,$70,$70,$22
		.BYTE	  6,$1F,  0, $B, $C,$1B,$19,$28,$19,$65,$AD,$2D,  2,  2,  2,  2,$2D,  2,  0,  0,  0,$10,$32
		.BYTE	  6,$1D,  0, $F, $D,$1E,$18,$1C,$1E,$83,  2,$82,$23,  2,  2,  2,$23,  2,  0,  0,$54,$50,$14
		.BYTE	  7,$1D,  0, $B, $F,$1C,  4,$32,$1E,$E4,  2,$82,  2,$29,  2,$29,  2,$29,  0,  0,$C0,$10,$15
		.BYTE	$46,$1A,  0, $D, $D,$20, $F,$19,  0,$65,$87,  2,  6,  2,  2,  2,  6,  6,$40,  0,$70,$30,$72
		.BYTE	  8,$23,  0, $C, $C,$20,$3C,$1C,  0,$B0,$82,  8,  2,$82,  8,  2,  8,  2,  0,  0,$70,$74,$B4
		.BYTE	$48,$23,  0,$1C, $E,$16, $E,$19,$12,$E1,  2,$82,$93,$13,  2,$13,$13,$13,  0,  0,$C0,$C0,$75
		.BYTE	  9,$27,  0,  8,$12,$1E, $C,$18,  0,$E7,  2,  7,  2,$10,  2,$10,  2,  2,  0,  0,$74,$BC,$23
		.BYTE	  9,$2F,  0, $E,$14,$28,$10,$23,  0,$66,$87,  2,$11,  2,  2,  2,  2,$11,$40,  0,$70,$30,$32
		.BYTE	$49,$2D,  0, $E, $F,$24,$12,$19,$14,$E0,$87,  2,  2,  2,$82,$82,  2,  2,  0,  0,$40,$70,$74
		.BYTE	 $A,$35,  0,$10, $E,$2A,$16,$28,  4,$E3,  2,$82,$82,  2,  2,$25,  2,$25,$40,  0,$84,$70,$55
		.BYTE	 $A,$38,  0, $F, $F,$2B,$19,$1E,  0,$E8,$87,  2,$84,  7,  4,$10,  2,$10,$40,  0,$B4,$70,$33
		.BYTE	 $A,$21,  0, $C, $C,$20,$3C,$1C,  0,$B0,$82,  8,  2,$82,  8,  2,  8,  2,  0,  0,$70,$74,$B4
		.BYTE	$4A,$3D,  0,$13,$13,$33,$1C,$23,  9,$62,$96,  2,  2,  2,  2,$16,  2,$16,  0,  0,$40,$24,$74
		.BYTE	$4A,$37,  0,$11, $F,$31,$23,$1A,  4,$88,  7,  2,$88,  5,  2,$26,  2,  2,$40,  0,$40,$10,$B5
		.BYTE	 $B,$44,  0, $A,$1E,$2F,$2D,$37,  0,$82,$83,  2,$BB,  2,  2,  2,$3B,  2,$40,$30,$B0,$7C,$24
		.BYTE	$4B,$41,  0,$16,$14,$30,$31,$23,  4,$2A,  2,$81,  2,$82,  2,  3,  7,$23,$40,$10,$54,$54,$76
		.BYTE	$4B,$46,  0,$12,$17,$31,$25,$26,$1E, $A,$82,  2,$A2,  2,  2,  2,$22,  2,$50,$10,$50,$54,$34
		.BYTE	 $B,$3C,  0,$15,$12,$37,$19,$32,  0,$DF,$83,  8,  2,  2,  2,  2,  8,  2,$20,$10,$74,$B4,$B5
		.BYTE	$CB,  5,  0,$40,$5E, $F,$25,$28,$FF,$E1,  9,$A9,$2E,$82,$23,$26,$31,$31,$FD,$30,$CC,$78,$84
		.BYTE	 $C,$49,  0,$13, $C,$37,$31,$23,  0,$65,  2,  2,  3,  2,  2,  2,  2,  2,  0,$30,$74,$70,$5B
		.BYTE	 $C,$4E,  0,$13,$17,$32,$6E,$28,$1E,$BD,$82,  2,$2E,  2,$2E,  2,  2,  2,$40,$10,$50,$B4,$74
		.BYTE	 $D,$52,  0,$1D,$19,$37,$2F,$23, $A,$E2,$82,  2,$9C,  2,  2,$1C,$1C,$1C,$54,$10,$94,$68,$B4
		.BYTE	 $D,$48,  0,$14,$23,$2D,$29,$2D,  0,$E3,$82, $A,$82,  7,  2, $A,  2, $A,$C0,$10,$B4,$74,$75
		.BYTE	 $D,$52,  0,$14,$24,$3C,$23,$37,$1E,$67,$83,  2,$3D,  2,  2,$3D,$3D,  2,  8,$30,$94,$84,$94
		.BYTE	 $E,$5C,  0,$14,$14,$27,$34,$28, $A,$68,$87,  2,  2,$82,$16,$16,$31,$31,$60,  0,$50,$14,$34
		.BYTE	 $E,$62,  0,$12,$19,$32,$1E,$1E, $A,$A7,$87,  2,  2,$17,$17,  2,$17,$17,$40,$10,$90,  4,$25
		.BYTE	 $E,$5F,  0,$14, $F,$43,$2D,$2A,  5,$E4,  8,$82,  2,$26,  2,  2,  2,$26,  0,$10,$50,$54,$15
		.BYTE	$10,$80,  0,$19,$20,$3C,$2E,$2A, $A,$F3,  2,$87,$A6,$28,  2,  2,$28,$26,$40,$10,$64,$68,$35
		.BYTE	 $F,$69,  0,$18,$1C,$32,$3C,$25,  0,$E2, $A,  2, $A, $A,  2, $A,  2, $A,$C0,$10,$74,$34,$75
		.BYTE	 $F,$6E,  0, $A,$19,$45,$2D,$32,  0,  4,  2,  7,  2,  2,  2,  2,  2,  2,$40,$10,$B4,$74,$36
		.BYTE	 $E,$16,  1,$12,$26,$2D,$32,$32,$FF,$E1,$38,  2,$38,  2,$38,  2,$38,  2,$54,$10,$54,$34,$75
		.BYTE	$11,$A2,  0,$1C,$2D,$41,$31,$3C, $C,$38,  7,$82,$87,  2,$17,  2,$17,  2,  0,$10,$54,$48,$35
		.BYTE	$50,$87,  0,$14,$19,$3F,$32,$23,  0,$AA,  7,$89,  2,  8,  7,  2,  8,  9,  0,$10,$74,$74,$15
		.BYTE	$1E,$72,  6,$3A,$55,$63,$55,$5F,$FF,$E9,$33,$8B,$1B,$23,$22,$28,$14,$1B,$A4,$60,$A4,$1C,$95
		.BYTE	$12,$AA,  0,$1A,$23,$4B,$34,$28,  6,$E8,  2,$88,$82,  2,  2,  8,  2,  2,$40,$10,$94,$A0,$34
		.BYTE	$13,$DC,  0,$1E,$47,$3C,$3C,$3C, $C,  9,$82,  2,$82,  2,$18,  2,$18,  2,  0,  0,$90,$80,$35
		.BYTE	$17,$2C,$10,$2F,  5,$28,$FF,  4, $C,$60,  2,  7,$13,  7,  2,$13,  7,$13,$FC,$FC,$FF,$F4,$F3
		.BYTE	$15,$29,  1,$19,$2D,$40,$2D,$46,  3,$5F,  2,$82,$87,  2,  2,  2,  2,$29,$40,$10,$40,$44,$74
		.BYTE	$11,$96,  0,$18,$14,$44,$37,$2D,  0,$88,$82,  3,  2,  2,  3,  2,  2,  2,  0,$10,$74,$74,$34
		.BYTE	$13,$64,  0,$17,$19,$37,$21,$46,  0,$ED,  7, $D,$19,$20,$20,$19,$21, $D,$A4,$20,$C0,$30,$36
		.BYTE	$16,$57,  1,$38,$30,$35,$2B,$50,$16,$F3,$80,$28,$80,$B2,$80,$A8,  0,  2,$54,$20,$A8,$A8,$73
		.BYTE	$59,$89,  0,$43,$19,$C8,$37,$78,  0,  0,  3,$10,  2,  2,  2,  2,  2,$10,$94,$60,$B4,$B4,$77
		.BYTE	$18,$78,  1,$20,$35,$4B,$32,$78,  6, $C,$A3,  7,$A3,  2,  2,$23,  3,  2,$50,$10,$54,$54,$75
		.BYTE	$12,$AF,  0,$18,$1E,$32,$2B,$2B,  0,$63,  2,  2,  2,  2,$82,$82,  2,  2,  0,$10,$74,$70,$74
		.BYTE	$13,$D2,  0,$23,$12,$17,$C8,$14, $F,  0,$87,$3B,$96,$3B,$16,$3B,$22,$16,$FC,$D0,$D8,$3C,$13
		.BYTE	$19,$20,  3,$28,$B4,$50,$3C,$50,  0,$64, $B,  2, $B,  2,  2, $B,  2, $B,$C0,$10,$B4,$78,  4
		.BYTE	$14,$EB,  0,$1C,$2A,$4F,$43,$3A, $C,$B0,$82,$23,  2,$82,  2,$23,  2,$32,$40,$10,$A4,$A4,$14
		.BYTE	$15,$31,  1,$1E,$34,$33,$32,$36,$18,$56,$82,$18,$18,$32,$32,  2,  2,$18,$80,$10,$94,$68,$36
		.BYTE	$14,$E4,  0,$1D,$25,$34,$3A,$37,  8,$60,$25,$82,$A5,$82,$A5,$82,$25,  2,$40,$10,$54,$90,$32
		.BYTE	$15,$3B,  1,$17,$2F,$50,$64,$3C,  0,$24,  3,  2,  3,  2,  2,  2,  3,  2,$80,$10,$74,$74,$34
		.BYTE	$12,$C5,  0,$1C,$23,$2F,$64,$26,  4,$68,$2E,$82,$2E,  2,  7,$2E,  2,$2E,$64,$10,$54,$54,$74
		.BYTE	$12,$B4,  0,$23,$26,$37,$32,$28,  0,$EC,$88,  2,  6,  2,  8,  6,  2,  6,$54,$50,$70,$78,$74
		.BYTE	$14,$F0,  0,$1E,$26,$41,$2D,$36,  5,$5F,$A5,$25,  2,  2,  2,  2,$25,  2,$60,$20,$94,$54,$35
		.BYTE	$16,$63,  1,$20,$46,$55,$28,$87,  0,$64,  2,  2,  2,  2,  2,  2,  2,  2,$20,$10,$70,$B4,$35
		.BYTE	$15,$22,  1,$19,$2D,$44,$96,$32,  0,$33,  3,  2,  2,  2,  2,  3,  2,  2,$10,$10,$70,$74,$35
		.BYTE	$15,  7,  1,$20,$33,$48,$32,$3C, $C,$C5,$96,  2,$82,$16,  2,$16,  2,$32,$60,$20,$94,$54,$36
		.BYTE	$17,$6F,  1,$21,$3D,$45,$3C,$64,$1C,$A7,$82,  2,$2A,  2,$2A,  2,$2A,  2,$40,$10,$60,$54,$36
		.BYTE	$17,$B8,  1,$1E,$37,$55,$28,$5A,  0,$5F,  2,  2,  2,  2,  2,  2,  2,  2,  0,$10,$74,$F8,$34
		.BYTE	$10,$78,  0,$14, $F,$43,$10,$62,  0,$20,  0,  2,  2,  2,  2,  1,  2,  2,  0,$10,$F4,$FC,$1C
		.BYTE	$17,$61,  1,$18,$3A,$4B,$37,$4B,  0,$67,  2,  2,$10,  2,  2,$10,$10,  2,$50,$10,$70,$74,$34
		.BYTE	$12,$A5,  0,$1E,$23,$3E, $A,$28,  0,$EC,  6,  2,  6,  2,  2,  6,  2,  6,$40,  0,$70,$70,$33
		.BYTE	$17,$70,  1,$17,$19,$41,$32,$50,  0,$66,$81,$3F,  5,$11,  5,$11,  2,  5,  0,$10,$F4,$78,$5C
		.BYTE	$17,$74,  1,$21,$20,$3C,$34,$3C,$10,$4C,$82,$1C,  2,  2,$9C,  2,  2,$1C,  4,$10,$54,$40,$37
		.BYTE	$19,$A2,  1,$23,$50,$5C,$96,$46,  5,$25,  2,$A5,$82,  2,$25,  2,$25,  2,$84,$10,$98,$54,$75
		.BYTE	$20,$AC,  3,$3A,$2A,$78,$37,$73,  0,$85,$82,  3,  8,  2,  2,  2,  3,  2,$54,$10,$B0,$B4,$76
		.BYTE	$18,$A1,  1,$12,$33,$51,$28,$3C,  0,$69,  2, $B, $B,  2,  2,  2, $A,  2,$C4,$10,$70,$74,$75
		.BYTE	$16,$66,  1,$25,$28,$41,$34,$5D,$12,$E2,  7,$82,  2,$82,  2,$3D,$3D,$37,$54,$20,$54,$A4,$73
		.BYTE	 $C,$CF,  1,$55,$3F,$41,$32,$46,$64,$D6,$18,$B2,$AA,$B2,$18,$32,$2A,  7,$A0,$20,$54,$64,$74
		.BYTE	$1E,$E7,  2,$32,$1F,$3F,$41,$46,$12,$8A,$82,$1A,  2,$1A,  2,  2,$1A,  2,$54,$60,$94,$94,$25
		.BYTE	$18,$95,  1,$17,$36,$55,$36,$8C,  0,$41, $D,  2, $D,  2,  2, $D,$10, $D,$34,$20,$B4,$74,$75
		.BYTE	$26,$F4,  6,$44,$4B,$78,$46,$50,  0,$E8,  3,  2, $B,  2, $B,  2, $A,  2,$40,$20,$74,$74,$74
		.BYTE	$19,$B0,  1,$28,$44,$55,$3A,$5F,  0,$E4,$BE,  2,$BE,  2,  2,$3E,  2,  2,$50,$10,$74,$74,$74
		.BYTE	$1D,$8C,  2,$19,$58,$59,$C8,$44,  0,$40,$82,  2,  2,$10,$10,  2,$10,  2,$A8,$50,$78,$B8,$74
		.BYTE	$20,$D4,  3,$3C,$55,$58,$28,$5A,$14,$94,$39,  7,$80,$B9,$87,$80,$39,  7,$54,$60,$50,$14,$36
		.BYTE	$1A,$94,  2,  0,$69,  0,  0,$F4,  4,$55,$80,  0,  0,$80,$80,$A1,$21,$21,  0,$30,$F0,$3D,$E5
		.BYTE	$1B, $B,  2,$21,$37,$8C,$5A,$6E,  0,$5F,  2,  2,  3,  2,  2,  2,  2,  2,$60,$10,$74,$74,$74
		.BYTE	$1D,$A1,  2,$43,$5F,$44,$3C,$78,$14,$E9,$87,$27,$3D,$B7,$27,$2F,$32,$2F,$68,$20,$A4,$14,$66
		.BYTE	$E4,$8C,  5,$5A,$78,$71,$C8,$78, $F,$E2,  2,$82,  2,$8B,$2E, $B,  2,$2C,$A8,$A4,$60,$68,$74
		.BYTE	$19,$B8,  1,$32,$5A,$53,$3C,$6E,  0,$64, $E,  2, $D,  2,$82, $D,  2, $D,$30,$20,$74,$74,$75
		.BYTE	$21,  6,  4,$2A,$69,$9B,$20,$FA,  0,  1,  3,  2,  2,  2,  2,  2,  3,  2,  0,$20,$70,$74,$24
		.BYTE	$21,$2E,  4,$33,$44,$48,$2F,$50,$12,$94,$8D,  2,  2, $D, $D,$1A,$1A,$1A,$34,$10,$64,$14,$35
		.BYTE	$D0, $A,  0,$46,$FF,$39,$64,$32,$FF,$A3,$26,$82,$A5,$A9,$28,$89,  0,  7,$FF,$FC,$FC,$FC,$F6
		.BYTE	$1C,$4B,  2,$37,$45,$55,$2D,$50,$18,$C2,$8D,$14,$82,$14, $D,  2,$14,$14,$40,$20,$A4,$58,$75
		.BYTE	$23,  0,  5,$24,$64,$61, $F,$C8,  0,$2B,  2,  2,  2,  2,$82,  2,  2,  2,$10,$10,$70,$74,$75
		.BYTE	$1F,$4B,  3,$4B,$3A,$5F,$3A,$4B,$12,$86,$A5,  2,$A5,$82,$A5,$82,$25,  2,$54,$60,$54,$A8,$15
		.BYTE	$62,$DF,  2,$64,$2A,$5E,$4E,$F0, $A,$8F,$82,  2,$27,$A7,$A7,$A2,$14,$20,$A4,$20,$B4,$4C,$A6
		.BYTE	$22,$A6,  4,$3A,$49,$73,$3F,$82,  0,$8E,$82,  2,$12,  2,$82,$92,  2,  2,$54,$60,$B0,$78,$56
		.BYTE	$22,$10,  4,$3B,$2A,$43,$2F,$55,$14,$D5,  2,$1F,  2,$20,  2,$1F,  2,$20,$B4,$70,$94,$54,$56
		.BYTE	$3F,$68,$1F,$32,$C8,$78,$44,$2C, $C,$1D,$8B,  2,$8B,  2,$82,$8B,$82,$8B,$C0,$3C,$74,$7D,$F0
		.BYTE	$25,$F4,  6,$1D,$3E,$8C,$28,$C3,  0,$34,  3,  2,  2,  2,  2,  2,  2,$82,$94,$64,$74,$B8,$35
		.BYTE	$2A,$70,$17,$46,$B4,$96,$3B,$C8,  0,$5F, $C,  2, $C,  2, $C,  2,  2, $C,$80,$20,$B4,$78,$75
		.BYTE	$3F,  8,  0,  7,  2,$12,  6,  6,  0,$65,  2,  2,  7,  2,  7,  2,  7,  2,  0,  0,  0,  0,$34
		.BYTE	$23,$D0,  2,$3B,$4E,$5A,$4B,$46,  0,$89,  2,$88,  2,$88,  2,  8,  8,$3C,$14,$10,$74,$74,$7C
		.BYTE	$26,$AE,  6,$50,$43,$69,$3C,$82,$1E,$55,$82,  2,$1F,  2,$10,$10,$1F,$1F,$74,$20,$C4,$6C,$A4
		.BYTE	$26,$8A,  7,$48,$69,$50,$3C,$96,$FF,$F3,$87,  2, $A,$89,$2E,$14,$3D,$33,$94,$20,$64,$64,$74
		.BYTE	$58,  8,$9D,$96, $A,$37,$FF,  6,$FF,$C9,  7,  2,  7,$17,  7,  7,$17,  7,$FC,$FC,$FF,$FC,$F4
		.BYTE	$24,$F6,  4,$2D,$30,$5F, $A,$AA,  5,$27,$82,$3F,$26,  2,  2,$3F,$26,  2,  0,$20,$D0,$F8,$56
		.BYTE	$23,$46,  5,$2F,$58,$78,$50,$73,$1E,$BC,  2,$A3,$82,$18,  2,$23,  2,$18,$94,$24,$94,$A8,$76
		.BYTE	$26,$C4,  9,$50,$69,$B4,$3C,$40, $C, $D,$82,  2,$83,$82,  2,  3,$82,$82,$80,$30,$98,$A9,$F6
		.BYTE	$28,$86,  1,$3C,$FF,$A5,$32,$D2,  0,$4A,  2,  2,  7,  2,  7,  2,  2,  2,$3F,$F0,$74,$74,$36
		.BYTE	$27,$2E,  9,$3E,$3A,$82,$41,$C8,  0,$DF,$82,  2,$82,  2, $E, $D,$8D, $E,$34,$20,$74,$74,$65
		.BYTE	$24,$36,  6,$48,$5A,$7D,$55,$78, $C,$B2,  2,$BE,  2,$1A,  2,$3E,  2,$1A,$64,$20,$90,$18,$74
		.BYTE	$26,$2A,  8,$34,$A0,$96, $A,$C2,  0,$64,$83,  7,$82,  2,  2,$82,  2,  2,$60,$10,$70,$75,$75
		.BYTE	$27,$20,  8,$3A,$82,$9B,$46,$96,  0,$E0,$83,  7,  7,  2,  3,  2,  2,  2,$44,$10,$74,$B4,$74
		.BYTE	$2B,$C4,  9,$23,$96,$C8,$5A,$5E,  0, $D,  2,  2,  2,  2,$83,  3,  2,  2,$18,$20,$74,$75,$74
		.BYTE	$2A,$DC, $A,$46,$5A,$8B,$50,$8C,$18,$BC,$82,  2,$9B,$38,  2,  2,$1B,$38,$50,$20,$A8,$B8,$B5
		.BYTE	$2B,$22, $B,$4B,$8C,$50,$96,$82,$64,$92, $D,$82,$19,$99,$30,$30,$30,$30,$A0,$20,$E4,$54,$B5
		.BYTE	$5E,$C0,  8,$96,$7D,$69,$50,$64,$35,$41,$87,$2C,$A8,$28,$28,$33,$33,$33,$94,$20,$90,$18,$74
		.BYTE	$29,$BA,  9,$3A,$5A,$73,$50,$7D,$30,$96,$87,  2,$82,  2,$95,  2,$15,$39,$74,$20,$94,$24,$E6
		.BYTE	$29,$12, $C,$4C,$4B,$89,$78,$96,  0,$69, $B, $B, $B,  2,$82,$82,  2, $B,$88,$30,$B8,$7C,$B6
		.BYTE	$29,$EA, $B,$43,$78,$87,$4E,$FA,$1B, $D,$2A,$82,$AA,  2,  2,$2A,  2,$82,$54,$60,$54,$68,$75
		.BYTE	$2A,$28, $A,$3E,$6B,$8C,$4B,$78,  0,$61, $B,$BE, $B,  2,$3E, $B,  2, $B,$94,$10,$F4,$74,$74
		.BYTE	$2B,$C6, $C,$37,$50,$64,$39,$5D,$15,$C1,$82,$20,  2,$20,  2,$20,  2,$20,$68,$38,$94,$78,$65
		.BYTE	$2C,$AC, $D,$2B,$35,$AA,$2D,$5E,  0,$DF, $D,  2, $E, $E,  2,  2, $E, $E,$38,$74,$B0,$79,$55
		.BYTE	$2C,$F4, $B,$4E,$78,$91,$3C,$A0,$32,$BC,$1E,$82,$95,$2C,$1E,  2,$15,$2C,$20,$24,$50,$18,$75
		.BYTE	$2D,$6C, $C,$63,$43,$9E,$48,$AA,$1F,$8E,  3,$82,$82,  2,$82,$82,$32,$32,$68,$68,$A4,$98,$55
		.BYTE	$2E,$1C,$25,$32,$5E,$F0,$32,$26,  0,$35,  2,  2,  2,  2,$8B,$82,$8B,$8B,$D1,$3C,$B4,$FE,$F5
		.BYTE	$3F,$A8,$2F,$48,$C2,$D2,$C8,$C2,$FF,$BC, $C,$99,  2,$19, $C,$99,  2,$99,$55,$7C,$E4,$7D,$F6
		.BYTE	$3F,$DC,$37,  0, $F,$68,  0,$84,  0,$93,  2,  2,  2,  2,  2,  2,  2,$82,  0,$3D,$FC,$BF,$F6
		.BYTE	$3F,$FF,$FF,$55,  0,$DC,$64,$84,$FF,$4B,$19,$82,$8C,$95,$AA,$82,$99,$A8,$94,$3C,$A4,$7F,$F7
		.BYTE	$3F,  0,  0,$FF,  0,$26,$2C,$FF,$FF,$41, $F,$9B,$8F,$82,$AB,$8F,$AC,$8F,$B8,$7E,$F1,$3F,$F7
		.BYTE	$3F,  0,  0,$50,  0,$40,$C8,$FF,$FF,$41,$9B, $E,  2,  2,$82,$AB,$8F,$AB,$FC,$3D,$F0,$FF,$F7
		.BYTE	$3F,  0,  0,$64,  0,$E6,$DC,$90,$1B,  0,$9E,  2,$22,$82,  2,$33,$33,$33,$3C,$FC,$FC,$FD,$F7
		.BYTE	$7F,$98,  8,$13,  0,$41,$2A,$96,  0,  0,  2,  1,  2,  2,  3,  2,  2,  2,$50,$3C,$74,$7C,$F7
		.BYTE	$3F,$C0,$12,$23,  0,$59,$28,$90,  0,  0,$82,  3,  2,$82,  2,  2,  2,$82,$50,$3C,$F4,$FD,$F7
		.BYTE	$3F,$50,  0,$14,  0,$37,$1F,$3C,  0,$80,  2,  2,  2,  2,  2,  2,  2,  2,$40,$3C,$74,$7C,$F7

; =============== S U B	R O U T	I N E =======================================
_b0_s65:
		LDA		#0
		STA		0
		STA		1
		TAY
loc_BF57:
		STA		(0),Y
		INY
		BNE		loc_BF57
		INC		1
		LDX		1
		CPX		#7
		BEQ		loc_BF74
		CPX		#1
		BNE		loc_BF57
		INC		1
		BNE		loc_BF57
		LDX		#1
loc_BF6E:
		STA		byte_6A3E,X
		INX
		BNE		loc_BF6E
loc_BF74:
		LDA		#$90
		STA		byte_6D3
		LDA		#$18
		STA		byte_6D4
		LDA		#$E
		STA		_cur_mmc_cmd
		LDA		#0
		STA		_cur_chr0_bank_prg_hi
		LDA		#$AC
		STA		byte_2A
		LDA		#$DB
		STA		byte_2B
		LDA		#$30
		STA		byte_6E0
		LDA		#$FF
		STA		byte_2D
		STA		byte_2E
		LDX		#0
loc_BF9D:
		STA		_players_pos_list,X
		INX
		CPX		#$80
		BNE		loc_BF9D

; =============== S U B	R O U T	I N E =======================================
_b0_s66:
		LDA		#$FF
		LDX		#0
loc_BFA9:
		STA		byte_6D40,X
		INX
		CPX		#$A0
		BNE		loc_BFA9
		RTS

		ECHO "bank 00 free space", [SAFE_STUB_ORG-.]

		ORG SAFE_STUB_ORG
		SAFE_STUB