
		ORG $8000

_b2_s0_ptr:
		.WORD	_b2_s0
_b2_s1_ptr:
		.WORD	_b2_s1
_b2_s2_ptr:
		.WORD	_b2_s2
_b2_s3_ptr:
		.WORD	_b2_s3
_b2_s4_ptr:
		.WORD	_b2_s4
_b2_s5_ptr:
		.WORD	_b2_s5
_b2_s6_screen_damage_shake_ptr:
		.WORD	_b2_s6_screen_damage_shake
_b2_s7_screen_spell_blink_ptr:
		.WORD	_b2_s7_screen_spell_blink
_b2_s8_screen_hit_blink_ptr:
		.WORD	_b2_s8_screen_hit_blink
_b2_s9_ptr:
		.WORD	_b2_s9
_b2_sA_ptr:
		.WORD	_b2_sA
_b2_sB_ptr:
		.WORD	_b2_sB
_b2_sC_ptr:
		.WORD	_b2_sC
_b2_sD_ptr:
		.WORD	_b2_sD
_b2_sE_ptr:
		.WORD	_b2_sE

_pak_data7C:
		.BYTE	$C8,$50,$1F,$1F,  1,  1,  7,$3F,$66,  1,  1,  7,$3F,$26,$C8,$60
		.BYTE	$D8,$D9, $C,$18,  3,  6,  1, $C,  8,  3,  2,$C8,$31,$FF,  0,  3
		.BYTE	 $F, $F,$1F,$1F,$3F,$3F,$3F,$C9,$41,$FF,$F0,$FF,  0,$40,$40,$40
		.BYTE	$C0,$C0,$E0,$E0,$3F,$7F,$7F,$7F,$C9,$51,$DF,$8F,$EF,$E0,$D8,$DE
		.BYTE	$9D,$8E,$8F,$DC,$FF,$9D,$8E,$8F,$DC,$C0,$61,$5C,$18,$78,$F8,$3E
		.BYTE	$63,$C0,$80,$5C,$18,$78,$F8,$3E,$62,$40,$80,$C8,$22,  0,$1F,$20
		.BYTE	$20,$A8,$E8,$F8,$C0,$32,$38,$1A, $E, $C, $E,  6,  4,  6,$C4,$E5
		.BYTE	$F1,$F3,$F1,$F9,$FB,$F9,$C0,$42,  7,  7,  6,  3,  3,  1,  1,  0
		.BYTE	$F8,$F8,$F8,$FC,$FC,$FE,$FE,$FF,$C0,$52,  0,  0,$40,$D0,$D9,$EE
		.BYTE	$36,  3,$FF,$FF,$DF,$DE,$DC,$EE,$36,  3,$C8,$33,$3F,$1E,$10, $D
		.BYTE	 $D,  7,$80,$C0,$E0,$E0,$F0,$F7,$C8,$43,$FF,  7,$40,$C0,$F0,$F7
		.BYTE	$38,$DB,$64,$BA,$9C,$2E,  7,$C0,$53,$30,$18,  0,$E0,$F8,$FC,$FC
		.BYTE	$67,$CF,$E3,$1B,  7,  7,  3,  3,  3,$C8,$63,$F8,$FC,$5F,$3B,$14
		.BYTE	  7, $D,$10,  7,  3,  4,  7, $D,$C8,$34,$1F,$7F,  2, $B, $C,$58
		.BYTE	$71,$E2,  6,  3,  7, $F,$1E,$FE,$C8,$44,$FF,$E0, $C,$18,$30,$FC
		.BYTE	$78,$B0,$C0,$60,$70,$38,$BC,$C8,$54,$FF,  3,$60,$F0,$CE,$F3,$7D
		.BYTE	$82,$F1,$FE,$EF,$F1,$C0,$64,$F0,$F8,$38,$CC,$B6,$CB,$61,$20,$F0
		.BYTE	$F8,$38,$CC,$B6,$CB,$61,  0,$C8,$35,$78,$F8,$B8,$E0,$18,$60,$80
		.BYTE	$1C,$F8,$E0,$80,$C8,$55,$47,  0,$80,$E6,$FD,$FF,$C8,$65,$83,  3
		.BYTE	$80,$60,$E7,$80,$60,$88,$23,$25,  3,  3,$24,$30,$C0,$44,$80,$24
		.BYTE	$2F,$E0,$F1,$44,$48,$3C,$1C, $E,  7,$A0,$E0,$78,$36,$39, $C, $C
		.BYTE	  3
_pak_data20:
		.BYTE	$C8,$10,$3F,$3F,$18,$3C,$7E,$EE,$84,$82,$10,$10,$54,$6E,$9E,$F6
		.BYTE	$C0,$20,  2, $F,$3F,$3B,$17,$1E, $E,  6, $C,$3D,$38,  2,  3,$11
		.BYTE	  9,  0,$C8,$30,  0,$C0,  6,  4,$C8,$50,$C0,$30,  2,  2,  1,  2
		.BYTE	$C8,$11,  7,  7,$1D,$3C,$7B,$10,$30,$20,$C0,$21,$7B,$F6,$F6,$FA
		.BYTE	$ED,$EF,$26,$1A,$20,$20,$80,$80,$41,$41,  1,  1,$C8,$31,$7E,$F7
		.BYTE	 $C,$13,$1F, $E,  1, $F,  7,$10,$10,  1,  6,  8,  8,$C8,$41,$1F
		.BYTE	$FF,  6,  1,  7,  4,$1F,$2F,$67,$F2, $C,  4,$33,$58,$ED,$C0,$51
		.BYTE	$6C,$FC,$EF,$7F, $C,  7,  6,$71,$93,$30,$F3,$50,$18, $C,  8,$40
		.BYTE	$C8,$61,$E0,$E0,$7E,$7C,$18,$70,$78,$18,$C8,$12,  3,$7F,$1C,$73
		.BYTE	$E7,$9E,$78,$FF,$7F,  8,$3F,$C0,$22,$CC,$EC,$FF,$7F,$7F,$5A,$40
		.BYTE	$AD,$CC, $C,  3,  0,$7F,$5A,$40,$AD,$C8,$32,$FA,$EF,$3F,$80,$98
		.BYTE	$40,$FD,$F3,$CD,$BF,$40,$7F,$9F,$3E,  2,$C0,$42,$3E,$FE,$FD,  3
		.BYTE	$B7,$B1,$30,$30,$3C,  0,  1,$10,$48,$CE,$C3,  0,$C8,$52, $B,$8E
		.BYTE	$10,$C0,$60,$E0,$40,$20,$C0,$C8,$13,  7,$17,$80,$DC,$3E,$DF, $C
		.BYTE	  8,  1,$C0,$23,$DD,$DD,$DB,$BB,$B7,$96,$8E,$2E,$91,$80,$81,  1
		.BYTE	$85,$A4,$AD,$4F,$C8,$33,$E5,$FF,$1E,$3C,  2,$7E,$BC,$BC,$BC,$B8
		.BYTE	$51,$C2,$82,$3C,$20,$C0,$43,$D8,$D8,$D8,$BC,$A4,$9E,$3C,  3,$18
		.BYTE	  0,$18,$7C,$C0,  0,$40,$F0,$C0,$53, $D,$13,$2F,$10,$17,  9,$37
		.BYTE	$7A,$41,$20,$20,  1,  9,  0,$23,$40,$C8,$63,$FC,$FC,$FC,$FE,$DD
		.BYTE	$62,$35,$1A,$F0,$98,$46,  5, $A,  4,$C8,$14,$3F,$3F,$18,$3C,$7E
		.BYTE	$77,$21,$40,  8,  8,$2A,$76,$39, $E,$C8,$24,$5F,$FC,$30,$40,$F1
		.BYTE	$F9,$7D,$AD, $E,$46,$3C,$1C,$48,$30,$C8,$34,  0,$F0,$30,$30,$30
		.BYTE	$20,$C8,$54,$18,$7C,$80,$80,$40,$C0,$80,$80,$C0,$C8,$64,$2C,$1C
		.BYTE	$C0,$C0,$80,$80,$40,$80,$88,$10,$10,$C7,$C0,$33,$13,$33,$13,$25
		.BYTE	$3F,$12
_pak_data42:
		.BYTE	$C8,$10,  7, $F, $F,$31,$4A,$B4, $E,$3B,$74,$C8,$20,$C0,$C0,$A8
		.BYTE	$40,$28,$40,$C8,$11, $F, $F,  1,$C1,$61,$31,  1,  1,$81,$41,$C9
		.BYTE	$21, $F,$FF,$E0,$13,$1B, $B,$23,  3,  3,  7,  3,  3, $B,  9,$C8
		.BYTE	$31,$80,$FF,  7,  6,  6,  6, $C, $C, $C,$18,  1,$C9,$41,  8,$F9
		.BYTE	$9F,$18, $C, $E,  5,  5,  1,  0,$10,$10,$10,$10, $E,$C8,$51,$80
		.BYTE	$E0,  1,  1,  1,  6,$C9,$12,$FF,$E7,$E7,$80,$E0,$FC,$F1,$EE,$EF
		.BYTE	$80,$E0,$FC,$F1,$EE,$EF,$C9,$22,$EF,$FF,$E0,$F7,$F7,$F7,$F6,$F7
		.BYTE	$F5,$EE,$EA,$EB,$EB,$EB,$C9,$32, $F,$FF,$C3,$EF,$2F,  7,  7,$E9
		.BYTE	$29, $D, $C, $C, $C,  4,  6,$C9,$42,  3,$8F,$9F,  7,$43,$81,$86
		.BYTE	$7D,$2B,  6,  1,  0,  0,$44,$C0,$52,$93,$B6,$DA,$D8,$B8,$50,$32
		.BYTE	$52,  0,$21,$51,$53,$32,$45,$21,$41,$C8,$62,$FC,$FC,$54,$38,$5F
		.BYTE	$2F,$24,$40,$42,$20,$50,$28,$65,$C0,$C8,$13,$1F,$1F,$80,$F0,$FE
		.BYTE	$3E,$C6,$80,$F0,$FE,$3E,$C6,$C9,$23,$FF,$FF,$C0,$F8,$FE,$F8,$26
		.BYTE	$9B,$CD,$66,$32,$11,$98,$C9,$33,$FF,$FF,  1,$FD,$8C,$CC,$C6,$C6
		.BYTE	$C6,$46,$67,$2D,$C9,$43,$80,$E7,$E5,$FE,$FE,$C2,  0,$E4,$3E,$7E
		.BYTE	$C2,$21,$1B,  0,$C9,$53,$70,$FF,$E2,$1C,$38,$78,$30,$C3,$87,  6
		.BYTE	 $C,  8, $C,  8,  0,$C8,$63,$F8,$F0,$70,$E0,$C0,$80,  8,$18,$30
		.BYTE	$60,$80,$C8,$24,$1F,$1F,$80,$C0,$C0,$E0,$E0,$80,$C0,$40,$20,$A0
		.BYTE	$C9,$34,$F8,$FF,$C3,$F0,$F0,$FB,$F7,$90,$50,$48,$28,$28,$38,$38
		.BYTE	$F0,$C8,$44,$CF,$FE,$C7,$80,  7, $F,$51,$E0,$20,$C0,$80,$86, $B
		.BYTE	$D5,$74,$C0,$54,  0,  0,$30,$70,$70,$38,$38,$1D,$38,$44,$C4,$86
		.BYTE	$86,$C3,$42,$60,$C8,$64,$E0,$C0, $F,  6,$30,$19, $F,$C8,$15,$78
		.BYTE	$FF,  1,  2,  7, $A,$10,$10,$10,$30,  1,  1,  6,  8,$C8,$25,  0
		.BYTE	$FF,$30,$30,$30,$18,$18,$18, $C, $C,$C8,$35,  3,$FF, $C,  6,  6
		.BYTE	  7,  3,  3,  6,$86,  1,  1,$C0,$45,$CE,$7C,$B8,$C0,$C0,$E3,$64
		.BYTE	$2E,  1,  2,  6,$1C,$18,  0,$80,$D2,$C0,$55,$2A,$1C,$1A,$15,$38
		.BYTE	$34,$68,$D0,$52,$64,$22,  4, $B,  4,  8,$30,$C8,$65,$FE,$BE,$80
		.BYTE	$20,$40,$20,$18,  4,$40,$E0,$B0,$58,$28,$1C,  4,$C8,$16,$70,$F0
		.BYTE	$C0,$30,$40,$A0,$C0,$50,$A0,$C8,$56,$38,$F0,$20,$20,$40,$80,$20
		.BYTE	$40,$80,$88,$18,$20,$18,$18,$14,  6,  8,  8,$88,$20,$20,$30,$70
		.BYTE	$30,$20,$A0,$40,$40
_pak_data36:
		.BYTE	$C0,$20,  0,  0,  1,  2,  1,  3,  2,  1,  3,  6, $D, $A,  9, $B
		.BYTE	 $A,  9,$C8,$30,$FF,$80,  3, $B, $C,  5,  7,  2,  7,  5, $C,$C0
		.BYTE	$40,  0,  0,  4,  2, $D,  6,  3,  1,  9,$1A,$15,$32,$2D,$36,$1B
		.BYTE	 $D,$C8,$50,$E0,  0,  6,  3,  1,$C8,$11, $F, $F,  1, $F,$7C,$13
		.BYTE	  1, $F,$7C,$93,$C0,$21, $E,  5,$42,$C0,$B1,$63,$C4,$8C,$EE,$35
		.BYTE	$5A,$CD,$B6,$6C,$D8,$B0,$C8,$31,$E3,$F3,$10,$30,$40,$C0,$60,$20
		.BYTE	$60,$C0,$80,$80,$C0,$C0,$41,$18,$88,$46,  3,$10,$A0,$63,$82,$60
		.BYTE	$B0,$58,$AC,$57,$AC,$6B,$9A,$C8,$51,$FC,$E0,$C1,  7,  8,$D1,$37
		.BYTE	$A8,$E7,$5C,$20,$C8,$12,$3F,$1F,$38, $F,  2,$C1,$80,  7,$38,$EF
		.BYTE	$32,$DD,$B6,$C8,$22,$F0,$7F,$80,  7,$3E,$F0,$C0,$C0,$40,$37,$BF
		.BYTE	$78,$C0,$C8,$42,$3F,$E7,$80,$D0,$E0,$70,$C8,$38,$10,$F0,$80,$70
		.BYTE	$C8,$38,$C8,$52,$F0,$80,$E0,$E0,$1C,$F0,$80,$C8,$13,$1F,  6,$40
		.BYTE	$E0,$C0,$20,$50,$E8,$3C,$C8,$23,$80,$F0,$1C,$FC,$D8,  8,$E0,$C8
		.BYTE	$33,  3,$1F,  4,  4,  6,$1C,$30,  2, $F,$C8,$43,$F8,$20,  8,$1A
		.BYTE	$16, $C,  4,  8,$88,  4,$1A,  0,$70,  1,  3,  1,$80, $C,$1A,$D9
		.BYTE	$AD,$B4,$AB,$DC,$78,$30,$10,$19,$3D,$34,$20,  0,  3,  7,  2,$88
		.BYTE	$14,$1A,$CF,$F8,$6F,$2F,$DF,$C6,  2,$E0,$20,$38,$DC,$EE,$EE,$88
		.BYTE	 $C,$12,  0, $F,  1,$11,$3B,$6E,$88,$14,$12,  1,$7F,  2,$1E,$FC
		.BYTE	$F8,$F0,$3C,$DD,$C0,$88,$14,$22,$FF,  0,$EE,$77,$77,$7B,$3B,$3D
		.BYTE	$3E,$3F,$88,$14,$2A,$F0,  0,$1F,$1F, $F,  3,$88,$1C,$22,$1F,  0
		.BYTE	$80,$C0,$F0,$F8,$F8,$88,$1C,$2A,$F0,  0,$F8,$F8,$F0,$E0
_pak_data57:
		.BYTE	$48,$40,$C8,$30,  6,$3E,  1,  1,  1,  1,  1,  1,  1,$C8,$21,$1F
		.BYTE	$3F,  1,  7,$1F,$7F,$7F,$FF,  2,  5,  7,  8,$11,$C0,$31,$FB,$F6
		.BYTE	$E5,$E5,$CF,$9F,$9F,$DF,$26,$4D,$5B,$9B,$BE,$F6,$F6,$F4,$C0,$41
		.BYTE	$DF,$EF,$CF,$CD,$CD,$EA,$F2,$F9,$74,$BC,$7E,$7E,$3E,$3F,$9F,$FF
		.BYTE	$C0,$51,$FD,$6E,$77,$33,$3B,$1D, $F,  1,$FF,$7F,$7F,$3F,$3F,$1F
		.BYTE	 $F,  1,$C9,$22,$FF,$FF,$80,$3F,  0,  0, $E,$3B,$F1,  8,  0,  3
		.BYTE	$C0,$32,$FF,$FF,$E3,$EF,$DF,$BF,$FF,$DE,$2C,$C0,$9C,$30,$60,$C0
		.BYTE	  0,  0,$C8,$42,$C3,$FF,$C0,$E0,$E0,$F0,$A1,$DF,$40,$60,$1E,  1
		.BYTE	$80,$80,$C9,$52,$FF,$E0,$FF,$38,$8F,$47,$E0,$78, $F,$87,$FC,$C0
		.BYTE	$F0,$F8,$4A,$63,$C8,$62,$C0,$C0,$7F,$3F,$7F,$3F,$C9,$23,$FF,$FF
		.BYTE	$80,$E0,  0,  4,  2,$1C,$82,$41,$F0,$18,$C0,$33,$FF,$FF,$FF,$EE
		.BYTE	$F7,$E7,$C7,$85,  6,  1,  0,  1,  0,$10,$20,$40,$C8,$43,  1,$FF
		.BYTE	  2,  6, $C,$F8,$E1,  1,  3,  6,  1,$C9,$53,$FF,$C0,$FF,$1C,$E2
		.BYTE	$8C,$78,$1F,$F3,$E7,$8F,  3,$1F,$C8,$24,  7,$3F,$80,$E0,$E0,$F0
		.BYTE	$F0,$F0,$40,$A0,$90,$C0,$34,$D8,$DC,$EC,$6E, $E,$A4,$D4,$50,$60
		.BYTE	$60,$30,$B0,$F0,$7A,$3A,$3F,$C0,$44,$D0,$F8,$EC,$EC,$ED,$6D,$5A
		.BYTE	$3A,$2F, $F,$1F,$3F,$3F,$BF,$FE,$FE,$C9,$54,$C0,$F9,$F9,$54,$9C
		.BYTE	$38,$F0,$E0,$80,$FC,$FC,$F8,$F0,$E0,$80,$88,$10,$21,$40,$65, $E
		.BYTE	  6,  5,  1,  1,$88,$18,$21,$80,$BB,$20,  4,$10,$62,  8,$A0,$40
		.BYTE	$88,$18,$19,  0,  3,$10,$30
_pak_data1E:
		.BYTE	$C8,  0,  0,$FF,$78,$F6,$DE,$3F, $B,  7,  6,  7,$C8,$10,  3,$FF
		.BYTE	  6,  6, $C, $E, $E,$1C, $C,  4,$10,$10,$C9,$20,$30,$FF,$E0,$18
		.BYTE	$18,  8,$20,$20,$20,$40,$40,  0,$40,$40,$C8,$30,$F8,$FF,$18, $D
		.BYTE	  2,  1,  1,  7, $D,$1F,$40,$30,$28,$1C,  8,$C8,$40,  1,$FF,$3F
		.BYTE	$3F,$3F,$7F,$7F,$3C,$7B,$3F,$40,$C8,$50,$FF,$E0,$1F,$1F,  7,$40
		.BYTE	$20,$28,$1B, $F,$10,$1F, $F,$C8,$60,$E0,$60, $C,  6,$1B, $F,  6
		.BYTE	$C8,$21,  0,$FF,  3,  7,$1F,$3F,$17,$7D,$AB,$7B,$C8,$31,  1,$FF
		.BYTE	$F9,$7B,$FB,$F9,$7B,$FD,$FC,$F9,  4,$C8,$41,$F8,$F7,$F8,$F0,$E0
		.BYTE	$80,$F8,$F4,$FC,  6, $E,$1A,$7F,  2,$C8,$51,$FF,$F0,$F8,$FC,$F8
		.BYTE	$F0,  2,  2,  6, $E,$BD,$F6,$D8,  4,$C8,$61,$FC,$7C,  2,$D9,$6C
		.BYTE	  1,  1,$FC,$6A,$D9,$6C,  1,  1,$C8,$12,  0,  3,$7E,$FF,$C8,$22
		.BYTE	  0,$FF,$FF,$FF,$FF,$FF,$FE,$FF,$FF,$FF,$C8,$32,  0,$FF,$FF,$FF
		.BYTE	$FF,$FF,$FF,$FF,$FF,$FF,$C8,$42,$2F,$FF,$FF,$BF,$DF,$5F,$5F,$1F
		.BYTE	$3F,$3F,$20,$20,$40,$C0,$80,$C9,$52,$1F,$FF,$B8,$3F,$3F,$3F, $F
		.BYTE	$C0,$C0,$40,$C0,$20,$60,$20,$60,$C0,$62,$1F, $F,  7,  6,$60,$ED
		.BYTE	$DB,  0,$A0,$F0,$F0,$D8,$75,$ED,$DB,  0,$C8,$13,  1,$1F,$36,$CB
		.BYTE	$35,$DF,$7F,$20,$C0,$23,$BF,$BF,$3F,$AF,$D7,$97,$D7,$DF,$30,$30
		.BYTE	$38,$28,$14,$15,$11,$19,$C0,$33,$9D,$DF,$DD,$BF,$3F,$9D,$8C,  6
		.BYTE	  1,  1,  0,  1,  3,$25,$14,$3E,$C0,$43,$86,$82,$81,$41,$C1,$80
		.BYTE	$C0,$40,$2E,$1A,  7,  1, $D,$1A, $D,$1F,$C9,$53,$E0,$FF,$25,$C0
		.BYTE	$C0,$C0, $F, $F, $F, $F,  0,  6, $F, $E,$C9,$63,$B0,$F3,$F3,$E0
		.BYTE	$A3,$CD,$A6,$60,  0,  1, $F, $D,$26,$60,  0,$C8,$14,  0, $F,$40
		.BYTE	$A0,$F4,$FB,$C0,$24,$DD,$FD,$EE,$FE,$F6,$FF,$7F,$8D,$20,  0,$10
		.BYTE	  0,$C8,$F6,$7F,$8D,$C0,$34,$81,$CD,$B3,$AD,$DA,$E1,$FB,$3F,$80
		.BYTE	$CC,$B2,$AD,$DA,$E1,$FB,$3F,$C8,$44, $F, $E,$80,$C2,$7C,$80,$C2
		.BYTE	$7D,  3,$C8,$54,$F0,  0,$FE,$FF,$FC,$C1,$C8,$64,$E0,$E0,$C0,$60
		.BYTE	$80,$C0,$60,$80,$C8,$25,  0,$FF,$E0,$B0,$E8,$F8,$FC,$3C,$5C,$5E
		.BYTE	$C8,$35,$1F,$FF,$6E,$AE,$AC,$96,$96,$84,$96,  6,$20,$A0,$A0,$A0
		.BYTE	$20,$C9,$45, $F,$FF,$C1,$16,$17,$1F,$60,$60,$E0,$E0,$E0,$D0,$50
		.BYTE	$A0,$C9,$55,$1F,$FF,  7, $F, $F, $F,$A0,$40,$E0,$60,$E0,$B0,$50
		.BYTE	$30,$C0,$65,  7,  7,  3,$41,$F0,$C8,$6E,$1D,$10,  8,$3C,$7E,$FF
		.BYTE	$CD,$6E,$1D,$C8,$46,  0,  3,$80,$80,$C8,$56,  0,$FF,$40,$C0,$A0
		.BYTE	$E0,$F0,$E0,$F0,$E0,$C8,$66,$1F,$FF,$F0,$D0,$E0,$50,$28,$B0,$D0
		.BYTE	$C0,$30,$E8,$B0,$D0,$C0,$88,$1F,$17,  0,$41,$19,$80,$88,$1F,$1F
		.BYTE	$3C,$FE,$20,$1A,$94,$42,$41,$2B,$1E,$28,$3C,$3E,$14,$88,$27,$1F
		.BYTE	  0,$E0,$40,$80,$80
_pak_data3A:
		.BYTE	$C0,$40,  3,  0,  6,$1C,$3A, $D,$15,$1F,  3,  0,  6,$1C,$3A, $D
		.BYTE	$15,$1F,$C8,$50,$FC,$FC,$37,$2D, $D, $C,  8,  8,$37,$2D, $D, $C
		.BYTE	  8,  8,$C8,$11,$3F,  0,  1,  1,  1,  1,  3,  3,$C9,$21,  1,$FF
		.BYTE	  0,  3,  3,$83,$43,$27,$17,$17, $B,$C0,$31,  1,  0,  1,  0,  8
		.BYTE	$10,$20,$20, $B,  4,$15,$14,$3A,$32,$62,$62,$C9,$41,$40,$FF,$2E
		.BYTE	  0,$C0,$80,$C0,$42,$C2,$82,$42,$C4,$84,$C4,$44,$C8,$51,$FF,$80
		.BYTE	$40,$44,  4,  8,  8,  8,  8,  8,  8,$C8,$61,$F8,  0,  8,  8,  4
		.BYTE	  4,  3,$C8,  2,$7F,$1F,  3,  6,  8,$10,$30,  1,  7,$1F,$3F,$7F
		.BYTE	$7F,$FC,$C9,$12,$C0,$F0,$FA,$20,$60,$40,$40,$80,$80,$F8,$F0,$E0
		.BYTE	$E0,$C9,$22,$80,  2,$AA,  0,  0,  0,  0,  0,$C8,$32,$3F,$32,  3
		.BYTE	  1,  1,  3,  1,  2,  2,  5,  6,$C8,$42,$F7,  7,$1F,  7,  1,  7
		.BYTE	  7,  3,  3,$1F,  7,  1,$C8,$52,$6C,$6C,  3,$1F,  1,  3,  3,$1F
		.BYTE	  1,  3,$C8,$62,  4,  0,$FF,$C8,  3,$7E,$38,$54,$FF,  1,$FF,$FF
		.BYTE	$FF,$FF,$FF,  7,$C0,$13,  0,  0,  1,  3,  4,  4,  8, $C,$33,$2F
		.BYTE	$1F,$3F,$3F,$3F,$7F,$7E,$C0,$23,  8, $C, $C,  8,  4,  6,$C0,$CC
		.BYTE	$7E,$7E,$7F,$7F,$3F,$3F,$D0,$CC,$C0,$33,$C7,$E3,$60,$E6,$73,$31
		.BYTE	$B8,$F8,$D7,$EB,$68,$E6,$73,$35,$BA,$FA,$C8,$43,$FF,$E3,$1C, $D
		.BYTE	$10,$C0,$80,$1C,$ED,$D0,$EE,$DF,$29,$D0,$B0,$C0,$53,  0,$80,$D1
		.BYTE	$30,$B8,$B8,$38,$1C,$38,$AC,$C4,  6,$83,$82,  3,  0,$C8,$63,$3C
		.BYTE	$88,  6,  1,  3, $E,$70,$80,$C8,  4,$FF,$1E,$80,$E0,$60,$20, $C
		.BYTE	 $E,$C5,$F2,$F7,$FB,$FB,  1,$C9,$14,$FF,$83,$FF,  0,  0,$F8,$4E
		.BYTE	  2,  1,  3,$11,$FE, $F,  7,$C0,$24,  3,$13,$21,  3,  2, $E,$CC
		.BYTE	$D8,  7,  7, $F,$EF,$DF,$3F,$DF,$DF,$C9,$34,$C0,$F0,$18,$C4,$D0
		.BYTE	$DD,$DB,$DB,$D1,$C9,$44,  2,$FC,$FC,$C0,$24, $C,$18,  9,  7,$C0
		.BYTE	$24,$CC,$58,$89,  7,$C8,$54,$1F,$70,  8,$98,$C0,  4,$38,$F7,$E6
		.BYTE	$EB,$C8,$64,$F0,$3F,  1,  9,$88,$C2,$7C,$AA,$3F,$DA,$94,$20,$C8
		.BYTE	  5,$FF,$98,$40,  4,  4,$40,$60,$A0,$E4,$5C,$78,$40,$40,$C8,$15
		.BYTE	$FF,$85,$20,$20,$10,$20,$80,$80,$C0,$C0,$C0,$E0,$E0,$C8,$25,$FF
		.BYTE	$52,$10,$10,$20,$E0,$E0,$E0,$E0,$E0,$C0,$C0,$40,$C8,$35,$FF,  0
		.BYTE	$99,$FD,$FA,$CA,$14,$14,$14,$2A,$C8,$45,$FF,$18,$80,$40,$6B,$E9
		.BYTE	$A8,$A8,$48,  4,  4,  4,$C8,$55,$FF,  0,  4,  4,  2,  2,  2,  2
		.BYTE	$82,$44,$C8,$65,$C0,  0,$A4,$98,$C8,$26,$1F,  0,$18,$20,$40,$80
		.BYTE	$80,$C8,$46,$40,$40,$C0,$C0,$88,$1D,$24,  0,$FC,  4,  6,$D7,$F3
		.BYTE	$7A,  8,$88,$29,$36,$FF, $F,  4,  2,  3,  3,$80,$60,$3E,$1F, $F
		.BYTE	$17, $F,$1F,$88,$29,$3E,$FE,$F0,  7,  7,  7,  3, $F,$1F,$1F,$3F
		.BYTE	$3F,$17, $B,$88,$31,$36,$1F,  1,$80,$A0,$D0,$D0,$F8,$F8,$88,$31
		.BYTE	$3E,$FE,$F0,$80,$C0,$C0,$80,$F8,$F0,$F8,$F8,$F8,$F0,$C0
_pak_data4:
		.BYTE	$4A,$23,$C8,$20,$3F,  3,  7, $F,$78,$FE,$FF,$FF,$F8,$72,$4B,$33
		.BYTE	$C9,$30, $F,$F1,$1F,  7,  0,  0,  0,  0,$37,$37,$12,$18,$1F,$4A
		.BYTE	$43,$C8,$40,$FF,$20,  1,$1F, $C,  2,  7,  3,  1,  7,  6,$C0,$21
		.BYTE	  8,$34,$64,  2,  2,  3,  7,$87,  8,$34,$64,  2,$82,$C0,$E0,$70
		.BYTE	$C0,$31,$85,$88,$88, $C,$18,$10,  0,  0,$70,$60,$60,$E0,$C0,$C0
		.BYTE	$E0,$D0,$C8,$41,$FE,$F0,  1,$E1,$E0,$C0,$31,$D1,$D8,$38,$F0,$F0
		.BYTE	$60,$C9,$22,$20,$E7,$E7,  8,$16,$13,$E0,$F0,$F1,  8,$16,$13,  1
		.BYTE	  3,  6,$C0,$32,$D1,$89,  9,$18, $C,  4,  0,  0,  6,  2,  2,  3
		.BYTE	  1,  1,  3,  3,$C8,$42,$FE,$F0,$40,$C7,  7,  3,$44,$C3, $B,$1C
		.BYTE	 $F, $F,  6, $A,  9,$18,$88,$10,$18, $E,$62,$20,$60,$A0,$A0,$F0
		.BYTE	  8, $A,  9,$20,$88,$10,$20,$F0,$60,$20,$80,$10,$10,$20,$C0
_pak_data2:
		.BYTE	$C8,$30,  3,  3,$3E,$41,$3E,$41,$C8,$40,  0,$FC,$3E,$3F,$1F,  7
		.BYTE	  3,  1,$C9,$50,  5,$E1,$E1,  1,  2,  2,  6,  1,  2,  2,  6,$C8
		.BYTE	$60,$C0,$FC,  2,  1,  2, $F,$17, $A,  2,  1,$C8,$31,  3,  3,  1
		.BYTE	$C3,  1,$C3,$C0,$41,$33,$CD,$F6,$FB,$BD,$ED,$F5,$3B,$33, $D,  6
		.BYTE	  3,  1,  1,  1,  3,$C9,$51,$ED,$CB,$FB,$47,$F6,$EC,$EC,$EE,$F6
		.BYTE	$FB,$47,$F6,$EE,$F2,$F8,$C8,$61,$F0,$FE,$FC,$72,$6D,$3B,$D4, $E
		.BYTE	$15,$FC,$72,$68,$18,$C8,$32,$DF,  3,$83,$C7,$10,$10,$10,$10,$28
		.BYTE	$BB,$D7,$C9,$42,$83,$FF,$3A,$C6,  1,$C7,  1,$AB,$BB,$D6,$29,$FF
		.BYTE	$93,$6D,$BB,$C0,$52,$C7,$7C,$38,$10,$10,$39,$7C,$FF,$C7,$7C,$BB
		.BYTE	$83,$82,  1,  0,  0,$C8,$62,  0,$FA,$D6,$EE,$6D,$93,$FE,  1,$C8
		.BYTE	$33,  1,  1,$87,$87,$C8,$43,$F1,$FF,$98,$67,$DF,$BF,$7B,$6F,$5E
		.BYTE	$B8,$98,$60,$C0,$80,$80,$C9,$53,$6F,$EB,$EB,$C5,$DE,$6E,$EF,$DF
		.BYTE	$BE,$C5,$DE,$6E,$EF,$9F,$3E,$C8,$63,$F0,$FE,$7E,$9D,$6C,$B9,$57
		.BYTE	$E0,$50,$7E,$9D,$2C,$30,$C8,$34,  3,  3,$F8,  4,$F8,  4,$C8,$44
		.BYTE	  0,$F8,$F8,$F8,$F0,$C0,$80,$C9,$54,$40,$E1,$E1,  0,$80,$80,$C0
		.BYTE	  0,$80,$80,$C0,$C8,$64,$80,$BC,$80,$80,$E0,$D0,$A0,$80,$88,$10
		.BYTE	$28,$18,  0,$44,$44
_pak_data2C:
		.BYTE	$4A,$25,$C8,$20,$7E,$7E,  2,  7, $B, $C,$18,$30,  2,  7, $B, $C
		.BYTE	$18,$30,$4A,$55,$C8,$50,  0,$FF,  1,  3,  7, $F, $F, $F,  5,  3
		.BYTE	$42,$24,$C0,$21,$D0,$EE,$5D,$3D,$1B,$69,$70,$68,$D0,$EE,$5D,$3D
		.BYTE	$1B,$69,$76,$6A,$42,$34,$C0,$31,$59,$36,$37, $E,  1,  1,  2,  1
		.BYTE	$59,$36,$37, $E,$30,$3C,$58,$7C,$42,$44,$C0,$41,  3,  2,  2,  1
		.BYTE	  1,  1,  0,  0,$38,$78,$58,$7C,$3C,$7C,$2E, $E,$4A,$54,$C8,$51
		.BYTE	$C7,$FF,$B0,$F8,$F8,$FF,$EC,$F4,$F8,$B0,  7,  3,  1,  3,  2,$C8
		.BYTE	$12,$1F,  0,  4,  2,  3, $F,$1F,$4B,$23,$C9,$22,$70,$F6,$F6,  0
		.BYTE	$E0,$D0,$B8,$60,$E0,$1F,$EF,$D4,$B8,$60,$E0,$C0,$32,$70,$A0,$40
		.BYTE	$E0,$E0,$C0,$C2,$C0,$70,$A8,$1C,  6,  3,$10,$12,$10,$C9,$42,$F0
		.BYTE	$FF,$87,$60,$7B,$FB,$DC,  9,  3,  7,  7,  4,  0,  0,  0,$4A,$53
		.BYTE	$C8,$52,$1F,$F8,$5F,$2F,$CB,  5,  1,$30,$F8,$FE,$FF,$FF,$4A,$63
		.BYTE	$C8,$62,$F0,  0,$FB,$5F,$2B,  5,$C8,$13,$1F,  0,$60,$D0,$E0,$F0
		.BYTE	$F8,$C0,$33, $E,  5,  2,  7,  7,  3,$43,  2, $E,$15,$38,$E0,$C0
		.BYTE	  8,$48,  8,$C9,$43, $F,$FF,$87,  7,$1E,$1F,$3B,$90,$C0,$E0,$E0
		.BYTE	$20,  0,  0,  0, $A,$20,$30,$88,  8,$30,$1E,$FE, $C,$1F,$1E,$1E
		.BYTE	$7F,$DC,$30,$18,$7F,$DC,$30,$88,$14,$13,  0,$FF,$2C,$7A,$FF,$BD
		.BYTE	$7E,$76,$2C,$10,$88,$14,$1B,$70,$2C,$18,$99,$66,$81,$C3,$42
_pak_data87:
		.BYTE	$C8,$40,  6,  3,  1,$3F,  3,$3E,$C8,$50,$2F,$9D, $E,  7, $B,  1
		.BYTE	  1,  8,  7,  7,  3,  1,$C8,$21,  7,  7,  3,  3,$E7,  3,$3F,$7F
		.BYTE	$C8,$31,$A0,$E0,$7F,$1E,  1,$1E,  1,$C8,$41,$1C, $F,  1,$1F,$FC
		.BYTE	$C1,  3,$3E,$E0,$C8,$51,$F7,$8F, $E,$80,$C0,$E8,$94, $E,  6,  3
		.BYTE	  1,$80,$C0,$C0,$C9,$61,  1,$F1,$FD,$96,$45, $A,  5,  7,  0,  0
		.BYTE	$B4,$6C, $A,  4,  0,$C8,$71,$F0,$F0,  3,  1,$63,$7E,  4,$1F,$7F
		.BYTE	$7E,$C0,$12,$1E, $F,$3F,$7F,$5F,$BF,$7F,$36,$1E, $F,$3D,$7E,$5F
		.BYTE	$BF,$7F,$36,$C8,$22,$A7,$A7,$13,  7,$B8,$98,$D0,$13,  2,$B8,$D0
		.BYTE	$80,$C0,$32,$90,$68,$95, $B,$1C,$76,$7E,$3F,  0,$60,$F1,$F8,$7C
		.BYTE	$7E,$7E,$3C,$C8,$42,$77,$BF,$3C,  1,$1F,$FC,$C3,$2C,$F6,  3,$3E
		.BYTE	$E0,  3, $C,$63,$C0,$52,$74,$96,  6,  6,$2B,$9B,$45,$3A,$13,$83
		.BYTE	$63,$F3,$F9,$D9,$64,$38,$C0,$62, $A,  2,$E1,$E0,$70,$40,$80,$E0
		.BYTE	  9,  1,$60,$E0,$F0,$D0,$D8,$E8,$C8,$72,$E0,$E0,$74,$A0,$80,$74
		.BYTE	$2C,$80,$C9,$13,$FE,$F9,$F9,$D0,$E8,$FA,$FC,$FC,$DE,$D0,$E8,$FA
		.BYTE	$6C,$FC,$DE,$C8,$23,$AE,$AF,$64,$70,  1, $B, $D,  4,$64,$20,  1
		.BYTE	  9, $C,$C0,$33,  5, $B,$D7,$66,$81,$80,$A4,$40,  1,  3,$C7, $E
		.BYTE	$1C,$3D,$3C,  3,$C0,$43,  1,$1F,$FC,$C3,$3C,$E0,$19,$77,$3E,$E0
		.BYTE	  0,  3,$3C,$E3,$1B,$E6,$C9,$53,$E0, $F,$FF,$36,$31,$36,$71,$6E
		.BYTE	$E1,$C0,$20,$CE,$C7, $D,  3,$C9,$63,  1,$FC,$FC,$68,$E0,$C0,$80
		.BYTE	  0,  2,$CC,$C0,$80,  0,  0,  2,$C8,$24,$3C,$3E,$22,$C7,$7E,$F8
		.BYTE	$C0,$3E,$FE,$F8,$C0,$C0,$34,$C0,$C0,$E0,$60,$A0,$40,$20,$10,$80
		.BYTE	$80,$C0,$40,$20,$80,$40,$A0,$C9,$44,$10,$BD,$EE,$90,$C8,  8,$40
		.BYTE	$E0,$F0,$20,$30,  0,$C0,$E0,  0,$C0,$54,$E8,$FC,$7C,$84,$DA,$1F
		.BYTE	 $F,  7,$E8,$7C,  4,$80,$5A, $F,$E7,  3,$C8,$64,  0,$80,  3,$C8
		.BYTE	$74,$F8,$B8,$80,$40,$20,$10,$80,$80,$C0,$60,$10,$48,$76,$C8,$75
		.BYTE	  0,  0,$88,$10, $A,  5,  0,  9,$28,$88,$18, $A,  7,  1, $A,$20
		.BYTE	$80,$80,$88,$10,$12,$F7,$A0,  8,  1,$20,$17,  6,  2,  5,  4,  2
		.BYTE	$88,$18,$12,$EC,$F7, $A,$74,$50,$20,$90,$10,$20,$80,$80,$A0,$80
		.BYTE	$40,$88,  9,$1A,$7F,$F9,$40, $C,$2E,$5A,$50,  5,$70,$D0,$A0,$84
		.BYTE	$25,$A5,$50,$88,  7,$22,  1,$81,$16,$18,$E0,$88,  8,$2A,$84,$F0
		.BYTE	$18,$7C,$1E,  6,$E0,  1,$88,$10,$2A,  3,  4,$80,$80,$40,$88,$28
		.BYTE	$15,$7F,$BB,$80,$30,  8,$80,  2,  2,$E0,$C0,$F0,$7C,$4C,$B4,$DC
		.BYTE	$88,$28,$1D,$C0,$E0,$16,$3C,$60,$C8,$80,$88,$20,$15,$63,$F8,  1
		.BYTE	  6,$3E,  7,$19,  1,  1,  1,  7,$88,$20,$1D,$D0,$60,  8,  4, $A
		.BYTE	  2,  3,$88,$1A,$30,$7F,$F8,  3, $E,$3E, $C,  4,  1,  1,  3,  3
		.BYTE	  3,  1,  1,$88,$22,$30,$7F,$E0,$E0,$10,  4,$E0,$F8,$FC,$FE,$FE
		.BYTE	$FF,$FF,$88,$22,$38,$E0,$F8,  1,  1,$43,$3E,$1C,$FE,$FE,$3C
_pak_data_banks_list:
		.BYTE	$D7,$EF,$FF,$DD,$77,$F6,$DD,$DF,$DF,$3F,$F6,$EF,$5E,$FF,$EF,$F7
		.BYTE	$FE,$E0
_pak_data_lib:
		.BYTE	  4
		.WORD	_pak_data0
		.WORD	_pak_param0
		.BYTE	$13
		.WORD	_pak_data1
		.WORD	_pak_param1
		.BYTE	$15
		.WORD	_pak_data2
		.WORD	_pak_param2
		.BYTE	$13
		.WORD	_pak_data3
		.WORD	_pak_param3
		.BYTE	$B
		.WORD	_pak_data4
		.WORD	_pak_param4
		.BYTE	$17
		.WORD	_pak_data5
		.WORD	_pak_param5
		.BYTE	  6
		.WORD	_pak_data6
		.WORD	_pak_param6
		.BYTE	$F
		.WORD	_pak_data7
		.WORD	_pak_param7
		.BYTE	$B
		.WORD	_pak_data8
		.WORD	_pak_param8
		.BYTE	  6
		.WORD	_pak_data9
		.WORD	_pak_param9
		.BYTE	$13
		.WORD	_pak_data3
		.WORD	_pak_paramA
		.BYTE	$15
		.WORD	_pak_data2
		.WORD	_pak_paramB
		.BYTE	$17
		.WORD	_pak_data5
		.WORD	_pak_paramC
		.BYTE	$16
		.WORD	_pak_dataD
		.WORD	_pak_paramD
		.BYTE	$11
		.WORD	_pak_dataE
		.WORD	_pak_paramE
		.BYTE	$14
		.WORD	_pak_dataF
		.WORD	_pak_paramF
		.BYTE	$B
		.WORD	_pak_data8
		.WORD	_pak_param10
		.BYTE	$F
		.WORD	_pak_data11
		.WORD	_pak_param11
		.BYTE	$10
		.WORD	_pak_data12
		.WORD	_pak_param12
		.BYTE	$13
		.WORD	_pak_data13
		.WORD	_pak_param13
		.BYTE	$16
		.WORD	_pak_dataD
		.WORD	_pak_param14
		.BYTE	$13
		.WORD	_pak_data1
		.WORD	_pak_param15
		.BYTE	$14
		.WORD	_pak_dataF
		.WORD	_pak_param16
		.BYTE	$13
		.WORD	_pak_data13
		.WORD	_pak_param17
		.BYTE	$10
		.WORD	_pak_data18
		.WORD	_pak_param18
		.BYTE	$11
		.WORD	_pak_dataE
		.WORD	_pak_param19
		.BYTE	$B
		.WORD	_pak_data4
		.WORD	_pak_param1A
		.BYTE	$19
		.WORD	_pak_data1B
		.WORD	_pak_param1B
		.BYTE	$13
		.WORD	_pak_data1C
		.WORD	_pak_param1C
		.BYTE	$17
		.WORD	_pak_data5
		.WORD	_pak_param1D
		.BYTE	$29
		.WORD	_pak_data1E
		.WORD	_pak_param1E
		.BYTE	$11
		.WORD	_pak_data1F
		.WORD	_pak_param1F
		.BYTE	$1B
		.WORD	_pak_data20
		.WORD	_pak_param20
		.BYTE	$F
		.WORD	_pak_data11
		.WORD	_pak_param21
		.BYTE	$12
		.WORD	_pak_data22
		.WORD	_pak_param22
		.BYTE	$16
		.WORD	_pak_dataD
		.WORD	_pak_param23
		.BYTE	$1B
		.WORD	_pak_data20
		.WORD	_pak_param24
		.BYTE	$13
		.WORD	_pak_data13
		.WORD	_pak_param25
		.BYTE	$B
		.WORD	_pak_data8
		.WORD	_pak_param26
		.BYTE	$14
		.WORD	_pak_dataF
		.WORD	_pak_param27
		.BYTE	$12
		.WORD	_pak_data22
		.WORD	_pak_param28
		.BYTE	$10
		.WORD	_pak_data12
		.WORD	_pak_param29
		.BYTE	$13
		.WORD	_pak_data3
		.WORD	_pak_param2A
		.BYTE	  6
		.WORD	_pak_data9
		.WORD	_pak_param2B
		.BYTE	$12
		.WORD	_pak_data2C
		.WORD	_pak_param2C
		.BYTE	$13
		.WORD	_pak_data1C
		.WORD	_pak_param2D
		.BYTE	$F
		.WORD	_pak_data7
		.WORD	_pak_param2E
		.BYTE	$29
		.WORD	_pak_data1E
		.WORD	_pak_param2F
		.BYTE	$20
		.WORD	_pak_data30
		.WORD	_pak_param30
		.BYTE	  4
		.WORD	_pak_data0
		.WORD	_pak_param31
		.BYTE	$12
		.WORD	_pak_data2C
		.WORD	_pak_param32
		.BYTE	$2B
		.WORD	_pak_data33
		.WORD	_pak_param33
		.BYTE	$15
		.WORD	_pak_data34
		.WORD	_pak_param34
		.BYTE	$12
		.WORD	_pak_data22
		.WORD	_pak_param35
		.BYTE	$1A
		.WORD	_pak_data36
		.WORD	_pak_param36
		.BYTE	$2B
		.WORD	_pak_data33
		.WORD	_pak_param37
		.BYTE	$1C
		.WORD	_pak_data38
		.WORD	_pak_param38
		.BYTE	  8
		.WORD	_pak_data39
		.WORD	_pak_param39
		.BYTE	$27
		.WORD	_pak_data3A
		.WORD	_pak_param3A
		.BYTE	$11
		.WORD	_pak_dataE
		.WORD	_pak_param3B
		.BYTE	$1C
		.WORD	_pak_data3C
		.WORD	_pak_param3C
		.BYTE	$1C
		.WORD	_pak_data38
		.WORD	_pak_param3D
		.BYTE	$19
		.WORD	_pak_data1B
		.WORD	_pak_param3E
		.BYTE	  8
		.WORD	_pak_data39
		.WORD	_pak_param3F
		.BYTE	  6
		.WORD	_pak_data9
		.WORD	_pak_param40
		.BYTE	$13
		.WORD	_pak_data41
		.WORD	_pak_param41
		.BYTE	$22
		.WORD	_pak_data42
		.WORD	_pak_param42
		.BYTE	$F
		.WORD	_pak_data11
		.WORD	_pak_param43
		.BYTE	$13
		.WORD	_pak_data41
		.WORD	_pak_param44
		.BYTE	$20
		.WORD	_pak_data30
		.WORD	_pak_param45
		.BYTE	$1C
		.WORD	_pak_data46
		.WORD	_pak_param46
		.BYTE	$1D
		.WORD	_pak_data47
		.WORD	_pak_param47
		.BYTE	$12
		.WORD	_pak_data2C
		.WORD	_pak_param48
		.BYTE	$B
		.WORD	_pak_data4
		.WORD	_pak_param49
		.BYTE	$1D
		.WORD	_pak_data47
		.WORD	_pak_param4A
		.BYTE	$1C
		.WORD	_pak_data38
		.WORD	_pak_param4B
		.BYTE	$19
		.WORD	_pak_data1B
		.WORD	_pak_param4C
		.BYTE	$2B
		.WORD	_pak_data33
		.WORD	_pak_param4D
		.BYTE	$1C
		.WORD	_pak_data4E
		.WORD	_pak_param4E
		.BYTE	$1B
		.WORD	_pak_data4F
		.WORD	_pak_param4F
		.BYTE	$1C
		.WORD	_pak_data3C
		.WORD	_pak_param50
		.BYTE	$10
		.WORD	_pak_data18
		.WORD	_pak_param51
		.BYTE	$1C
		.WORD	_pak_data4E
		.WORD	_pak_param52
		.BYTE	$14
		.WORD	_pak_data53
		.WORD	_pak_param53
		.BYTE	$29
		.WORD	_pak_data1E
		.WORD	_pak_param54
		.BYTE	$19
		.WORD	_pak_data55
		.WORD	_pak_param55
		.BYTE	$20
		.WORD	_pak_data30
		.WORD	_pak_param56
		.BYTE	$15
		.WORD	_pak_data57
		.WORD	_pak_param57
		.BYTE	$1C
		.WORD	_pak_data46
		.WORD	_pak_param58
		.BYTE	$1F
		.WORD	_pak_data4F
		.WORD	_pak_param59
		.BYTE	$19
		.WORD	_pak_data55
		.WORD	_pak_param5A
		.BYTE	$2B
		.WORD	_pak_data3A
		.WORD	_pak_param5B
		.BYTE	$3C
		.WORD	_pak_data5C
		.WORD	_pak_param5C
		.BYTE	$10
		.WORD	_pak_data12
		.WORD	_pak_param5D
		.BYTE	$22
		.WORD	_pak_data1F
		.WORD	_pak_param5E
		.BYTE	$15
		.WORD	_pak_data34
		.WORD	_pak_param5F
		.BYTE	$22
		.WORD	_pak_data42
		.WORD	_pak_param60
		.BYTE	$1E
		.WORD	_pak_data61
		.WORD	_pak_param61
		.BYTE	$1A
		.WORD	_pak_data36
		.WORD	_pak_param62
		.BYTE	$1E
		.WORD	_pak_data61
		.WORD	_pak_param63
		.BYTE	$10
		.WORD	_pak_data18
		.WORD	_pak_param64
		.BYTE	$24
		.WORD	_pak_data65
		.WORD	_pak_param65
		.BYTE	$33
		.WORD	_pak_data66
		.WORD	_pak_param66
		.BYTE	$2B
		.WORD	_pak_data3A
		.WORD	_pak_param67
		.BYTE	  4
		.WORD	_pak_data0
		.WORD	_pak_param68
		.BYTE	$C
		.WORD	_pak_data69
		.WORD	_pak_param69
		.BYTE	$10
		.WORD	_pak_data18
		.WORD	_pak_param6A
		.BYTE	$1F
		.WORD	_pak_data4F
		.WORD	_pak_param6B
		.BYTE	  6
		.WORD	_pak_data6
		.WORD	_pak_param6C
		.BYTE	$1D
		.WORD	_pak_data47
		.WORD	_pak_param6D
		.BYTE	$2A
		.WORD	_pak_data6E
		.WORD	_pak_param6E
		.BYTE	$44
		.WORD	_pak_data5C
		.WORD	_pak_param6F
		.BYTE	$1C
		.WORD	_pak_data4E
		.WORD	_pak_param70
		.BYTE	$33
		.WORD	_pak_data71
		.WORD	_pak_param71
		.BYTE	$13
		.WORD	_pak_data41
		.WORD	_pak_param72
		.BYTE	$22
		.WORD	_pak_data42
		.WORD	_pak_param73
		.BYTE	$1C
		.WORD	_pak_data46
		.WORD	_pak_param74
		.BYTE	$33
		.WORD	_pak_data66
		.WORD	_pak_param75
		.BYTE	$2A
		.WORD	_pak_data6E
		.WORD	_pak_param76
		.BYTE	$F
		.WORD	_pak_data7
		.WORD	_pak_param77
		.BYTE	$14
		.WORD	_pak_data53
		.WORD	_pak_param78
		.BYTE	$28
		.WORD	_pak_data79
		.WORD	_pak_param79
		.BYTE	$24
		.WORD	_pak_data65
		.WORD	_pak_param7A
		.BYTE	$44
		.WORD	_pak_data5C
		.WORD	_pak_param7B
		.BYTE	$17
		.WORD	_pak_data7C
		.WORD	_pak_param7C
		.BYTE	$28
		.WORD	_pak_data79
		.WORD	_pak_param7D
		.BYTE	$33
		.WORD	_pak_data71
		.WORD	_pak_param7E
		.BYTE	$2A
		.WORD	_pak_data6E
		.WORD	_pak_param7F
		.BYTE	$1E
		.WORD	_pak_data61
		.WORD	_pak_param80
		.BYTE	$24
		.WORD	_pak_data65
		.WORD	_pak_param81
		.BYTE	$51
		.WORD	_pak_data82
		.WORD	_pak_param82
		.BYTE	$33
		.WORD	_pak_data71
		.WORD	_pak_param83
		.BYTE	$51
		.WORD	_pak_data82
		.WORD	_pak_param84
		.BYTE	$62
		.WORD	_pak_data85
		.WORD	_pak_param85
		.BYTE	$62
		.WORD	_pak_data85
		.WORD	_pak_param86
		.BYTE	$2B
		.WORD	_pak_data87
		.WORD	_pak_param87
		.BYTE	$2B
		.WORD	_pak_data33
		.WORD	_pak_param88
		.BYTE	$2B
		.WORD	_pak_data33
		.WORD	_pak_param89
		.BYTE	$19
		.WORD	_pak_data1B
		.WORD	_pak_param8A
_pak_param0:
		.BYTE	$10,$30,$15,$1C
_pak_param1:
		.BYTE	$11, $F,$10, $F,$30,$27,$12
_pak_param2:
		.BYTE	$11, $F,$15, $F,$36,$26,$30
_pak_param3:
		.BYTE	$11,$30,$31, $F,$17,  6,$28
_pak_param4:
		.BYTE	$11,$30,$11, $F,$15,$2B,$12
_pak_param5:
		.BYTE	$11,$15, $F, $F,$30,$29,$26
_pak_param7:
		.BYTE	$11,$36, $F, $F,$26,  0,$36
_pak_param6:
		.BYTE	$10,$30,$29,$1A
_pak_param8:
		.BYTE	$11, $F,$25,$13,$30,$16,$1C
_pak_param9:
		.BYTE	$10,$11,$27,$30
_pak_paramA:
		.BYTE	$11,$25,$2A, $F,$10,  0,$11
_pak_paramB:
		.BYTE	$11, $F,$15, $F,$30,$37,$13
_pak_paramC:
		.BYTE	$11,$13, $F, $F,$37,$2C,$28
_pak_paramD:
		.BYTE	$11,$36,$27,$16,$13,$2A,$24
_pak_paramE:
		.BYTE	$11,$30, $C, $F,  7,$3A,$1C
_pak_paramF:
		.BYTE	$10,$30,$1C,$15
_pak_param10:
		.BYTE	$11, $F,$10,$15,$30,$2B,$19
_pak_param11:
		.BYTE	$11, $F, $F,$13,$30,$26,$16
_pak_param12:
		.BYTE	$10,$30,$10,  0
_pak_param13:
		.BYTE	$11, $F,$36, $F,$38,$18,$16
_pak_param14:
		.BYTE	$11,$30,$26,$24,  0,$1C,$3B
_pak_param1B:
		.BYTE	$11,$15, $F, $F,$30,$26,$11
_pak_param15:
		.BYTE	$11, $F,$1C, $F,$3C,$10,$1B
_pak_param16:
		.BYTE	$10,$30,$17,$1C
_pak_param17:
		.BYTE	$11, $F,$26, $F,$31,$2C,$13
_pak_param2B:
		.BYTE	$10,$15,$2B,$30
_pak_param19:
		.BYTE	$11,$30,  0, $F,  2,$1C,$16
_pak_param1A:
		.BYTE	$11,$30,$24, $F,$2C,$1C,$18
_pak_param26:
		.BYTE	$11, $F,$1B,$11,$3C,$14,$12
_pak_param27:
		.BYTE	$10,$26,$15,$11
_pak_param1D:
		.BYTE	$11,$1A, $F, $F,$35,$16,$23
_pak_param21:
		.BYTE	$11, $F, $F,$25,$30,$2A,$1B
_pak_param23:
		.BYTE	$11,$31,$23,$11,$1B,$15,$26
_pak_param20:
		.BYTE	$11, $F,$15,$26,$30,$10,$1C
_pak_param28:
		.BYTE	$11, $F,$27, $F,$29,$1A,  7
_pak_param1F:
		.BYTE	$11,$30,$17, $F,$3C,$2C,$15
_pak_param24:
		.BYTE	$11, $F, $E,$27,$3C,$2C,$13
_pak_param1C:
		.BYTE	$11,$37, $F, $F,$30,$26,  6
_pak_param22:
		.BYTE	$11, $F,$3B, $F,$37,$28,$1C
_pak_param25:
		.BYTE	$11, $F,$37, $F,$23,$14,$12
_pak_param1E:
		.BYTE	$11,$30,$15, $F,$17,  7,$10
_pak_param29:
		.BYTE	$10,$30,$27,$16
_pak_param2A:
		.BYTE	$11,$30,$28, $F,$22,$11,$24
_pak_param2D:
		.BYTE	$11,$25, $F, $F,$37,$1C,  4
_pak_param2C:
		.BYTE	$11,$16,$30,  0,$37,$26,$2C
_pak_param2F:
		.BYTE	$11,$30,$15, $F,$23,$13,$36
_pak_param2E:
		.BYTE	$11,$1C, $F, $F,$37,$19,$16
_pak_param30:
		.BYTE	$11,$27,$15,$37,$36,$18,$17
_pak_param31:
		.BYTE	$10,$30, $E,  0
_pak_param33:
		.BYTE	$11,$30,  7,$11,$1A,$18,$1C
_pak_param32:
		.BYTE	$11,$11,$37,  7,$30,$21,$26
_pak_param35:
		.BYTE	$11, $F,$2C, $F,$15,  4,$1B
_pak_param37:
		.BYTE	$11,$30,  7,$15,$11,  0,$26
_pak_param18:
		.BYTE	$10,$10,  0,$3C
_pak_param3A:
		.BYTE	$11,$21, $F, $F,$30,$27,$17
_pak_param36:
		.BYTE	$11,  1,$15,$26,$30,$1C,$17
_pak_param34:
		.BYTE	$11, $F,$15, $F,$30,$13,$26
_pak_param38:
		.BYTE	$11,$36, $F, $F,$17,$26,  0
_pak_param39:
		.BYTE	$11,$1A, $F, $F,$30,$29,$17
_pak_param3B:
		.BYTE	$11,$30,  6, $F,$14,$22,  0
_pak_param3C:
		.BYTE	$11,$30,$27,$17,$1C,$10,$15
_pak_param3D:
		.BYTE	$11,$30, $F, $F,$13,$27,$16
_pak_param3E:
		.BYTE	$11,$22, $F, $F,$10,$37,  0
_pak_param3F:
		.BYTE	$11, $C, $F, $F,$30,$1C,  0
_pak_param40:
		.BYTE	$10,$30,$2C,$10
_pak_param41:
		.BYTE	$10,$30,$1C,$10
_pak_param42:
		.BYTE	$11,$38,$25, $F,$30,$10,$2C
_pak_param43:
		.BYTE	$11, $F, $F,$1B,$31,  0,$12
_pak_param44:
		.BYTE	$10,$37,$19,$27
_pak_param45:
		.BYTE	$11,$27,$15,$37,$30,$10,$22
_pak_param46:
		.BYTE	$11,$30,$15, $F,$37,$18,$1C
_pak_param47:
		.BYTE	$11, $C,  0, $F,$1C,$10,$17
_pak_param48:
		.BYTE	$11,$1A,$35,$22,$3B,$2A,$37
_pak_param49:
		.BYTE	$11,$30,$1C, $F,$13,$24,$26
_pak_param4A:
		.BYTE	$11,  0,$37, $F,  2,$1B,$14
_pak_param4B:
		.BYTE	$11,$31, $F, $F,$1C,$3B,$23
_pak_param4C:
		.BYTE	$11,$2B, $F, $F,$26,$30,$15
_pak_param4D:
		.BYTE	$11,$37,$10,$13,$15,$12,$2A
_pak_param4E:
		.BYTE	$11,$21, $F, $F,$30,$16,  7
_pak_param4F:
		.BYTE	$11,$2C,$12,$15,$19,$36,$1B
_pak_param50:
		.BYTE	$11,$30,  3,$13,$27,$16,$1B
_pak_param51:
		.BYTE	$10,$11, $C,$26
_pak_param52:
		.BYTE	$11,$25,  0,  0,$30,$3C,$21
_pak_param56:
		.BYTE	$11,$37,$2B,$30,$32,$21,$15
_pak_param54:
		.BYTE	$11,$30,$15, $F,$2B,$1B,$17
_pak_param55:
		.BYTE	$11,$30,$15,$17,$36, $C,$10
_pak_param57:
		.BYTE	$11,$30,$15, $F,$1C, $C,  3
_pak_param59:
		.BYTE	$12,$27,$15,$13,$30,$1B,$17,$16,$28,$1C
_pak_param58:
		.BYTE	$11,$37,$15, $F,$30,  0,$27
_pak_param5C:
		.BYTE	$11,$37,$26,$30,$10,$17,  7
_pak_param5A:
		.BYTE	$11,$30,$15,$10,$3A,$16,$1C
_pak_param5B:
		.BYTE	$11,$29,$11,$21,$30,$2C,  1
_pak_param5D:
		.BYTE	$10,$3C,$2C,$11,$12,$30,$21,$15,$30,$3C, $F,  0,$1B,$27
_pak_param5E:
		.BYTE	$14,$30,$11,$21,$30,$23,$10,$30,$24,$2B,$27,$26,  7,$37,$26,$15
_pak_param60:
		.BYTE	$11,$30,$12, $F,$2C,$1C,$1A
_pak_param5F:
		.BYTE	$11, $F,$21, $F,$37,$1B,  0
_pak_param65:
		.BYTE	$11,$30,  7,$11,  9,$19,$25
_pak_param61:
		.BYTE	$11,$22, $F, $F,$30,$26,$12,$12,$30,$24,$11,$30,$10, $F,$16,$19
		.BYTE	$27
_pak_param62:
		.BYTE	$11,  8,$23,$30,$31,$10, $C
_pak_param63:
		.BYTE	$11,$10, $F, $F,$17,$36,  0
_pak_param64:
		.BYTE	$10,$2B,$1B,$14
_pak_param67:
		.BYTE	$11,$12,$15,$2C,$37,$24,  0
_pak_param66:
		.BYTE	$11,$15,  0,$10,$10,  0,$37
_pak_param84:
		.BYTE	$23,$30,$18,$28,$25,$37,$30, $F,$26,$23,$29,$19,$26,$29,$19,$23
_pak_param68:
		.BYTE	$10,$30, $E,$16
_pak_param69:
		.BYTE	$10,$30,$18,$10
_pak_param53:
		.BYTE	$11, $F,$15,$26,$30,$10, $C
_pak_param6A:
		.BYTE	$10,$15,  5,$30
_pak_param6B:
		.BYTE	$12,$23,  2,$1B,$3C,  0,$2B,$13,$11,$15
_pak_param6C:
		.BYTE	$10,$30,$10,  0
_pak_param6D:
		.BYTE	$11,  7,$35,  0,$30,$15,$1C,$12,$31,$1B,$15,$31,$22, $F,$12,$26
		.BYTE	$2C
_pak_param6E:
		.BYTE	$11,$15,  7, $F,$30,$26,$13
_pak_param6F:
		.BYTE	$12,$30,$25,$37,$17, $E, $F,$13,$29,$19
_pak_param70:
		.BYTE	$11,$23, $F, $F,$30,$37,$27
_pak_param71:
		.BYTE	$10,$30,$27,$21
_pak_param72:
		.BYTE	$10,$36,$13,$26
_pak_param73:
		.BYTE	$11,$30,$15, $F,$26,$17,$13
_pak_param74:
		.BYTE	$11,$37,$15, $F,$30,$1C,$10
_pak_param75:
		.BYTE	$11,$11,$1B,$2B,$2B,$1B,$24
_pak_param76:
		.BYTE	$11,$21, $C, $F,$30,$10,$16
_pak_param77:
		.BYTE	$11,  6, $F, $F,$22,$14,$2B
_pak_param78:
		.BYTE	$11, $F,$15,$26,$30,$37,  7
_pak_param79:
		.BYTE	$11,$30,$37,$26,$13,$26, $C
_pak_param7A:
		.BYTE	$11,$30,  1,$26, $C,$1C,$2B
_pak_param7B:
		.BYTE	$12,$30,$11,$31,$10, $E, $F,$1B,$13,  3
_pak_param7C:
		.BYTE	$11,$30,$15, $C,$10,$19,$27
_pak_param7D:
		.BYTE	$11,$31,$37,  5,$18,  0,$10
_pak_param7E:
		.BYTE	$10,$27,  7,$3B
_pak_param7F:
		.BYTE	$11,$34,$10, $F,$39,$2B,$1C
_pak_param80:
		.BYTE	$11,$2A, $F, $F,$23,$1C,$1A
_pak_param81:
		.BYTE	$11,$30,  9,$23,  4,$14,$21
_pak_param82:
		.BYTE	$23,$30,$1C,$2C,$21,$10,$37, $F,  0,$1A,$23,$13,  0,$23,$13,$1A
_pak_param83:
		.BYTE	$10,$14, $C,$30
_pak_param85:
		.BYTE	$23,$30,$26,$16,$30,  0,$16,$30,$2C,$1C,$23,$26,$16, $C,$26,$16
_pak_param86:
		.BYTE	$23,$3C,$2C,$1C,$3C, $C,$1C,$3C,$21,$11,$21,$2C,$1C,  1,$2C,$1C
		.BYTE	$11,$30,$15, $C,$10,$19,$27
_pak_param87:
		.BYTE	$11,$26,$37,  0,$30,$21,$11
_pak_param88:
		.BYTE	$11,$37,$10,$13,$19,$27,$1A
_pak_param89:
		.BYTE	$11,$37,$10,$13,$15,$12,$2A
_pak_param8A:
		.BYTE	$11,$2A, $F, $F,$27,$37,$18

; =============== S U B	R O U T	I N E =======================================
_get_far_pak_data_ptr_byte_safe:
		TXA
		PHA
		TYA
		PHA
		LDY		#0
		LDX		#_pak_data_ptr
		LDA		_tmp_pak_data_bank
		JSR		_far_byte_read_by_ptr
		STA		word_B7
		PLA
		TAY
		PLA
		TAX
		LDA		word_B7

; =============== S U B	R O U T	I N E =======================================
_inc_pak_data_ptr:
		INC		_pak_data_ptr
		BNE		locret_397C8
		INC		_pak_data_ptr+1
locret_397C8:
		RTS

; =============== S U B	R O U T	I N E =======================================
; packed data is in banks 2 and	3, so for every	single
; data record only 1 bit is enough to select desired
; bank,  so we pick this	bit here from the res blits list.
_get_pak_data_bank:
		TYA
		PHA
		TXA
		PHA
		LSR
		LSR
		LSR
		TAX
		LDA		_enemy_roster_index_list,X
		PHA
		AND		#7
		TAX
		PLA
		LSR
		LSR
		LSR
		TAY
		LDA		_pak_data_banks_list,Y
loc_397E0:
		ASL
		DEX
		BPL		loc_397E0
		LDY		#2
		BCC		loc_397E9
		INY
loc_397E9:
		STY		_tmp_pak_data_bank
		PLA
		TAX
		PLA
		TAY
		RTS

; =============== S U B	R O U T	I N E =======================================
_b2_s8_screen_hit_blink:
		LDX		#3
		STX		byte_C8
		LDX		#5
		BNE		sub_397FE

; =============== S U B	R O U T	I N E =======================================
_b2_s7_screen_spell_blink:
		LDX		#1
		STX		byte_C8
		LDX		#8

; =============== S U B	R O U T	I N E =======================================
sub_397FE:
		LDA		#$98
		STA		_PPU_MASK
loc_39803:
		TXA
		PHA
		JSR		sub_3A2E1
		LDA		#$10
loc_3980A:
		STA		_ram_pal_buf,X
		INX
		CPX		#$19
		BNE		loc_3980A
		JSR		sub_17435B
		LDX		byte_C8
		JSR		_vblank_count
		JSR		sub_3A2ED
		JSR		sub_17435B
		LDX		byte_C8
		JSR		_vblank_count
		PLA
		TAX
		DEX
		BNE		loc_39803
		LDA		#$18
		STA		_PPU_MASK
		RTS

; =============== S U B	R O U T	I N E =======================================
_b2_s6_screen_damage_shake:
		JSR		_vblank
		LDA		#2
		STA		byte_BA
		LDX		#0
loc_39839:
		STX		byte_BB
		TXA
		LDX		#1
		AND		#2
		BEQ		loc_39845
		LDA		#3
		DEX
loc_39845:
		TAY
		LDA		byte_6D0,X
		CLC
		ADC		byte_BA
		STA		byte_6D0,X
		LDX		#$40
loc_39851:
		LDA		_spr_ram,Y
		SEC
		SBC		byte_BA
		STA		_spr_ram,Y
		INY
		INY
		INY
		INY
		DEX
		BNE		loc_39851
		LDX		#2
		JSR		_vblank_count
		LDA		byte_BA
		EOR		#$FF
		STA		byte_BA
		INC		byte_BA
		LDX		byte_BB
		INX
		CPX		#$C
		BNE		loc_39839
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_39876:
		LDA		#0
		STA		byte_4C1
		LDX		#$19
loc_3987D:
		STA		_pak_data_ptr,X
		DEX
		BPL		loc_3987D
		LDX		#$34
loc_39884:
		STA		byte_4BF,X
		DEX
		BNE		loc_39884
		LDX		#$20
loc_3988C:
		STA		byte_696,X
		DEX
		BNE		loc_3988C
		STX		byte_4F5
		INX
		STX		byte_4F6
		LDA		#1
		STA		byte_4F3
		LDA		#$90
		STA		byte_4F4
		LDA		#$F
		STA		_ram_pal_buf
		LDA		byte_6E0
		LDX		#3
loc_398AD:
		STA		_ram_pal_buf,X
		DEX
		BNE		loc_398AD

; =============== S U B	R O U T	I N E =======================================
sub_398B3:
		LDA		#0
		TAX
loc_398B6:
		STA		byte_400,X
		INX
		CPX		#$70
		BCC		loc_398B6
		LDX		#$C
loc_398C0:
		STA		byte_4C2,X
		DEX
		BNE		loc_398C0
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_398C7:
		LSR
		AND		#4
		BNE		loc_398D8
		LDA		#$10
		CLC
		ADC		_pak_data_ptr
		STA		_pak_data_ptr
		BCC		locret_398D7
		INC		_pak_data_ptr+1
locret_398D7:
		RTS
loc_398D8:
		BCC		loc_398DD
		JSR		_inc_pak_data_ptr
loc_398DD:
		JSR		_get_far_pak_data_ptr_byte_safe
		PHA
		JSR		_get_far_pak_data_ptr_byte_safe
		TAY
		PLA
		JSR		sub_398EA
		TYA

; =============== S U B	R O U T	I N E =======================================
sub_398EA:
		ASL
		BCC		loc_398F2
		PHA
		JSR		_inc_pak_data_ptr
		PLA
loc_398F2:
		BNE		sub_398EA
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_398F5:
		DEY
		CPY		#8
		BCS		loc_398FE
		CPX		#4
		BCC		loc_39901
loc_398FE:
		LDY		#0
		RTS
loc_39901:
		TYA
		ASL
		ASL
		AND		#$1C
		STA		byte_BA
		TXA
		AND		#3
		ORA		byte_BA
		STA		byte_BA
		LDX		#0
		LDY		#8
loc_39913:
		LDA		byte_697,X
		BPL		loc_3991E
		AND		#$1F
		CMP		byte_BA
		BEQ		loc_39937
loc_3991E:
		INX
		INX
		INX
		INX
		DEY
		BNE		loc_39913
		LDX		#0
		LDY		#8
loc_39929:
		LDA		byte_697,X
		BPL		loc_39935
		INX
		INX
		INX
		INX
		DEY
		BNE		loc_39929
loc_39935:
		SEC
		RTS
loc_39937:
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
_b2_s5:
		LDX		word_B7+1
		LDY		byte_B9
		INY
		JSR		sub_398F5
		BCC		loc_39944
		RTS
loc_39944:
		STX		byte_BA
		LDX		#4
loc_39948:
		TXA
		PHA
		JSR		sub_3A056
		JSR		sub_39E9E
		PLA
		TAX
		DEX
		BNE		loc_39948
		RTS

; =============== S U B	R O U T	I N E =======================================
_b2_s4:
		LDX		word_B7+1
		LDY		byte_B9
		INY
		JSR		sub_398F5
		BCC		loc_39961
		RTS
loc_39961:
		STX		byte_BA
		JSR		sub_3A056
		LDX		byte_BA
		LDA		byte_697,X
		AND		#$7F
		STA		byte_697,X
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
_b2_s3:
		LDX		word_B7+1
		LDY		byte_B9
		INY
		JSR		_b2_s1
		BCS		locret_39988
		LDA		byte_697,X
		ORA		#$80
		STA		byte_697,X
		JSR		sub_39E9E
		CLC
locret_39988:
		RTS

; =============== S U B	R O U T	I N E =======================================
_b2_s2:
		JSR		sub_17435B
		LDX		#0
loc_3998E:
		STX		byte_BA
		LDA		byte_697,X
		BPL		loc_3999A
		JSR		sub_39E9E
		LDX		byte_BA
loc_3999A:
		INX
		INX
		INX
		INX
		CPX		#$20
		BNE		loc_3998E
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
_b2_s1:
		LDX		word_B7+1
		LDA		_enemy_roster_index_list,X
		CMP		#$FF
		BEQ		locret_399EB
		LDY		byte_B9
		INY
		BNE		loc_399CD
		TXA
		PHA
		STA		byte_B9
		LDY		#0
		LDX		#0
loc_399BA:
		LDA		byte_697,X
		AND		#3
		CMP		byte_B9
		BNE		loc_399C4
		INY
loc_399C4:
		INX
		CPX		#8
		BNE		loc_399BA
		STY		byte_B9
		PLA
		TAX
loc_399CD:
		JSR		sub_399EC
		BCS		locret_399EB
		LDX		byte_BA
		LDY		byte_BB
		LDA		byte_4CF,Y
		STA		byte_699,X
		LDA		byte_4C0
		BMI		locret_399EB
		JSR		sub_39D93
		BCS		locret_399EB
		LDX		byte_BA
		STA		byte_698,X
locret_399EB:
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_399EC:
		JSR		sub_398F5
		BCS		loc_399F3
		SEC
		RTS
loc_399F3:
		TYA
		BNE		loc_399F8
		SEC
		RTS
loc_399F8:
		LDA		byte_BA
		STA		byte_697,X
		STX		byte_BA
		AND		#3
		STA		byte_BB
		ASL
		ASL
		ASL
		CLC
		ADC		byte_BB
		STA		byte_BB
		TAY
		LDA		byte_4CF,Y
		BNE		loc_39A1B
		JSR		sub_39AA9
		LDY		byte_BB
		LDX		byte_BA
		BCC		loc_39A1B
		RTS
loc_39A1B:
		STA		byte_699,X

; =============== S U B	R O U T	I N E =======================================
sub_39A1E:
		LDA		byte_4D2,Y
		CLC
		BNE		loc_39A25
		RTS
loc_39A25:
		ADC		byte_4C1
		CMP		#$41
		BCC		loc_39A2D
		RTS
loc_39A2D:
		LDA		byte_4D7,Y
		STA		byte_BD
		LDA		word_4D5,Y
		STA		_pak_data_ptr
		LDA		word_4D5+1,Y
		STA		_pak_data_ptr+1
		TYA
		TAX
		JSR		_get_pak_data_bank
		LDX		#0
loc_39A43:
		JSR		_get_far_pak_data_ptr_byte_safe
		PHA
		JSR		_inc_pak_data_ptr
		AND		#$40
		BNE		loc_39A58
		JSR		_get_far_pak_data_ptr_byte_safe
		CLC
		ADC		#$4F
		STA		byte_400,X
		INX
loc_39A58:
		PLA
		BPL		loc_39A43
		JSR		sub_398C7
		DEC		byte_BD
		BNE		loc_39A43
		STX		byte_BC
		LDA		#$48
		STA		byte_BD
loc_39A68:
		LDX		#0
		LDA		byte_4C1
		BEQ		loc_39A88
		STA		byte_BE
		LDX		#0
		LDY		#0
loc_39A75:
		LDA		_spr_ram,Y
		SEC
		SBC		byte_BD
		CMP		#8
		BCS		loc_39A80
		INX
loc_39A80:
		INY
		INY
		INY
		INY
		DEC		byte_BE
		BNE		loc_39A75
loc_39A88:
		LDY		#0
loc_39A8A:
		LDA		byte_400,Y
		SEC
		SBC		byte_BD
		CMP		#8
		BCS		loc_39A95
		INX
loc_39A95:
		INY
		CPY		byte_BC
		BNE		loc_39A8A
		CPX		#9
		BCC		loc_39A9F
		RTS
loc_39A9F:
		INC		byte_BD
		LDA		byte_BD
		CMP		#$C8
		BNE		loc_39A68
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_39AA9:
		LDA		byte_4C0
		AND		#$7F
		BEQ		loc_39AB2
		SEC
		RTS
loc_39AB2:
		LDX		byte_BB
		LDA		byte_4CF,X
		BEQ		loc_39ABB
		SEC
		RTS
loc_39ABB:
		LDA		byte_4F5
		STA		byte_BD
		LDA		byte_4F6
		STA		byte_BC
		LDA		byte_4F3
		STA		byte_BE
		LDA		byte_4F4
		STA		byte_BF
		LDA		#0
		STA		_pak_data_ptr+1
		LDA		byte_BB
		AND		#3
		TAY
		LDA		_enemy_roster_index_list,Y
		CMP		#$A7
		BCC		loc_39AE0
		RTS
loc_39AE0:
		ASL
		ROL		_pak_data_ptr+1
		ASL
		ROL		_pak_data_ptr+1
		CLC
		ADC		_enemy_roster_index_list,Y
		BCC		loc_39AEE
		INC		_pak_data_ptr+1
loc_39AEE:
		CLC
		ADC		#<[_pak_data_lib]
		STA		_pak_data_ptr
		LDA		#>[_pak_data_lib]
		ADC		_pak_data_ptr+1
		STA		_pak_data_ptr+1
		LDY		byte_BB
		LDX		#_pak_data_ptr
		JSR		_get_data_next_byte
		STA		byte_4D7,Y
		JSR		_get_data_next_byte
		STA		word_4D5,Y
		JSR		_get_data_next_byte
		STA		word_4D5+1,Y
		JSR		_get_data_next_byte
		PHA
		JSR		_get_data_next_byte
		STA		_pak_data_ptr+1
		PLA
		STA		_pak_data_ptr
		JSR		_get_data_next_byte
		STA		byte_C0
		AND		#$F
		BEQ		loc_39B4C
		STA		byte_C1
		LDA		#$C
		STA		byte_C2
		JSR		sub_39B9D
		BCC		loc_39B32
		RTS
loc_39B32:
		LDX		byte_BB
		LDA		byte_C4
		STA		byte_4D3,X
		LDA		byte_C0
		AND		#$F
		STA		byte_C2
		ASL
		CLC
		ADC		byte_C2
		CLC
		ADC		_pak_data_ptr
		STA		_pak_data_ptr
		BCC		loc_39B4C
		INC		_pak_data_ptr+1
loc_39B4C:
		LDA		byte_C0
		LSR
		LSR
		LSR
		LSR
		AND		#$F
		BEQ		loc_39B69
		STA		byte_C1
		LDA		#0
		STA		byte_C2
		JSR		sub_39B9D
		BCC		loc_39B62
		RTS
loc_39B62:
		LDX		byte_BB
		LDA		byte_C4
		STA		byte_4D4,X
loc_39B69:
		JSR		sub_39C5F
		BCC		loc_39B6F
		RTS
loc_39B6F:
		LDX		byte_BB
		LDA		byte_BD
		STA		byte_4F5
		LDA		byte_BC
		STA		byte_4F6
		LDA		byte_C4
		STA		byte_4CF,X
		LDA		byte_4F3
		STA		byte_4D1,X
		LDA		byte_4F4
		STA		byte_4D0,X
		LDA		byte_C3
		STA		byte_4D2,X
		LDA		byte_BE
		STA		byte_4F3
		LDA		byte_BF
		STA		byte_4F4
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_39B9D:
		LDA		#0
		STA		byte_C3
		STA		byte_C4
		LDA		byte_C2
		LSR
		LSR
		AND		#1
		TAX
		LDA		byte_BC,X
		STA		byte_C5
		BEQ		loc_39C11
loc_39BB0:
		LDX		byte_C2
		BNE		loc_39BDB
		LDY		_enemy_roster_index_list+3
		INY
		BEQ		loc_39BDB
		LDY		#3
loc_39BBC:
		LDA		_ram_pal_buf,Y
		CMP		byte_6E0
		BNE		loc_39BDB
		DEY
		BNE		loc_39BBC
		LDA		byte_C3
		ASL
		CLC
		ADC		byte_C3
		TAY
		LDA		(_pak_data_ptr),Y
		CMP		byte_6E0
		BNE		loc_39BDB
		LDA		#0
		PHA
		JMP		loc_39C23
loc_39BDB:
		LDA		#0
		STA		byte_C6
		LDX		byte_C2
loc_39BE1:
		LDA		byte_C3
		ASL
		CLC
		ADC		byte_C3
		TAY
		LDA		#3
		STA		byte_C7
loc_39BEC:
		LDA		_ram_pal_buf+1,X
		CMP		(_pak_data_ptr),Y
		BNE		loc_39BFE
		INX
		INY
		DEC		byte_C7
		BNE		loc_39BEC
		LDA		byte_C6
		JMP		loc_39C38
loc_39BFE:
		INX
		DEC		byte_C7
		BNE		loc_39BFE
		INC		byte_C6
		LDA		byte_C5
		CMP		byte_C6
		BNE		loc_39BE1
		CMP		#4
		BNE		loc_39C11
		SEC
		RTS
loc_39C11:
		PHA
		ASL
		CLC
		ADC		byte_C5
		CLC
		ADC		byte_C2
		TAX
		INC		byte_C5
		LDA		byte_C3
		ASL
		CLC
		ADC		byte_C3
		TAY
loc_39C23:
		LDA		#3
		STA		byte_C7
		LDA		byte_6B8
		BNE		loc_39C37
loc_39C2C:
		LDA		(_pak_data_ptr),Y
		STA		_ram_pal_buf+1,X
		INX
		INY
		DEC		byte_C7
		BNE		loc_39C2C
loc_39C37:
		PLA
loc_39C38:
		LDX		byte_C3
		INX
		STX		byte_C3
loc_39C3D:
		DEX
		BEQ		loc_39C45
		ASL
		ASL
		JMP		loc_39C3D
loc_39C45:
		ORA		byte_C4
		STA		byte_C4
		LDA		byte_C3
		CMP		byte_C1
		BEQ		loc_39C52
		JMP		loc_39BB0
loc_39C52:
		LDA		byte_C2
		LSR
		LSR
		AND		#1
		TAX
		LDA		byte_C5
		STA		byte_BC,X
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_39C5F:
		LDX		byte_BB
		LDA		word_4D5,X
		STA		_pak_data_ptr
		LDA		word_4D5+1,X
		STA		_pak_data_ptr+1
		LDA		byte_4D7,X
		STA		byte_C0
		JSR		_get_pak_data_bank
		LDA		#0
		STA		byte_C3
		STA		byte_C4
loc_39C79:
		LDA		_pak_data_ptr
		PHA
		LDA		_pak_data_ptr+1
		PHA
		LDA		#0
		STA		byte_C5
		LDA		#$FF
		STA		byte_C6
		STA		byte_C7
loc_39C89:
		JSR		_get_far_pak_data_ptr_byte_safe
		TAX
		AND		#$40
		BNE		loc_39C94
		JSR		_inc_pak_data_ptr
loc_39C94:
		JSR		_inc_pak_data_ptr
		TXA
		BPL		loc_39C89
		LSR
		AND		#4
		BEQ		loc_39CB0
		BCC		loc_39CA6
		JSR		_get_far_pak_data_ptr_byte_safe
		STA		byte_C5
loc_39CA6:
		JSR		_get_far_pak_data_ptr_byte_safe
		STA		byte_C6
		JSR		_get_far_pak_data_ptr_byte_safe
		STA		byte_C7
loc_39CB0:
		LDX		#0
loc_39CB2:
		LDA		byte_C5
		ASL		byte_C6
		ROL		byte_C7
		BCC		loc_39CBD
		JSR		_get_far_pak_data_ptr_byte_safe
loc_39CBD:
		STA		byte_400,X
		LDY		#8
loc_39CC2:
		ASL
		ROR		byte_410,X
		DEY
		BNE		loc_39CC2
		INX
		CPX		#$10
		BNE		loc_39CB2
		LDX		#0
loc_39CD0:
		TXA
		ORA		#7
		TAY
loc_39CD4:
		LDA		byte_400,X
		STA		byte_420,Y
		INX
		DEY
		TXA
		AND		#7
		BNE		loc_39CD4
		CPX		#$20
		BNE		loc_39CD0
		PLA
		STA		_pak_data_ptr+1
		PLA
		STA		_pak_data_ptr
		LDA		#0
		STA		byte_C1
loc_39CEF:
		JSR		_get_far_pak_data_ptr_byte_safe
		STA		byte_C2
		LSR
		AND		#3
		TAX
		INX
		LDA		byte_C2
		AND		#$40
		BNE		loc_39D0C
		INC		byte_C3
		JSR		_inc_pak_data_ptr
		JSR		_inc_pak_data_ptr
		LDX		#0
		JMP		loc_39D17
loc_39D0C:
		JSR		_get_far_pak_data_ptr_byte_safe
		AND		#$F
		CMP		byte_C4
		BCC		loc_39D17
		STA		byte_C4
loc_39D17:
		TXA
		TAY
		INY
		LDA		#$20
loc_39D1C:
		LSR
		DEY
		BNE		loc_39D1C
		TAY
		AND		byte_C1
		BNE		loc_39D7E
		TYA
		ORA		byte_C1
		STA		byte_C1
		LDY		#$10
		TXA
		BNE		loc_39D32
		LDY		#0
		INX
loc_39D32:
		STY		byte_20
		DEX
		TXA
		ASL
		ASL
		ASL
		ASL
		CLC
		ADC		#<[byte_400]
		STA		_tmp21
		LDA		#0
		ADC		#>[byte_400]
		STA		_tmp21+1
		LDA		#$10
		CLC
		ADC		_tmp21
		STA		_tmp21+2
		LDA		#0
		ADC		_tmp21+1
		STA		byte_24
		LDA		#0
		STA		byte_1F
		LDA		byte_20
		LSR
		LSR
		LSR
		LSR
		AND		#1
		TAX
		LDA		byte_BE,X
		INC		byte_BE,X
		BNE		loc_39D69
		SEC
		RTS
loc_39D69:
		LDY		#4
loc_39D6B:
		LSR
		ROR		byte_1F
		DEY
		BNE		loc_39D6B
		ORA		byte_20
		STA		byte_20
		LDA		byte_32
		CMP		#$FD
		BNE		loc_39D7E
		JSR		sub_1741D7
loc_39D7E:
		LDA		byte_C2
		BMI		loc_39D85
		JMP		loc_39CEF
loc_39D85:
		JSR		sub_398C7
		DEC		byte_C0
		BEQ		loc_39D8F
		JMP		loc_39C79
loc_39D8F:
		INC		byte_C4
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_39D93:
		LDX		byte_BB
		LDA		byte_4CF,X
		BNE		loc_39D9C
		SEC
		RTS
loc_39D9C:
		STA		byte_C0
		LDA		byte_4C0
		BEQ		loc_39E08
		BPL		loc_39DA7
		CLC
		RTS
loc_39DA7:
		LDA		#$1D
		SEC
		SBC		byte_C0
		STA		byte_BC
		LDX		byte_C0
		DEX
		TXA
		LSR
		EOR		#$FF
		SEC
		ADC		#$F
		STA		byte_BD
		LDA		#0
		STA		byte_BE
loc_39DBE:
		LDA		#0
loc_39DC0:
		STA		byte_BF
		TAX
		LDA		byte_697,X
		BPL		loc_39DFB
		LDA		byte_698,X
		CLC
		ADC		byte_699,X
		CMP		byte_BD
		BCC		loc_39DFB
		LDA		byte_698,X
		CLC
		SBC		byte_C0
		CMP		#$20
		BCS		loc_39DE1
		CMP		byte_BD
		BCS		loc_39DFB
loc_39DE1:
		INC		byte_BE
		LDA		byte_BE
		CMP		byte_BC
		BNE		loc_39DEB
		SEC
		RTS
loc_39DEB:
		EOR		#1
		LSR
		LDA		byte_BE
		BCC		loc_39DF4
		EOR		#$FF
loc_39DF4:
		ADC		byte_BD
		STA		byte_BD
		JMP		loc_39DBE
loc_39DFB:
		LDA		byte_BF
		CLC
		ADC		#4
		CMP		#$20
		BNE		loc_39DC0
		LDA		byte_BD
		CLC
		RTS
loc_39E08:
		LDA		#2
		STA		byte_BD
		LDX		#0
loc_39E0E:
		LDA		byte_697,X
		BPL		loc_39E20
		LDA		byte_698,X
		SEC
		ADC		byte_699,X
		CMP		byte_BD
		BCC		loc_39E20
		STA		byte_BD
loc_39E20:
		INX
		INX
		INX
		INX
		CPX		#$20
		BNE		loc_39E0E
		LDA		byte_BD
		LDX		byte_BA
		CLC
		ADC		byte_699,X
		CMP		#$1F
		BCC		loc_39E35
		RTS
loc_39E35:
		LDA		byte_BD
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_39E39:
		LDA		byte_C1
		LSR
		ORA		#$50
		STA		byte_470
		LDA		#0
		ROL
		SEC
		LDX		byte_BB
		ADC		byte_4CF,X
		LSR
		ORA		#$40
		STA		byte_471
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_39E51:
		LDA		byte_471
		AND		#$F
		PHA
		ORA		#$20
		STA		byte_471
		JSR		sub_17474C
		PLA
		ASL
		PHA
		ASL
		ASL
		STA		_tmp21
		TAX
		LDY		#0
loc_39E69:
		LDA		byte_400,X
		STA		byte_400,Y
		INX
		INY
		CPY		_tmp21
		BCC		loc_39E69
		PLA
		STA		_tmp21
		TAX
		LDY		#0
loc_39E7B:
		CPX		#$C
		BCC		loc_39E84
		LDA		byte_4B7,X
		BCS		loc_39E87
loc_39E84:
		LDA		byte_460,X
loc_39E87:
		STA		byte_460,Y
		INX
		INY
		CPY		_tmp21
		BCC		loc_39E7B
		LDA		byte_470
		CLC
		ADC		#$20
		STA		byte_470
		JSR		sub_17474C
loc_39E9C:
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_39E9E:
		LDY		byte_BA
		LDA		byte_697,Y
		AND		#3
		STA		byte_BB
		ASL
		ASL
		ASL
		CLC
		ADC		byte_BB
		STA		byte_BB
		TAX
		LDA		byte_4C1
		STA		byte_C5
		LDA		word_4D5,X
		STA		_pak_data_ptr
		LDA		word_4D5+1,X
		STA		_pak_data_ptr+1
		LDA		byte_4D7,X
		STA		byte_C0
		JSR		_get_pak_data_bank
		LDA		byte_4C0
		BMI		loc_39E9C
		BNE		loc_39EF9
loc_39ECE:
		JSR		_get_far_pak_data_ptr_byte_safe
		PHA
		JSR		_inc_pak_data_ptr
		AND		#$40
		BNE		loc_39EE9
		LDA		byte_C5
		ASL
		ASL
		TAX
		JSR		_get_far_pak_data_ptr_byte_safe
		CLC
		ADC		#$4F
		STA		_spr_ram,X
		INC		byte_C5
loc_39EE9:
		PLA
		BPL		loc_39ECE
		JSR		sub_398C7
		DEC		byte_C0
		BNE		loc_39ECE
		LDA		byte_C5
		STA		byte_4C1
		RTS
loc_39EF9:
		LDA		byte_698,Y
		STA		byte_C1
		LDA		byte_4D0,X
		STA		byte_C7
		DEC		byte_C7
		LDA		byte_4D1,X
		STA		byte_C6
		DEC		byte_C6
		JSR		sub_39E39
		JSR		sub_398B3
		JSR		_vblank
loc_39F15:
		LDA		#0
		STA		byte_C2
loc_39F19:
		JSR		_get_far_pak_data_ptr_byte_safe
		STA		byte_C3
		AND		#$40
		BNE		loc_39F7F
		LDA		byte_C5
		ASL
		ASL
		TAX
		LDA		byte_C2
		AND		#$10
		BNE		loc_39F35
		INC		byte_C6
		LDA		byte_C2
		ORA		#$10
		STA		byte_C2
loc_39F35:
		LDA		byte_C6
		STA		_spr_ram+1,X
		LDA		byte_C3
		ROR
		ROR
		ROR
		ROR
		PHA
		AND		#3
		STA		byte_C4
		LDY		byte_BB
		LDA		byte_4D3,Y
		LDY		byte_C4
		INY
loc_39F4D:
		DEY
		BEQ		loc_39F55
		LSR
		LSR
		JMP		loc_39F4D
loc_39F55:
		AND		#3
		STA		byte_C4
		PLA
		AND		#$C0
		ORA		byte_C4
		STA		_spr_ram+2,X
		LDA		byte_C1
		ASL
		ASL
		ASL
		STA		byte_C4
		JSR		_get_far_pak_data_ptr_byte_safe
		CLC
		ADC		byte_C4
		STA		_spr_ram+3,X
		JSR		_get_far_pak_data_ptr_byte_safe
		CLC
		ADC		#$4F
		STA		_spr_ram,X
		INC		byte_C5
		JMP		loc_3A031
loc_39F7F:
		LDA		byte_C3
		LSR
		LSR
		LSR
		LSR
		AND		#3
		TAY
		LDX		byte_BB
		LDA		byte_4D4,X
		INY
loc_39F8E:
		DEY
		BEQ		loc_39F96
		LSR
		LSR
		JMP		loc_39F8E
loc_39F96:
		AND		#3
		STA		byte_1E
		JSR		_get_far_pak_data_ptr_byte_safe
		PHA
		AND		#$F
		STA		word_4
		LDA		byte_471
		AND		#$F
		STA		word_4+1
		PLA
		LSR
		LSR
		LSR
		LSR
		AND		#7
		TAX
		BEQ		loc_39FC1
		LDA		#0
loc_39FB5:
		CLC
		ADC		word_4+1
		DEX
		BNE		loc_39FB5
		ASL
		CLC
		ADC		word_4
		STA		word_4
loc_39FC1:
		LDA		byte_C1
		AND		#1
		CLC
		ADC		word_4
		STA		byte_4C2
		LDA		word_4+1
		ASL
		ASL
		STA		word_6
		LDA		byte_4C2
		LDX		#0
loc_39FD6:
		STA		word_6+1
		INX
		SEC
		SBC		word_6
		BCS		loc_39FD6
		DEX
		LDA		#0
loc_39FE1:
		CLC
		ADC		word_4+1
		DEX
		BNE		loc_39FE1
		STA		word_6
		ASL		word_4+1
		LDA		word_6+1
		SEC
		SBC		word_4+1
		BCC		loc_39FF4
		STA		word_6+1
loc_39FF4:
		LDA		word_6+1
		LSR
		CLC
		ADC		word_6
		TAX
		LDA		byte_1E
		CPX		#$C
		BCS		loc_3A006
		STA		byte_460,X
		BCC		loc_3A009
loc_3A006:
		STA		byte_4B7,X
loc_3A009:
		LDA		byte_C3
		LSR
		AND		#3
		TAX
		TAY
		INY
		LDA		#$10
loc_3A013:
		LSR
		DEY
		BNE		loc_3A013
		STA		byte_C4
		AND		byte_C2
		BNE		loc_3A029
		LDA		byte_C2
		ORA		byte_C4
		STA		byte_C2
		INC		byte_C7
		LDA		byte_C7
		STA		byte_BC,X
loc_3A029:
		LDA		byte_BC,X
		LDX		byte_4C2
		STA		byte_400,X
loc_3A031:
		LDA		byte_C3
		BMI		loc_3A038
		JMP		loc_39F19
loc_3A038:
		JSR		sub_398C7
		DEC		byte_C0
		BEQ		loc_3A042
		JMP		loc_39F15
loc_3A042:
		JSR		_vblank
		JSR		sub_39E51
		LDX		byte_BA
		LDA		byte_4C1
		STA		byte_69A,X
		LDA		byte_C5
		STA		byte_4C1
locret_3A055:
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_3A056:
		LDA		byte_6B8
		BNE		locret_3A055
		LDA		byte_4C0
		BNE		loc_3A062
loc_3A060:
		SEC
		RTS
loc_3A062:
		LDY		byte_BA
		LDA		byte_697,Y
		BPL		loc_3A060
		AND		#3
		STA		byte_BB
		ASL
		ASL
		ASL
		CLC
		ADC		byte_BB
		STA		byte_BB
		TAX
		LDA		byte_698,Y
		STA		byte_C1
		LDA		byte_69A,Y
		STA		byte_C2
		LDA		word_4D5,X
		STA		_pak_data_ptr
		LDA		word_4D5+1,X
		STA		_pak_data_ptr+1
		LDA		byte_4D7,X
		STA		byte_C0
		JSR		_get_pak_data_bank
		JSR		sub_39E39
loc_3A095:
		JSR		_get_far_pak_data_ptr_byte_safe
		STA		byte_BF
		AND		#$40
		BNE		loc_3A0AD
		LDA		byte_C2
		ASL
		ASL
		TAX
		LDA		#$F8
		STA		_spr_ram,X
		INC		byte_C2
		JSR		_inc_pak_data_ptr
loc_3A0AD:
		JSR		_inc_pak_data_ptr
		LDA		byte_BF
		BMI		loc_3A0B7
		JMP		loc_3A095
loc_3A0B7:
		JSR		sub_398C7
		DEC		byte_C0
		BEQ		loc_3A0C1
		JMP		loc_3A095
loc_3A0C1:
		JSR		sub_398B3
		JSR		_vblank
		JSR		sub_39E51
		LDY		byte_BA
		LDX		byte_BB
		LDA		byte_4D2,X
		BEQ		loc_3A138
		STA		byte_BD
		LDA		byte_69A,Y
		STA		byte_BC
		LDA		byte_4C1
		SEC
		SBC		byte_BD
		STA		byte_4C1
		SEC
		SBC		byte_BC
		BEQ		loc_3A105
		ASL
		ASL
		STA		byte_BE
		LDA		byte_BC
		CLC
		ADC		byte_BD
		ASL
		ASL
		TAY
		LDA		byte_BC
		ASL
		ASL
		TAX
loc_3A0F9:
		LDA		_spr_ram,Y
		STA		_spr_ram,X
		INX
		INY
		DEC		byte_BE
		BNE		loc_3A0F9
loc_3A105:
		LDA		byte_BD
		STA		byte_BE
		LDA		byte_4C1
		ASL
		ASL
		TAX
		LDA		#$F8
loc_3A111:
		STA		_spr_ram,X
		INX
		INX
		INX
		INX
		DEC		byte_BE
		BNE		loc_3A111
		LDX		#0
loc_3A11E:
		LDA		byte_697,X
		BPL		loc_3A130
		LDA		byte_69A,X
		CMP		byte_BC
		BCC		loc_3A130
		SEC
		SBC		byte_BD
		STA		byte_69A,X
loc_3A130:
		INX
		INX
		INX
		INX
		CPX		#$20
		BNE		loc_3A11E
loc_3A138:
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
_b2_s0:
		LDY		byte_62
		INY
		BEQ		loc_3A142
		JSR		sub_3A267
loc_3A142:
		JSR		_vblank_and_render_off_flag10_set
		LDA		#$FD
		STA		byte_32
		LDA		#0
		STA		byte_6B8
		JSR		sub_39876
		JSR		sub_3A157
		JMP		_clear_nmi_flag_10

; =============== S U B	R O U T	I N E =======================================
sub_3A157:
		LDA		#0
		STA		byte_4C0
		STA		byte_6B7
		LDX		#0
loc_3A161:
		STX		word_B7+1
		LDA		#0
		STA		byte_B9
		LDA		_enemy_roster_index_list,X
		CMP		#$FF
		BEQ		loc_3A1D6
		LDA		byte_571,X
		BNE		loc_3A1A8
		LDA		#$80
		STA		byte_4C0
		JSR		_b2_s1
		BCS		loc_3A188
		JSR		_b2_s4
		LDA		#0
		STA		byte_697,X
		JMP		loc_3A194
loc_3A188:
		LDX		word_B7+1
		LDA		#$FF
		STA		_enemy_roster_index_list,X
		LDA		#0
		STA		byte_571,X
loc_3A194:
		LDA		#0
		STA		byte_4C0
		LDA		byte_6B8
		BEQ		loc_3A1A3
		LDA		#$80
		STA		byte_4C0
loc_3A1A3:
		LDX		word_B7+1
		JMP		loc_3A1D6
loc_3A1A8:
		JSR		_b2_s3
		LDX		word_B7+1
		BCS		loc_3A1BA
		INC		byte_B9
		LDA		byte_B9
		CMP		byte_571,X
		BCC		loc_3A1A8
		BCS		loc_3A1D6
loc_3A1BA:
		LDA		#$FF
		STA		byte_6B7
		LDA		byte_B9
		STA		byte_571,X
		BNE		loc_3A1D6
loc_3A1C6:
		LDA		#$FF
		STA		_enemy_roster_index_list,X
		LDA		#0
		STA		byte_571,X
		INX
		CPX		#4
		BNE		loc_3A1C6
		DEX
loc_3A1D6:
		INX
		CPX		#4
		BNE		loc_3A161
		LDX		#1
		STX		byte_4C1
		LDA		byte_6B8
		BNE		loc_3A25E
		LDA		#$F0
		DEX
loc_3A1E8:
		STA		_spr_ram,X
		INX
		INX
		INX
		INX
		BNE		loc_3A1E8
		TXA
		LDX		#$40
loc_3A1F4:
		STA		_ram_pal_buf+$18,X
		DEX
		BNE		loc_3A1F4
		STX		byte_BA
loc_3A1FC:
		LDA		byte_697,X
		BPL		loc_3A22A
		STA		byte_BB
		AND		#$7F
		STA		byte_697,X
		AND		#3
		ASL
		ASL
		ASL
		STA		byte_BC
		LDA		byte_BB
		LSR
		LSR
		AND		#7
		ORA		byte_BC
		TAY
		LDA		byte_699,X
		SEC
		ADC		byte_BA
		CMP		#$1E
		BCS		loc_3A22A
		STA		byte_BA
		TXA
		ORA		#$80
		STA		byte_400,Y
loc_3A22A:
		INX
		INX
		INX
		INX
		CPX		#$20
		BNE		loc_3A1FC
		DEC		byte_BA
		LDA		#$20
		SEC
		SBC		byte_BA
		LSR
		STA		byte_BA
		LDY		#0
loc_3A23E:
		LDA		byte_400,Y
		BPL		loc_3A259
		AND		#$1F
		TAX
		LDA		byte_697,X
		ORA		#$80
		STA		byte_697,X
		LDA		byte_BA
		STA		byte_698,X
		SEC
		ADC		byte_699,X
		STA		byte_BA
loc_3A259:
		INY
		CPY		#$20
		BNE		loc_3A23E
loc_3A25E:
		LDA		#1
		STA		byte_4C0
		LSR		byte_6B7
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_3A267:
		LDX		#0
loc_3A269:
		LDA		_enemy_roster_index_list,X
		CMP		#$FF
		BNE		loc_3A276
		INX
		CPX		#3
		BNE		loc_3A269
		RTS
loc_3A276:
		STX		byte_8
		INX
		STX		byte_9
loc_3A27B:
		LDA		#$17
		STA		word_4
		LDA		#0
		STA		word_4+1
		LDX		byte_8
		LDA		_enemy_roster_index_list,X
		LDX		#word_4
		JSR		_mul16_to_8
		LDA		#<[_b0_d43_enemies_lib]
		LDY		#>[_b0_d43_enemies_lib]
		LDX		#word_4
		JSR		_add16_to_16
		LDY		#$A
loc_3A29F:
		LDA		#0
		LDX		#word_4
		JSR		_far_byte_read_by_ptr
		AND		#$3F
		CMP		#$3B
		BCS		loc_3A2B6
		INY
		CPY		#$12
		BNE		loc_3A29F
		DEC		byte_8
		BPL		loc_3A27B
		RTS
loc_3A2B6:
		SBC		#$3B
		TAX
		LDA		byte_3A2DC,X
		TAY
		LDX		#2
loc_3A2BF:
		LDA		_enemy_roster_index_list,X
		STA		_enemy_roster_index_list+1,X
		LDA		byte_571,X
		STA		byte_572,X
		DEX
		CPX		byte_9
		BCS		loc_3A2BF
		LDX		byte_9
		TYA
		STA		_enemy_roster_index_list,X
		LDA		#0
		STA		byte_571,X
		RTS
byte_3A2DC:
		.BYTE	  9,$75,$47,$56,$59

; =============== S U B	R O U T	I N E =======================================
sub_3A2E1:
		LDX		#$19
loc_3A2E3:
		LDA		byte_3E6,X
		STA		_ram_pal_buf+$18,X
		DEX
		BNE		loc_3A2E3
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_3A2ED:
		LDX		#$19
loc_3A2EF:
		LDA		_ram_pal_buf+$18,X
		STA		byte_3E6,X
		DEX
		BNE		loc_3A2EF
		RTS

; =============== S U B	R O U T	I N E =======================================
_b2_sA:
		CMP		#$FF
		BEQ		loc_3A30C
		LDX		#0
loc_3A2FF:
		CMP		_enemy_roster_index_list,X
		BEQ		loc_3A30A
		INX
		CPX		#4
		BCC		loc_3A2FF
		RTS
loc_3A30A:
		STX		word_B7+1
loc_3A30C:
		LDX		word_B7+1
		TXA
		ASL
		ASL
		ASL
		ADC		word_B7+1
		PHA
		TAY
		JSR		sub_39A1E
		PLA
		BCC		loc_3A31D
		RTS
loc_3A31D:
		TAY
		LDA		byte_4CF,Y
		STA		byte_C0
		JMP		loc_39DA7

; =============== S U B	R O U T	I N E =======================================
_b2_s9:
		LDA		#0
		STA		byte_32
		JSR		sub_39876
		LDX		#$C
loc_3A32F:
		LDA		_ram_pal_buf+$C,X
		STA		byte_60A8,X
		DEX
		BNE		loc_3A32F
		LDA		#$FF
		STA		byte_6B8
		JSR		sub_3A157
		LDX		#$C
loc_3A342:
		LDA		byte_60A8,X
		STA		_ram_pal_buf+$C,X
		DEX
		BNE		loc_3A342
		FAR		$00,$6F		; _b16_s0
		RTS

; =============== S U B	R O U T	I N E =======================================
_b2_sB:
		LDA		byte_6A63
		BEQ		loc_3A355
		RTS
loc_3A355:
		FARX	_b4_s6
		LDA		byte_566
		AND		#$C4
		BEQ		loc_3A360
		RTS
loc_3A360:
		LDX		#0
		STX		byte_52
loc_3A364:
		STX		byte_51
		LDA		byte_6A9B,X
		AND		#8
		BNE		loc_3A39B
		TXA
		ASL
		TAX
		LDA		byte_73C,X
		AND		byte_73D,X
		BPL		loc_3A39B
		LDA		byte_73D,X
		AND		#$40
		BNE		loc_3A39B
		LDA		byte_73C,X
		AND		#$40
		BNE		loc_3A3AC
		LDA		byte_567
		AND		#$C
		BEQ		loc_3A396
		LDA		byte_567
		AND		#3
		CMP		byte_51
		BNE		loc_3A39B
loc_3A396:
		JSR		loc_3A3CF
		INC		byte_52
loc_3A39B:
		LDX		byte_51
		INX
		CPX		#4
		BNE		loc_3A364
		JSR		sub_1743B8
		AND		#$F
		STA		byte_6A68
		TXA
		RTS
loc_3A3AC:
		JSR		sub_1743B8
		LDX		byte_51
		CMP		#0
		BNE		loc_3A3BC
		LDA		#$80
		STA		byte_54C,X
		BNE		loc_3A39B
loc_3A3BC:
		JSR		sub_1743B8
		AND		#1
		CLC
		ADC		#4
		ASL
		ASL
		ASL
		ASL
		ORA		#$80
		STA		byte_54C,X
		BNE		loc_3A39B
loc_3A3CF:
		FARX	_b4_sC
		LDA		#$3F
		FARX	_b4_s7_window_display_safe
		LDX		byte_51
		JSR		sub_3A6FD
		LDA		byte_54
		CLC
		ADC		#$18
		FARX	_b4_s7_window_display_safe
		CMP		#$FF
		BNE		loc_3A417
		LDA		byte_52
		BEQ		loc_3A412
		DEC		byte_52
loc_3A3EE:
		DEC		byte_51
		LDX		byte_51
		LDA		byte_6A9B,X
		AND		#8
		BNE		loc_3A3EE
		TXA
		ASL
		TAX
		LDA		byte_73C,X
		AND		byte_73D,X
		BPL		loc_3A3EE
		LDA		byte_73D,X
		AND		#$40
		BNE		loc_3A3EE
		LDA		byte_73C,X
		AND		#$40
		BNE		loc_3A3EE
loc_3A412:
		DEC		byte_52
		DEC		byte_51
		RTS
loc_3A417:
		STA		word_4
		LDA		byte_54
		ASL
		ASL
		CLC
		ADC		word_4
		TAX
		LDA		byte_3A733,X
		STA		byte_53
		CMP		#0
		BEQ		loc_3A44A
		CMP		#1
		BEQ		loc_3A473
		CMP		#3
		BNE		loc_3A435
		JMP		loc_3A5A8
loc_3A435:
		CMP		#7
		BNE		loc_3A43C
		JMP		loc_3A689
loc_3A43C:
		LDX		byte_51
		LDA		byte_6A9B,X
		ORA		#$20
		STA		byte_6A9B,X
		JSR		loc_3A675
		RTS
loc_3A44A:
		JSR		loc_3A457
		CPX		#$FF
		BEQ		loc_3A454
		JMP		loc_3A677
loc_3A454:
		JMP		loc_3A3CF
loc_3A457:
		LDA		#$39
loc_3A459:
		FARX	_b4_s7_window_display_safe
		CMP		#$FF
		BEQ		loc_3A46F
		CMP		#$80
		BCC		loc_3A46F
		AND		#$7F
		STA		byte_59
		FARX	_b4_s3
		LDA		byte_5A
		ORA		#$80
loc_3A46F:
		TAX
		LDA		byte_53
		RTS
loc_3A473:
		LDA		#1
		STA		byte_D0
		LDX		byte_51
		LDA		byte_6A9B,X
		AND		#3
		STA		byte_CE
		JSR		_sram_b0_s39
		LDY		#0
		LDA		byte_8
		BEQ		loc_3A48A
		INY
loc_3A48A:
		INC		byte_D0
		TYA
		PHA
		JSR		_sram_b0_s39
		PLA
		TAY
		LDA		byte_8
		BEQ		loc_3A498
		INY
loc_3A498:
		CPY		#2
		BNE		loc_3A4B0
		LDA		#$22
		FARX	_b4_s7_window_display_safe
		CMP		#$FF
		BNE		loc_3A4A8
		JMP		loc_3A3CF
loc_3A4A8:
		CLC
		ADC		#1
		STA		byte_D0
		JMP		loc_3A4BD
loc_3A4B0:
		LDA		#1
		STA		byte_D0
		JSR		_sram_b0_s39
		LDA		byte_8
		BNE		loc_3A4BD
		INC		byte_D0
loc_3A4BD:
		LDX		byte_51
		LDA		byte_6A4B,X
		LDX		byte_D0
		DEX
		BEQ		loc_3A4C9
		LSR
		LSR
loc_3A4C9:
		AND		#3
		FARX	_b1_s14
		CMP		#$FF
		BNE		loc_3A4D5
		JMP		loc_3A3CF
loc_3A4D5:
		PHA
		LDA		byte_7E
		LDX		byte_D0
		DEX
		BEQ		loc_3A4F1
		ASL
		ASL
		LDX		byte_51
		PHA
		LDA		byte_6A4B,X
		AND		#3
		STA		byte_6A4B,X
		PLA
		ORA		byte_6A4B,X
		JMP		loc_3A500
loc_3A4F1:
		LDX		byte_51
		PHA
		LDA		byte_6A4B,X
		AND		#$C
		STA		byte_6A4B,X
		PLA
		ORA		byte_6A4B,X
loc_3A500:
		STA		byte_6A4B,X
		PLA
		TAY
		LDA		#[_b4_dD_spells_list_idx-_sys0_sub_idx_lib]
		JSR		_sys0_byte_read_y
		AND		#$3F
		STA		byte_CF
		LDA		byte_D0
		PHA
		LDA		byte_CF
		PHA
		LDA		#$41
		STA		byte_CF
		TYA
		PHA
		FARX	_b0_s45
		PLA
		TAY
		PLA
		STA		byte_CF
		LDA		word_4
		CMP		#$C1
		BNE		loc_3A536
		LDA		byte_CF
		ASL
		ADC		byte_CF
		LSR
		LSR
		BNE		loc_3A534
		CLC
		ADC		#1
loc_3A534:
		STA		byte_CF
loc_3A536:
		LDA		#0
		STA		byte_D0
		TYA
		PHA
		LDA		byte_CE
		PHA
		LDA		byte_51
		STA		byte_CE
		JSR		_sram_b0_sB
		PLA
		STA		byte_CE
		PLA
		TAY
		PLA
		STA		byte_66
		BCS		loc_3A569
		LDA		#$3D
		FARX	_b4_s7_window_display_safe
		LDA		#$20
		FARX	_b4_s9
		FARX	_b4_s5_do_message_speed_delay
		FARX	_b4_s5_do_message_speed_delay
		FARX	_b4_s5_do_message_speed_delay
		FARX	_b4_s5_do_message_speed_delay
		JMP		loc_3A3CF
loc_3A569:
		LDA		#[_b4_dD_spells_list_idx-_sys0_sub_idx_lib]
		JSR		_sys0_byte_read_y
		BMI		loc_3A57B
		LDX		#0
		AND		#$40
		BEQ		loc_3A578
		LDX		#$80
loc_3A578:
		JMP		loc_3A675
loc_3A57B:
		LDX		#$39
		AND		#$40
		BNE		loc_3A582
		DEX
loc_3A582:
		TYA
		PHA
		TXA
		FARX	_b4_s7_window_display_safe
		CMP		#$FF
		BEQ		loc_3A59B
		CMP		#$80
		BCC		loc_3A59B
		AND		#$7F
		STA		byte_59
		FARX	_b4_s3
		LDA		byte_5A
		ORA		#$80
loc_3A59B:
		TAX
		PLA
		TAY
		CPX		#$FF
		BNE		loc_3A5A5
		JMP		loc_3A473
loc_3A5A5:
		JMP		loc_3A675
loc_3A5A8:
		LDA		byte_51
		STA		byte_CE
		JSR		_sram_b0_s28
		LDA		word_4
		BNE		loc_3A5C9
		LDA		#$3D
		FARX	_b4_s7_window_display_safe
		LDA		byte_CE
		STA		byte_D2
		LDA		#$D1
		FARX	_b4_s9
		LDX		#$1E
		JSR		_vblank_count
		JMP		loc_3A3CF
loc_3A5C9:
		LDA		#$3B
		FARX	_b4_s7_window_display_safe
		CMP		#$FF
		BNE		loc_3A5D5
		JMP		loc_3A3CF
loc_3A5D5:
		STA		byte_CF
		LDA		#0
		STA		byte_46
		JSR		_sram_b0_s28
		LDA		word_4+1
		AND		#$7F
		STA		byte_CF
		STA		byte_45
		STA		byte_D3
		FARX	_b0_s60
		BNE		loc_3A5F4
		FARX	_b0_s5E
		BCC		loc_3A5F4
		INC		byte_46
loc_3A5F4:
		FARX	_b0_s5F
		BCC		loc_3A5FD
		INC		byte_46
		INC		byte_46
loc_3A5FD:
		LDA		byte_46
		BNE		loc_3A61D
		LDA		#$3D
		FARX	_b4_s7_window_display_safe
		FARX	_bE_s2
		FARX	_bE_s5
		LDA		byte_51
		STA		byte_D2
		LDA		#$BF
		FARX	_b4_s9
		LDX		#$3C
		JSR		_vblank_count
		JMP		loc_3A5A8
loc_3A61D:
		CMP		#1
		BEQ		loc_3A635
		CMP		#2
		BEQ		loc_3A642
		LDA		#$21
		FARX	_b4_s7_window_display_safe
		CMP		#$FF
		BNE		loc_3A631
loc_3A62E:
		JMP		loc_3A5A8
loc_3A631:
		CMP		#0
		BEQ		loc_3A642
loc_3A635:
		JSR		loc_3A457
		CPX		#$FF
		BEQ		loc_3A62E
		LDY		byte_45
		LDA		#6
		BNE		loc_3A677
loc_3A642:
		LDX		byte_45
		LDA		#[_b0_d42_effects_list_idx-_sys0_sub_idx_lib]
		JSR		_sys0_byte_read_x
		STA		byte_46
		BIT		byte_46
		BVS		loc_3A660
		LDX		#$80
		AND		#$20
		BNE		loc_3A66F
		LDX		byte_51
		LDA		byte_540,X
		AND		#3
		TAX
		JMP		loc_3A66F
loc_3A660:
		LDY		#$38
		AND		#$20
		BEQ		loc_3A667
		INY
loc_3A667:
		TYA
		JSR		loc_3A459
		CPX		#$FF
		BEQ		loc_3A62E
loc_3A66F:
		LDY		byte_45
		LDA		#3
		BNE		loc_3A677
loc_3A675:
		LDA		byte_53
loc_3A677:
		STX		word_4
		ASL
		ASL
		ASL
		ASL
		ORA		word_4
		LDX		byte_51
		STA		byte_54C,X
		TYA
		STA		byte_558,X
		RTS
loc_3A689:
		LDA		#$3D
		FARX	_b4_s7_window_display_safe
		FARX	_b4_sA
		LDA		#$83
		FARX	_bB_s3_apu_load
		FAR		$2D,$17		; _bD_s26
		LDA		word_4
		STA		byte_D2
		LDX		#$50
		FARX	_b4_s1D
		CMP		#$50
		BEQ		loc_3A6A8
		LDA		#8
loc_3A6A8:
		FARX	_b4_s8_msg_mFF_arg0_and_delay_or_wait_for_keypress
		LDA		byte_6A6B
		BNE		loc_3A6D7
		LDA		byte_566
		AND		#8
		BNE		loc_3A6CC
		LDA		byte_6A6A
		CMP		#$A
		BCS		loc_3A6CC
		LDA		byte_566
		AND		#3
		TAX
		JSR		sub_1743B8
		CMP		byte_3A6F9,X
		BCC		loc_3A6D7
loc_3A6CC:
		FARX	_b0_s47
		FARX	_b4_s5_do_message_speed_delay
		PLA
		PLA
		LDA		#$FD
		RTS
loc_3A6D7:
		LDA		#$17
		FARX	_b4_s8_msg_mFF_arg0_and_delay_or_wait_for_keypress
		LDA		byte_566
		CLC
		ADC		#1
		AND		#3
		PHA
		LDA		byte_566
		AND		#$FC
		STA		byte_566
		PLA
		ORA		byte_566
		ORA		#4
		STA		byte_566
		PLA
		PLA
		RTS
byte_3A6F9:
		.BYTE	$80,$80,$40,  0

; =============== S U B	R O U T	I N E =======================================
sub_3A6FD:
		TXA
		PHA
		LDA		byte_6A9B,X
		AND		#3
		STA		byte_CE
		JSR		_sram_b0_s2C
		CMP		#7
		BEQ		loc_3A721
		LDA		#1
		STA		byte_D0
		JSR		_sram_b0_s39
		LDA		byte_8
		PHA
		INC		byte_D0
		JSR		_sram_b0_s39
		PLA
		ORA		byte_8
		BNE		loc_3A725
loc_3A721:
		LDY		#2
		BNE		loc_3A727
loc_3A725:
		LDY		#0
loc_3A727:
		PLA
		TAX
		LDA		byte_52
		BEQ		loc_3A72E
		INY
loc_3A72E:
		STY		byte_54
		STX		byte_CE
		RTS
byte_3A733:
		.BYTE	  0,  1,  7,  3,  0,  1,  2,  3,  0,  7,  2,  3,  0,  2,  3

; =============== S U B	R O U T	I N E =======================================
_b2_sD:
		JSR		_sram_b0_s2C
		CMP		#7
		BNE		loc_3A750
		JSR		sub_1743B8
		CMP		#$41
		BCC		loc_3A752
loc_3A750:
		CLC
		RTS
loc_3A752:
		JSR		_b2_sE
		LDA		off_3A946
		STA		word_3E
		LDA		off_3A946+1
		STA		word_3E+1
		FAR		$97,$17		; _bA_sB
		BCC		loc_3A750
		TAX
		LDA		#[_b0_d3F_idx-_sys0_sub_idx_lib]
		JSR		_sys0_byte_read_x
		TAX
		STA		byte_47
		CMP		#$F
		BCC		sub_3A7E9
		CMP		#$15
		BCC		loc_3A79E
		CMP		#$1E
		BCC		loc_3A7A1
		CMP		#$1E
		BEQ		loc_3A7A4
		CMP		#$1F
		BEQ		loc_3A7A7
		CMP		#$24
		BCC		loc_3A787
		CLC
		RTS
loc_3A787:
		JSR		sub_3A7E9
		LDA		byte_47
		SEC
		SBC		#$20
		ASL
		TAX
		LDA		off_3A985,X
		STA		word_3C
		LDA		off_3A985+1,X
		STA		word_3C+1
		JMP		(word_3C)
loc_3A79E:
		JMP		loc_3A7F9
loc_3A7A1:
		JMP		loc_3A810
loc_3A7A4:
		JMP		sub_3A85E
loc_3A7A7:
		JMP		sub_3A876

; =============== S U B	R O U T	I N E =======================================
sub_3A7AA:
		LDX		byte_CE
		LDA		byte_6A9B,X
		ORA		#$20
		STA		byte_6A9B,X
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_3A7B6:
		LDA		byte_CE
		ASL
		TAX
		LDA		byte_73D,X
		ORA		#$40
		STA		byte_73D,X
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_3A7C4:
		LDX		byte_CE
		LDA		byte_6A9B,X
		ORA		#8
		STA		byte_6A9B,X
		TXA
		ASL
		TAX
		LDA		byte_73C,X
		ORA		#3
		STA		byte_73C,X
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_3A7DB:
		LDA		byte_CE
		ASL
		TAX
		LDA		byte_73D,X
		ORA		#$10
		STA		byte_73D,X
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_3A7E9:
		LDA		byte_CE
		STA		byte_D2
		LDX		byte_47
		CPX		#$D
		BEQ		loc_3A854
		LDA		byte_3A950,X
		JMP		sub_3A93C
loc_3A7F9:
		CMP		#$10
		BNE		loc_3A805
		LDA		#$8E
		FARX	_bB_s3_apu_load
		FARX	_b2_s7_screen_spell_blink
loc_3A805:
		JSR		sub_3A7E9
		LDX		byte_47
		LDA		byte_3A965,X
		JMP		sub_3A93C
loc_3A810:
		CMP		#$1D
		BNE		loc_3A81D
		LDX		byte_CE
		LDA		byte_718,X
		AND		#8
		BEQ		loc_3A852
loc_3A81D:
		LDA		byte_CE
		STA		byte_D3
		LDA		byte_47
		CMP		#$17
		BEQ		loc_3A831
		JSR		sub_3A88D
		BCC		loc_3A852
		FARX	_b4_s12
		STA		byte_D3
loc_3A831:
		LDX		byte_47
		LDA		byte_3A950,X
		JSR		sub_3A7E9
		FARX	_b4_s12
		STA		byte_D2
		LDX		byte_47
		LDA		byte_3A965,X
		JSR		sub_3A93C
		LDA		byte_47
		CMP		#$1D
		SEC
		BNE		locret_3A853
		LDA		#$FC
		JMP		sub_3A93C
loc_3A852:
		CLC
locret_3A853:
		RTS
loc_3A854:
		JSR		sub_3A8A4
		BCC		loc_3A852
		LDA		#$E2
		JMP		sub_3A93C

; =============== S U B	R O U T	I N E =======================================
sub_3A85E:
		JSR		sub_3A7E9
		JSR		sub_3A8BA
		BCC		loc_3A86F
		LDA		word_4
		BNE		loc_3A874
		LDA		#$EC
		JMP		sub_3A93C
loc_3A86F:
		LDA		#$EB
		JMP		sub_3A93C
loc_3A874:
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_3A876:
		JSR		sub_3A901
		BCC		loc_3A88B
		LDA		word_4
		STA		byte_D3
		JSR		sub_3A7E9
		LDA		byte_D3
		STA		byte_D2
		LDA		#$F1
		JMP		sub_3A93C
loc_3A88B:
		CLC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_3A88D:
		LDX		#0
loc_3A88F:
		TXA
		ASL
		TAY
		LDA		byte_530,Y
		AND		byte_531,Y
		BMI		loc_3A8A0
		INX
		CPX		#8
		BNE		loc_3A88F
		DEX
loc_3A8A0:
		STX		byte_64
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_3A8A4:
		LDX		#7
loc_3A8A6:
		TXA
		ASL
		TAY
		LDA		byte_530,Y
		BPL		loc_3A8B3
		LDA		byte_531,Y
		BPL		loc_3A8B8
loc_3A8B3:
		DEX
		BPL		loc_3A8A6
		CLC
		RTS
loc_3A8B8:
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_3A8BA:
		LDX		byte_4C
		DEX
		BNE		loc_3A8C1
		CLC
		RTS
loc_3A8C1:
		LDX		#0
		STX		word_4+1
loc_3A8C5:
		TXA
		ASL
		TAY
		LDA		byte_73C,Y
		AND		byte_73D,Y
		BPL		loc_3A8E4
		CPX		byte_CE
		BEQ		loc_3A8E4
		LDA		byte_6A9B,X
		AND		#8
		STA		word_4
		LDA		byte_73D,Y
		AND		#$40
		ORA		word_4
		BEQ		loc_3A8E6
loc_3A8E4:
		INC		word_4+1
loc_3A8E6:
		INX
		CPX		#4
		BNE		loc_3A8C5
		LDA		word_4+1
		PHA
		JSR		_sram_b0_s33
		DEC		word_4
		PLA
		SEC
		SBC		word_4
		BNE		loc_3A8FD
loc_3A8F9:
		STA		word_4
		SEC
		RTS
loc_3A8FD:
		LDA		#1
		BNE		loc_3A8F9

; =============== S U B	R O U T	I N E =======================================
sub_3A901:
		JSR		sub_3A8BA
		BCS		loc_3A907
		RTS
loc_3A907:
		LDX		#3
loc_3A909:
		TXA
		ASL
		TAY
		LDA		byte_73C,Y
		AND		byte_73D,Y
		BPL		loc_3A91F
		CPX		byte_CE
		BEQ		loc_3A91F
		LDA		byte_718,X
		AND		#8
		BNE		loc_3A924
loc_3A91F:
		DEX
		BPL		loc_3A909
		CLC
		RTS
loc_3A924:
		STX		word_4
		SEC
		RTS

; =============== S U B	R O U T	I N E =======================================
_b2_sE:
		LDA		off_3A944
		STA		word_3C
		LDA		off_3A944+1
		STA		word_3C+1
		LDA		byte_CE
		ASL
		ASL
		ASL
		LDX		#word_3C
		JMP		_add8_to_16	; A = value

; =============== S U B	R O U T	I N E =======================================
sub_3A93C:
		FARX	_b4_s8_msg_mFF_arg0_and_delay_or_wait_for_keypress
		FARX	_b4_s16_do_half_message_speed_delay
		SEC
		RTS
off_3A944:
		.WORD	byte_79C
off_3A946:
		.WORD	byte_3A948
byte_3A948:
		.BYTE	$FF,$FF,$FF,$FF, $F,  0,  0,  0
byte_3A950:
		.BYTE	$DE,$DD,$DF,$E6,$E7,$E8,$E9,$EE,$EF,$F7,$3A,$FD,$E1,$E2,  0,$D7
		.BYTE	$D9,$F2,$D6,$4B,$F4
byte_3A965:
		.BYTE	$DA,$E0,$E3,$F3,$F6,$F9,$FE,$D8,$FA,$EA,$F0,  4,$ED,$E5,$E4,$F8
		.BYTE	$40,$40,$17,$4D,$F5,$DB,$DB,$12,$12,$12,$12,$FF,$FF,$FB,$EB,$F1
off_3A985:
		.WORD	sub_3A7AA
		.WORD	sub_3A7B6
		.WORD	sub_3A7C4
		.WORD	sub_3A7DB

; =============== S U B	R O U T	I N E =======================================
_b2_sC:
		CPX		#5
		BNE		loc_3A994
		JSR		sub_3A9E8
loc_3A994:
		TAY
		PHA
		TXA
		CMP		#4
		BCS		loc_3A9A7
		CPY		#$40
		BCC		loc_3A9A7
		PLA
		SBC		#$40
		PHA
		TXA
		CLC
		ADC		#8
loc_3A9A7:
		ASL
		TAX
		LDA		_str_libs_list,X
		STA		word_6E
		LDA		_str_libs_list+1,X
		STA		word_6E+1
		LDY		#0
		PLA
		BEQ		loc_3A9CC
		TAX
loc_3A9B9:
		LDA		(word_6E),Y
		CMP		#$FF
		BEQ		loc_3A9C8
loc_3A9BF:
		INC		word_6E
		BNE		loc_3A9B9
		INC		word_6E+1
		JMP		loc_3A9B9
loc_3A9C8:
		DEX
		BNE		loc_3A9BF
		INY
loc_3A9CC:
		LDX		#$F
		LDA		#0
loc_3A9D0:
		STA		word_4,X
		DEX
		BPL		loc_3A9D0
loc_3A9D5:
		LDA		(word_6E),Y
		CMP		#$FF
		BEQ		loc_3A9E3
		STA		word_4+1,X
		INY
		INX
		CPX		#$F
		BCC		loc_3A9D5
loc_3A9E3:
		LDA		#$60
		STA		word_4+1,X
		RTS

; =============== S U B	R O U T	I N E =======================================
sub_3A9E8:
		TAY
		PHA
		TXA
		PHA
		TYA
		BNE		loc_3AA0A
		LDA		byte_60B7
		LSR
		BCC		loc_3AA0A
		LDA		#<[_str_lib_erdrick]
		STA		word_6E
		LDA		#>[_str_lib_erdrick]
		STA		word_6E+1
		LDX		#$FF
		LDY		#0
		PLA
		PLA
		PLA
		PLA
		JMP		loc_3A9D5
loc_3AA0A:
		PLA
		TAX
		PLA
		RTS
_str_libs_list:
		.WORD	_str_lib0_items_low0
		.WORD	_str_lib1_items_low1
		.WORD	_str_lib2_enemy_low0
		.WORD	_str_lib3_enemy_low1
		.WORD	_str_lib4_spells
		.WORD	_str_lib5_classes
		.WORD	_str_lib6_sex
		.WORD	_str_lib7_locations
		.WORD	_str_lib8_items_hi0
		.WORD	_str_lib9_items_hi1
		.WORD	_str_libA_enemy_hi0
		.WORD	_str_libB_enemy_hi1
		.WORD	_str_lib_erdrick
_str_lib5_classes:
		.BYTE	_H,_e,_r,_o,$FF
		.BYTE	_W,_i,_z,_a,_r,_d,$FF
		.BYTE	_P,_i,_l,_g,_r,_i,_m,$FF
		.BYTE	_S,_a,_g,_e,$FF
		.BYTE	_S,_o,_l,_d,_i,_e,_r,$FF
		.BYTE	_M,_e,_r,_c,_h,_a,_n,_t,$FF
		.BYTE	_F,_i,_g,_h,_t,_e,_r,$FF
		.BYTE	_G,_o,_o,_f,_str,_o,_f,_f,$FF
_str_lib_erdrick:
		.BYTE	_E,_r,_d,_r,_i,_c,_k,$FF
_str_lib6_sex:
		.BYTE	_M,_a,_l,_e,$FF
		.BYTE	_F,_e,_m,_a,_l,_e,$FF
_str_lib7_locations:
		.BYTE	_A,_l,_i,_a,_h,_a,_n,$FF
		.BYTE	_R,_e,_e,_v,_e,__,__,$FF
		.BYTE	_R,_o,_m,_a,_l,_y,__,__,$FF
		.BYTE	_K,_a,_n,_a,_v,_e,__,$FF
		.BYTE	_N,_o,_a,_n,_i,_e,_l,_s,$FF
		.BYTE	_A,_s,_s,_a,_r,_a,_m,$FF
		.BYTE	_I,_s,_i,_s,__,__,__,$FF
		.BYTE	_P,_o,_r,_t,_o,_g,_a,__,$FF
		.BYTE	_B,_a,_h,_a,_r,_a,_t,_a,$FF
		.BYTE	_D,_h,_a,_m,_a,__,__,$FF
		.BYTE	_L,_a,_n,_c,_e,_l,__,$FF
		.BYTE	_J,_i,_p,_a,_n,_g,__,$FF
		.BYTE	_E,_g,_i,_n,_b,_e,_a,_r,$FF
		.BYTE	_S,_a,_m,_a,_n,_a,_o,__,$FF
		.BYTE	_S,_o,_o,__,__,__,__,$FF
		.BYTE	_T,_a,_n,_t,_e,_g,_e,_l,$FF
		.BYTE	_H,_a,_u,_k,_s,_n,_e,_s,_s,$FF
		.BYTE	_C,_a,_n,_t,_l,_i,_n,$FF
		.BYTE	_K,_o,_l,__,__,__,__,$FF
		.BYTE	_R,_i,_m,_u,_l,_d,_a,_r,$FF
_str_lib4_spells:
		.BYTE	_B,_l,_a,_z,_e,$FF
		.BYTE	_B,_l,_a,_z,_e,_m,_o,_r,_e,$FF
		.BYTE	_B,_l,_a,_z,_e,_m,_o,_s,_t,$FF
		.BYTE	_F,_i,_r,_e,_b,_a,_l,$FF
		.BYTE	_F,_i,_r,_e,_b,_a,_n,_e,$FF
		.BYTE	_F,_i,_r,_e,_v,_o,_l,_t,$FF
		.BYTE	_B,_a,_n,_g,$FF
		.BYTE	_B,_o,_o,_m,$FF
		.BYTE	_E,_x,_p,_l,_o,_d,_e,_t,$FF
		.BYTE	_I,_c,_e,_B,_o,_l,_t,$FF
		.BYTE	_S,_n,_o,_w,_b,_l,_a,_s,_t,$FF
		.BYTE	_S,_n,_o,_w,_s,_t,_o,_r,_m,$FF
		.BYTE	_I,_c,_e,_S,_p,_e,_a,_r,_s,$FF
		.BYTE	_I,_n,_f,_e,_r,_n,_o,_s,$FF
		.BYTE	_I,_n,_f,_e,_r,_m,_o,_r,_e,$FF
		.BYTE	_I,_n,_f,_e,_r,_m,_o,_s,_t,$FF
		.BYTE	_Z,_a,_p,$FF
		.BYTE	_L,_i,_g,_h,_t,_n,_i,_n,_g,$FF
		.BYTE	_B,_e,_a,_t,$FF
		.BYTE	_D,_e,_f,_e,_a,_t,$FF
		.BYTE	_S,_a,_c,_r,_i,_f,_i,_c,_e,$FF
		.BYTE	_E,_x,_p,_e,_l,$FF
		.BYTE	_L,_i,_m,_b,_o,$FF
		.BYTE	_R,_o,_b,_M,_a,_g,_i,_c,$FF
		.BYTE	_S,_l,_o,_w,$FF
		.BYTE	_S,_p,_e,_e,_d,_U,_P,$FF
		.BYTE	_H,_e,_a,_l,$FF
		.BYTE	_H,_e,_a,_l,_m,_o,_r,_e,$FF
		.BYTE	_H,_e,_a,_l,_a,_l,_l,$FF
		.BYTE	  0,$FF
		.BYTE	_H,_e,_a,_l,_u,_s,$FF
		.BYTE	_H,_e,_a,_l,_u,_s,_a,_l,_l,$FF
		.BYTE	_V,_i,_v,_i,_f,_y,$FF
		.BYTE	_R,_e,_v,_i,_v,_e,$FF
		.BYTE	_S,_l,_e,_e,_p,$FF
		.BYTE	_A,_w,_a,_k,_e,$FF
		.BYTE	_S,_t,_o,_p,_S,_p,_e,_l,_l,$FF
		.BYTE	_S,_u,_r,_r,_o,_u,_n,_d,$FF
		.BYTE	_R,_e,_t,_u,_r,_n,$FF
		.BYTE	_C,_h,_a,_o,_s,$FF
		.BYTE	_T,_r,_a,_n,_s,_f,_o,_r,_m,$FF
		.BYTE	_B,_e,_D,_r,_a,_g,_o,_n,$FF
		.BYTE	_I,_r,_o,_n,_i,_z,_e,$FF
		.BYTE	_S,_a,_p,$FF
		.BYTE	_D,_e,_f,_e,_n,_c,_e,$FF
		.BYTE	_U,_p,_p,_e,_r,$FF
		.BYTE	_I,_n,_c,_r,_e,_a,_s,_e,$FF
		.BYTE	_I,_n,_c,_r,_e,_a,_s,_e,$FF
		.BYTE	_B,_o,_u,_n,_c,_e,$FF
		.BYTE	_B,_a,_r,_r,_i,_e,_r,$FF
		.BYTE	_B,_i,_k,_i,_l,_l,$FF
		.BYTE	_C,_h,_a,_n,_c,_e,$FF
		.BYTE	_A,_n,_t,_i,_d,_o,_t,_e,$FF
		.BYTE	_N,_u,_m,_b,_O,_f,_f,$FF
		.BYTE	_C,_u,_r,_s,_e,_O,_f,_f,$FF
		.BYTE	_R,_e,_p,_e,_l,$FF
		.BYTE	_D,_a,_y,_str,_N,_i,_g,_h,_t,$FF
		.BYTE	_O,_p,_e,_n,$FF
		.BYTE	_X,_str,_R,_a,_y,$FF
		.BYTE	_O,_u,_t,_s,_i,_d,_e,$FF
		.BYTE	_I,_n,_v,_i,_s,_i,_b,_l,_e,$FF
		.BYTE	_S,_t,_e,_p,_G,_u,_a,_r,_d,$FF
_str_lib0_items_low0:
		.BYTE	_C,_y,_p,_r,_e,_s,_s ,$FF
		.BYTE	_C,_l,_u,_b,$FF
		.BYTE	_C,_o,_p,_p,_e,_r,$FF
		.BYTE	_M,_a,_g,_i,_c,$FF
		.BYTE	_I,_r,_o,_n,$FF
		.BYTE	_B,_a,_t,_t,_l,_e,$FF
		.BYTE	_B,_r,_o,_a,_d,$FF
		.BYTE	_W,_i,_z,_a,_r,_d,_apo,_s,$FF
		.BYTE	_P,_o,_i,_s,_o,_n,$FF
		.BYTE	_I,_r,_o,_n,$FF
		.BYTE	_T,_h,_o,_r,_n,$FF
		.BYTE	_G,_i,_a,_n,_t,$FF
		.BYTE	_C,_h,_a,_i,_n,$FF
		.BYTE	_T,_h,_o,_r,_apo,_s,$FF
		.BYTE	_S,_n,_o,_w,_b,_l,_a,_s,_t,$FF
		.BYTE	_D,_e,_m,_o,_n,$FF
		.BYTE	_S,_t,_a,_f,_f,___,_o,_f,$FF
		.BYTE	_S,_w,_o,_r,_d,___,_o,_f,$FF
		.BYTE	_S,_t,_a,_f,_f,___,_o,_f,$FF
		.BYTE	_S,_w,_o,_r,_d,___,_o,_f,$FF
		.BYTE	_M,_u,_l,_t,_i,_str,_e,_d,_g,_e,$FF
		.BYTE	_S,_t,_a,_f,_f,___,_o,_f,$FF
		.BYTE	_S,_w,_o,_r,_d,___,_o,_f,$FF
		.BYTE	_Z,_o,_m,_b,_i,_e,$FF
		.BYTE	_F,_a,_l,_c,_o,_n,$FF
		.BYTE	_S,_l,_e,_d,_g,_e,$FF
		.BYTE	_T,_h,_u,_n,_d,_e,_r,$FF
		.BYTE	_S,_t,_a,_f,_f,___,_o,_f,$FF
		.BYTE	_S,_w,_o,_r,_d,___,_o,_f,$FF
		.BYTE	_O,_r,_o,_c,_h,_i,$FF
		.BYTE	_D,_r,_a,_g,_o,_n,$FF
		.BYTE	_S,_t,_a,_f,_f,___,_o,_f,$FF
		.BYTE	_C,_l,_o,_t,_h,_e,_s,$FF
		.BYTE	_T,_r,_a,_i,_n,_i,_n,_g,$FF
		.BYTE	_L,_e,_a,_t,_h,_e,_r,$FF
		.BYTE	_F,_l,_a,_s,_h,_y,$FF
		.BYTE	_H,_a,_l,_f,___,_P,_l,_a,_t,_e,$FF
		.BYTE	_F,_u,_l,_l,___,_P,_l,_a,_t,_e,$FF
		.BYTE	_M,_a,_g,_i,_c,$FF
		.BYTE	_C,_l,_o,_a,_k,___,_o,_f,$FF
		.BYTE	_A,_r,_m,_o,_r,___,_o,_f,$FF
		.BYTE	_I,_r,_o,_n,$FF
		.BYTE	_A,_n,_i,_m,_a,_l,$FF
		.BYTE	_F,_i,_g,_h,_t,_i,_n,_g,$FF
		.BYTE	_S,_a,_c,_r,_e,_d,$FF
		.BYTE	_A,_r,_m,_o,_r,___,_o,_f,$FF
		.BYTE	_W,_a,_t,_e,_r,___,_F,_l,_y,_i,_n,_g,$FF
		.BYTE	_C,_h,_a,_i,_n,$FF
		.BYTE	_W,_a,_y,_f,_a,_r,_e,_r,_apo,_s,$FF
		.BYTE	_R,_e,_v,_e,_a,_l,_i,_n,_g,$FF
		.BYTE	_M,_a,_g,_i,_c,$FF
		.BYTE	_S,_h,_e,_l,_l,$FF
		.BYTE	_A,_r,_m,_o,_r,___,_o,_f,$FF
		.BYTE	_D,_r,_a,_g,_o,_n,$FF
		.BYTE	_S,_w,_o,_r,_d,_e,_d,_g,_e,$FF
		.BYTE	_A,_n,_g,_e,_l,_apo,_s,$FF
		.BYTE	_L,_e,_a,_t,_h,_e,_r,$FF
		.BYTE	_I,_r,_o,_n,$FF
		.BYTE	_S,_h,_i,_e,_l,_d,___,_o,_f,$FF
		.BYTE	_S,_h,_i,_e,_l,_d,___,_o,_f,$FF
		.BYTE	_S,_h,_i,_e,_l,_d,___,_o,_f,$FF
		.BYTE	_B,_r,_o,_n,_z,_e,$FF
		.BYTE	_S,_i,_l,_v,_e,_r,$FF
		.BYTE	_G,_o,_l,_d,_e,_n,$FF
_str_lib8_items_hi0:
		.BYTE	_I,_r,_o,_n ,$FF
		.BYTE	_M,_y,_s,_t,_e,_r,_i,_o,_u,_s,$FF
		.BYTE	_U,_n,_l,_u,_c,_k,_y,$FF
		.BYTE	_T,_u,_r,_b,_a,_n,$FF
		.BYTE	_N,_o,_h,$FF
		.BYTE	_L,_e,_a,_t,_h,_e,_r,$FF
		.BYTE	_I,_r,_o,_n,$FF
		.BYTE	_S,_a,_c,_r,_e,_d,$FF
		.BYTE	_R,_i,_n,_g,___,_o,_f,$FF
		.BYTE	_S,_h,_o,_e,_s,___,_o,_f,$FF
		.BYTE	_G,_o,_l,_d,_e,_n,$FF
		.BYTE	_M,_e,_t,_e,_o,_r,_i,_t,_e,$FF
		.BYTE	_B,_o,_o,_k,___,_o,_f,$FF
		.BYTE	___,___,$FF
		.BYTE	_W,_i,_z,_a,_r,_d,_apo,_s,$FF
		.BYTE	_B,_l,_a,_c,_k,$FF
		.BYTE	_S,_a,_g,_e,_apo,_s,$FF
		.BYTE	_M,_i,_r,_r,_o,_r,___,_o,_f,$FF
		.BYTE	_V,_a,_s,_e,___,_o,_f,$FF
		.BYTE	_L,_a,_m,_p,___,_o,_f,$FF
		.BYTE	_S,_t,_a,_f,_f,___,_o,_f,$FF
		.BYTE	_S,_t,_o,_n,_e,___,_o,_f,$FF
		.BYTE	_I,_n,_v,_i,_s,_i,_b,_i,_l,_i,_t,_y,$FF
		.BYTE	_M,_a,_g,_i,_c,$FF
		.BYTE	_T,_h,_i,_e,_f,_apo,_s,$FF
		.BYTE	_M,_a,_g,_i,_c,$FF
		.BYTE	_F,_i,_n,_a,_l,$FF
		.BYTE	_D,_r,_e,_a,_m,$FF
		.BYTE	_W,_a,_k,_e,___,_U,_p,$FF
		.BYTE	_R,_o,_y,_a,_l,$FF
		.BYTE	_O,_r,_i,_c,_o,_n,$FF
		.BYTE	_S,_t,_r,_e,_n,_g,_t,_h,$FF
		.BYTE	_A,_g,_i,_l,_i,_t,_y,$FF
		.BYTE	_V,_i,_t,_a,_l,_i,_t,_y,$FF
		.BYTE	_L,_u,_c,_k,$FF
		.BYTE	_I,_n,_t,_e,_l,_l,_i,_g,_e,_n,_c,_e,$FF
		.BYTE	_A,_c,_o,_r,_n,_s,___,_o,_f,$FF
		.BYTE	_M,_e,_d,_i,_c,_a,_l,$FF
		.BYTE	_A,_n,_t,_i,_d,_o,_t,_e,$FF
		.BYTE	_F,_a,_i,_r,_y,$FF
		.BYTE	_W,_i,_n,_g,___,_o,_f,$FF
		.BYTE	_L,_e,_a,_f,___,_o,_f,$FF
		.BYTE	___,___,___,$FF
		.BYTE	_L,_o,_c,_k,_e,_t,___,_o,_f,$FF
		.BYTE	_F,_u,_l,_l,___,_M,_o,_o,_n,$FF
		.BYTE	_W,_a,_t,_e,_r,$FF
		.BYTE	_S,_a,_i,_l,_o,_r,_apo,_s,$FF
		.BYTE	_E,_c,_h,_o,_i,_n,_g,$FF
		.BYTE	_F,_a,_i,_r,_y,$FF
		.BYTE	_S,_i,_l,_v,_e,_r,$FF
		.BYTE	_S,_p,_h,_e,_r,_e,___,_o,_f,$FF
		.BYTE	_P,_o,_i,_s,_o,_n,___,_M,_o,_t,_h,$FF
		.BYTE	_S,_p,_i,_d,_e,_r,_apo,_s,$FF
		.BYTE	_S,_t,_o,_n,_e,___,_o,_f,$FF
		.BYTE	_R,_a,_i,_n,_b,_o,_w,$FF
		.BYTE	_S,_i,_l,_v,_e,_r,$FF
		.BYTE	_R,_e,_d,$FF
		.BYTE	_Y,_e,_l,_l,_o,_w,$FF
		.BYTE	_P,_u,_r,_p,_l,_e,$FF
		.BYTE	_B,_l,_u,_e,$FF
		.BYTE	_G,_r,_e,_e,_n,$FF
_str_lib1_items_low1:
		.BYTE	_S,_t,_i,_c,_k,$FF
		.BYTE	$FF
		.BYTE	_S,_w,_o,_r,_d,$FF
		.BYTE	_K,_n,_i,_f,_e,$FF
		.BYTE	_S,_p,_e,_a,_r,$FF
		.BYTE	_A,_x,_e,$FF
		.BYTE	_S,_w,_o,_r,_d,$FF
		.BYTE	_W,_a,_n,_d,$FF
		.BYTE	_N,_e,_e,_d,_l,_e,$FF
		.BYTE	_C,_l,_a,_w,$FF
		.BYTE	_W,_h,_i,_p,$FF
		.BYTE	_S,_h,_e,_a,_r,_s,$FF
		.BYTE	_S,_i,_c,_k,_l,_e,$FF
		.BYTE	_S,_w,_o,_r,_d,$FF
		.BYTE	_S,_w,_o,_r,_d,$FF
		.BYTE	_A,_x,_e,$FF
		.BYTE	_R,_a,_i,_n,$FF
		.BYTE	_G,_a,_i,_a,$FF
		.BYTE	_R,_e,_f,_l,_e,_c,_t,_i,_o,_n,$FF
		.BYTE	_D,_e,_s,_t,_r,_u,_c,_t,_i,_o,_n,$FF
		.BYTE	_S,_w,_o,_r,_d,$FF
		.BYTE	_F,_o,_r,_c,_e,$FF
		.BYTE	_I,_l,_l,_u,_s,_i,_o,_n,$FF
		.BYTE	_S,_l,_a,_s,_h,_e,_r,$FF
		.BYTE	_S,_w,_o,_r,_d,$FF
		.BYTE	_H,_a,_m,_m,_e,_r,$FF
		.BYTE	_S,_w,_o,_r,_d,$FF
		.BYTE	_T,_h,_u,_n,_d,_e,_r,$FF
		.BYTE	_K,_i,_n,_g,_s,$FF
		.BYTE	_S,_w,_o,_r,_d,$FF
		.BYTE	_K,_i,_l,_l,_e,_r,$FF
		.BYTE	_J,_u,_d,_g,_m,_e,_n,_t,$FF
		.BYTE	$FF
		.BYTE	_S,_u,_i,_t,$FF
		.BYTE	_A,_r,_m,_o,_r,$FF
		.BYTE	_C,_l,_o,_t,_h,_e,_s,$FF
		.BYTE	_A,_r,_m,_o,_r,$FF
		.BYTE	_A,_r,_m,_o,_r,$FF
		.BYTE	_A,_r,_m,_o,_r,$FF
		.BYTE	_E,_v,_a,_s,_i,_o,_n,$FF
		.BYTE	_R,_a,_d,_i,_a,_n,_c,_e,$FF
		.BYTE	_A,_p,_r,_o,_n,$FF
		.BYTE	_S,_u,_i,_t,$FF
		.BYTE	_S,_u,_i,_t,$FF
		.BYTE	_R,_o,_b,_e,$FF
		.BYTE	_H,_a,_d,_e,_s,$FF
		.BYTE	_C,_l,_o,_t,_h,$FF
		.BYTE	_M,_a,_i,_l,$FF
		.BYTE	_C,_l,_o,_t,_h,_e,_s,$FF
		.BYTE	_S,_w,_i,_m,_s,_u,_i,_t,$FF
		.BYTE	_B,_i,_k,_i,_n,_i,$FF
		.BYTE	_A,_r,_m,_o,_r,$FF
		.BYTE	_T,_e,_r,_r,_a,_f,_i,_r,_m,_a,$FF
		.BYTE	_M,_a,_i,_l,$FF
		.BYTE	_A,_r,_m,_o,_r,$FF
		.BYTE	_R,_o,_b,_e,$FF
		.BYTE	_S,_h,_i,_e,_l,_d,$FF
		.BYTE	_S,_h,_i,_e,_l,_d,$FF
		.BYTE	_S,_t,_r,_e,_n,_g,_t,_h,$FF
		.BYTE	_H,_e,_r,_o,_e,_s,$FF
		.BYTE	_S,_o,_r,_r,_o,_w,$FF
		.BYTE	_S,_h,_i,_e,_l,_d,$FF
		.BYTE	_S,_h,_i,_e,_l,_d,$FF
		.BYTE	_C,_r,_o,_w,_n,$FF
_str_lib9_items_hi1:
		.BYTE	_H,_e,_l,_m,_e,_t ,$FF
		.BYTE	_H,_a,_t,$FF
		.BYTE	_H,_e,_l,_m,_e,_t,$FF
		.BYTE	$FF
		.BYTE	_M,_a,_s,_k,$FF
		.BYTE	_H,_e,_l,_m,_e,_t,$FF
		.BYTE	_M,_a,_s,_k,$FF
		.BYTE	_A,_m,_u,_l,_e,_t,$FF
		.BYTE	_L,_i,_f,_e,$FF
		.BYTE	_H,_a,_p,_p,_i,_n,_e,_s,_s,$FF
		.BYTE	_C,_l,_a,_w,$FF
		.BYTE	_A,_r,_m,_b,_a,_n,_d,$FF
		.BYTE	_S,_a,_t,_o,_r,_i,$FF
		.BYTE	$FF
		.BYTE	_R,_i,_n,_g,$FF
		.BYTE	_P,_e,_p,_p,_e,_r,$FF
		.BYTE	_S,_t,_o,_n,_e,$FF
		.BYTE	_R,_a,$FF
		.BYTE	_D,_r,_o,_u,_g,_h,_t,$FF
		.BYTE	_D,_a,_r,_k,_n,_e,_s,_s,$FF
		.BYTE	_C,_h,_a,_n,_g,_e,$FF
		.BYTE	_L,_i,_f,_e,$FF
		.BYTE	_H,_e,_r,_b,$FF
		.BYTE	_B,_a,_l,_l,$FF
		.BYTE	_K,_e,_y,$FF
		.BYTE	_K,_e,_y,$FF
		.BYTE	_K,_e,_y,$FF
		.BYTE	_R,_u,_b,_y,$FF
		.BYTE	_P,_o,_w,_d,_e,_r,$FF
		.BYTE	_S,_c,_r,_o,_l,_l,$FF
		.BYTE	$FF
		.BYTE	_S,_e,_e,_d,$FF
		.BYTE	_S,_e,_e,_d,$FF
		.BYTE	_S,_e,_e,_d,$FF
		.BYTE	_S,_e,_e,_d,$FF
		.BYTE	_S,_e,_e,_d,$FF
		.BYTE	_L,_i,_f,_e,$FF
		.BYTE	_H,_e,_r,_b,$FF
		.BYTE	_H,_e,_r,_b,$FF
		.BYTE	_W,_a,_t,_e,_r,$FF
		.BYTE	_W,_y,_v,_e,_r,_n,$FF
		.BYTE	_W,_o,_r,_l,_d,___,_T,_r,_e,_e,$FF
		.BYTE	$FF
		.BYTE	_L,_o,_v,_e,$FF
		.BYTE	_H,_e,_r,_b,$FF
		.BYTE	_B,_l,_a,_s,_t,_e,_r,$FF
		.BYTE	_T,_h,_i,_g,_h,___,_B,_o,_n,_e,$FF
		.BYTE	_F,_l,_u,_t,_e,$FF
		.BYTE	_F,_l,_u,_t,_e,$FF
		.BYTE	_H,_a,_r,_p,$FF
		.BYTE	_L,_i,_g,_h,_t,$FF
		.BYTE	_P,_o,_w,_d,_e,_r,$FF
		.BYTE	_W,_e,_b,$FF
		.BYTE	_S,_u,_n,_l,_i,_g,_h,_t,$FF
		.BYTE	_D,_r,_o,_p,$FF
		.BYTE	_O,_r,_b,$FF
		.BYTE	_O,_r,_b,$FF
		.BYTE	_O,_r,_b,$FF
		.BYTE	_O,_r,_b,$FF
		.BYTE	_O,_r,_b,$FF
		.BYTE	_O,_r,_b,$FF
_str_lib2_enemy_low0:
		.BYTE	_S,_l,_i,_m,_e,$A5,$FF
		.BYTE	_B,_l,_a,_c,_k,___,_R,_a,_v,_e,_n,$A5,$FF
		.BYTE	_H,_o,_r,_n,_e,_d,$FF
		.BYTE	_G,_i,_a,_n,_t,$FF
		.BYTE	_M,_a,_s,_k,_e,_d,___,_M,_o,_t,_h,$A5,$FF
		.BYTE	_F,_r,_o,_g,_g,_o,_r,_e,$A5,$FF
		.BYTE	_B,_a,_b,_b,_l,_e,$A5,$FF
		.BYTE	_M,_a,_g,_i,_c,_i,_a,_n,$A5,$FF
		.BYTE	_S,_c,_o,_r,_p,_i,_o,_n,$FF
		.BYTE	_H,_e,_a,_l,_e,_r,$A5,$FF
		.BYTE	_D,_e,_m,_o,_n,$FF
		.BYTE	_S,_p,_i,_k,_e,_d,___,_H,_a,_r,_e,$A5,$FF
		.BYTE	_P,_o,_i,_s,_o,_n,___,_T,_o,_a,_d,$A5,$FF
		.BYTE	_C,_a,_t,_e,_r,_p,_i,_l,_l,_a,_r,$A5,$FF
		.BYTE	_H,_u,_m,_a,_n,_a,_b,_a,_t,$A5,$FF
		.BYTE	_P,_u,_t,_r,_e,_p,_u,_p,$A5,$FF
		.BYTE	_K,_i,_l,_l,_e,_r,___,_B,_e,_e,$A5,$FF
		.BYTE	_A,_r,_m,_y,___,_C,_r,_a,_b,$A5,$FF
		.BYTE	_G,_a,_s,___,_C,_l,_o,_u,_d,$A5,$FF
		.BYTE	_D,_e,_m,_o,_n,___,_T,_o,_a,_d,_s,_t,_o,_o,_l,$A5,$FF
		.BYTE	_P,_o,_i,_s,_o,_n,$FF
		.BYTE	_A,_v,_e,_n,_g,_e,_r,$FF
		.BYTE	_M,_a,_d,_h,_o,_u,_n,_d,$A5,$FF
		.BYTE	_D,_e,_a,_d,_l,_y,$FF
		.BYTE	_S,_h,_a,_d,_o,_w,$A5,$FF
		.BYTE	_V,_a,_m,_p,_i,_r,_e,$A5,$FF
		.BYTE	_M,_a,_n,_str,_E,_a,_t,_e,_r,$FF
		.BYTE	_R,_o,_g,_u,_e,$FF
		.BYTE	_V,_a,_m,_p,_i,_r,_e,___,_C,_a,_t,$A5,$FF
		.BYTE	_K,_i,_n,_g,$FF
		.BYTE	_W,_i,_l,_d,___,_A,_p,_e,$A5,$FF
		.BYTE	_T,_r,_i,_c,_k,___,_B,_a,_g,$A5,$FF
		.BYTE	_M,_u,_m,_m,_y,___,_M,$A1,$FF
		.BYTE	_I,_n,_f,_e,_r,_n,_u,_s,$FF
		.BYTE	_L,_u,_m,_p,_u,_s,$A7,$FF
		.BYTE	_F,_l,_a,_m,_a,_p,_e,_d,_e,$A5,$FF
		.BYTE	_M,_u,_m,_m,$A0,$FF
		.BYTE	_M,_a,_g,_e,$FF
		.BYTE	_H,_u,_n,_t,_e,_r,$FF
		.BYTE	_A,_v,_e,_n,_g,_e,_r,$FF
		.BYTE	_N,_e,_v,$A5,$FF
		.BYTE	_H,_e,_a,_t,___,_C,_l,_o,_u,_d,$A5,$FF
		.BYTE	_T,_o,_n,_g,_u,_e,_b,_e,_a,_r,$A5,$FF
		.BYTE	_C,_u,_r,_e,_r,$A5,$FF
		.BYTE	_R,_a,_m,_m,_o,_r,_e,$A5,$FF
		.BYTE	_C,_a,_t,_u,_l,_a,$A5,$FF
		.BYTE	_E,_v,_i,_l,___,_M,_a,_g,_e,$A5,$FF
		.BYTE	_S,_i,_m,_i,_a,_c,$A5,$FF
		.BYTE	_G,_a,_r,_u,_d,_a,$A5,$FF
		.BYTE	_M,_e,_t,_a,_l,___,_S,_l,_i,_m,_e,$A5,$FF
		.BYTE	_G,_o,_a,_t,_e,_g,_o,_n,$A5,$FF
		.BYTE	_E,_x,_e,_c,_u,_t,_i,_o,_n,_e,_r,$A5,$FF
		.BYTE	_D,_e,_m,_o,_n,_i,_t,_e,$A5,$FF
		.BYTE	_D,_e,_r,_a,_n,_g,_e,_r,$A5,$FF
		.BYTE	_M,_a,_n,_str,_E,_a,_t,_e,_r,$FF
		.BYTE	_E,_l,_i,_m,_i,_n,_a,_t,_o,_r,$A5,$FF
		.BYTE	_G,_r,_e,_a,_t,___,_B,_e,_a,_k,$A5,$FF
		.BYTE	_S,_l,_i,_m,_e,___,_S,_n,_a,_i,$A3,$FF
		.BYTE	_S,_k,_y,___,_D,_r,_a,_g,_o,_n,$A5,$FF
		.BYTE	_B,_a,_r,_n,_a,_b,_a,_s,$A7,$FF
		.BYTE	_W,_i,_t,_c,_h,$A4,$FF
		.BYTE	_A,_v,_e,_n,_g,_e,_r,$FF
		.BYTE	_I,_n,_f,_e,_r,_n,_u,_s,$FF
		.BYTE	_M,_a,_r,_i,_n,_e,$FF
_str_libA_enemy_hi0:
		.BYTE	_M,_a,_n,___,_O,_apo,___,_W,_a,_r,$A5,$FF
		.BYTE	_M,_e,_r,_z,_o,_n,$A5,$FF
		.BYTE	_K,_i,_n,_g,___,_S,_q,_u,_i,_d,$A5,$FF
		.BYTE	_C,_r,_a,_b,_u,_s,$A7,$FF
		.BYTE	_M,_e,_r,_z,_o,_n,_c,_i,_a,_n,$A5,$FF
		.BYTE	_H,_a,_d,_e,_s,_apo,$FF
		.BYTE	_F,_i,_e,_r,_c,_e,___,_B,_e,_a,_r,$A5,$FF
		.BYTE	_H,_o,_r,_k,$A5,$FF
		.BYTE	_B,_i,_g,_h,_o,_r,_n,$A5,$FF
		.BYTE	_S,_t,_i,_n,_g,_w,_i,_n,_g,$A5,$FF
		.BYTE	_V,_e,_n,_o,_m,$FF
		.BYTE	_B,_l,_u,_e,___,_B,_e,_a,_k,$A5,$FF
		.BYTE	_L,_e,_t,_h,_a,_l,$FF
		.BYTE	_A,_v,_e,_n,_g,_e,_r,$A5,$FF
		.BYTE	_L,_a,_v,$A6,$FF
		.BYTE	_W,_i,_t,_c,_h,$FF
		.BYTE	_O,_l,_d,___,_H,_a,_g,$A5,$FF
		.BYTE	_T,_e,_r,_r,_o,_r,$FF
		.BYTE	_G,_l,_a,_c,_i,_e,_r,$FF
		.BYTE	_W,_y,_v,_e,_r,_n,$A5,$FF
		.BYTE	_K,_o,_n,_g,$A5,$FF
		.BYTE	_T,_o,_r,_t,_r,_a,_g,_o,_n,$A5,$FF
		.BYTE	_E,_l,_y,_s,_i,_u,_m,$FF
		.BYTE	_B,_o,_m,_b,___,_C,_r,_a,_g,$A5,$FF
		.BYTE	_G,_r,_i,_z,_z,_l,$A0,$FF
		.BYTE	_V,_o,_o,_d,_o,_o,$FF
		.BYTE	_K,_i,_n,_g,$FF
		.BYTE	_S,_n,_o,_w,___,_D,_r,_a,_g,_o,_n,$A5,$FF
		.BYTE	_T,_r,_o,_l,_l,$A5,$FF
		.BYTE	_F,_r,_o,_s,_t,___,_C,_l,_o,_u,_d,$A5,$FF
		.BYTE	_D,_a,_n,_c,_i,_n,_g,$FF
		.BYTE	_M,_i,_n,_i,_d,_e,_m,_o,_n,$A5,$FF
		.BYTE	_T,_e,_n,_t,_a,_c,_l,_e,_s,$A7,$FF
		.BYTE	_S,_k,_e,_l,_e,_t,_o,_n,$A5,$FF
		.BYTE	_M,_i,_m,_i,_c,$A5,$FF
		.BYTE	_M,_a,_r,_a,_u,_d,_e,_r,$A5,$FF
		.BYTE	_H,_o,_l,_o,_g,_h,_o,_s,_t,$A5,$FF
		.BYTE	_O,_r,_o,_c,_h,_i,$A5,$FF
		.BYTE	_S,_t,_o,_n,_e,$FF
		.BYTE	_S,_a,_l,_a,_m,_a,_n,_d,_e,_r,$A5,$FF
		.BYTE	_R,_e,_d,___,_S,_l,_i,_m,_e,$A5,$FF
		.BYTE	_G,_o,_o,_p,_i,$A4,$FF
		.BYTE	_V,_i,_l,_e,___,_S,_h,_a,_d,_o,_w,$A5,$FF
		.BYTE	_V,_o,_o,_d,_o,_o,$FF
		.BYTE	_M,_e,_t,_a,_l,$FF
		.BYTE	_G,_h,_o,_u,_l,$A5,$FF
		.BYTE	_L,_i,_o,_n,_h,_e,_a,_d,$A5,$FF
		.BYTE	_B,_o,_s,_s,___,_T,_r,_o,_l,_l,$A5,$FF
		.BYTE	_G,_o,_l,_d,___,_B,_a,_s,_h,_e,_r,$A5,$FF
		.BYTE	_S,_c,_a,_l,_g,_o,_n,$A5,$FF
		.BYTE	_K,_i,_n,_g,___,_M,_e,_r,_z,_o,_n,$A5,$FF
		.BYTE	_K,_r,_a,_g,_a,_c,_l,_e,_s,$A7,$FF
		.BYTE	_D,_a,_r,_t,_h,_b,_e,_a,_r,$A5,$FF
		.BYTE	_G,_r,_a,_n,_i,_t,_e,$FF
		.BYTE	_L,_e,_o,_n,_a,$A5,$FF
		.BYTE	_A,_r,_c,_h,_m,_a,_g,_e,$A5,$FF
		.BYTE	_M,_a,_g,_i,_w,_y,_v,_e,_r,_n,$A5,$FF
		.BYTE	_W,_i,_n,_g,_e,_d,$FF
		.BYTE	_H,_y,_d,_r,_a,$A5,$FF
		.BYTE	_T,_r,_o,_l,_l,___,_K,_i,_n,_g,$A5,$FF
		.BYTE	_G,_r,_e,_e,_n,$FF
		.BYTE	_B,_a,_r,_o,_g,$A5,$FF
		.BYTE	_P,_u,_t,_r,_e,_g,_o,_n,$A5,$FF
		.BYTE	_L,_i,_o,_n,_r,_o,_a,_r,$A5,$FF
		.BYTE	_S,_w,_o,_r,_d,_o,_i,_d,$A5,$FF
		.BYTE	_K,_i,_n,_g,___,_H,_y,_d,_r,_a,$A5,$FF
		.BYTE	_B,_a,_r,_a,_m,_o,_s,$FF
		.BYTE	_B,_a,_r,_a,_m,_o,_s,$FF
		.BYTE	_B,_a,_r,_a,_m,_o,_s,$A5,$FF
		.BYTE	_Z,_o,_m,_a,$A5,$FF
		.BYTE	_Z,_o,_m,_a,$A5,$FF
		.BYTE	_O,_r,_t,_e,_g,_a,$A5,$FF
		.BYTE	_K,_a,_n,_d,_a,_r,$A5,$FF
		.BYTE	_K,_a,_n,_d,_a,_r,$A5,$FF
		.BYTE	_K,_a,_n,_d,_a,_r,$FF
_str_lib3_enemy_low1:
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	_R,_a,_b,_b,_i,_t,$A5,$FF
		.BYTE	_A,_n,_t,_e,_a,_t,_e,_r,$A5,$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	_W,_a,_s,_p,$A5,$FF
		.BYTE	$FF
		.BYTE	_A,_n,_t,_e,_a,_t,_e,_r,$A5,$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	_S,_i,_l,_k,_w,_o,_r,_m,$A5,$FF
		.BYTE	_R,_a,_v,_e,_n,$A5,$FF
		.BYTE	$FF
		.BYTE	_T,_o,_a,_d,_s,_t,_o,_o,_l,$A5,$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	_M,_o,_t,_h,$A5,$FF
		.BYTE	_K,_n,_i,_g,_h,_t,$A5,$FF,$FF
		.BYTE	_F,_r,_o,_g,_g,_o,_r,_e,$A5,$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	_C,_r,_a,_b,$A5,$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	_T,_o,_a,_d,_s,_t,_o,$A2,$FF
		.BYTE	_F,_l,$A0,$FF
		.BYTE	_J,_a,_c,_k,_a,_l,$A5,$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	_C,_h,_e,_s,_t,$A5,$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	_B,_e,_a,_k,$A5,$FF
		.BYTE	_K,_n,_i,_g,_h,_t,$A5,$FF
		.BYTE	_S,_l,_i,_m,_e,$A5,$FF
_str_libB_enemy_hi1:
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	_C,_o,_n,_d,_o,_r,$A5,$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	_Z,_o,_m,_b,_i,_e,$A5,$FF
		.BYTE	$FF
		.BYTE	_A,_r,_m,_o,_r,$A5,$FF
		.BYTE	$FF
		.BYTE	_B,_a,_s,_h,_e,_r,$FF
		.BYTE	_D,_o,_c,_t,_o,_r,$A5,$FF
		.BYTE	$FF
		.BYTE	_S,_h,_a,_d,_o,_w,$A5,$FF
		.BYTE	_B,_a,_s,_h,_e,_r,$A5,$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	_B,_i,_r,_d,$A5,$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	_S,_h,_a,_m,_a,_n,$A5,$FF
		.BYTE	_T,_o,_r,_t,_r,_a,_g,_o,_n,$A5,$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	_J,_e,_w,_e,_l,$A5,$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	_H,_u,_l,_k,$A5,$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	_W,_a,_r,_l,_o,_c,_k,$A5,$FF
		.BYTE	_B,_a,_b,_b,_l,_e,$A5,$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	_T,_i,_t,_a,_n,$A5,$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	_D,_e,_m,_o,_n,$A5,$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	_D,_r,_a,_g,_o,_n,$A5,$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	_B,_o,_m,_u,_s,$A5,$FF
		.BYTE	_G,_o,_n,_u,_s,$A5,$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	_H,_e,_n,_c,_h,_m,$A1,$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF
		.BYTE	$FF

		ECHO "bank 02 free space", [$BFD8-.]

		ORG $BFD8
		SEI
		INC	$BFDF
		JMP	_RESET
		.BYTE	$80
		.BYTE	"DRAGON WARRIOR "
		.BYTE	$33
		.WORD	$FFFF
		.WORD	0
		.BYTE	$48
		.BYTE	  4
		.BYTE	  1
		.BYTE	$F
		.BYTE	  7
		.BYTE	$9D
		.WORD	$BFD8
		.WORD	$BFD8
		.WORD	$BFD8
