; SOUNDS: (for an easy but lousy test, change $3d929 in the rom and go up or down stairs)
BGM_SILENCE = $00
BGM_LEVELUP = $01
BGM_DQ_THEME = $02
BGM_NOCHANGE_03 = $03
BGM_OVERWORLD = $04
BGM_ALEFGARD = $05
BGM_ORIENTAL = $06
BGM_DUNGEON = $07
BGM_TOWER = $08
BGM_DUNGEON_ORIENTAL_09 = $09 ; pyramid?
BGM_SHRINE = $0A
BGM_SAILING = $0B 
BGM_0C = $0C ; something plot sounding jingle
BGM_VILLAGE = $0D
BGM_FLYING = $0E
BGM_TOWN = $0F
BGM_BATTLE = $10
BGM_EVIL_11 = $11
BGM_EVIL_12 = $12 ; final battle? zoma battle?
BGM_DEAD_13 = $13
BGM_SLEEP_JINGLE = $14
BGM_PRIEST_WORK_JINGLE = $15
BGM_VICTORY_JINGLE = $16
BGM_CURSE_JINGLE = $17
BGM_INSTRUMENT_JINGLE_18 = $18
BGM_ENDTHEME_19 = $19
BGM_INSTRUMENT_JINGLE_1A = $1A
BGM_INSTRUMENT_JINGLE_1B = $1B
BGM_INSTRUMENT_JINGLE_1C = $1C
BGM_INSTRUMENT_JINGLE_1D = $1D
BGM_INSTRUMENT_JINGLE_1E = $1E
BGM_ENDING_1F = $1F
BGM_QUAKE_20 = $20
BGM_QUAKE_21 = $21
BGM_QUAKE_22 = $22
BGM_EXPLOSION_HISSING = $23
BGM_WIND_24 = $24
BGM_WIND_25 = $25
BGM_ENDING_26 = $26
BGM_DQ3_THEME = $27
BGM_MENU = $28

; ..junk..

SFX_NOCHANGE_80 = $80
SFX_TRAP_TILE = $81
SFX_STAIRSTEPS = $82
SFX_RUNAWAY = $83
SFX_POISON_TILE = $84
SFX_MENU_TINK = $85
SFX_MENU_PROMPT = $86

;87 SFX sweeping down hit
;88 SFX crit!
;89 SFX player windup
;8A SFX sweeping up hit
;8B SFX enemy windup
;8C SFX attack miss (low pitched)
;8D SFX attack miss (high pitched)
SFX_ENEMY_CASTING = $8E
SFX_OPEN_CHEST = $8F
SFX_OPEN_DOOR = $90
;91 SFX low flame
;92 SFX warp/WoW
;93 SFX fall
SFX_TRAVEL_GATE = $94
SFX_BLAST_95 = $95
;96 SFX unknown blip
;97 SFX massive explosion
;98 SFX thwaaaok
;99 SFX krsssshth
SFX_BOUNCE = $9A
;9B SFX fwap
SFX_ZOMA_FREEZE_BEAM = $9C
;9D SFX I think its a special enemy hit
;9E SFX skitter skitter
;9F SFX WARP warp (warp) {{warp}}
;A0 SFX kweh kweh kweh
;A1 SFX laser beams
;A2 SFX bwomp
;A3 SFX ...cracracracrakoom
;A4 SFX cloong
;A5 SFX low flame
;A6 SFX theeeoooowwww
;A7 SFX kyowrowrowr
;A8 SFX swiish
;A9 SFX crack
;AA SFX bruuuuuuuumotor
;AB SFX low flame
;AC SFX not so low flame
; - sound ids after this seem to do nothing
