; SOUNDS: (for an easy but lousy test, change $3d929 in the rom and go up or down stairs)
BGM_SILENCE = $00
BGM_LEVELUP = $01
BGM_DQ_THEME = $02
BGM_NOCHANGE_03 = $03
BGM_OVERWORLD = $04
BGM_ALEFGARD = $05
BGM_ORIENTAL = $06
BGM_DUNGEON = $07
BGM_TOWER = $08
BGM_DUNGEON_ORIENTAL_09 = $09 ; pyramid?
BGM_SHRINE = $0A
BGM_SAILING = $0B 
BGM_OLIVIA = $0C ; promontory of olivia event
BGM_VILLAGE = $0D
BGM_FLYING = $0E
BGM_TOWN = $0F
BGM_BATTLE = $10
BGM_EVIL_11 = $11
BGM_EVIL_12 = $12 ; final battle? zoma battle?
BGM_DEAD_13 = $13
BGM_SLEEP_JINGLE = $14
BGM_PRIEST_WORK_JINGLE = $15
BGM_VICTORY_JINGLE = $16
BGM_CURSE_JINGLE = $17
BGM_INSTRUMENT_JINGLE_18 = $18
BGM_ENDTHEME_19 = $19
BGM_JINGLE_RAINBOW_DROP = $1A ; rainbow drop
BGM_JINGLE_SILVER_HARP = $1B ; silver harp
BGM_JINGLE_FAIRY_FLUTE = $1C ; fairy flute
BGM_JINGLE_ECHOING_FLUTE = $1D ; echoing flute
BGM_JINGLE_ECHOING_FLUTE_DUD = $1E ; echoing flute (dud?)
BGM_ENDING_1F = $1F
BGM_QUAKE_20 = $20
BGM_QUAKE_21 = $21
BGM_QUAKE_22 = $22
BGM_VOLCANO_HISSING = $23
BGM_WIND_24 = $24
BGM_WIND_25 = $25
BGM_LOCKET_OF_LOVE = $26
BGM_DQ3_THEME = $27
BGM_MENU = $28
BGM_BATTLE_INTRO_SLOW_29 = $29

; ..junk..

SFX_NOCHANGE_80 = $80
SFX_TRAP_TILE = $81
SFX_STAIRSTEPS = $82
SFX_RUNAWAY = $83
SFX_POISON_TILE = $84
SFX_MENU_TINK = $85
SFX_MENU_PROMPT = $86
SFX_SWEEPING_DOWN_HIT_87 = $87
SFX_ENEMY_CRIT = $88
SFX_PLAYER_ATTACKING = $89 ; windup
SFX_PLAYER_GETS_HIT = $8A ; SFX sweeping up hit
SFX_ENEMY_ATTACKING = $8B ; windup
SFX_PLAYER_ATTACK_MISS = $8C ; (low pitched)
SFX_ENEMY_ATTACK_MISS = $8D ; (high pitched)
SFX_ENEMY_CASTING = $8E ; ANYBODY casting? probably
SFX_OPEN_CHEST = $8F
SFX_OPEN_DOOR = $90
SFX_BREATH_ATTACK = $91 ; low flame (blazing or blizzard breath)
SFX_WARP_92 = $92 ; not quite sure what this means, related to samanao events?
SFX_FALL = $93
SFX_TRAVEL_GATE = $94
SFX_BLAST_95 = $95
SFX_BLIP_96 = $96
SFX_MAGICBALL_EXPLODE = $97
SFX_VOLCANO_ERUPTION_SPEW = $98
SFX_POISON_NEEDLE = $99 ; krsssshth
SFX_BOUNCE = $9A
SFX_LIGHT_FIRE = $9B
SFX_ZOMA_FREEZE_BEAM = $9C
SFX_BALL_OF_LIGHT_HIT = $9D
SFX_SKITTER_SKITTER_9E = $9E
SFX_INVISIBILITY = $9F ; warp (warp) {{warp}}
SFX_KWEHKWEHKWEH_A0 = $A0
SFX_BALL_OF_LIGHT_LASERS = $A1
SFX_BUMP_WALL = $A2
SFX_PYRAMID_BOULDER_MOVE = $A3 ; "cracracracrakoom"
;A4 SFX cloong
;A5 SFX low flame
SFX_THEEEOOOOWWWW_A6 = $A6
;A7 SFX kyowrowrowr
;A8 SFX swiish
;A9 SFX crack
;AA SFX bruuuuuuuumotor
;AB SFX low flame
;AC SFX not so low flame
; - sound ids after this seem to do nothing
